### ISSUE TITLE
Sharp borders in navbar and contact us form 

### ISSUE THREAD

**Issue by abdulshahvez** [anuragverma108/SwapReads#1]
This sharp border does not allign up with the beautifull design of the website . Should give some border radius and make it look different and good . i would love to fix it so can u plz assign me this?

**Comment by nandu-99** [comment]
please assign this issue to me, i can work on this, i have made the local setup as well, i can make the changes, and resolve this issue

**Comment by bhavanishanker-png** [comment]
Please assign this issue to me. I'm equipped to handle it as I possess all the necessary knowledge to resolve it.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by anuragverma108** [comment]
Assigned @abdulshahvez

**Comment by Gokilp** [comment]
please assign to me #gssoc24
