### ISSUE TITLE
Adding Animation 

### ISSUE THREAD

**Issue by harshmishra19** [anuragverma108/SwapReads#100]
### Describe the feature

- Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
- If you could assign me this task under GSSOC24, I would be thrilled to work on it. 
### Add ScreenShots

![Screenshot (116)](https://github.com/anuragverma108/SwapReads/assets/115486960/48216c06-2ab5-4ae2-99cf-d18826ffc441)
![Screenshot (115)](https://github.com/anuragverma108/SwapReads/assets/115486960/f7a2246d-00dc-44b5-8f39-b59198f6dfb8)

On hovering the cursor on the image you can see the animation 
I would like to add this feature on you site

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
