### ISSUE TITLE
BUG: Navbar is missing in the "Book recommendation"  Page

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is Navbar in all page but that is missing in the Book recommendation page

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/cda7b56f-978e-41ad-85d0-cea71046f0cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@anuragverma108 can you please assign this task to me. I will also correct the style of select field

**Comment by Ananya-Nair20** [comment]
Hello @anuragverma108 

I am participating in GSSOC'24. I am interested in resolving this issue. Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you

**Comment by Maheshwari-Love** [comment]
@anuragverma108 It will be very helpful if you go on First come first serve please

**Comment by Maheshwari-Love** [comment]
@huamanraj please add labels and can you please assign me?

**Comment by huamanraj** [comment]
> @RitiChandak @anuragverma108 can you please assign this task to me. I will also correct the style of select field

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
