### ISSUE TITLE
BUG: Alignment of content in Hero Section is Not Perfect

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content in the hero section are currently not aligned properly. This misalignment affects the overall visual appeal and user experience of the page.

![allignment](https://github.com/anuragverma108/SwapReads/assets/129402285/67290bda-401e-4407-a6b6-ed513d56c6a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Please assign this issue to me!

**Comment by huamanraj** [comment]
> Please assign this issue to me!

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by susrith-maddi** [comment]
Please assign me this issue

**Comment by Bhumi-letscode** [comment]
hey @huamanraj, i can resolve the alignment issues of the hero section and make it look more defined. Kindly assign me this issue.
