### ISSUE TITLE
Adding other login option

### ISSUE THREAD

**Issue by Ramsey99** [anuragverma108/SwapReads#101]
I want to add other login options (eg. Google, Facebook) to the login page. Please assign me for this.

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Ramsey99** [comment]
Thank you. I am working on it

**Comment by sahithinandikula** [comment]
I want to work on this .  kindly assign me this issue

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.

**Comment by Siddhi0504** [comment]
Hello , I want to add one more option to the social media section i.e. Instagram. Can you please assign this to me?

**Comment by say-het** [comment]
Hello, I'm a Experienced Contributor, I have completed Multiple challenges like _**Hacktoberfest-2020 and 2023.**_
I would like to work on this issue. Can you please assign this to me.
