### ISSUE TITLE
Feat: Enhancement of Book Exchange hub section

### ISSUE THREAD

**Issue by mythri1010** [anuragverma108/SwapReads#1013]
### Describe the feature

Hello, project Admin @anuragverma108, I want to modify the Book Exchange section into a more appealing place to exchange info between the buyer and the seller, So At the start, i want to add an "enter your email" in the forms so that the first contact is made right there before the request is passed. 
plus the button alignment is off, so i ll fix that too
This is how it is now:
![image](https://github.com/anuragverma108/SwapReads/assets/142799652/e8e048fe-4e9b-478d-ae48-e1f489234449)

### Add ScreenShots

Adding on what i have mentioned before, i want to try adding a faded-out picture as an example given below in this section to enhance it more--
![image](https://github.com/anuragverma108/SwapReads/assets/142799652/7cfda9d9-1f3a-4957-8ff7-488082665a0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Hello, project Admin @anuragverma108, I want to modify the Book Exchange section into a more appealing place to exchange info between the buyer and the seller, So At the start, i want to add an "enter your email" in the forms so that the first contact is made right there before the request is passed. 
> plus the button alignment is off, so i ll fix that too
> This is how it is now:
> ![image](https://github.com/anuragverma108/SwapReads/assets/142799652/e8e048fe-4e9b-478d-ae48-e1f489234449)
> 
> 
> 
> ### Add ScreenShots
> 
> Adding on what i have mentioned before, i want to try adding a faded-out picture as an example given below in this section to enhance it more--
> ![image](https://github.com/anuragverma108/SwapReads/assets/142799652/7cfda9d9-1f3a-4957-8ff7-488082665a0c)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by mythri1010** [comment]
Alright, thank you
