### ISSUE TITLE
BUG: Back to top button not working in E-books section

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The back to top functionality is not working when we click on it in the E-books section. I would like to add the functionality for it.
Please assign this issue to me!.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
