### ISSUE TITLE
BUG: In the genre section, for different genres the hover effect is zooming the div/cards which is disturbing readability across the page

### ISSUE THREAD

**Issue by Poushmita** [anuragverma108/SwapReads#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![zoom in](https://github.com/anuragverma108/SwapReads/assets/146666416/bf71f2d9-e6ab-482f-9908-7a9f2f3695e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![zoom in](https://github.com/anuragverma108/SwapReads/assets/146666416/bf71f2d9-e6ab-482f-9908-7a9f2f3695e8)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Poushmita** [comment]
Yes, now It has been solved already
