### ISSUE TITLE
Feat: Create Signup Page Frontend

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1018]
### Describe the feature

We need to create a new signup page for our application. The signup page should allow users to register by providing necessary information such as username, email, and password. The design should be consistent with the overall look and feel of the application.

Please assign this issue to me.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
