### ISSUE TITLE
BUG: Forgot Password Not visible

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/148524648/4f0b2e95-67a7-4b85-9046-9084dc698392)

Color of forgot password needs to be changed to enhance visibililty.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open source contributing!
