### ISSUE TITLE
Feat: Can adjust  the heading and the text in the E-Books section

### ISSUE THREAD

**Issue by poushmitaPaul** [anuragverma108/SwapReads#1020]
### Describe the feature

I would like to adjust the heading (Free E-Books) and the text below it which is essential for text visibility from a user experience because it's overlapping the texts of genre div.

### Add ScreenShots

![e-books](https://github.com/anuragverma108/SwapReads/assets/161232111/68590da9-2cee-4f5d-9fa7-2e7a31f6f8d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vassu627** [comment]
Hey! I am Vasantha as a contributor, I would like to contribute in making this website.

**Comment by poushmitaPaul** [comment]
yes it was solved already
