### ISSUE TITLE
DOC: Position of select language section is looking deformed

### ISSUE THREAD

**Issue by poushmitaPaul** [anuragverma108/SwapReads#1022]
### What's wrong with the existing documentation

The select language portion is overlapping with the navbar section and some text of this section is not visible for this which effecting the user experience and welfare of visibility of the page. 

### Add ScreenShots

![select language](https://github.com/anuragverma108/SwapReads/assets/161232111/77f8845a-4a09-4aa6-9fd6-3c861c9da551)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
