### ISSUE TITLE
Feat: Frontend page of Rate Us

### ISSUE THREAD

**Issue by poushmitaPaul** [anuragverma108/SwapReads#1023]
### Describe the feature

We need to create a better page for Rate Us section (Frontend)

### Add ScreenShots

![rate us](https://github.com/anuragverma108/SwapReads/assets/161232111/0a9d1eda-6199-488c-aa61-a561aadee633)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> We need to create a better page for Rate Us section (Frontend)
> 
> ### Add ScreenShots
> ![rate us](https://private-user-images.githubusercontent.com/161232111/334886532-0a9d1eda-6199-488c-aa61-a561aadee633.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMDE1NTAsIm5iZiI6MTcxNzAwMTI1MCwicGF0aCI6Ii8xNjEyMzIxMTEvMzM0ODg2NTMyLTBhOWQxZWRhLTYxOTktNDg4Yy1hYTYxLWE1NjFhYWRlZTYzMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNjQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWEzN2U3YzJlMGY5ZjE4NGQyYTAyMDE1YzEzNzhjMTlhMGZmNTFlODg1NDM2MWY4NTNhMjZiYzMxN2VmNTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jmT9x0R_DABcnOcSxlYRb3YKM0FDYvs0AMsqJqn_ro4)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

work on this!!
