### ISSUE TITLE
DOC: Update about How to make PR and contribute to project section in Readme

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1024]
### What's wrong with the existing documentation

There should be the section of how to contribute in this project, update required for adding the section "How to make PR" Or how to contribute. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@RitiChandak can you please assign this task to me?

**Comment by huamanraj** [comment]
> @RitiChandak can you please assign this task to me?

https://github.com/anuragverma108/SwapReads/blob/main/CONTRIBUTING.md 
we have already this! if you want you can improve this!!!
