### ISSUE TITLE
Enhance Login Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1026]
### Describe the feature

Hey @anuragverma108 .

- Enhance the visual appeal and user interaction of the footer and "Forgot Password?"  and also adding hover effect to the reset password.
- Ensure consistent and readable design across different screen sizes.

**please add the gssoc labels and I would like to work on it. Thank you!!**

### Add ScreenShots

Before making the changes, it looks like:
![Screenshot 2024-05-29 223025](https://github.com/anuragverma108/SwapReads/assets/159511364/c9a4090a-ff0a-4949-8d13-6235669601b8)

After making the changes:
![Screenshot 2024-05-29 225215](https://github.com/anuragverma108/SwapReads/assets/159511364/8608c6ad-4946-49a1-ad38-7cf609a1e8cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new  one. Find another issue or feature to contribute to. Thank you!
