### ISSUE TITLE
BUG: About us page not working

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108 , the about option in navbar is not working. I would like to correct this issue.

Kindly assign me this under GSSoC'24, I'll do my best.

Screenshot
![Screenshot 2024-05-29 230650](https://github.com/anuragverma108/SwapReads/assets/100590445/275e7437-2e65-4fa6-b284-25a732024a84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned! 
Make sure to attach before & after screenshots in your PR. Also, star the repo  before working on it. While creating your PR, ensure you pull all existing changes  beforehand to avoid conflicts. 
Happy open-source contributing!

**Comment by Tabindanoor** [comment]
can you assign me that task
