### ISSUE TITLE
BUG: Navbar is not available in book recommendation section

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108 , Navbar is not available in book recommendation section. I would like to add it so that it will become easy for user to switch sections.

Kindly assign me this issue under GSSoC'24. I'll do my best.

Screenshot

![Screenshot 2024-05-29 231157](https://github.com/anuragverma108/SwapReads/assets/100590445/afb0dcc8-dac2-45cb-a611-10e90da37ac8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned! 
Make sure to attach before & after screenshots in your PR. Also, star the repo  before working on it. While creating your PR, ensure you pull all existing changes  beforehand to avoid conflicts. 
Happy open-source contributing!

**Comment by RitiChandak** [comment]
@Dilpreet0501 also align select genre

**Comment by AnanyaBharti** [comment]
Hello, 
I want to work on this issue please assign this to me.

**Comment by Dilpreet0501** [comment]
> @Dilpreet0501 also align select genre

Sure!!
