### ISSUE TITLE
BUG: Despite it being a closed isssue, the "Book Title" is still appearing twice in the "Book Exchange Hub"

### ISSUE THREAD

**Issue by sandy-queen** [anuragverma108/SwapReads#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello. The "Book Title" is appearing twice in the "Book Exchange Hub" section. Though it seems like it was previously fixed by someone, the issue is still happening. I can still see the Book Title written twice and in the wrong format. 

Also, I think that there should be some gap between the description paragraph and the book title. 

![swapreads](https://github.com/anuragverma108/SwapReads/assets/147652780/2666659c-75b8-40ce-8756-09a8109c6e71)

**@anuragverma108 Please assign this issue to me. I would like to work on it.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!

**Comment by sandy-queen** [comment]
Thank you for assigning, I am working on it!

**Comment by sandy-queen** [comment]
Hello. I have made the required changes. Please add the labels to this issue, so I can make a PR
