### ISSUE TITLE
BUG: Login Page - Forgot Password and Reset Page font color white so not visible

### ISSUE THREAD

**Issue by Jemipaul123** [anuragverma108/SwapReads#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-30 001614](https://github.com/anuragverma108/SwapReads/assets/107522016/7952f165-8941-4e81-b601-8f765b2b5a8d)

The font color of Forgot password and Reset Here is white and hence not visible.

I would like to work on this issue. I am a GSSOC'24 contributor. Pls assign me @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
