### ISSUE TITLE
BUG: Scrollbar present even from the loading page.

### ISSUE THREAD

**Issue by Jemipaul123** [anuragverma108/SwapReads#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/107522016/53e02b12-c3b4-42bd-b0af-66246ce029c5)

Scrollbar present even from the loading page which is not needed there and it is a bad outlook.
Can u assign me this issue? I am a GSSOC'24 contributor. @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/107522016/53e02b12-c3b4-42bd-b0af-66246ce029c5)
> 
> 
> 
> Scrollbar present even from the loading page which is not needed there and it is a bad outlook.
> Can u assign me this issue? I am a GSSOC'24 contributor. @anuragverma108 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
