### ISSUE TITLE
BUG: SendNow button not aligned properly

### ISSUE THREAD

**Issue by Jemipaul123** [anuragverma108/SwapReads#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-30 002608](https://github.com/anuragverma108/SwapReads/assets/107522016/3111938e-2151-42cf-826c-19a33d35d1d6)
Its aligned towards one side which doesn;t look good.
Can you assign me this issue? I am a GSSOC'24 contributor. @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new  one. Find another issue or feature to contribute to. Thank you!
