### ISSUE TITLE
BUG:MISSING ONE GENRE INFORMATION IN GENRES SECTION 

### ISSUE THREAD

**Issue by nilesh07g** [anuragverma108/SwapReads#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In exploring different genres 
9th Genre information is empty 

Screenshot 
![IMG_1921](https://github.com/anuragverma108/SwapReads/assets/142440160/c61d212e-02df-433b-8e25-9505ce9d7072)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nilesh07g** [comment]
@anuragverma108  
Kindly assign this issue to me 
I can fix this issue under GSSOC 24
Thank You

**Comment by Praneeth-2602** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/137754636/2ed30691-8284-436d-8775-f7c217e9108a)
I guess everything is normal
