### ISSUE TITLE
BUG:Overflow on mobile and couple others

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- There is a horizontal scroll bar on mobile due to some cotent overflowing to the right:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/ee7d96d9-a0ba-4a3c-a121-434cdba1459c)
- The chat and back to the top buttons are not aligned:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/ec01c57b-7252-48af-a7ee-01e3cdec15d4)
- The cursor is back on mobile:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/36cfb20e-3b47-463b-8b60-2710ccd17013)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned! 
Make sure to attach before & after screenshots in your PR. Also, star the repo  before working on it. While creating your PR, ensure you pull all existing changes  beforehand to avoid conflicts. 
Happy open-source contributing!
