### ISSUE TITLE
Feat: Adding FAQ section

### ISSUE THREAD

**Issue by YUG-1092005** [anuragverma108/SwapReads#104]
### Describe the feature

FAQ section here can be created to resolve doubts of users 
kindly assign this issue to me under GSSOC 24

### Add ScreenShots

After contact info FAQ section can be created 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by YUG-1092005** [comment]
Hi @anuragverma108 your website's FAQ section is created , should i create pull request in main branch or i have to create new branch??

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.
