### ISSUE TITLE
BUG: SignUp missing in login signup page

### ISSUE THREAD

**Issue by Praneeth-2602** [anuragverma108/SwapReads#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/137754636/c6066bd4-0908-499a-a03a-a468d84f67d6)

As you can see the Create account option is missing. It was there previously.

![image](https://github.com/anuragverma108/SwapReads/assets/137754636/9f0a9adf-e0bc-4540-9dae-4f994cb4de98)

Please assign this issue to me. I will add the signup option and enhance the functionality of the login page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new  one. Find another issue or feature to contribute to. Thank you!
