### ISSUE TITLE
DOC : Padding of Genre section in DarkMode

### ISSUE THREAD

**Issue by payalgupta25** [anuragverma108/SwapReads#1042]
### What's wrong with the existing documentation

So on switching to dark mode the genre section is having no padding in top and bottom which looks quite not right 
I would love to contribute and add a little padding to make it look nice

### Add ScreenShots

![Screenshot 2024-05-30 124836](https://github.com/anuragverma108/SwapReads/assets/139633883/bf5c8474-403c-499e-9221-87b631bbc13e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> 
> So on switching to dark mode the genre section is having no padding in top and bottom which looks quite not right 
> I would love to contribute and add a little padding to make it look nice
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-30 124836](https://github.com/anuragverma108/SwapReads/assets/139633883/bf5c8474-403c-499e-9221-87b631bbc13e)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Bhumi-letscode** [comment]
hey @huamanraj, i would love to correct the alignment settings of the dark mode of genre section and make it look presentable. kindly assign me this task. You will not be disappointed.
