### ISSUE TITLE
BUG: [URGENT] Someone has restructured the code and made wrong changes

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have solve 2 issue but now those changes are overwritten by someone so the issue is What ever issues I solved are arise again  refer the following screenshot:

https://github.com/anuragverma108/SwapReads/pull/875
I have solved the Issue #870 
but know the same issue arise again

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/91b08e09-7a04-4918-9dcc-8eab57de547c)

I have solved the issue no.#881
but now someone as change the path of "recommended books" in directory.
https://github.com/anuragverma108/SwapReads/pull/929
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/0ee9efdc-9514-421c-93d6-5235908e4713)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@RitiChandak @anuragverma108  @huamanraj I have found these bugs of wrong merging of a PR 
The Path of Book Recommendation page is changed to wrong folder so that issue is arising...
some one has pushed previous code without syncing the new changes

**Comment by huamanraj** [comment]
> @RitiChandak @anuragverma108  @huamanraj I have found these bugs of wrong merging of a PR 
> The Path of Book Recommendation page is changed to wrong folder so that issue is arising...
> some one has pushed previous code without syncing the new changes

work on it 💪

**Comment by Maheshwari-Love** [comment]
but i think it should be revert because i think other' contributor's  changes also affected I have found these because i solved those issues so i have found where the wrong changes are done..
any suggestions please @huamanraj

**Comment by huamanraj** [comment]
> but i think it should be revert because i think other' contributor's  changes also affected I have found these because i solved those issues so i have found where the wrong changes are done..
> any suggestions please @huamanraj 

you can correct the new codebase! so other changes wouldn't get affected
