### ISSUE TITLE
Adding a book reviews section too above the footer or below testimonials

### ISSUE THREAD

**Issue by Vaishnavi1047** [anuragverma108/SwapReads#1045]
### Describe the feature

Adding a book reviews section too above the footer or below testimonials
somewhat as stated in the pic the space between looks unpleasant 

### Add ScreenShots

![Screenshot 2024-05-30 143127](https://github.com/anuragverma108/SwapReads/assets/149894552/ba43a776-4cf5-4e43-a8a1-2ae2fee977b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Adding a book reviews section too above the footer or below testimonials
> somewhat as stated in the pic the space between looks unpleasant 
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-30 143127](https://github.com/anuragverma108/SwapReads/assets/149894552/ba43a776-4cf5-4e43-a8a1-2ae2fee977b6)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by sanjanasp786** [comment]
Hey could you please assign these project to me under gssoc'24.
