### ISSUE TITLE
Feat: Change the color combination in login page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1046]
### Describe the feature

THe input fields are having whitesmoke color in back so the text written in this is not clearly visible .

### Add ScreenShots

![Screenshot 2024-05-30 143815](https://github.com/anuragverma108/SwapReads/assets/118350936/db06bd68-3de0-4b29-817b-d7e086dff4e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> THe input fields are having whitesmoke color in back so the text written in this is not clearly visible .
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-30 143815](https://github.com/anuragverma108/SwapReads/assets/118350936/db06bd68-3de0-4b29-817b-d7e086dff4e5)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

https://www.instagram.com/reel/C7YV1nIsjwo/?utm_source=ig_web_copy_link

**Comment by huamanraj** [comment]
> Hii i want to know which color you want like what if i change the color of the text to black IMO black is the best option 
> ![Screenshot 2024-05-30 161808](https://github.com/anuragverma108/SwapReads/assets/118350936/11799a43-df7b-4c18-bbc9-bbdf5a159fa6)
> 

dont use completely black use a shade of black!
