### ISSUE TITLE
BUG: Dark mode not working during login/signup

### ISSUE THREAD

**Issue by mukund-gpt** [anuragverma108/SwapReads#1051]
https://github.com/anuragverma108/SwapReads/assets/142800930/de60ac8e-9efb-4fc1-90c1-15f5f20d0bc8

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

assign the task to me i will manage it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@mukund-gpt 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by RitiChandak** [comment]
@mukund-gpt any updates?
