### ISSUE TITLE
Feat: Improve the whole About Us page

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#1053]
### Describe the feature

I want to improve the whole UI of the About us page.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/146222028/b0c900ce-413c-42fa-adc6-b2f84be5be00)
This looks very basic and I want to improve it and make it more appealing. Please assign this to me under GSSoC'24. @huamanraj @anuragverma108 @RitiChandak 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by RitiChandak** [comment]
@Madhuri36 please make sure that @anuragverma108 approve the UI
