### ISSUE TITLE
BUG:adding header and footer in book recomandation 

### ISSUE THREAD

**Issue by RiyaaBhatt** [anuragverma108/SwapReads#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello Admin,

I have identified that the book recommendation page is missing a header and footer. Could you please assign this issue to me under GSSoC'24?

Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
#919 This is an existing issue where someone is already adding the header and footer to all the pages.
