### ISSUE TITLE
BUG: Change Signup Page

### ISSUE THREAD

**Issue by aarushi-taori** [anuragverma108/SwapReads#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To maintain uniformity in whole website, we need to change the design of register page and make it same as sign in page. 

![Screenshot 2024-05-30 174608](https://github.com/anuragverma108/SwapReads/assets/113369937/707672bd-8676-4164-b603-9b6232c105f0)
![Screenshot 2024-05-30 174622](https://github.com/anuragverma108/SwapReads/assets/113369937/849fe98d-722d-4693-9f60-33e41d7820bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned! 
Make sure to attach before & after screenshots in your PR. Also, star the repo  before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts. 
Happy open source contributing!

**Comment by aarushi-taori** [comment]
@RitiChandak I by mistake removed my assignment, Please assign again

**Comment by huamanraj** [comment]
> @RitiChandak I by mistake removed my assignment, Please assign again

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor reach out for any help needed!! 
Happy open-source contributing!
