### ISSUE TITLE
BUG: font style is different in login header

### ISSUE THREAD

**Issue by aashkaaaaaa** [anuragverma108/SwapReads#1065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

font style is different in login header
![Screenshot 2024-05-30 190243](https://github.com/anuragverma108/SwapReads/assets/138461600/3da0fdf4-27e7-44dc-af49-c8c7f01ee03c)
![Screenshot 2024-05-30 190320](https://github.com/anuragverma108/SwapReads/assets/138461600/7e8014f0-0e05-4135-86e5-d85b2587d219)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
