### ISSUE TITLE
BUG: improve login footer

### ISSUE THREAD

**Issue by aashkaaaaaa** [anuragverma108/SwapReads#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-30 190405](https://github.com/anuragverma108/SwapReads/assets/138461600/6aa0623e-872f-4b3b-9934-4f4422fde8a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
