### ISSUE TITLE
BUG: Changing mode button is not well aligned 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In small screen the dark mode icon is not well aligned in the middle of the navbar vertically .
![Screenshot 2024-05-30 193059](https://github.com/anuragverma108/SwapReads/assets/118350936/c3f3915b-ad5f-41be-8dd5-0542df8e7f48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
