### ISSUE TITLE
BUG: In small screen the more dropdown don't showing all options .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the small screen the dropdown more is not showing all options only one option is visible all other are hiding .
![Screenshot 2024-05-30 193421](https://github.com/anuragverma108/SwapReads/assets/118350936/92092d41-cbae-420e-91f6-04543d0259f4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> In the small screen the dropdown more is not showing all options only one option is visible all other are hiding . ![Screenshot 2024-05-30 193421](https://private-user-images.githubusercontent.com/118350936/335215190-92092d41-cbae-420e-91f6-04543d0259f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM0NzYsIm5iZiI6MTcxNzI0MzE3NiwicGF0aCI6Ii8xMTgzNTA5MzYvMzM1MjE1MTkwLTkyMDkyZDQxLWNiYWUtNDIwZS05MWY2LTA0NTQzZDAyNTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMTU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWRmYmUyMDljN2Y0MmExY2Y2NGQ1M2NjMDgwNTg4ZjIzMjEwNGY2Njg5ZjM0NTVkNzI0ZGJkYzc0YWVjZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RJTujF9hzvo1-JBc3EK_pG4R0TL7NAIx67hWAQJhTao)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
