### ISSUE TITLE
BUG: There are two index.html file becuase of which some issue arising

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two index.html  files present in the repo that's why some problem are arising like We have to update in both the index.html file a simple example 
I have solved the issue of book title written twice in this index.html file But (refer to 2nd screenshot)
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/499a0d77-2615-439f-b00f-f91137d92c58)

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/5d8496b7-3873-498e-9af5-b657aca4f0b0)

.

In this outer file index.html the the code is that for which the issue was raised
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/d9d0d238-0bdc-49fc-a784-b4b0c4167570)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@huamanraj Please take action on this so that we can start working on other issues which are dependent on this file

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Maheshwari-Love** [comment]
I want to discuss this issue with you to get started with code @RitiChandak
