### ISSUE TITLE
BUG:The "Connect with the Reader" button in Book exchange Hub section is not in the centre.

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1440" alt="Screenshot 2024-05-30 at 8 35 23 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/a0df651b-966c-40b8-a1e9-ffdd6a469f79">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> <img alt="Screenshot 2024-05-30 at 8 35 23 PM" width="1440" src="https://private-user-images.githubusercontent.com/119745655/335255752-a0df651b-966c-40b8-a1e9-ffdd6a469f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM1MDUsIm5iZiI6MTcxNzI0MzIwNSwicGF0aCI6Ii8xMTk3NDU2NTUvMzM1MjU1NzUyLWEwZGY2NTFiLTk2NmMtNDBiOC1hMWU5LWZmZGQ2YTQ2OWY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDJkNDk0OGI2YjhiNTM2ZTVmMzQyYTE1YjZhMDUwMTczZDc1OTRiNjljYzY1ODZjNmU4NWE3ZmZjNWU3N2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9eHCuRezm9_AuYknnjCo2I5Bi5USQQXLJ97_jO4j1OA">
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
