### ISSUE TITLE
BUG:The "Send Now" button in the contact page is not in the centre.

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before:
<img width="1440" alt="Screenshot 2024-05-30 at 8 35 12 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/77a6b8c2-4f2d-486c-84a3-6c2540b5d445">
After:
<img width="1440" alt="Screenshot 2024-05-30 at 8 34 47 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/5461e764-8f4c-4d17-8f81-57e8ae0078ab">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> Before: <img alt="Screenshot 2024-05-30 at 8 35 12 PM" width="1440" src="https://private-user-images.githubusercontent.com/119745655/335257376-77a6b8c2-4f2d-486c-84a3-6c2540b5d445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM1NDksIm5iZiI6MTcxNzI0MzI0OSwicGF0aCI6Ii8xMTk3NDU2NTUvMzM1MjU3Mzc2LTc3YTZiOGMyLTRmMmQtNDg2Yy04NGEzLTZjMjU0MGI1ZDQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzdmOTY2YWYzMjIxYWU4MGRiNzhjOGE5ZTZiOWJhNzM2YjZlNmIzOTE3OWMxYTAzMjMzNGVhMTEzYjdhMWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xPWmer5E1n21Jvi0w6nUbzaYPfvt3fJNEtG_-0m2OLY"> After: <img alt="Screenshot 2024-05-30 at 8 34 47 PM" width="1440" src="https://private-user-images.githubusercontent.com/119745655/335257460-5461e764-8f4c-4d17-8f81-57e8ae0078ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM1NDksIm5iZiI6MTcxNzI0MzI0OSwicGF0aCI6Ii8xMTk3NDU2NTUvMzM1MjU3NDYwLTU0NjFlNzY0LThmNGMtNGQxNy04ZjgxLTU3ZThhZTAwNzhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGM2YWIyZWNjODMzYzhlZWQxNDQyMzZiNWEwYzQyMjY2MmVlODcxZjBkMTRjMzRiZDVkYzZmNjljZTBiMGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zZrBlasfBIgp1BCddoe8xLfn8R7UYgZkdpuZ8NkcRqk">
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
