### ISSUE TITLE
Improvement in  the Contact section

### ISSUE THREAD

**Issue by shrutigolwalk0109** [anuragverma108/SwapReads#1075]
### Describe the feature

We can add some border effects and also a hover effect to make the contact form look better ,
Kindly Assign me this Issue under GSSOC, I would like to work on it.

### Add ScreenShots

Before: 

![WhatsApp Image 2024-05-30 at 21 03 17_317d90b7](https://github.com/anuragverma108/SwapReads/assets/132553685/ac7be636-ac0f-4978-bd78-55d3ab795b96)

After:
![WhatsApp Image 2024-05-30 at 21 02 16_a03d0ba7](https://github.com/anuragverma108/SwapReads/assets/132553685/4574a799-a261-4415-a47f-d26115129c2a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> We can add some border effects and also a hover effect to make the contact form look better , Kindly Assign me this Issue under GSSOC, I would like to work on it.
> 
> ### Add ScreenShots
> Before:
> 
> ![WhatsApp Image 2024-05-30 at 21 03 17_317d90b7](https://private-user-images.githubusercontent.com/132553685/335276493-ac7be636-ac0f-4978-bd78-55d3ab795b96.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM1ODQsIm5iZiI6MTcxNzI0MzI4NCwicGF0aCI6Ii8xMzI1NTM2ODUvMzM1Mjc2NDkzLWFjN2JlNjM2LWFjMGYtNDk3OC1iZDc4LTU1ZDNhYjc5NWI5Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmZiZmMyYzYwMDU1MGM2MjU2MTI2NTViYzQ5YzlkN2M3NjQ3YWNiMzM5OTljYzhjMjViMDA0YzAxZTEyZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lUX0tUi14Y2bX24xlbDYRSOdbOXxiF8MK4mWwonpZvE)
> 
> After: ![WhatsApp Image 2024-05-30 at 21 02 16_a03d0ba7](https://private-user-images.githubusercontent.com/132553685/335276492-4574a799-a261-4415-a47f-d26115129c2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM1ODQsIm5iZiI6MTcxNzI0MzI4NCwicGF0aCI6Ii8xMzI1NTM2ODUvMzM1Mjc2NDkyLTQ1NzRhNzk5LWEyNjEtNDQxNS1hNDdmLWQyNjExNTEyOWMyYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWE5MjhlM2ZkNTZkYWZmMDAzMjRkM2JiNGEyOTU1NTcwMDM0ZDY0MGJmZDZkNDJjODVkNTk3NGE2OGFjZWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2z8Zab7fyTwev1t5-JiqZCYP0KP3ZGe9aGRme8RHlv4)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
