### ISSUE TITLE
Feat: Automated Thank You Email for Newsletter Subscription

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [anuragverma108/SwapReads#1078]
### Describe the feature

I want to Implement an automated system that sends a thank you or appreciation email to users upon subscribing to the website newsletter by using Nodemailer. The mail can consists of attachments if required as well. Also an alert with "Thank you for subscribing to newsletter!" message can be implemented for immediate feedback.

### Add ScreenShots

![gssoc7](https://github.com/anuragverma108/SwapReads/assets/128472306/d8a9dfed-239e-499f-8357-280b11ee787f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayesha-Siddiqua88** [comment]
Please assign me this issue.

**Comment by huamanraj** [comment]
> @anuragverma108 Please assign me this issue.

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
