### ISSUE TITLE
Change Repeating Testimonials to Unique Entries

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 

Currently, the testimonials section on our website contains repeating entries, which negatively impacts user experience and credibility. We need to update this section to ensure each testimonial is unique and accurately reflects the diverse feedback from our users.

Issue:

https://github.com/anuragverma108/SwapReads/assets/159511364/1360b14e-b2c9-47e4-8043-8e31e3a403a2

I would like to remove multiple repeating entries like the prem sampath and Aron Loes repeated twice and to create the unique ones.

**please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> Hey @anuragverma108
> 
> Currently, the testimonials section on our website contains repeating entries, which negatively impacts user experience and credibility. We need to update this section to ensure each testimonial is unique and accurately reflects the diverse feedback from our users.
> 
> Issue:
> 
>  SwapReads.-.Google.Chrome.2024-05-30.22-19-41.mp4 
> I would like to remove multiple repeating entries like the prem sampath and Aron Loes repeated twice and to create the unique ones.
> 
> **please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
