### ISSUE TITLE
chatbox icon is not properly aligned

### ISSUE THREAD

**Issue by sidhigrover** [anuragverma108/SwapReads#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to align the chatbox icon to the right side .
<img width="1440" alt="Screenshot 2024-05-30 at 10 36 36 PM" src="https://github.com/anuragverma108/SwapReads/assets/123989540/40fce2fd-b0df-412a-bd91-2e2c667a386f">
please assign me this issue under gssoc @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> We need to align the chatbox icon to the right side . <img alt="Screenshot 2024-05-30 at 10 36 36 PM" width="1440" src="https://private-user-images.githubusercontent.com/123989540/335313889-40fce2fd-b0df-412a-bd91-2e2c667a386f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3MDYsIm5iZiI6MTcxNzI0MzQwNiwicGF0aCI6Ii8xMjM5ODk1NDAvMzM1MzEzODg5LTQwZmNlMmZkLWIwZGYtNDEyYS1iZDkxLTJlMmM2NjdhMzg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTg0NjM5ZDEwYjFjOWJhZjI2OWJhZDM3NjQxODNlNzkwYzA3ZWMyOWZiNTAyNWU3YzhjNWI2YTU1YjdlODQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YQ0xs5evD-Rtpq0KWIXskWiNuPxO5I8knOh42mb4pxA"> please assign me this issue under gssoc @anuragverma108
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by sidhigrover** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### What happened?
> > We need to align the chatbox icon to the right side . <img alt="Screenshot 2024-05-30 at 10 36 36 PM" width="1440" src="https://private-user-images.githubusercontent.com/123989540/335313889-40fce2fd-b0df-412a-bd91-2e2c667a386f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3MDYsIm5iZiI6MTcxNzI0MzQwNiwicGF0aCI6Ii8xMjM5ODk1NDAvMzM1MzEzODg5LTQwZmNlMmZkLWIwZGYtNDEyYS1iZDkxLTJlMmM2NjdhMzg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTg0NjM5ZDEwYjFjOWJhZjI2OWJhZDM3NjQxODNlNzkwYzA3ZWMyOWZiNTAyNWU3YzhjNWI2YTU1YjdlODQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YQ0xs5evD-Rtpq0KWIXskWiNuPxO5I8knOh42mb4pxA"> please assign me this issue under gssoc @anuragverma108
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [x]   I'm a GSSOC'24 contributor
> > * [x]   I want to work on this issue
> 
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

hey,just saw today this
