### ISSUE TITLE
BUG:switch day to night mode nothing will happen at login/signup page

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1440" alt="Screenshot 2024-05-30 at 10 48 28 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/4db2274f-2015-42ff-bd20-04d0f2745935">
<img width="1440" alt="Screenshot 2024-05-30 at 10 48 33 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/243f370b-f458-4089-9750-edad9450b599">

left and right image after switching the day to night moe nothing will happen

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> <img alt="Screenshot 2024-05-30 at 10 48 28 PM" width="1440" src="https://private-user-images.githubusercontent.com/145912232/335317324-4db2274f-2015-42ff-bd20-04d0f2745935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3MjIsIm5iZiI6MTcxNzI0MzQyMiwicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzE3MzI0LTRkYjIyNzRmLTIwMTUtNDJmZi1iZDIwLTA0ZDBmMjc0NTkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzE1MWMyMTUwMjkwYTE4MWY1MjY3ZGJkMTk3OWU2Mzk0ODU3ZTQ4OTNmOTA2YjkyMzIzZDY0MTUzY2U4M2Y3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-d2Ltuig-ICb970-VvXQuCTrdg-YH-l3d2Z5Mw7YR-c"> <img alt="Screenshot 2024-05-30 at 10 48 33 PM" width="1440" src="https://private-user-images.githubusercontent.com/145912232/335317390-243f370b-f458-4089-9750-edad9450b599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3MjIsIm5iZiI6MTcxNzI0MzQyMiwicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzE3MzkwLTI0M2YzNzBiLWY0NTgtNDA4OS05NzUwLWVkYWQ5NDUwYjU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjAzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQ4YzYxOTJjZTFjYmNmZDY4NDYwNThhMzc3YjUyMThkMDMxMDE0NGE5YzRhYWQwOGJmMzQxMDc5MTg3NzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.781ypbSqoJrCeS-i7vUGMnlPyKfMKmgkW7Z7bsg2Jh0">
> left and right image after switching the day to night moe nothing will happen
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> <img alt="Screenshot 2024-05-30 at 10 48 28 PM" width="1440" src="https://private-user-images.githubusercontent.com/145912232/335317324-4db2274f-2015-42ff-bd20-04d0f2745935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3NDMsIm5iZiI6MTcxNzI0MzQ0MywicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzE3MzI0LTRkYjIyNzRmLTIwMTUtNDJmZi1iZDIwLTA0ZDBmMjc0NTkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDgwYmM1MWE5OTljYWJiMzM2MGYwZTU0NzAyODljNGJlNWVjMDFkZmEyMWQ0OTE4ODE4ZGI2ZTY2ZDMyODUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UxaeA2tl8hM32LY8-NA9GWDAm38seWGBxKCxKRqH4lE"> <img alt="Screenshot 2024-05-30 at 10 48 33 PM" width="1440" src="https://private-user-images.githubusercontent.com/145912232/335317390-243f370b-f458-4089-9750-edad9450b599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3NDMsIm5iZiI6MTcxNzI0MzQ0MywicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzE3MzkwLTI0M2YzNzBiLWY0NTgtNDA4OS05NzUwLWVkYWQ5NDUwYjU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2MxOTRkMzZjMGI3MmE4N2VlMjlmNDdjZmIxNTBiNjk4NWUxNWVkMTEzMGQyYjJkN2UwYTFmNWE5MDcyODY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bDukCwHg90Vt--tTqUJsoxBJ13pzygKzlC2f6P9GnHg">
> left and right image after switching the day to night moe nothing will happen
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
