### ISSUE TITLE
Feat:Switchable sign In Sign Up page

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1083]
### Describe the feature

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/5cf395cb-547d-4c92-a1c3-36e4276388b1)
In This we are seeing login and signup together but we can a button New To swapreads create an account and switch to sign up page

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/4a683f7f-79ff-4bbb-803d-c58909719297)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> ![image](https://private-user-images.githubusercontent.com/101548649/335319891-5cf395cb-547d-4c92-a1c3-36e4276388b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3NjYsIm5iZiI6MTcxNzI0MzQ2NiwicGF0aCI6Ii8xMDE1NDg2NDkvMzM1MzE5ODkxLTVjZjM5NWNiLTU0N2QtNGM5Mi1hMWMzLTM2ZTQyNzYzODhiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWJkNzQzYWUyMjJmZjZmNWRkZTUzOTEwNDA4Yjg1YjU4ZTJlZjRhNjBlZTQ2ZDUwNzQwZjUxM2FjNWRkM2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_w_DxS8m1lupX_TTaOd9W1p9rC7ZKCE7MN7Ch_YEsM) In This we are seeing login and signup together but we can a button New To swapreads create an account and switch to sign up page
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/101548649/335320190-4a683f7f-79ff-4bbb-803d-c58909719297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM3NjYsIm5iZiI6MTcxNzI0MzQ2NiwicGF0aCI6Ii8xMDE1NDg2NDkvMzM1MzIwMTkwLTRhNjgzZjdmLTc5ZmYtNGJiYi04MDNkLWM1ODkwOTcxOTI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQyYzE1MDA4ZDcyMTM3NmQ1YWRlODRmNWIzYjI4ZDEyMmU4ZWIyNzgyYzMxY2QzODJlZGZjNTYxYzBhM2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTAgqhFkivddIyekj5ORDFWtqM3wIiwal7lNFdSA99c)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
