### ISSUE TITLE
Feat: Add a Button to Login/signup wIth GOOGLE

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1084]
### Describe the feature

I want to add signin with google button to this page

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/e04ac117-a625-47cf-a5a7-e57405a8914d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> I want to add signin with google button to this page
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/101548649/335320781-e04ac117-a625-47cf-a5a7-e57405a8914d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM4NTYsIm5iZiI6MTcxNzI0MzU1NiwicGF0aCI6Ii8xMDE1NDg2NDkvMzM1MzIwNzgxLWUwNGFjMTE3LWE2MjUtNDdjZi1hNWE3LWU1NzQwNWE4OTE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjc3MjVhYmJjMjU3MmM3MDM0M2EzOTkzNDlhMTE4NzE3MzBhNmE3OTIxYzJkYTdlMTFlMGYwMTJiZGU0ODVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wu7vzckPntfwDeve2TZHtY4RW1IqNrLlqRV-BgtSi9U)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by nishant0708** [comment]
Hey I will also add backend of the button wIll it be fine?
