### ISSUE TITLE
BUG: Dark Mode Not Working in Login Page and Navbar is not alike in Login Page

### ISSUE THREAD

**Issue by aarushi-taori** [anuragverma108/SwapReads#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Dark Mode Not Working in Login Page and Navbar is not alike in Login Page

![image](https://github.com/anuragverma108/SwapReads/assets/113369937/ba0ea115-616e-4927-ab6d-127007a48778)
![image](https://github.com/anuragverma108/SwapReads/assets/113369937/8df3f4a2-3ef7-4661-b6f6-246c53ecf511)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aarushi-taori** [comment]
@RitiChandak Please Assign me this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Tarungupta18** [comment]
@RitiChandak please assign me this issue excited to contribute

**Comment by RitiChandak** [comment]
@Tarungupta18 Issues are assigned on a first-come, first-served basis. If a contributor doesn't
contribute within 1 week, it will be reassigned to the next person who requested it.
You can wait or find another bug/feature to contribute to. Thank you!

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> Dark Mode Not Working in Login Page and Navbar is not alike in Login Page
> 
> ![image](https://private-user-images.githubusercontent.com/113369937/335321823-ba0ea115-616e-4927-ab6d-127007a48778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDQxNjAsIm5iZiI6MTcxNzI0Mzg2MCwicGF0aCI6Ii8xMTMzNjk5MzcvMzM1MzIxODIzLWJhMGVhMTE1LTYxNmUtNDkyNy1hYjZkLTEyNzAwN2E0ODc3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWMxNGE2NWQ0ZjdmMWYyMmY2YTI0ZjhmM2JjMThlZDYyZGFhNDY0MzQ1MWJlZGMzYWRiNzRhNzIzMGI5Y2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eOIp2X-nGDowYDIFHeimK5E9-cEZelZZT31WHNXoePY) ![image](https://private-user-images.githubusercontent.com/113369937/335321955-8df3f4a2-3ef7-4661-b6f6-246c53ecf511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDQxNjAsIm5iZiI6MTcxNzI0Mzg2MCwicGF0aCI6Ii8xMTMzNjk5MzcvMzM1MzIxOTU1LThkZjNmNGEyLTNlZjctNDY2MS1iNmY2LTI0NmM1M2VjZjUxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTNhMGI5ZDczYjc2NDNiM2JmNmJiNTYyMmI4N2NmMjVjMjU4YjAxYzYxZDBhODVhNDI0MWNhMDNmZWMyNmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BCPxmFylJgc0kAAqN_5yp0iPL70eVvayJOY0IYJ6e8Q)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
