### ISSUE TITLE
BUG: Uniformity Not Maintained in Dark Mode and Light Model in Home Page Box

### ISSUE THREAD

**Issue by aarushi-taori** [anuragverma108/SwapReads#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Uniformity Not Maintained in Dark Mode and Light Model in Home Page Box

![image](https://github.com/anuragverma108/SwapReads/assets/113369937/c719ef56-b09a-4a15-950f-342e55eb9bfc)
![image](https://github.com/anuragverma108/SwapReads/assets/113369937/d66944f2-92f1-4204-9762-18e9a89f551e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aarushi-taori** [comment]
@RitiChandak Please assign me this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
