### ISSUE TITLE
DOC:add hover effect and change the font color of "select language" icon

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#1087]
### What's wrong with the existing documentation

add white font color and add a  hover on border of the icon 

### Add ScreenShots

<img width="213" alt="Screenshot 2024-05-30 at 10 47 46 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/c5dc00b6-30af-4db7-bc76-5d8a8988da7f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> add white font color and add a hover on border of the icon
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-05-30 at 10 47 46 PM" width="213" src="https://private-user-images.githubusercontent.com/145912232/335323060-c5dc00b6-30af-4db7-bc76-5d8a8988da7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM5NzMsIm5iZiI6MTcxNzI0MzY3MywicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzIzMDYwLWM1ZGMwMGI2LTMwYWYtNGRiNy1iYzc2LTVkOGE4OTg4ZGE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDg4ZTI1N2Y1NmY2YzVlODE2ODgwZGQ1ZWFmODY3Y2QyYjE4NWY0NzRiOGM1YjMxYTlhY2U5N2VhNzkyZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0NBCHp35zEb7dWKRGm3Q90EWd_B0tRyrrj9Jue7jYt8">
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
