### ISSUE TITLE
DOC:increase the width of dropdown content at menu

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#1088]
### What's wrong with the existing documentation

by increasing the width of dropdown
the alignment of font are in straight line like that
<img width="305" alt="Screenshot 2024-05-30 at 11 35 10 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/e76ff256-920f-4af0-a82e-33aec82d73a4">

### Add ScreenShots

<img width="177" alt="Screenshot 2024-05-30 at 1 27 04 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/c1ac86f0-9287-4dee-aba8-d7de704aa374">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> by increasing the width of dropdown the alignment of font are in straight line like that <img alt="Screenshot 2024-05-30 at 11 35 10 PM" width="305" src="https://private-user-images.githubusercontent.com/145912232/335328927-e76ff256-920f-4af0-a82e-33aec82d73a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM5OTcsIm5iZiI6MTcxNzI0MzY5NywicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzI4OTI3LWU3NmZmMjU2LTkyMGYtNGFmMC1hODJlLTMzYWVjODJkNzNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjdlNzk2NDk5ODU0NGFmMjE3MzJmY2FlMDI2ZTE3ODhiYTZiMzFhNDQ3MTViY2RmOWQyNjEwYTRhMWFmYmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ZW2fyQ1cO2tTxYvHLdyWE0Obb6LYNqKFIaBRkqmXbk">
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-05-30 at 1 27 04 PM" width="177" src="https://private-user-images.githubusercontent.com/145912232/335327928-c1ac86f0-9287-4dee-aba8-d7de704aa374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDM5OTcsIm5iZiI6MTcxNzI0MzY5NywicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzI3OTI4LWMxYWM4NmYwLTkyODctNGRlZS1hYmE4LWQ3ZGU3MDRhYTM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTIzMTZmY2E0YzUzYWE4NzU4MzA1NDRmN2QxYjUwOWNhYzFkMDU1YzUxNGI3MjUzMTdlZmE1NjIyMDkyMDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XhW5JgVNVsJ1OZKXI3HZOTz8rQRXahZ-CAWqQttLE-A">
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
