### ISSUE TITLE
DOC:add feedback inplace of contact

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#1089]
### What's wrong with the existing documentation

write feedback in place of wriiten contact

### Add ScreenShots

<img width="753" alt="Screenshot 2024-05-30 at 10 58 58 PM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/08a760cf-420f-46cb-bd27-a5cc7ecf5536">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> write feedback in place of wriiten contact
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-05-30 at 10 58 58 PM" width="753" src="https://private-user-images.githubusercontent.com/145912232/335330115-08a760cf-420f-46cb-bd27-a5cc7ecf5536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDQzMjAsIm5iZiI6MTcxNzI0NDAyMCwicGF0aCI6Ii8xNDU5MTIyMzIvMzM1MzMwMTE1LTA4YTc2MGNmLTQyMGYtNDZjYi1iZDI3LWE1Y2M3ZWNmNTUzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjEzNWRmMDYzZTE0MzFjZmRiYzBmNDZjNzZiZmFlNWIyZTM4MDc5ZGM3YmFhODhiNzFhYjU0Nzc5ZDYzNTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RlGnIvaDKL6ukBdOjcFlf5n0tytTUCJMAEKNLYUkYbQ">
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
