### ISSUE TITLE
Feature: Add hover-effect on social media icons 

### ISSUE THREAD

**Issue by Harshsaini001** [anuragverma108/SwapReads#1090]
### Describe the feature

The hover effect on social media icons is an interactive design feature that enhances the visual appeal and user experience of your website.

### Add ScreenShots

![Screenshot 2024-05-30 234514](https://github.com/anuragverma108/SwapReads/assets/127672737/74173e17-756b-4321-b44d-de704920add1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshsaini001** [comment]
Hey @anuragverma108 , I want to add hover on social media icons . Please assign this issue to me under GSSOC.

**Comment by ayush-jsrt** [comment]
Hey there @anuragverma108. I've made the required changes and started a pull request. Let me know if any changes are needed. Thanks!
Also could you please add the GSSOC label to the issue.

**Comment by anuragverma108** [comment]
@Harshsaini001 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
