### ISSUE TITLE
BUG: order of elements in some sections

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The map should come after form in "Contact " section
The form should also have better UI

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The map should come after form in "Contact " section The form should also have better UI
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
