### ISSUE TITLE
Dropdown 'More' not working

### ISSUE THREAD

**Issue by m3kvt** [anuragverma108/SwapReads#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In mobile view the more functionality is not working. Nothing is displayed on clicking the dropdown.

https://github.com/anuragverma108/SwapReads/assets/98379619/3d6c6a46-bc95-4406-9439-036735c5fa55

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@anuragverma108 Kindly assign me this task.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> In mobile view the more functionality is not working. Nothing is displayed on clicking the dropdown.
> 
>  SwapReads.-.Google.Chrome.2024-05-31.03-04-34.mp4 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue
> 
> @anuragverma108 Kindly assign me this task.

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by m3kvt** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

Sure. I will do the same

**Comment by huamanraj** [comment]
> Hi @anuragverma108 , I won't be able to solve this. Can you assign this to someone else who raised the same issue?

its okay 👍
