### ISSUE TITLE
BUG:firebase Login and signup broken again

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The normal login and signup functionalities are broken again I am guessing due to classname or id changes of the elements. Here is a video:

https://github.com/anuragverma108/SwapReads/assets/32983571/7daa7636-19be-48cf-8375-cf3f83217f14

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
