### ISSUE TITLE
Subtle scroll animations.

### ISSUE THREAD

**Issue by yashi-15** [anuragverma108/SwapReads#11]
I want to add subtle scroll animations on the website page. Adding these subtle animations will make website look more modern and a bit dynamic improving the user experience.

Kindly assign this issue to me under GSSoC'24, so that I can start working on it.

**Comment by Ankesh2004** [comment]
I have experience of adding scroll or in-view animations using Framer Motion. 
Kindly assign this issue to me under GSSoC'24, so that I can start working on it.

**Comment by anuragverma108** [comment]
Assigned @yashi-15

**Comment by anuragverma108** [comment]
Any Updates @yashi-15. Are you working on the issue ??

**Comment by yashi-15** [comment]
> Any Updates @yashi-15. Are you working on the issue ??

Yes I am working, I will make the PR till evening.
