### ISSUE TITLE
BUG: Unresponsive Login Page Behaviour

### ISSUE THREAD

**Issue by aryansharma220** [anuragverma108/SwapReads#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/133234867/585189be-3825-4437-ba96-5fd26fe4f0fd

The login Page is not responsive.
@anuragverma108 Please assign it to me so that i can make the changes you might like.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.
