### ISSUE TITLE
Feat:Improve navbar on tablet and mobile

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#1101]
### Describe the feature

The navbar on tablet is overflowing and on mobile can be improved by making it fill the width of the screen and bringing brand on the navbar middle.

### Add ScreenShots

tablet;
![Screen Shot 2024-05-31 at 10 12 12](https://github.com/anuragverma108/SwapReads/assets/32983571/e9845b54-6723-4579-9b5c-4d8e0fc99f9d)

mobile:
![Screen Shot 2024-05-31 at 10 12 33](https://github.com/anuragverma108/SwapReads/assets/32983571/f5d3e397-943e-4b03-b40e-2a849a2e2835)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
