### ISSUE TITLE
Feat: Improving the UI of Hero Section for Mobile devices

### ISSUE THREAD

**Issue by Sypher0Dronzer** [anuragverma108/SwapReads#1102]
### Describe the feature

For mobile devices the hero section takes up a lot of vertical space resulting in additional scrolling, resizing of the texts along with its alignment needs to be done to improve the user experience for mobile users

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/83546205/ad752ebc-e926-4d9b-98e6-e80b837a3901)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sypher0Dronzer** [comment]
please assign this issue to me @anuragverma108

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
