### ISSUE TITLE
BUG: Mode changing button is bot working  ion signup and login page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The mode changing button is not working on login and signup page when i am changing the mode then the mode actually doesn't changing .

https://github.com/anuragverma108/SwapReads/assets/118350936/861fb28b-ffa5-43a4-9129-f79166f212ee

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Praneeth-2602** [comment]
Issue already exists ig #1085

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
