### ISSUE TITLE
BUG: Link add to company logo

### ISSUE THREAD

**Issue by MadMax1311** [anuragverma108/SwapReads#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description 

Link add to company logo (Swap Reads) When we click, it refresh the page.

![image](https://github.com/anuragverma108/SwapReads/assets/140179838/294c3089-920c-47a9-9d01-67356104e3c3)

Please, @anuragverma108 assign me this issue with label.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mukund-gpt** [comment]
@anuragverma108 plz assign to me, i will manage it

**Comment by anuragverma108** [comment]
@MadMax1311 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
