### ISSUE TITLE
Improvement in footer of Login page 

### ISSUE THREAD

**Issue by Deekshashakyawal** [anuragverma108/SwapReads#1109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to contribute under GSSOC'24 . Please assign me this issue . 
I want to improve the footer of login page , as its not looking appropriate , It is looking like a box that is very odd in the UI.

![Screenshot 2024-05-31 125509](https://github.com/anuragverma108/SwapReads/assets/119758705/2a8edbc8-65af-4815-9802-5dd0e5a9a3e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> I want to contribute under GSSOC'24 . Please assign me this issue . I want to improve the footer of login page , as its not looking appropriate , It is looking like a box that is very odd in the UI.
> 
> ![Screenshot 2024-05-31 125509](https://private-user-images.githubusercontent.com/119758705/335483627-2a8edbc8-65af-4815-9802-5dd0e5a9a3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg2MjksIm5iZiI6MTcxNzI1ODMyOSwicGF0aCI6Ii8xMTk3NTg3MDUvMzM1NDgzNjI3LTJhOGVkYmM4LTY1YWYtNDgxNS05ODAyLTVkZDBlNWE5YTNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjEyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDJjZTY3ZGU1NzY1OTJkMDYzNWZiYjQwNDI3N2Y3ZTRhYzExMzdhODI2YjhiYjhjYzQ5ZDNlMjJjYmM0OWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.412zeMPgZXR_EeIpdC2aZraI4pYWEC5OrTOAzRk1Q-A)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
