### ISSUE TITLE
Adding a feature of "To Read Later " webpage 

### ISSUE THREAD

**Issue by suhanigupta23** [anuragverma108/SwapReads#1110]
### Describe the feature

We can add a webpage of "TO READ LATER" just like a "To do" or like a wish list which can be linked to the free E-Books section. Where we can add the books to READ LATER section.

### Add ScreenShots

<img width="1251" alt="Screenshot 2024-05-31 at 1 59 06 PM" src="https://github.com/anuragverma108/SwapReads/assets/144280247/f64c1b26-deec-4c3c-90f7-065fe1e5cf9d">
<img width="983" alt="Screenshot 2024-05-31 at 1 59 37 PM" src="https://github.com/anuragverma108/SwapReads/assets/144280247/f5c12c6b-ab3d-467e-8dac-663d227cf9ca">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
