### ISSUE TITLE
BUG: Spacing of multiple sections in dark mode

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some sections in home page does not have proper spacing in dark mode 

i would like to add proper spacing to each section of the home page ,so it does not look congested and each section will look same
![Screenshot 2024-05-31 144830](https://github.com/anuragverma108/SwapReads/assets/85826117/e7f14e20-cc6e-4cce-bea7-366a744529f6)
![Screenshot 2024-05-31 144843](https://github.com/anuragverma108/SwapReads/assets/85826117/43784790-e273-4ee1-8fea-da2f3b6308c3)

Some are good-
![Screenshot 2024-05-31 144913](https://github.com/anuragverma108/SwapReads/assets/85826117/38fc4839-9a0d-4f15-bfb8-871d4bd5438e)

It is also good in light mode-
![Screenshot 2024-05-31 144932](https://github.com/anuragverma108/SwapReads/assets/85826117/94e4a07f-82e6-4232-a1aa-9435eb706962)

After proper spacing, it would be more attractive
Kindly assign me this issue.
best regards.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
