### ISSUE TITLE
BUG: Toggle button alignment in dark mode

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-31 145421](https://github.com/anuragverma108/SwapReads/assets/85826117/547b9338-acfe-4075-bbbf-d133fea3313a)
![Screenshot 2024-05-31 145432](https://github.com/anuragverma108/SwapReads/assets/85826117/7028bc7f-c479-4967-84c9-fc6b413c38e9)
![Screenshot 2024-05-31 145353](https://github.com/anuragverma108/SwapReads/assets/85826117/e93b47da-89b9-409f-ad51-d393b065176e)
![Screenshot 2024-05-31 145402](https://github.com/anuragverma108/SwapReads/assets/85826117/6d4dee8d-5296-4eaa-be94-ca64362db498)
The toggle button alignment is good in light mode but it needs to be corrected in dark mode

Kindly assign me this issue.
Best regards

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> ![Screenshot 2024-05-31 145421](https://private-user-images.githubusercontent.com/85826117/335522954-547b9338-acfe-4075-bbbf-d133fea3313a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg3NTcsIm5iZiI6MTcxNzI1ODQ1NywicGF0aCI6Ii84NTgyNjExNy8zMzU1MjI5NTQtNTQ3YjkzMzgtYWNmZS00MDc1LWJiYmYtZDEzM2ZlYTMzMTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTI2MGE5ZDNhMmIxMDBmZTEyYjYzY2FiYjgyNWQ2YjgxMDRkMjFkN2RlNTNkNGU4ODM0ODRjYjc4NjhjM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oohMcNhK_HMdlSIZS55OpNAWswC1hMda_EiQ1ExmTPo) ![Screenshot 2024-05-31 145432](https://private-user-images.githubusercontent.com/85826117/335522970-7028bc7f-c479-4967-84c9-fc6b413c38e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg3NTcsIm5iZiI6MTcxNzI1ODQ1NywicGF0aCI6Ii84NTgyNjExNy8zMzU1MjI5NzAtNzAyOGJjN2YtYzQ3OS00OTY3LTg0YzktZmM2YjQxM2MzOGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTNkMzYxYTU4MTRiNjU3ZTYwNDZjNmYzZTkxMzYzOTc4NWQ4NzcyNmQ0MjBkN2M0NjYxZGUwMjJmNTI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0-Qlq64QLcEIOOVCEW44Yo_KK3_vle-TP_u-Jx1TGAE) ![Screenshot 2024-05-31 145353](https://private-user-images.githubusercontent.com/85826117/335522980-e93b47da-89b9-409f-ad51-d393b065176e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg3NTcsIm5iZiI6MTcxNzI1ODQ1NywicGF0aCI6Ii84NTgyNjExNy8zMzU1MjI5ODAtZTkzYjQ3ZGEtODliOS00MDlmLWFkNTEtZDM5M2IwNjUxNzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNWNiNDZmMGM4OWVlZDA5NTFlMzA5OGQ1ZGMyYzk4ZTlhN2MzY2ZlZmMzZTc4NDU5MjQ5Yzg5MDA3OWYwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnGVrnCi91gSFAqaW6dA2G4DSTGqED18OjNkvEtVhCc) ![Screenshot 2024-05-31 145402](https://private-user-images.githubusercontent.com/85826117/335522988-6d4dee8d-5296-4eaa-be94-ca64362db498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg3NTcsIm5iZiI6MTcxNzI1ODQ1NywicGF0aCI6Ii84NTgyNjExNy8zMzU1MjI5ODgtNmQ0ZGVlOGQtNTI5Ni00ZWFhLWJlOTQtY2E2NDM2MmRiNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNjM3NjdmYzIzOGZiYzE4NGM5MjFkYmRjN2M5YWVjMWMzZWYwNmQ4M2ZmYWJiMDhlNTcxN2YxNmY2ZjFlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6mGVun9u92aXvymMEEnCbKtvQXWSRg1pAK6yU67loEk) The toggle button alignment is good in light mode but it needs to be corrected in dark mode
> 
> Kindly assign me this issue. Best regards
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
