### ISSUE TITLE
Feat: Add parallax effect on "free e-books"

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#1115]
### Describe the feature

I would like to add parallax effect on each book.
Just like I did in the book of home-page

It will match the theme and make the website more user interactive.

### Add ScreenShots

![Screenshot 2024-05-31 150614](https://github.com/anuragverma108/SwapReads/assets/85826117/b2d09f51-e644-41ab-97f3-75150821eb33)

https://github.com/anuragverma108/SwapReads/assets/85826117/6efa93fc-82a7-4171-be3a-b9bed12eaa10

On hovering it will move, just like the image in home page. It was done by me only

Kindly assign me this issue.
Best regards

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> I would like to add parallax effect on each book. Just like I did in the book of home-page
> 
> It will match the theme and make the website more user interactive.
> 
> ### Add ScreenShots
> ![Screenshot 2024-05-31 150614](https://private-user-images.githubusercontent.com/85826117/335529962-b2d09f51-e644-41ab-97f3-75150821eb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg4MDksIm5iZiI6MTcxNzI1ODUwOSwicGF0aCI6Ii84NTgyNjExNy8zMzU1Mjk5NjItYjJkMDlmNTEtZTY0NC00MWFiLTk3ZjMtNzUxNTA4MjFlYjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE2MTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDI0YWM0NTkwMmFmMWFkZTMyNTllMDdmM2YyNzgyODUzY2E4ODlmNWU0NWE2ODY0ZWVmNzY2ZDAyNmYyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TJ5xVUKymSVqFTQ_CoqRWUv57ULAJv48yuqiEOj9CQs)
> 
>  Recording.2024-05-10.202809.mp4 
> On hovering it will move, just like the image in home page. It was done by me only
> 
> Kindly assign me this issue. Best regards
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
