### ISSUE TITLE
BUG: Add navbar and footer to book recommendation page

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no navbar and footer in the book recommendation page.
I would like to add it.
![image](https://github.com/anuragverma108/SwapReads/assets/130165687/2eb2408a-5509-4b4a-947f-aec74f687a8b)
Please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> There is no navbar and footer in the book recommendation page. I would like to add it. ![image](https://private-user-images.githubusercontent.com/130165687/335531496-2eb2408a-5509-4b4a-947f-aec74f687a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTg4ODAsIm5iZiI6MTcxNzI1ODU4MCwicGF0aCI6Ii8xMzAxNjU2ODcvMzM1NTMxNDk2LTJlYjI0MDhhLTU1MDktNGI0YS05NDdmLWFlYzc0ZjY4N2E4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmY5MDY2OTE1YWIxNGZkYTk4ODA2MWM2ZTBkYzgyYTgxNmE4ZTU3ZDg2Nzk1ZTM5YjczYzhiMzQ3NDQ0YzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n7bogeGhorKIR_8KqwjvHJR2O0CGcLM8-mShpd1Uuv4) Please assign this task to me
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
