### ISSUE TITLE
BUG : Not Proper Margin top and Margin Bottom in Blocks

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to give proper margin from top and bottom for better view.

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/159fbfb6-48e9-4791-bb52-a3e900339082)

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/16d54ea5-395d-4d50-8523-017f09da0a79)

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/6a38f9cb-3bac-42fc-8a6f-b7127496af62)

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/98d48847-6537-4773-a187-a52bc5081969)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@anuragverma108 please assign me this task.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> I want to give proper margin from top and bottom for better view.
> 
> ![image](https://private-user-images.githubusercontent.com/126322584/335538101-159fbfb6-48e9-4791-bb52-a3e900339082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkwODIsIm5iZiI6MTcxNzI1ODc4MiwicGF0aCI6Ii8xMjYzMjI1ODQvMzM1NTM4MTAxLTE1OWZiZmI2LTQ4ZTktNDc5MS1iYjUyLWEzZTkwMDMzOTA4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjE5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTRjNDA3NmZhOWNiNDZiZWNkMzgxZjkxYWRlZGUzYzRhZWM2OGUwMzg2MjViYjdlZGUxNTM3ZGNiMTYxNGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wgl2KZ8WFFAnsoDux7m2nYzY7gOb_nvj73bg6MMPU8w)
> 
> ![image](https://private-user-images.githubusercontent.com/126322584/335538206-16d54ea5-395d-4d50-8523-017f09da0a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkwODIsIm5iZiI6MTcxNzI1ODc4MiwicGF0aCI6Ii8xMjYzMjI1ODQvMzM1NTM4MjA2LTE2ZDU0ZWE1LTM5NWQtNGQ1MC04NTIzLTAxN2YwOWRhMGE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjE5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzYxMjFiMDFjM2UyYjgzMTI5MGQwYzcyNjE5ZTk1ZDllOGY4ZjhkMmQxMTAyNmViZjhhOWJmODAzZWUyMGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I1ErvnL9Bjwb7pySGSXV6QFR8qB5uWqIwF9hdqpnuVA)
> 
> ![image](https://private-user-images.githubusercontent.com/126322584/335538335-6a38f9cb-3bac-42fc-8a6f-b7127496af62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkwODIsIm5iZiI6MTcxNzI1ODc4MiwicGF0aCI6Ii8xMjYzMjI1ODQvMzM1NTM4MzM1LTZhMzhmOWNiLTNiYWMtNDJmYy04YTZmLWI3MTI3NDk2YWY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjE5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmEzZmZjMzNkNDBiZDk0NzUyZjE3NDhkYjdiMzM3NGE0MzgwNzgzMjI1MGM1MzdjMTExZWZhMzkxY2Y5MDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8FgedcK68NZC4Mhu9z--MsuGBTYSlPxfmvZOJ0HV_U)
> 
> ![image](https://private-user-images.githubusercontent.com/126322584/335538386-98d48847-6537-4773-a187-a52bc5081969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkwODIsIm5iZiI6MTcxNzI1ODc4MiwicGF0aCI6Ii8xMjYzMjI1ODQvMzM1NTM4Mzg2LTk4ZDQ4ODQ3LTY1MzctNDc3My1hMTg3LWE1MmJjNTA4MTk2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjE5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWIxYzU4OTEyYmRiZDY3MGEzY2YwNzdjYzdlNjRhYmQ2OTdjMTg2YjZkNGMyMjRjZjNiMWU2NjY0OWJiYjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P8UKtHfdqB6rIc5lEhFCPKbDFNIyCFrsWoljwSGm1n8)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
