### ISSUE TITLE
BUG: Add Hover text in Social media 

### ISSUE THREAD

**Issue by AkhilaSunesh** [anuragverma108/SwapReads#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/140897461/a1d68d89-1a29-48ec-91be-a32434502c9a)
Add a hover text so that the user will have an idea where he or she is clicking (on which icon).

Also increase the size of the icons, the cursor is blocking the icons.
Kindly assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
