### ISSUE TITLE
BUG: Quick links not working

### ISSUE THREAD

**Issue by AkhilaSunesh** [anuragverma108/SwapReads#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/140897461/edddd235-1ab6-4c8e-963a-46539549a021)
Quick links not working in the footer.

Kindly assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
