### ISSUE TITLE
BUG: Footer links in free e-books page not working

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer links on click should direct it to the respective sections.
For now they are inactive

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/88c5b0d3-9692-441b-9ff8-ffc8398c6675)

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/2735a239-6efd-4f1d-aadd-5b15a00f7c87)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@anuragverma108 Please assign this issue to me

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The footer links on click should direct it to the respective sections. For now they are inactive
> 
> ![image](https://private-user-images.githubusercontent.com/126975547/335557355-88c5b0d3-9692-441b-9ff8-ffc8398c6675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkzNzIsIm5iZiI6MTcxNzI1OTA3MiwicGF0aCI6Ii8xMjY5NzU1NDcvMzM1NTU3MzU1LTg4YzViMGQzLTk2OTItNDQxYi05ZmY4LWZmYzgzOThjNjY3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmY2M2E2MmIxMTg3MjViNzgyNWUwNmM3MTA2YWVkNDgwMjE3NDVlNDQxNGJlMzllZDA3OTVjODI2NTk4NDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2WtwUvFMR8Q2nHJTbIOSxILHrWY32l4Zerwr_oq65Ns)
> 
> ![image](https://private-user-images.githubusercontent.com/126975547/335557423-2735a239-6efd-4f1d-aadd-5b15a00f7c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTkzNzIsIm5iZiI6MTcxNzI1OTA3MiwicGF0aCI6Ii8xMjY5NzU1NDcvMzM1NTU3NDIzLTI3MzVhMjM5LTZlZmQtNGYxZC1hYWRkLTViMTVhMDBmN2M4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWRlMTY3NjJjNjg5NDNmOWYxMDcxYTc5YTJjN2Q4Y2ZjMjExMjQ4ZmMyMjBhNjgzODg4MjIxZWUxNjI5MzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l-cK2TnMlkNONDmO28uWFQgQD6mYvUIekaMcg-02k9A)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by ayush-848** [comment]
@huamanraj Assign this issue to me.
