### ISSUE TITLE
Feat: Social Media Icons: Adding Hover Effects for Engagement

### ISSUE THREAD

**Issue by thevijayshankersharma** [anuragverma108/SwapReads#1122]
### Describe the feature

Elevate the interactivity of your website by incorporating captivating hover effects to your social media icons. This tutorial will guide you through the process of implementing stylish hover animations that catch the eye and encourage user engagement. Whether you're a seasoned web developer or just starting out, you'll learn how to effortlessly integrate these effects using CSS and HTML, making your website not only visually appealing but also more interactive. Engage your audience like never before with this simple yet effective enhancement to your social media presence!

### Add ScreenShots

After the issue has been assigned.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
