### ISSUE TITLE
Feat: Add navbar to about page

### ISSUE THREAD

**Issue by MadMax1311** [anuragverma108/SwapReads#1127]
### Describe the feature

Add a navbar to the about page that helps users to easily navigate.

Please, @anuragverma108 assign me this issue with label 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/140179838/2aaf0e53-5768-46a4-85fb-839145410fb1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
