### ISSUE TITLE
Visual appeal of the login/signup page.

### ISSUE THREAD

**Issue by justmirr** [anuragverma108/SwapReads#113]
### Describe the feature

Scroll bars in login pages are not a good UI practice. I'll reshape the page into two grids with text with the updated font on the left grid and the login/signup box on the right while maintaining responsiveness. I'll also make the copyright text visually match the page's rest for better appeal. Please assign this to me.

### Add ScreenShots

![loginpage](https://github.com/anuragverma108/SwapReads/assets/75358919/466c0f23-8ce0-4bba-96f8-1bdf1c512832)
![sample](https://github.com/anuragverma108/SwapReads/assets/75358919/4364932c-06a7-4364-815d-d62238327f7d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by khushilatey16** [comment]
Pls Assign this issue to me under the label of GSSOC'24 . I assure u that I'll update the visuals of login/signup page with the help of my UI skills

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Scroll bars in login pages are not a good UI practice. I'll reshape the page into two grids with text with the updated font on the left grid and the login/signup box on the right while maintaining responsiveness. I'll also make the copyright text visually match the page's rest for better appeal. Please assign this to me.
> 
> ### Add ScreenShots
> 
> ![loginpage](https://github.com/anuragverma108/SwapReads/assets/75358919/466c0f23-8ce0-4bba-96f8-1bdf1c512832)
> ![sample](https://github.com/anuragverma108/SwapReads/assets/75358919/4364932c-06a7-4364-815d-d62238327f7d)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue


@justmirr  Work on it and collaborate with @khushilatey16 to get a better result! 

i am the mentor of this project so reach out to me for any help!

**Comment by justmirr** [comment]
Sure @huamanraj I'll start the work right away. @khushilatey16

**Comment by RitiChandak** [comment]
@justmirr @khushilatey16 any updates?
