### ISSUE TITLE
BUG: In login page ,it shows logout option without login.

### ISSUE THREAD

**Issue by rony6432** [anuragverma108/SwapReads#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![swap reader ishue](https://github.com/anuragverma108/SwapReads/assets/119131859/989af98d-1846-4cbd-86a2-2cd129aaf32b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> ![swap reader ishue](https://private-user-images.githubusercontent.com/119131859/335613965-989af98d-1846-4cbd-86a2-2cd129aaf32b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk1NzEsIm5iZiI6MTcxNzI1OTI3MSwicGF0aCI6Ii8xMTkxMzE4NTkvMzM1NjEzOTY1LTk4OWFmOThkLTE4NDYtNGNiZC04NmEyLTJjZDEyOWFhZjMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2NhOTZjNjE4YmIwNzhjOWVjZWQ5Mjc4Njg0Y2UwNDBlODdkNmU3NWQyYzM4ZTRkMDYyYTJjOGUyNmFiZTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O3J2DJzdBo2luOzQ3srGysa2rXVmj0NnQhA0dABmN3A)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
