### ISSUE TITLE
Feat: Alignment  of header properly 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1132]
### Describe the feature

I think the header content is not properly aligned 

### Add ScreenShots

![Screenshot 2024-05-31 205020](https://github.com/anuragverma108/SwapReads/assets/118350936/27431594-2ffb-4c31-9416-7aba0fc99363)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> I think the header content is not properly aligned
> 
> ### Add ScreenShots
> ![Screenshot 2024-05-31 205020](https://private-user-images.githubusercontent.com/118350936/335632103-27431594-2ffb-4c31-9416-7aba0fc99363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk1NDMsIm5iZiI6MTcxNzI1OTI0MywicGF0aCI6Ii8xMTgzNTA5MzYvMzM1NjMyMTAzLTI3NDMxNTk0LTJmZmItNGMzMS05NDE2LTdhYmEwZmM5OTM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA2OTM0MWE0YTRiYTlmYzQ0MDMxODY3ZjZjNGRjY2Y3ODA0ZTNhNGE0Nzg0M2RkZDkxMzc4Njg4OTBkZDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xi5Nkfvk2N8QU8Ep6ir2j99bn2M1MfYJRGucJaYkCqQ)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
