### ISSUE TITLE
BUG: Connect with a reader button is not properly aligned 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The connect with a reader button is not properly aligned in the small screen and is overflowing from the container .
![Screenshot 2024-05-31 205229](https://github.com/anuragverma108/SwapReads/assets/118350936/1b394f3f-7990-4757-b26e-762cc2639b1b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The connect with a reader button is not properly aligned in the small screen and is overflowing from the container . ![Screenshot 2024-05-31 205229](https://private-user-images.githubusercontent.com/118350936/335632811-1b394f3f-7990-4757-b26e-762cc2639b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk1MTEsIm5iZiI6MTcxNzI1OTIxMSwicGF0aCI6Ii8xMTgzNTA5MzYvMzM1NjMyODExLTFiMzk0ZjNmLTc5OTAtNDc1Ny1iMjZlLTc2MmNjMjYzOWIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDU3YWRkYzY5Mzg4Njg5MTU2MGUyOWFkMDlmYThhNmY3NTk2ZTlkZDIxOTg0NzgzNWU5OWU4NWI3NDUxYWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pAcnpMfPBBjsnWO_t9QfuS2vC2NyC-PYk7VOmh4G8n4)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
