### ISSUE TITLE
BUG: Navbar is not properly responsive for Small devices

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After clicking on hamburger menu i found that the contents from the menu is overflowing and giving scroll but by just increase the height by 10px we can fix that .
![Screenshot 2024-05-31 205530](https://github.com/anuragverma108/SwapReads/assets/118350936/32c10a27-05a7-47fc-9059-b1100cee145c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Azhar-0401** [comment]
is your feature request related to a problem? Please describe.
Currently Navbar is not properly responsive for Small devices. 

Describe the solution you'd like
Adding CSS property for responsive the website

Additional context
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> After clicking on hamburger menu i found that the contents from the menu is overflowing and giving scroll but by just increase the height by 10px we can fix that . ![Screenshot 2024-05-31 205530](https://private-user-images.githubusercontent.com/118350936/335633733-32c10a27-05a7-47fc-9059-b1100cee145c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk0NzEsIm5iZiI6MTcxNzI1OTE3MSwicGF0aCI6Ii8xMTgzNTA5MzYvMzM1NjMzNzMzLTMyYzEwYTI3LTA1YTctNDdmYy05MDU5LWIxMTAwY2VlMTQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDNmMzdjMWRlMTUwMTA3ZDc2ZjkyMjc3ZTIxYTFlMzQ2OGNlOGE5Y2I5Y2NiZTY3ODA4MGQ1OTY0MjI2NTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.clugM9jMjeFU7Iv80mSCl_k3zTHb_iF2R316MYEM3ow)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Snehapandey07** [comment]
Hey @anuragverma108 will you please assign me this issue under GSSOC 24, I would be happy to contribute!
