### ISSUE TITLE
BUG: Mode toggling button is not aligned properly 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The mode changing button and the hamburger menu are not at the same level and aligned properly .

![Screenshot 2024-05-31 205714](https://github.com/anuragverma108/SwapReads/assets/118350936/2d41d867-8f06-43be-b928-e8bad4def2ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The mode changing button and the hamburger menu are not at the same level and aligned properly .
> 
> ![Screenshot 2024-05-31 205714](https://private-user-images.githubusercontent.com/118350936/335634116-2d41d867-8f06-43be-b928-e8bad4def2ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk0NDcsIm5iZiI6MTcxNzI1OTE0NywicGF0aCI6Ii8xMTgzNTA5MzYvMzM1NjM0MTE2LTJkNDFkODY3LThmMDYtNDNiZS1iOTI4LWU4YmFkNGRlZjJjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjI1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTliYTllODBjYzcyNzllODY3NjYyM2IwNWFkNDc5ZjI0NmJhZTg3N2ZjZTBiNjYyMGViY2IwY2U2NmY1YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSerWn1JaAU4sPqExBP95N4zyEs3yzxvNeKGIBDkpW4)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Snehapandey07** [comment]
Hey @anuragverma108 will you please assign me this issue under GSSOC 24, I would be happy to contribute!
