### ISSUE TITLE
BUG: Overlapping of chatbot and Go to top buttons !

### ISSUE THREAD

**Issue by SiddharthaArepalli** [anuragverma108/SwapReads#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I will fix the overlaping of the chatbot and Go to top buttons.
![Screenshot 2024-05-31 230605](https://github.com/anuragverma108/SwapReads/assets/140429954/43e75f80-ac1e-4702-a267-86b2a52217d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by SiddharthaArepalli** [comment]
@huamanraj 
Done with the task I have made a PR plz checkout !!
