### ISSUE TITLE
Align Play Now button

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1139]
It would be great if we align the play now button with same indent level as of text

![Screenshot 2024-05-31 235544](https://github.com/anuragverma108/SwapReads/assets/142779809/29aadefe-9e5f-425c-a79b-824d92a11404)

**Comment by anuragverma108** [comment]
@root-0101 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by anuragverma108** [comment]
You have not been assigned to work on this issue. This violates our open source code of conduct. 
Please focus on the issue you have been assigned to.

**Comment by Snehapandey07** [comment]
Hey @anuragverma108 will you please assign me this issue under GSSOC 24, I would be happy to contribute!

**Comment by Aashka19** [comment]
Hey @anuragverma108 will you please assign me , i would be happy to contribute.
