### ISSUE TITLE
Add review page

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#114]
### Describe the feature

I want to add a review page as there is a review link in a footer , so i want to create that page.

### Add ScreenShots

<img width="112" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/145490348/d7d74383-2aaf-41ef-ae84-31adc19a8d6e">

Please assign me this issue under GSS0C'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by khushilatey16** [comment]
Please assign me this issue under GSS0C'24. I assure that I'll fix this issue by making  a proper review page for SwapReads
