### ISSUE TITLE
Read more hover effect

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1140]
As now the hover effect of Read more button makes if fade and is hard to read for the users. 

![Screenshot 2024-05-31 235603](https://github.com/anuragverma108/SwapReads/assets/142779809/492bbb87-031b-426a-b733-b42d2249d478)

**Comment by anuragverma108** [comment]
Assigned! @root-0101 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Aashka19** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me ?
