### ISSUE TITLE
BUG: Chatbot Design Issues on Smaller Devices and slow response

### ISSUE THREAD

**Issue by eiva078** [anuragverma108/SwapReads#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The chatbot has significant design issues on smaller devices. The interface is not optimized for mobile screens, causing the chatbot to go out of the screen, making it difficult to use. Additionally, the chatbot frequently fails to generate responses, leaving users without necessary interactions or information. The CSS implementation needs to be reviewed to ensure proper alignment and consistent styling across devices. A thorough design for mobile responsiveness and an investigation into the backend response mechanism are essential to resolve these problems and enhance user experience.

![Screenshot 2024-06-01 055038](https://github.com/anuragverma108/SwapReads/assets/100897650/1c2b8437-8884-4823-a246-378236afd85c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by eiva078** [comment]
@anuragverma108 Sir this issue has not been fixed but someone has closed this issue. What to do sir??

**Comment by huamanraj** [comment]
> @anuragverma108 Sir this issue has not been fixed but someone has closed this issue. What to do sir??

![Screenshot_2024-06-02-05-29-45-393_com.android.chrome.jpg](https://github.com/anuragverma108/SwapReads/assets/113578582/944ca166-2676-420b-9c4b-65e71ede0ab0)

hey 👋 ! 
i am the mentor! and sorry to not give you enough justification about closing the issue but chatbot is working fine on every small screen! you are using dev tools in the wrong way buddy!
