### ISSUE TITLE
 [BUG] Hover Card Display Issue

### ISSUE THREAD

**Issue by Rahul91025** [anuragverma108/SwapReads#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

** Describe the bug **
When hovering over a card element, the double inverted comma is displayed outside the card, causing a visual inconsistency and potential confusion for users.

** To Reproduce **

1. Hover over any card element on the page.
2. Observe the position of the double inverted comma relative to the card.

** Expected behavior **
The double inverted comma should be displayed within the boundaries of the card, maintaining a visually coherent design.

** Screenshots **

![Screenshot (177)](https://github.com/anuragverma108/SwapReads/assets/126942167/4985aa3e-6c6e-48c4-bdcf-ceb0f244a908)

"I am a contributor to GSSOC'24."

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Azhar-0401** [comment]
is your feature request related to a problem? Please describe.
Currently No Hover effect in card.

Describe the solution you'd like
Adding Hover effect on card.

Additional context
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by huamanraj** [comment]
> is your feature request related to a problem? Please describe. Currently No Hover effect in card.
> 
> Describe the solution you'd like Adding Hover effect on card.
> 
> Additional context Assign me this work under GSSoc
> 
> Sir i'm Experienced in Frontend Developer , there are some my work link https://www.shinnextream.in/ https://innovationnitrr.netlify.app/
> 
> so, please assign me

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> ** Describe the bug ** When hovering over a card element, the double inverted comma is displayed outside the card, causing a visual inconsistency and potential confusion for users.
> 
> ** To Reproduce ** Steps to reproduce the behavior:
> 
> 1. Hover over any card element on the page.
> 2. Observe the position of the double inverted comma relative to the card.
> 
> ** Expected behavior ** The double inverted comma should be displayed within the boundaries of the card, maintaining a visually coherent design.
> 
> ** Screenshots **
> 
> ![Screenshot (177)](https://private-user-images.githubusercontent.com/126942167/335775603-4985aa3e-6c6e-48c4-bdcf-ceb0f244a908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTk3NTAsIm5iZiI6MTcxNzI1OTQ1MCwicGF0aCI6Ii8xMjY5NDIxNjcvMzM1Nzc1NjAzLTQ5ODVhYTNlLTZjNmUtNDhjNC1iZGNmLWNlYjBmMjQ0YTkwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNjMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzQwMzczOWY4MDcwMGMyNzE3NWI1NDI4YjM5MWEyYmVhMjM4YjZmNDU2YWUzNDM3MDRkZmQwZGY2OGNmOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wm6vd40cLP86iScU4zOwee0qphwind4culANBv62xPo)
> 
> "I am a contributor to GSSOC'24."
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [ ]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by RitiChandak** [comment]
@Rahul91025 any updates
