### ISSUE TITLE
BUG: Issues in Testimonials section, No Change in Background color of cards, Issue in border  radius in dark theme

### ISSUE THREAD

**Issue by mukund-gpt** [anuragverma108/SwapReads#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 2.  Issue in border  radius in dark theme

![Screenshot 2024-06-01 104157](https://github.com/anuragverma108/SwapReads/assets/142800930/e01b68e3-a964-4564-b6b2-7e4083832989)
![Screenshot 2024-06-01 104216](https://github.com/anuragverma108/SwapReads/assets/142800930/8409b0d2-ead3-4e4d-8669-5146402947a4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ### 1. No Change in Background color of cards during switching between dark and light theme
> ### 2.  Issue in border  radius in dark theme
> 
> 
> ![Screenshot 2024-06-01 104157](https://github.com/anuragverma108/SwapReads/assets/142800930/e01b68e3-a964-4564-b6b2-7e4083832989)
> ![Screenshot 2024-06-01 104216](https://github.com/anuragverma108/SwapReads/assets/142800930/8409b0d2-ead3-4e4d-8669-5146402947a4)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

 assigned
