### ISSUE TITLE
Feat: Want to Add Hover in Social Media links

### ISSUE THREAD

**Issue by mukund-gpt** [anuragverma108/SwapReads#1149]
### Add ScreenShots

![Screenshot 2024-06-01 105526](https://github.com/anuragverma108/SwapReads/assets/142800930/b58f51e0-6966-4781-8c01-a738897dfdd6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Azhar-0401** [comment]
***is your feature request related to a problem? Please describe.***
Currently No Want to Add Hover in Social Media links.

***Describe the solution you'd like***
Adding Hover in Social Media links 

***Additional context***
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by Tanishka023** [comment]
Hey!! @anuragverma108 I can fix this issue easily, please assign this to me

**Comment by mukund-gpt** [comment]
**plz assign the task to me**
