### ISSUE TITLE
Feat: Click to redirect location

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#1153]
### Describe the feature

When user click to the address it will redirect them to the google map

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/73558583/465a8e85-12ca-4b22-a332-31466536f75c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> When user click to the address it will redirect them to the google map
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/73558583/465a8e85-12ca-4b22-a332-31466536f75c)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned!
