### ISSUE TITLE
BUG: UNWANTED SPACE AND THEME NOT CHANGE ON DARK-MODE OF MORE SECTION 

### ISSUE THREAD

**Issue by AbhinaySngh** [anuragverma108/SwapReads#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/162811933/ce65199f-1364-4b9b-9b9e-93d23432ba33

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhinaySngh** [comment]
@anuragverma108 please assign me this issue under GSSOC'24 label.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> 
> https://github.com/anuragverma108/SwapReads/assets/162811933/ce65199f-1364-4b9b-9b9e-93d23432ba33
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned
