### ISSUE TITLE
BUG: ALIGNMENT OF TEXT IN BOOK EXCHANGE HUB 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/a15610c3-9d9b-442a-8474-5bd5f367a6b0)

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/783cf95b-6c09-4c95-a01d-96846c3e1c03)

The paragraph "connect with the fellow readers..."  is lil too close to the container. I would like to work on this issue, please assign me this issue under GSSOC'24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108  @huamanraj please assign me this issue under GSSOC'24

**Comment by huamanraj** [comment]
> @anuragverma108 @huamanraj please assign me this issue under GSSOC'24

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
