### ISSUE TITLE
BUG: Testimonials card being overlapped  

### ISSUE THREAD

**Issue by harshcodesit** [anuragverma108/SwapReads#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the "some frequently asked question"  section is overlapping the Testimonials cards and cutting the  bottom edges.

![Screenshot 2024-06-01 134623](https://github.com/anuragverma108/SwapReads/assets/145207595/e6fb9b11-8781-4ddc-9f1b-86f749a18a8f)

![Screenshot 2024-06-01 133918](https://github.com/anuragverma108/SwapReads/assets/145207595/df7c9e64-6fa8-46f6-a737-b7f9467239dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
hey @anuragverma108 
I have worked on the same type of bug before,
please assign me the issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by harshcodesit** [comment]
@huamanraj 
PR created sir,  issue resolved 
thanks
