### ISSUE TITLE
Feat: The hover effect on pricing card

### ISSUE THREAD

**Issue by harshcodesit** [anuragverma108/SwapReads#1158]
### Describe the feature

The hover effect on the pricing card does not match the theme of the website and looking so dull and boring 
it should be improved

### Add ScreenShots

![Screenshot 2024-06-01 134115](https://github.com/anuragverma108/SwapReads/assets/145207595/0d1b7a1e-1879-4cc5-a35c-c5d0e341e26b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Azhar-0401** [comment]
is your feature request related to a problem? Please describe.
Currently No   Hover effect  in pricing card.

Describe the solution you'd like
Adding Hover effect on pricing card.

Additional context
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by harshcodesit** [comment]
@huamanraj 
I have worked on the same type of feature before , you can see my work on the genre cards , the hover effect on the pricing card should also be improved 

please assign the issue to me

**Comment by huamanraj** [comment]
> @huamanraj 
> I have worked on the same type of feature before , you can see my work on the literacy realms cards , the hover effect on the pricing card should also be improved 
> 
> please assign the issue to me 

assigned
