### ISSUE TITLE
BUG: Book Recommendation not working on freeBooks.html

### ISSUE THREAD

**Issue by kdanjana** [anuragverma108/SwapReads#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the freeBooks.html, Book Recommendation is not redirecting to its respective page .

https://github.com/anuragverma108/SwapReads/assets/103878831/e6bf9f43-4430-4745-9350-ac37b2ca9b82

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> On the freeBooks.html, Book Recommendation is not redirecting to its respective page .
> 
> https://github.com/anuragverma108/SwapReads/assets/103878831/e6bf9f43-4430-4745-9350-ac37b2ca9b82
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [x] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
