### ISSUE TITLE
BUG: Text not visible in cookie popup

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As the text of the cookie popup not visible in dark mode

![Screenshot 2024-06-01 142306](https://github.com/anuragverma108/SwapReads/assets/142779809/814cdee6-f428-46f7-911d-c72ca7ada270)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> As the text of the cookie popup not visible in dark mode
> 
> ![Screenshot 2024-06-01 142306](https://github.com/anuragverma108/SwapReads/assets/142779809/814cdee6-f428-46f7-911d-c72ca7ada270)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
