### ISSUE TITLE
BUG: Can't differentiate the FAQ Section not enough margin

### ISSUE THREAD

**Issue by Madhu-mac** [anuragverma108/SwapReads#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Heading of the FAQ section is attached into the Testimonials section which is looking a bit off. We can improve this by adding some space after the testimonials and making the FAQ headings aligned with the questions below with proper background colours to make it look like one section.

![image](https://github.com/anuragverma108/SwapReads/assets/99901964/d1e8527f-e008-464a-a7ad-dc939edba7cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
Hi, @anuragverma108 @huamanraj - please add labels and assign this issue to me under GSSOC'24, Thanks.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Heading of the FAQ section is attached into the Testimonials section which is looking a bit off. We can improve this by adding some space after the testimonials and making the FAQ headings aligned with the questions below with proper background colours to make it look like one section.
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/99901964/d1e8527f-e008-464a-a7ad-dc939edba7cb)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by Madhu-mac** [comment]
@anuragverma108 Can you please look into this PR. Thanks!
