### ISSUE TITLE
BUG: Very less padding for the Heading which degrade the UI

### ISSUE THREAD

**Issue by satyam8932** [anuragverma108/SwapReads#1165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108  There is very little or almost no padding which needs to be fixed to improve the UI for various headings one i have added screenshot and there are more
Please assign me this issue under GSSOC labels and Levels

![image](https://github.com/anuragverma108/SwapReads/assets/82116707/545fab30-c559-4a2a-bb50-72895bf6b9e2)

Thanks

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by satyam8932** [comment]
@anuragverma108 can you please assign it to me bro

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> @anuragverma108  There is very little or almost no padding which needs to be fixed to improve the UI for various headings one i have added screenshot and there are more
> Please assign me this issue under GSSOC labels and Levels
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/82116707/545fab30-c559-4a2a-bb50-72895bf6b9e2)
> 
> 
> Thanks
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by satyam8932** [comment]
Thanks @huamanraj
