### ISSUE TITLE
BUG: Font is not visible in dark mode

### ISSUE THREAD

**Issue by Shreyaa173** [anuragverma108/SwapReads#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/144673309/a5a16226-5b6d-44a6-b31e-116148b6bb79)
this font is not visible in dark mode.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently Font is not visible in dark mode.

*Describe the solution you'd like*
Adding transparency and css property to add visible font

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/144673309/a5a16226-5b6d-44a6-b31e-116148b6bb79)
> this font is not visible in dark mode.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
