### ISSUE TITLE
Feat: want to add hover effect

### ISSUE THREAD

**Issue by Shreyaa173** [anuragverma108/SwapReads#1167]
### Describe the feature

I want to add hover effect on the different nook conatiners.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/144673309/7c6c6c08-b4bf-4616-b0c1-e16c41d7b6da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> I want to add hover effect on the different nook conatiners.
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/144673309/7c6c6c08-b4bf-4616-b0c1-e16c41d7b6da)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
