### ISSUE TITLE
footer update 

### ISSUE THREAD

**Issue by dhairyagothi** [anuragverma108/SwapReads#1168]
![image](https://github.com/anuragverma108/SwapReads/assets/142989448/aaa19511-1948-4899-8a7a-ab4d5d418fef)

there should be some gap in footer , which can make it look more beautiful ,
please assign me this issue under gssoc

**Comment by anuragverma108** [comment]
Assigned! @dhairyagothi 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by dhairyagothi** [comment]
> Assigned! @dhairyagothi Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts. Happy open-source contributing!

thankyou for assigning me soon i will make PR with changes
