### ISSUE TITLE
Feat: Adding Hover Effects to the Cards of Literary Realms Section

### ISSUE THREAD

**Issue by kamalesh-og** [anuragverma108/SwapReads#117]
Hello @anuragverma108 ,

### Describe the feature

Adding Hovering Effects to the cards of Literary Realms Section like the one in the Benefits to enhance the UI of the page further.
Can you please Assign me this issue, I'd be delighted to work upon this issue and make the UI of this website more beautiful and flawless.
Thank You.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/163159351/0ccfad18-5882-436d-9ffd-19b4be11cb01)
Improving this section by adding hovering effects to every other card over here.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Husan7** [comment]
Hi sir i am Husandeep Singh here gssoc contributor can you assign this issue to me

**Comment by Nih1tGupta** [comment]
I'm eager to contribute and would love working on this under GSSoC'24.
Also I m working on a similar one. So can you please assign this to me
Also vanilla effect for cards may be suited.

**Comment by kamalesh-og** [comment]
Thank You @anuragverma108
