### ISSUE TITLE
BUG: Contact form not show any message after click on send now button

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we click on send now button in contact form it show fill email in footer's email and not show any message like **"Thank you for contact"** i will add this message show when user click on send now.
https://www.loom.com/share/d4cdc476cf5b4a0395632058188deb23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> When we click on send now button in contact form it show fill email in footer's email and not show any message like **"Thank you for contact"** i will add this message show when user click on send now.
> https://www.loom.com/share/d4cdc476cf5b4a0395632058188deb23
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> When we click on send now button in contact form it show fill email in footer's email and not show any message like **"Thank you for contact"** i will add this message show when user click on send now.
> https://www.loom.com/share/d4cdc476cf5b4a0395632058188deb23
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
