### ISSUE TITLE
BUG: Logo in the navbar is not in right position

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Logo should be  left corner of the website but it is in little middle

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Logo should be  left corner of the website but it is in little middle
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by gudia18** [comment]
okay , Thanks @huamanraj sir , I will take care of mentioned points
