### ISSUE TITLE
BUG: The cards in the "Literary Realms" do not match the dark mode

### ISSUE THREAD

**Issue by sandy-queen** [anuragverma108/SwapReads#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we switch over to the dark mode of the website, the cards in the literary realms section do not change their colours. I think that I can change these colors to match them with the overall look of website in the dark mode. 

![light](https://github.com/anuragverma108/SwapReads/assets/147652780/0ce9b601-8197-45b3-a690-a072860afd9a)

![dark](https://github.com/anuragverma108/SwapReads/assets/147652780/dec7c559-2bac-4b58-adcd-b5f8f81db6bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sandy-queen** [comment]
@anuragverma108 Please assign these issue to me under the GSSOC as I would like to work on it.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> When we switch over to the dark mode of the website, the cards in the literary realms section do not change their colours. I think that I can change these colors to match them with the overall look of website in the dark mode. 
> 
> ![light](https://github.com/anuragverma108/SwapReads/assets/147652780/0ce9b601-8197-45b3-a690-a072860afd9a)
> 
> 
> ![dark](https://github.com/anuragverma108/SwapReads/assets/147652780/dec7c559-2bac-4b58-adcd-b5f8f81db6bc)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by sandy-queen** [comment]
Thank you for assigning this to me. I am working on it.
