### ISSUE TITLE
BUG: Alignment of Testimonial Message is Not Perfect

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The alignment of the testimonial message on the website is not perfect. The text should be centered both vertically and horizontally. Additionally, the quotes are also not aligned perfectly.

![testimonial alligment](https://github.com/anuragverma108/SwapReads/assets/129402285/1c41f748-5398-4dba-97c2-0630d7a7589a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tanishka023** [comment]
Hey @anuragverma108 Please assign this to me, I can fix this easily

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The alignment of the testimonial message on the website is not perfect. The text should be centered both vertically and horizontally. Additionally, the quotes are also not aligned perfectly.
> 
> ![testimonial alligment](https://github.com/anuragverma108/SwapReads/assets/129402285/1c41f748-5398-4dba-97c2-0630d7a7589a)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
