### ISSUE TITLE
BUG:  Adding hover effect to Cookies Accept and Reject button 

### ISSUE THREAD

**Issue by Damini2004** [anuragverma108/SwapReads#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hover effect will help user to to know which button he will click which may look as tempting.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Hover effect will help user to to know which button he will click which may look as tempting.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
