### ISSUE TITLE
BUG: fixing the spacing between the more  dropdown elements

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#1184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The alignment and spacing of more button dropdown menu is not adjusted properly
![Screenshot 2024-06-01 222415](https://github.com/anuragverma108/SwapReads/assets/146806880/2982af55-70be-4901-ba1a-843ae8e3b4cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The alignment and spacing of more button dropdown menu is not adjusted properly
> ![Screenshot 2024-06-01 222415](https://github.com/anuragverma108/SwapReads/assets/146806880/2982af55-70be-4901-ba1a-843ae8e3b4cf)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
