### ISSUE TITLE
Feat: Navbar will hide when someone scroll down and popup when someone scroll up

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#1187]
### Describe the feature

when we scroll down to the webpage navbar will get hide and when we try to go up navbar will popup 

### Add ScreenShots

see the changes in navbar⤵️
https://github.com/anuragverma108/SwapReads/assets/146806880/e02a3530-3127-4af6-9f31-a7f9e36bde9c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> when we scroll down to the webpage navbar will get hide and when we try to go up navbar will popup 
> 
> ### Add ScreenShots
> 
> see the changes in navbar⤵️
> https://github.com/anuragverma108/SwapReads/assets/146806880/e02a3530-3127-4af6-9f31-a7f9e36bde9c
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
