### ISSUE TITLE
BUG: Correcting all the re-direct links

### ISSUE THREAD

**Issue by ThisIsSahaj** [anuragverma108/SwapReads#1189]
### Is there an existing issue for this?
NO
- [X] I have searched the existing issues

### What happened?

`Correcting all the Files Structure of the Projects and linking each file Correctly`

> Problem

When you go to ABOUT page the url is : 
![image](https://github.com/anuragverma108/SwapReads/assets/118066299/c379fde7-525a-4a1c-b9ba-b3ae6a03f956)

And then when you again click HOME button the  url becomes this: 
![image](https://github.com/anuragverma108/SwapReads/assets/118066299/d121e91d-fc04-402f-a7fa-8604560651b2)

Then if you again click the ABOUT button it shows this: 
![image](https://github.com/anuragverma108/SwapReads/assets/118066299/e31fef75-7372-4cdb-a59a-8e83e2f116c4)

This is happening because there is NO PROPER FILE STRUCTURE in the project, it is all messed up
Due to wrong linking, all the pages redirects gets messed up

`SOLUTION`
I will correct all the file linking links and make a proper Structure of The files

Please assign me this issue under GSSOC

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mehrun171** [comment]
I would like to work on this issue tooo

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> NO
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> `Correcting all the Files Structure of the Projects and linking each file Correctly`
> 
> > Problem
> 
> When you go to ABOUT page the url is : 
> ![image](https://github.com/anuragverma108/SwapReads/assets/118066299/c379fde7-525a-4a1c-b9ba-b3ae6a03f956)
> 
> And then when you again click HOME button the  url becomes this: 
> ![image](https://github.com/anuragverma108/SwapReads/assets/118066299/d121e91d-fc04-402f-a7fa-8604560651b2)
> 
> Then if you again click the ABOUT button it shows this: 
> ![image](https://github.com/anuragverma108/SwapReads/assets/118066299/e31fef75-7372-4cdb-a59a-8e83e2f116c4)
> 
> This is happening because there is NO PROPER FILE STRUCTURE in the project, it is all messed up
> Due to wrong linking, all the pages redirects gets messed up
> 
> `SOLUTION`
> I will correct all the file linking links and make a proper Structure of The files
> 
> Please assign me this issue under GSSOC
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by ThisIsSahaj** [comment]
@huamanraj Thankyou for assigning the issue. Can you please add level 2 tag as this will require me to correct all the re direct links of all the buttons, tabs, books etc. and also will need to change the file structure

**Comment by ThisIsSahaj** [comment]
@huamanraj someone has already made the changes and it has also been merged. How can it be like that if I am the one assigned for the issue

**Comment by huamanraj** [comment]
> @huamanraj someone has already made the changes and it has also been merged. How can it be like that if I am the one assigned for the issue
> 

maybe this is because similar issue is assigned to two persons! because there is lot of issues and we can remember all of that and contributors and not searching and creating the duplicate issues!  

you can still make some minor changes with a good approach and create a PR! and tag PA
