### ISSUE TITLE
BUG: Changes in More section

### ISSUE THREAD

**Issue by mehrun171** [anuragverma108/SwapReads#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Under the Navbar in the More section when we click on few links they are not getting directed to the right page...This issue need to be addressed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Under the Navbar in the More section when we click on few links they are not getting directed to the right page...This issue need to be addressed.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by mehrun171** [comment]
Thanks ..vl update soon on this

**Comment by mehrun171** [comment]
Hey!!just noticed that not only in the home section but every other section like literary realms etc., have to issue of not getting redirected to the right pages when clicking at elements in more section...what would you suggest me to do??

**Comment by mehrun171** [comment]
Or i would take little time and solve all of them...could u provide with label 2 tag as everything needs to be updated and chnaged

**Comment by mehrun171** [comment]
What do you say @huamanraj ??? i am already working on this issue as of now

**Comment by huamanraj** [comment]
> What do you say @huamanraj ??? i am already working on this issue as of now

work on this and this isn't tough to do so i dont think L2 will justify! but PR is reviewed PA so at that time you can ask from him toh give L2 if he want he can!

**Comment by mehrun171** [comment]
Who is the PA?

**Comment by RitiChandak** [comment]
@anuragverma108 is the PA
