### ISSUE TITLE
Feat: Add Footer in About page as it informative page

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1194]
### Describe the feature

we should add the Footer in tha About page so that user can get complete info about this project as the footer contains all links and social media links

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/4071c279-6e5f-4280-8863-51d4138d5046)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@huamanraj can you please assign this issue to me?

**Comment by Tanishka023** [comment]
Hey @anuragverma108 I can fix this issue easily, please this to me
