### ISSUE TITLE
 header in dark mode.

### ISSUE THREAD

**Issue by sreshtech** [anuragverma108/SwapReads#1199]
### Describe the feature

In dark mode, the header appears in two different colors, while in bright mode, it remains a single color

### Add ScreenShots

![Screenshot (919)](https://github.com/anuragverma108/SwapReads/assets/121309862/33a55c09-2059-4ae9-9d41-cf9fc2a74824)

![Screenshot (919)](https://github.com/anuragverma108/SwapReads/assets/121309862/4a0b0f72-89ea-49bc-8180-bf5dc70967a8)

![Screenshot (920)](https://github.com/anuragverma108/SwapReads/assets/121309862/172b404f-a2cb-4db0-a25e-9b2b92fe3153)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aashka19** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me?
