### ISSUE TITLE
Unnecessary border without hovering in for second card in pricing section

### ISSUE THREAD

**Issue by Joy-Agrawal** [anuragverma108/SwapReads#12]
The second card in pricing section is showing border without even before hovering ,and is looking odd among the left and right cards
also the button color for this card is different
![before](https://github.com/anuragverma108/SwapReads/assets/104222673/b92e05eb-01e5-4273-88f9-f896e65dac60)

**Comment by anuragverma108** [comment]
Assigned @Joy-Agrawal 
The button should become brown in color on hovering. Make it like that

**Comment by Joy-Agrawal** [comment]
button color made brown on hovering
before hovering:
![before2](https://github.com/anuragverma108/SwapReads/assets/104222673/b6de5241-0da5-454b-81a9-c1e5531e0abd)
After hovering:
![after2](https://github.com/anuragverma108/SwapReads/assets/104222673/9e206576-be0d-41d3-84ca-b9f3e2146abd)
