### ISSUE TITLE
Social Media Links are not working

### ISSUE THREAD

**Issue by Anshika040** [anuragverma108/SwapReads#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Social Media Links are not working and redirecting to correct page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshita1611** [comment]
Hi, I would like to work on this issue, can you please assign it to me?

**Comment by nishantharkut** [comment]
The issue has been resolved. someone changed the footer and didnt make the changes i implemented. you can check this out in the code, it has been commented out
