### ISSUE TITLE
BUG: Correct Path of Book list for swapping

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/129655645/85baa6b5-9fdd-4cce-8062-733a597e06ee)
If any one wants to fix this bug then do comment I will assign it to you !

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@anuragverma108 can you assign me this issue....
