### ISSUE TITLE
Feat: Sending mail when user clicks send now on contact form

### ISSUE THREAD

**Issue by atharvarekhawar** [anuragverma108/SwapReads#1204]
### Describe the feature

When a user clicks the send now button on the contact form a mail with the information will be sent to the project admin who he can then respond accordingly.

### Add ScreenShots

![swapread](https://github.com/anuragverma108/SwapReads/assets/113119063/1eb373a0-6c06-4c40-a62c-dae83a5fc314)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by atharvarekhawar** [comment]
@anuragverma108 plz assign it to me

**Comment by huamanraj** [comment]
> @anuragverma108 plz assign it to me

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
