### ISSUE TITLE
BUG: Dropdown not visible correctly

### ISSUE THREAD

**Issue by atharvarekhawar** [anuragverma108/SwapReads#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when clicked on dropdown 'more' the content in it it hidden by the books below.

![swapread-1](https://github.com/anuragverma108/SwapReads/assets/113119063/eec94a5f-a41c-4d32-8082-86808bbf076b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by atharvarekhawar** [comment]
@anuragverma108  plz assign it to me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
