### ISSUE TITLE
Feat: Adding hover effect in Testimonials section 

### ISSUE THREAD

**Issue by SadafKausar2025** [anuragverma108/SwapReads#1207]
### Describe the feature

I want to add hover in testimonials box and also
text [know what our customer says ] is not margin properly

### Add ScreenShots

![Screenshot (1875)](https://github.com/anuragverma108/SwapReads/assets/137484958/d9d73931-e2a0-485b-a196-8000ad68b37d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
hello @anuragverma108 
can you please assign me this issue?

**Comment by rajRishi22** [comment]
hello @anuragverma108 
can you please assign this issue to me?
