### ISSUE TITLE
BUG: SignUp and Login is not redirecting the user after the process

### ISSUE THREAD

**Issue by atharvarekhawar** [anuragverma108/SwapReads#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When sign up button is clicked nothing is happening and page is just getting reloaded but here the user should be redirected to login page and after login redirected to Home page.

https://github.com/anuragverma108/SwapReads/assets/113119063/c4585b82-e0bc-4d34-b6cb-432019b8ef03

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by atharvarekhawar** [comment]
@anuragverma108 plz assign it to me

**Comment by Ananya-Nair20** [comment]
Hello @anuragverma108,

I am participating in GSSOC'24 and would like to resolve this issue. Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you

**Comment by huamanraj** [comment]
> @anuragverma108 plz assign it to me

Assigned!
just redirect it to index! 

Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
