### ISSUE TITLE
Add social media and feedback section in blog page 

### ISSUE THREAD

**Issue by rajlaxmi03** [anuragverma108/SwapReads#121]
### Describe the feature

Add social media and feedback section in blog page 

### Add ScreenShots

Add social media and feedback section in blog page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by rajlaxmi03** [comment]
Thankyou @anuragverma108
