### ISSUE TITLE
Feat:Make Navbar disappear on scrolling upwards

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1218]
### Describe the feature

I would like to request the addition of a feature where the navbar disappears when scrolling upwards and reappears when scrolling downwards. This feature will enhance the user experience by providing more screen space when reading content and ensuring easy access to navigation when needed.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by gudia18** [comment]
@kashnx , are u still working on this issue , or I would i to work on

**Comment by kashnx** [comment]
I am working.
