### ISSUE TITLE
BUG:About Us Page doesnt Match with the Theme

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Different color of the about us page than others
![image](https://github.com/anuragverma108/SwapReads/assets/148524648/533a7cf8-7b66-4629-93d2-f4efb8748678)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@kashnx solve this issue with this issue #1221

**Comment by kashnx** [comment]
Done
