### ISSUE TITLE
BUG: Different Navbar on about us page

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/148524648/0d1f89d0-7f13-49d3-ba4a-3a7a89cbd338)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
