### ISSUE TITLE
fixing css of testimonials section

### ISSUE THREAD

**Issue by dhairyagothi** [anuragverma108/SwapReads#1224]
![image](https://github.com/anuragverma108/SwapReads/assets/142989448/56e1202b-bc5a-4e6f-a1c4-542e1ed93a23)

making text center and comma inside the box will make it look more beautiful

please assign this issue to me under gssoc

**Comment by Ananya-Nair20** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you

**Comment by Aashka19** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me?
