### ISSUE TITLE
Feat: Google Auth and validation using Firebase on login and Signup

### ISSUE THREAD

**Issue by adarsh1001111** [anuragverma108/SwapReads#123]
### Describe the feature

@anuragverma108 please assign this issue to me
<img width="868" alt="Screenshot 2024-05-11 at 1 04 58 PM" src="https://github.com/anuragverma108/SwapReads/assets/130575709/20150d51-b254-4c47-8a41-1d644b43274d">
I propose integrating Google Authentication via Firebase to enhance the website's security and user experience.

### Add ScreenShots

<img width="477" alt="Screenshot 2024-05-11 at 1 02 03 PM" src="https://github.com/anuragverma108/SwapReads/assets/130575709/eb4eee65-a56a-48dd-a812-ff99e9be68f4">
<img width="461" alt="Screenshot 2024-05-11 at 1 02 11 PM" src="https://github.com/anuragverma108/SwapReads/assets/130575709/6b01e933-836b-417a-837f-a92492575ae4">

would change the authentication system only, since the UI/UX is already assigned to other contributors.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adarsh1001111** [comment]
@anuragverma108 is this issue already assigned to someone else?

**Comment by anuragverma108** [comment]
Yes it already exists
