### ISSUE TITLE
Feat: Improve Rating System from Star to Slot-Making System

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#1234]
### Describe the feature

I would like to propose an enhancement to the current rating system. Currently, we use a star-based rating system. I believe that switching to a slot-making system could provide a more nuanced and user-friendly experience. The slot-making system allows users to allocate ratings in a more granular and detailed manner, which can lead to more accurate and useful feedback.

Switching to a slot-making system would offer the following benefits:

More detailed feedback from users.
Enhanced user engagement due to the interactive nature of the slot-making system.
Better data for analyzing user preferences and improving our services/products.

### Add ScreenShots

To illustrate the proposed change, here are some screenshots comparing the current star rating system with the proposed slot-making system:

Current Star Rating System:

![Screenshot 2024-06-02 155229](https://github.com/anuragverma108/SwapReads/assets/140592148/3abb8800-2c28-401f-948c-a65a41ca2771)

Proposed Slot-Making System:

https://github.com/anuragverma108/SwapReads/assets/140592148/be574c03-b052-4735-aa30-e721bbfbd44d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
please /assign me under this issue

**Comment by huamanraj** [comment]
> please /assign me under this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by SrijaVuppala295** [comment]
@huamanraj , please add level label to it!!!
