### ISSUE TITLE
DOC:  Fix Name Appearing Under Navbar

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#1235]
### What's wrong with the existing documentation

There is a visual misalignment issue with the navbar on our website. The name "Swap Reads" is currently appearing below the navbar instead of being properly aligned within it. This affects the overall look and user experience of the navigation bar.

### Add ScreenShots

![Screenshot 2024-06-02 160131](https://github.com/anuragverma108/SwapReads/assets/140592148/44b3558d-46e9-4f20-84e0-a0a86137f0d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
please /assign this issue to me

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> 
> There is a visual misalignment issue with the navbar on our website. The name "Swap Reads" is currently appearing below the navbar instead of being properly aligned within it. This affects the overall look and user experience of the navigation bar.
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-06-02 160131](https://github.com/anuragverma108/SwapReads/assets/140592148/44b3558d-46e9-4f20-84e0-a0a86137f0d3)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
