### ISSUE TITLE
DOC: Icon in the titlebar is missing in some pages

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#1238]
### What's wrong with the existing documentation

Icons are missing in the titlebar , want to add icons in the titlebar.

### Add ScreenShots

![Screenshot 2024-06-02 153605](https://github.com/anuragverma108/SwapReads/assets/140592148/6fb0d274-e285-46d3-8e5e-46fd09f7ec24)
![Screenshot 2024-06-02 160120](https://github.com/anuragverma108/SwapReads/assets/140592148/1febbd8e-cc11-4d05-bfb1-a785a9ab169c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
please /assign me under this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
