### ISSUE TITLE
Vedio link is not working

### ISSUE THREAD

**Issue by Anshika040** [anuragverma108/SwapReads#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Vedio link on the novel is not working is not working

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
