### ISSUE TITLE
DOC: Know What your customers say not aligned properly

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#1242]
### What's wrong with the existing documentation

In the testimonials section, the line know wht your customers say is not properly aligned

### Add ScreenShots

![Screenshot 2024-06-02 163209](https://github.com/anuragverma108/SwapReads/assets/140592148/f6e655fa-7353-473c-8142-6c0311ab2f41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vibhu315** [comment]
heyy @anuragverma108 ,
can you assign this issue to me ?
And please add the label to the issue
