### ISSUE TITLE
BUG:Image size is not aligned with cards in mobile version 

### ISSUE THREAD

**Issue by RiyaaBhatt** [anuragverma108/SwapReads#1243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Image size is not aligned with cards in mobile version 

![Screenshot_2024-06-02-16-35-16-78_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/anuragverma108/SwapReads/assets/128878008/8d738c2e-f303-48db-b0ac-215eb9bacc00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so react out for any support needed!!

Happy open-source contributing!
