### ISSUE TITLE
Feat:  Adding the popUp feature in maps using mapBox

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#1245]
### Describe the feature

The "pop-out" feature allows users to view a larger or more detailed version of a specific area or element on the map by clicking on it. This enhances the user experience by providing additional information or context without cluttering the main map view.
This "pop-out" feature in maps allows users to click or interact with specific elements, such as markers or regions, to view additional information or a detailed view in a separate window. This feature enhances user engagement by providing supplementary context without cluttering the main map view. Users can easily access more detailed information about areas of interest, improving their overall experience with the map application.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/140592148/94be9510-1572-49a9-a66b-ee40bf5d7652)

### Wanna add popUp in this way 

![image](https://github.com/anuragverma108/SwapReads/assets/140592148/4b05ff03-61e7-4e89-9dac-e9bd1b419ad8)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
