### ISSUE TITLE
BUG: CHATBOT remains same even if there is a change from day to night mode 

### ISSUE THREAD

**Issue by cecily-mee** [anuragverma108/SwapReads#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Chatbot does not change its mode even if other components of the website change the mode based on the 'night/day' mode preference selected by the user. 
![image](https://github.com/anuragverma108/SwapReads/assets/143897317/b80cef31-92c5-4fcd-af07-ffad1954c1e9)
![image](https://github.com/anuragverma108/SwapReads/assets/143897317/e411acac-ca1d-48ff-a0b8-4f477f48b0d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rajRishi22** [comment]
I can work on this issue , if i assigned.

**Comment by cecily-mee** [comment]
i would like to work on this issue raised by me if it can be assigned to me . Thanks
