### ISSUE TITLE
Feat:want to add this animation in books

### ISSUE THREAD

**Issue by RiyaaBhatt** [anuragverma108/SwapReads#1247]
### Describe the feature

Hello admin I want to add following animation in home page could you please assign this to me under gssoc'24 

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/128878008/b46a65d6-3f24-44c2-a4b4-eeb23faf0748

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@anuragverma108 Please look into it

**Comment by anuragverma108** [comment]
@RiyaaBhatt 
Can you send me a screenshot after applying it into Swapreads in your localhost. If it looks good then I will assign it to you!

**Comment by RiyaaBhatt** [comment]
ya sure

**Comment by huamanraj** [comment]
> ya sure

update?

**Comment by RiyaaBhatt** [comment]
Individually, it functions correctly. However, there is an issue when integrating it into the website screen. This is what I am currently addressing.

**Comment by huamanraj** [comment]
> Individually, it functions correctly. However, there is an issue when integrating it into the website screen. This is what I am currently addressing.

ok! try using different class names and css file for that!

**Comment by huamanraj** [comment]
any updates @RiyaaBhatt
