### ISSUE TITLE
BUG: Updating Twitter icon to X icon

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/8594bcdf-291a-4014-8953-c6186d7b126c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
