### ISSUE TITLE
BUG:"Know what our customers say" is not aligned in the centre.

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1440" alt="Screenshot 2024-06-02 at 8 42 44 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/4548fb76-0dcf-484f-a586-e1b7fc0b567a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Vibhu315** [comment]
heyy,
I want to fix the issue can you assign me the issue
