### ISSUE TITLE
BUG: up arrow and messaging collide 

### ISSUE THREAD

**Issue by isandhyadev** [anuragverma108/SwapReads#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Both icons collide
![Screenshot (388)](https://github.com/anuragverma108/SwapReads/assets/95486852/966a3688-d954-4e06-b7bb-9289ba0ef40f)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
