### ISSUE TITLE
Feat: Social Media Links in the footer section are not working

### ISSUE THREAD

**Issue by jinx-vi-0** [anuragverma108/SwapReads#126]
### Describe the feature

I will add all social media links in the footer section.

hey @anuragverma108, please assign this issue to me.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/120160355/8254c4b1-cc40-4d4a-8eec-5d68e482ab55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sudhanshu2306** [comment]
@jinx-vi-0 but is there any social media account for swap-read website??

**Comment by nishantharkut** [comment]
The social media links are working, someone changed the footer, you can checkout in the code, it has been commented out

**Comment by anuragverma108** [comment]
Issue already exists !
