### ISSUE TITLE
BUG:Text in the book exchange Hub starts from extreme left end of the box.

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before:
<img width="1440" alt="Screenshot 2024-06-02 at 9 35 10 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/90f95efa-2232-4986-99ed-9ad06c88aa67">
After:
<img width="1440" alt="Screenshot 2024-06-02 at 9 38 02 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/3e523fc1-e614-4999-8fbf-e940f1f824ee">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
