### ISSUE TITLE
BUG: Cursor effect does not look great , sometimes it  can frustrate people 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cursor effect on the website  doest look good 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Cursor effect on the website  doest look good 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

remove it! 
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!

**Comment by gudia18** [comment]
okay , Thanks !
