### ISSUE TITLE
Improvement in Color of The Address and it's detail 

### ISSUE THREAD

**Issue by 1754riya** [anuragverma108/SwapReads#1274]
### Is there an existing issue for this?
 I have searched the existing issues
### What happened?
The address and its details in the same color do not look good. I will change its color and make it appear in a better way.

### Record:
1.  I agree to follow this project's Code of Conduct
2.  I'm a GSSOC'24 contributor
3.  I want to work on this issue.
![Screenshot (74)](https://github.com/anuragverma108/SwapReads/assets/167575288/83e320d0-0abd-48ff-b14f-214446fdaa0d)

@anuragverma108, Please assign me this task.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
