### ISSUE TITLE
BUG: No footer on about us page 

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Will add a responsive footer on about us page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> Will add a responsive footer on about us page.
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

kindly check the existing issue before creating new one i have already raised the issue for this refer issue no.#1194
