### ISSUE TITLE
Feat: Improve the UI/UX of the about page

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#1280]
### Describe the feature

I want to improve the UI/UX of about page as it's UI is not looking good.

### Add ScreenShots

<img width="943" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/145490348/82c8bcbf-5974-48c0-afa9-7ac04d4bb440">

I will impeove it's header and the website.
Please assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
not planned!!
