### ISSUE TITLE
Feat: Wanted to make the Testimonials section responsive

### ISSUE THREAD

**Issue by mukund-gpt** [anuragverma108/SwapReads#1282]
### Add ScreenShots

![Screenshot 2024-06-03 122451](https://github.com/anuragverma108/SwapReads/assets/142800930/b28bd1fb-742f-4494-80e5-fe304c12a86e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
preassigned to someone else!! make sure to read the issue that you are creating!!
