### ISSUE TITLE
[BUG] : Footer is not Responsive

### ISSUE THREAD

**Issue by Sudhanshu2306** [anuragverma108/SwapReads#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On resizing, specifically squeezing the page rest of the site is responsive but footer runs out of the box. Right part elements should come downside the left side.

![image](https://github.com/anuragverma108/SwapReads/assets/126086429/af1fa5ae-b2ee-443c-8a8e-6269a397bbec)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sudhanshu2306** [comment]
@anuragverma108 Footer part is not responsive, Please assign this to me, adding CSS (flex) in media queries for different size frames will solve this. Thank You!

**Comment by anuragverma108** [comment]
Assigned !
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Sudhanshu2306** [comment]
@anuragverma108 sure sure, I starred the repo, also I have created a pull request for this bug check if any improvements needed. 
A request : please add level label to this according to the difficulty, I thought you missed during so much chaos, a lot of work from your side. Thank You!
