### ISSUE TITLE
Feat: Adding Contributor section

### ISSUE THREAD

**Issue by Abhigna-arsam** [anuragverma108/SwapReads#1296]
### Describe the feature

I propose to add a contributor section involves creating a visually appealing layout showcasing profiles

### Add ScreenShots

![Screenshot 2024-06-03 160024](https://github.com/anuragverma108/SwapReads/assets/125258286/060eccaa-d2fa-42d4-95e2-a528e5982b1b)

i propose to add contributor section after FAQ section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abhigna-arsam** [comment]
@anuragverma108 kindly please assign this work to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
but create it in about us page not in index! 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
