### ISSUE TITLE
The colour for text in the free e book section is not visible

### ISSUE THREAD

**Issue by suhanigupta23** [anuragverma108/SwapReads#1304]
### What's wrong with the existing documentation

The colour of text and the background is merging. We can change the text colour to white like headings.

### Add ScreenShots

<img width="1363" alt="Screenshot 2024-06-03 at 5 47 36 PM" src="https://github.com/anuragverma108/SwapReads/assets/144280247/d8f84c0b-66eb-4b38-bd1c-9f8b2b0ca09c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
