### ISSUE TITLE
Dark mode in login/sign up not wokring

### ISSUE THREAD

**Issue by deepxnshiiii** [anuragverma108/SwapReads#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/118647735/fea42eda-7a84-443b-93f4-81d0deb803ca)
![image](https://github.com/anuragverma108/SwapReads/assets/118647735/bc5a13f0-aba9-4193-8087-237e887c69cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
