### ISSUE TITLE
Feat: Review cards must be made to appear in a ROW

### ISSUE THREAD

**Issue by divyalaldinani** [anuragverma108/SwapReads#1308]
### Describe the feature

The reviews written by customers must be placed such that they occupy the width of the web page and eliminate the web page that is created by making them appear in a single column.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/82147067/b8b7a2dd-1213-4fe8-8ea0-c955a7192ce9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
