### ISSUE TITLE
BUG: Texts are not visible in the dark mode .

### ISSUE THREAD

**Issue by ayushrskiaa** [anuragverma108/SwapReads#1309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

texts are not visible on a perticular section of the home page.

![image](https://github.com/anuragverma108/SwapReads/assets/130389607/f4a4314c-0eca-434f-b1cb-d83d4c758ea2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
@anuragverma108  please assign me this issue ,I would like to work on this.
Thank you

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by ayushrskiaa** [comment]
@RitiChandak    Please check it and accept the pull request.
And also add the labels to this pull request.
Thank you.
