### ISSUE TITLE
BUG: Page not scrolling neither footer on the page

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/148524648/d6a7e9a6-d383-484f-8f37-e011fe01fbbd)

Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
