### ISSUE TITLE
BUG: Book recommendation page not opening on clicking the link

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/148524648/ae97338b-6806-478f-a196-d74dac817d45)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/148524648/ae97338b-6806-478f-a196-d74dac817d45)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

there is a linking issue.  fix that !
