### ISSUE TITLE
BUG: Zod Validation 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [anuragverma108/SwapReads#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**@anuragverma108**  I have not seen any Zod Validation in this project in backend.

As a Good Authenticated Site. There Should be Zod Authentication on website , So then the user can't add wrong type of username and passwords while registring to the database.

More about Zod -> https://zod.dev/

![image](https://github.com/anuragverma108/SwapReads/assets/122930278/c5244dfc-2e00-47ed-8b61-40d87a010e64)
I have only provided the username of lenght 1 and  password of length 3 so it should specify that min password lenght required and min username length required 
So This Issue can be solved using Zod Validation

![image](https://github.com/anuragverma108/SwapReads/assets/122930278/0b41f0b1-93c0-46ba-89e8-c5ad82616345)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujjwalagrawal-1** [comment]
@anuragverma108  I want to contribute to this Project as I know all about Zod Authentication on the site.

Please Assign me this issue.

**Comment by anuragverma108** [comment]
Assigned!
Make sure to star the repo before working on it! Happy open-source contributing!
