### ISSUE TITLE
BUG: Adjust Placement of Theme Change Button for Improved UI 

### ISSUE THREAD

**Issue by kosuri-indu** [anuragverma108/SwapReads#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a theme change button that need adjustment for a better user experience:

**Theme Change Button** : As seen in the screenshot below, the Theme Change Button is currently too below close to the right edge of the screen. This could potentially make it difficult for users to interact with the button, especially on smaller screens or touch devices.

![Screenshot 2024-06-03 200519](https://github.com/anuragverma108/SwapReads/assets/118645569/e1f45e41-87e3-4126-81b3-c3c3140523f8)

![Screenshot 2024-06-03 200447](https://github.com/anuragverma108/SwapReads/assets/118645569/c9a59487-61b4-4e24-ab9d-c2660522fb9e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by kosuri-indu** [comment]
Sure sir, have done it!
