### ISSUE TITLE
Add dark theme in login/signup page 

### ISSUE THREAD

**Issue by ankiiitagupta** [anuragverma108/SwapReads#1328]
### Describe the feature

In login/signup page toggle button is present but dark mode is not working.

Kindly assign this issue to me under GSSOC'24.

### Add ScreenShots

![Screenshot 2024-06-03 205602](https://github.com/anuragverma108/SwapReads/assets/108889476/c94265ff-ecfd-46c1-8464-11c6e755331f)
![Screenshot 2024-06-03 205614](https://github.com/anuragverma108/SwapReads/assets/108889476/612b379f-5e80-4877-a7ae-3c1f32107cc7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!
