### ISSUE TITLE
BUG: NavBar items different alignment

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While toggling the Dark and Light mode, the Navigation bar items are getting out of aligned
This can be seen clearly in the following Screenshots:

![image](https://github.com/anuragverma108/SwapReads/assets/145102345/62886c31-8c90-4a32-a720-4c5b45f865e7)
![image](https://github.com/anuragverma108/SwapReads/assets/145102345/cc70360c-8735-4127-beb1-c77eee3306a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
This is for PC in Firefox browser

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
