### ISSUE TITLE
Remove Repeated Text in Footer Section

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 

The text in the footer section of our website is currently repeating, which negatively affects the user experience and the visual appeal of our site.

The footer section is as follows:
![Screenshot 2024-06-03 213649](https://github.com/anuragverma108/SwapReads/assets/159511364/65c3c89f-0811-4ac1-8ed8-7d784467b741)

**please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
This issue already exists. Please check the existing issues before raising a new
one. Find another issue or feature to contribute to. Thank you!

**Comment by Saipradyumnagoud** [comment]
/assign
the issue is not solved i will work on the issue

**Comment by SaiTejaswaniBikkasani** [comment]
Hey @anuragverma108 . You assigned and merged the pull request to @Saipradyumnagoud but the issue was assigned to me and the issue was assigned to me last night.

**Comment by anuragverma108** [comment]
@SaiTejaswaniBikkasani 
The PR is reverted. 
You can now work on the issue!
Sorry for the inconvenience caused.

**Comment by SaiTejaswaniBikkasani** [comment]
@anuragverma108 
Thank you. I'll proceed with the task.
