### ISSUE TITLE
BUG: Text of testimonials section not visible in dark mode.

### ISSUE THREAD

**Issue by ANSHIKA-26** [anuragverma108/SwapReads#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text color of the testimonials in the dark mode is too black hence making it difficult to read in black backgrounds , I plan to improve the UI of the testimonials card by making changes to the font size , color of the testimonials , please assign this issue to me under GGSOC.
![image](https://github.com/anuragverma108/SwapReads/assets/114569262/96e7065f-a2cf-44e3-b371-8d27be0d6705)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
