### ISSUE TITLE
BUG:dark/light mode button position on Book Recommendation page

### ISSUE THREAD

**Issue by Sidhuavneet** [anuragverma108/SwapReads#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/94036516/f5bdc437-82a2-462a-b843-ba4a515ca533)
Dark/Light mode button position is not proper in book recommendation page that is on other pages it remains in the same alignment as other buttons on the navbar whereaes on this page it is getting shifted to next line

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sidhuavneet** [comment]
Can you assign me this issue so that i can work on it?

**Comment by huamanraj** [comment]
> Can you assign me this issue so that i can work on it?
> 

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊

**Comment by huamanraj** [comment]
> Can you assign me this issue so that i can work on it?
> 

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
