### ISSUE TITLE
Feat:Testimonies Section in Mobile View Completly dirty.

### ISSUE THREAD

**Issue by jayraj175coder** [anuragverma108/SwapReads#1336]
### Describe the feature

Pls assign me this issue for level 2...
@anu

### Add ScreenShots
![Screenshot_2024-06-03-22-40-47-618_com android chrome](https://github.com/anuragverma108/SwapReads/assets/135996214/235e0f2b-ebc8-4cc3-8eca-eb6d397715a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by huamanraj** [comment]
> Assigned level 2 @RitiChandak .
> Lot of work is there .
> 

someone else is working on this issue!
