### ISSUE TITLE
Feat: password strength feature

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1337]
### Describe the feature

creating a password strength feature so that when user go for signup he should add a strong password that will be hard to crack.
Users are currently able to sign up with the password "1234," but an error should be implemented to ensure they sign up with a stronger password.

Creating a feature to ensure that users log in with a strong password is very important.

### Add ScreenShots

some thing like this:

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/0c28d3ae-79d1-404e-abae-6c81842b07c0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@huamanraj can you please assign this...?

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
