### ISSUE TITLE
BUG: Reset password Page UI distorted 

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The UI of Forgot Password is Distorted...
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/812d79f2-fbd5-4360-b3b1-0bab61a22e88)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@RitiChandak please assign me this issue...

**Comment by RitiChandak** [comment]
Assigned!!
