### ISSUE TITLE
BUG:  Testimonial Message Not Readable in Dark Mode

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The testimonial message on the website is not readable when the dark mode is enabled. The text color blends with the background, making it difficult for users to read the content.
![Uploading testimonial alligment.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
someone is working on thsi
