### ISSUE TITLE
BUG: Line Height in FAQ's Answers Is Too Much

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The line height in the FAQ's answers is excessively large, leading to a lot of whitespace and making the content appear disjointed. This affects the readability and overall user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
