### ISSUE TITLE
BUG: Alignment of Dark/Light Mode Toggler in Header Is Not Perfect

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The alignment of the toggler for the dark/light mode in the header is not perfect. It appears misaligned, which affects the overall aesthetics and user experience of the website.
![toggler](https://github.com/anuragverma108/SwapReads/assets/129402285/7bb5eb88-2e72-4392-abaf-d52b9841e2d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The alignment of the toggler for the dark/light mode in the header is not perfect. It appears misaligned, which affects the overall aesthetics and user experience of the website.
> ![toggler](https://github.com/anuragverma108/SwapReads/assets/129402285/7bb5eb88-2e72-4392-abaf-d52b9841e2d8)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue



Assigned!
change the design also 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
