### ISSUE TITLE
Addition of icons on navbar

### ISSUE THREAD

**Issue by Niyatizzz** [anuragverma108/SwapReads#135]
### Describe the feature

Hi, I would like to add icons to the navbar next to home, benefits, etc to improve the website further and make it more user friendly! Please assign me this issue under gssoc'24.

### Add ScreenShots

![Screenshot 2024-05-11 153143](https://github.com/anuragverma108/SwapReads/assets/145595531/2cdb9ed7-9a09-4bfc-8d36-13b08721579c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SalehaTabassum** [comment]
Please assign this issue to me

**Comment by Nih1tGupta** [comment]
Icons for list items in a navbar can enhance usability and visual appeal, helping users quickly identify and navigate to different sections of a website.
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..

**Comment by anuragverma108** [comment]
Assigned !
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Vedant285** [comment]
I would like to add icons in nav bar and make it user attractive and friendly

**Comment by RitiChandak** [comment]
@Niyatizzz any updates?
