### ISSUE TITLE
BUG: Redirect links in book recommendation navbar not working

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108 , the redirect links to benefits, home etc is not not working in pages other than home.

Kindly assign me this issue under GSSoC'24. I'll do my best.

**Screenshot**

![Screenshot 2024-06-04 160151](https://github.com/anuragverma108/SwapReads/assets/100590445/c2538396-165f-4f4f-a685-46c5b6488772)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Hello @anuragverma108 , the redirect links to benefits, home etc is not not working in pages other than home.
> For this, need to make separate pages for genre, literacy realm code is required just like about us page and login/sign up page.
> 
> Kindly assign me this issue under GSSoC'24. I'll do my best.
> 
> **Screenshot**
> 
> ![Screenshot 2024-06-04 160151](https://github.com/anuragverma108/SwapReads/assets/100590445/c2538396-165f-4f4f-a685-46c5b6488772)
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
