### ISSUE TITLE
BUG:by click on toggle background color showing but not toggling 

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#1366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240604_164422](https://github.com/anuragverma108/SwapReads/assets/59639410/9723b269-6988-49f5-a8e2-68ffd6ce06e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @anuragverma108 please assign this issue to me under gssoc 24

**Comment by kapilG0** [comment]
Hello @huamanraj i mistakely unassigned me i already fixed that please reassign to me under gssoc 24.

**Comment by kapilG0** [comment]
Hello @huamanraj i raised pr #1546 for this issue please check and please reassign to me under gssoc 24 thanks

**Comment by huamanraj** [comment]
> Hello @huamanraj i raised pr #1546 for this issue please check and please reassign to me under gssoc 24 thanks
> 

will look into this soon

**Comment by kapilG0** [comment]
> > Hello @huamanraj i raised pr #1546 for this issue please check and please reassign to me under gssoc 24 thanks
> 
> will look into this soon

Ok
