### ISSUE TITLE
Feat: testimonials needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#1367]
### Describe the feature

![Screenshot_20240604_164716](https://github.com/anuragverma108/SwapReads/assets/59639410/625183ca-81dd-4aa5-90e9-1a9d8d02ec90)

### Add ScreenShots

![Screenshot_20240604_164716](https://github.com/anuragverma108/SwapReads/assets/59639410/87731b95-fec7-4c44-88f0-16e988f977c4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @anuragverma108 please assign this issue to me under gssoc 24

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> ![Screenshot_20240604_164716](https://github.com/anuragverma108/SwapReads/assets/59639410/625183ca-81dd-4aa5-90e9-1a9d8d02ec90)
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot_20240604_164716](https://github.com/anuragverma108/SwapReads/assets/59639410/87731b95-fec7-4c44-88f0-16e988f977c4)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue


Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!
