### ISSUE TITLE
Feat:in desktop after click on more it is not working properly 

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#1368]
### Describe the feature

![Screenshot_20240604_165111](https://github.com/anuragverma108/SwapReads/assets/59639410/6549a075-d622-45a5-a116-0120f51ea081)

### Add ScreenShots

![Screenshot_20240604_165111](https://github.com/anuragverma108/SwapReads/assets/59639410/88f5acc8-c785-45e5-8a41-db01bdc50ec1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @anuragverma108 please assign this issue to me under gssoc 24

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> ![Screenshot_20240604_165111](https://github.com/anuragverma108/SwapReads/assets/59639410/6549a075-d622-45a5-a116-0120f51ea081)
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot_20240604_165111](https://github.com/anuragverma108/SwapReads/assets/59639410/88f5acc8-c785-45e5-8a41-db01bdc50ec1)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor so you can reach out to me for any help!
Happy open-source contributing!

**Comment by kapilG0** [comment]
Hello @huamanraj i raised pr https://github.com/anuragverma108/SwapReads/pull/1526 for this please check
