### ISSUE TITLE
Feat: To add a page/section named "Our Contributors"

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#1379]
### Describe the feature

The people who contributed to this repo will have their name, avatar and github url displayed

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/00f25022-f09c-406e-a0fd-f9591bcbade5)

It will be better if we add it below "Meet Our team"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@huamanraj @anuragverma108 please have a look at this feature

**Comment by anuragverma108** [comment]
Assigned! @ayush-848
