### ISSUE TITLE
BUG: Testimonial card text is not visible in dark mode

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 Testimonial card text is not visible in dark mode

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/a358a361-4cc4-4322-93c7-40f1d7d18c65)

@anuragverma108 I would like to contribute under GSSoC 2024

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned! @SuhainaFathimaM 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
