### ISSUE TITLE
BUG: Adding Dark mode to login page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Adding Dark mode to login page

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/2c53a502-18b8-4250-8c0b-34180dc70032)

@anuragverma108 I would like to contribute under GSSoC 2024. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Someone is already been working on this issue
