### ISSUE TITLE
Switching the Index Page CSS to Tailwind CSS 

### ISSUE THREAD

**Issue by huamanraj** [anuragverma108/SwapReads#1384]
**the contributors are getting issues in finding right CSS so switching it to tailwind will work better !!! 
the code quality must be production grade and faster shipping of code!!**

**Comment by Maheshwari-Love** [comment]
@huamanraj You can assign this to me, I will definitely work on it

**Comment by huamanraj** [comment]
> @huamanraj You can assign this to me, I will definitely work on it

great work on it 💪

**Comment by katarianikita2003** [comment]
I would like to work on this issue, Can you please assign it to me?

**Comment by huamanraj** [comment]
> I would like to work on this issue, Can you please assign it to me?

you can work on other pages! he is assigned to index

**Comment by avinash-24-aptrix** [comment]
> **the contributors are getting issues in finding right CSS so switching it to tailwind will work better !!! the code quality must be production grade and faster shipping of code!!**

i can convert this from css->Tailwind CSS

**Comment by Maheshwari-Love** [comment]
I am working on this issue, due to exams it has been late and also getting some UI issue for responsiveness after conversion, which are to be solved, I will be getting back as soon as possible...
