### ISSUE TITLE
BUG:Nav bar(home page)

### ISSUE THREAD

**Issue by Abhigna-arsam** [anuragverma108/SwapReads#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

current:
![Screenshot 2024-06-04 215521](https://github.com/anuragverma108/SwapReads/assets/125258286/cb043c09-06c6-42bb-bc4d-3afb13802ca9)
Expected:
![image](https://github.com/anuragverma108/SwapReads/assets/125258286/cf00c56b-4d2b-4dec-8e3c-ae5e734e603e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abhigna-arsam** [comment]
@anuragverma108 please assign the above work to me

**Comment by anuragverma108** [comment]
Assiuned!
