### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [anuragverma108/SwapReads#1386]
### Describe the feature

I want to tell you that we have to dockerize the app because when in future anyone want to clone our app and use our app in different operating system then our project dont run in their system so for removing this problem we have to dockerize the app so that everyone can easily use our app

### Add ScreenShots

no screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by agarwalhimanshugaya** [comment]
Please assign me this issue under Gssoc'24

**Comment by huamanraj** [comment]
not planned !!
