### ISSUE TITLE
BUG: If user login, logout option doesn't showing on the navbar

### ISSUE THREAD

**Issue by Madhu-mac** [anuragverma108/SwapReads#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If user login to the website, logout button has to be shown on the nav-bar or with the user details 

https://github.com/anuragverma108/SwapReads/assets/99901964/28cb4699-a2af-44a5-9949-3ddcab2fdb1a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
@anuragverma108  Assign me this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by anuragverma108** [comment]
Assigned!
Make sure to star the repo before working on it! Happy open-source contributing!
