### ISSUE TITLE
Feat: Add light and dark mode in Booklist page

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#1393]
### Describe the feature

I want to add light and dark mode feature in booklist for swapping page as it is missing in this page.

### Add ScreenShots

<img width="950" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/145490348/b74af4c1-c9e2-410f-82d2-60c058acd447">

Please assign me this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> I want to add light and dark mode feature in booklist for swapping page as it is missing in this page.
> 
> ### Add ScreenShots
> <img alt="image" width="950" src="https://private-user-images.githubusercontent.com/145490348/336558061-b74af4c1-c9e2-410f-82d2-60c058acd447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODIyNjksIm5iZiI6MTcxNzU4MTk2OSwicGF0aCI6Ii8xNDU0OTAzNDgvMzM2NTU4MDYxLWI3NGFmNGMxLWM5ZTItNDEwZi04MmQyLTYwYzA1OGFjZDQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMDA2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDlhZTY1OGNkMDZlZTRlMjI1NmJjMTdmNWQzYzY4N2RmMDZhM2IyYWM5N2QwYzAzOGZhZTkwMzUyNWViNTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GAknqDtwim7M1Bj_z8_3jHURmNhxCGriumALppdoI9I">
> Please assign me this issue under GSSOC'24
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
