### ISSUE TITLE
BUG: Nav-bar buttons needs proper paddding 

### ISSUE THREAD

**Issue by Madhu-mac** [anuragverma108/SwapReads#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Nav-bar buttons needs proper padding from the sides, as it looks clusterred with the current padding 

![Screenshot_20240511_163837](https://github.com/anuragverma108/SwapReads/assets/99901964/48e954dd-d34d-4d71-8e5b-e271ca362403)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
@anuragverma108  Assign this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by G0HAN3** [comment]
Hello @anuragverma108 , could you please assign this issue to me? I believe my skills are well-suited to address it. Thank you!

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
