### ISSUE TITLE
BUG: Remove Extra Image from Header

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an extra image present in the header of the website that is not necessary. This extra image affects the overall design and clarity of the header section. Removing it will improve the visual appeal and streamline the header content.
![header](https://github.com/anuragverma108/SwapReads/assets/129402285/f1828789-f5a1-4465-a0e1-a1287077d52a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
/assign 

label as level 3

**Comment by Saipradyumnagoud** [comment]
I want to work on this issue please assign me the issue
/assign

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Saipradyumnagoud** [comment]
can you please assign me this  i will work on this
/assign
