### ISSUE TITLE
BUG: Button Text Not Visible Properly in Dark Mode

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In dark mode, the text on some buttons is not visible properly. The contrast between the button background and the text is insufficient, making it difficult to read the button labels. This affects user experience, especially for those who prefer using dark mode.
![btn-text](https://github.com/anuragverma108/SwapReads/assets/129402285/eae5bba3-9822-44a0-a657-99541cbd4e10)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
@anuragverma108 Please assign this issue to me|

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
