### ISSUE TITLE
BUG: unresponsive for mobile screen 

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_2024-06-05-02-07-35-18_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/anuragverma108/SwapReads/assets/148524648/44704002-553b-4168-83d6-bc0498be6610)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
