### ISSUE TITLE
Feat: adding autoplay in testimonials slider

### ISSUE THREAD

**Issue by dhairyagothi** [anuragverma108/SwapReads#1404]
### Describe the feature

i can add autoplay to testimonials slider all slides will change on its own

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/142989448/9b653461-d63d-4f56-a1bf-9ddc259460dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
