### ISSUE TITLE
Update Twitter Icon and Enhance Login/Signup Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 

- Replace the existing Twitter icon in the footer with the new Twitter logo.
- The hover effect of instagram icon in footer of login page has red color and I will add the gradient of instagram
- The requirements for strong password isn't looking good and need to change by removing additional bullet points.
- The footer of the login page need to enhance.

The things need to change in login page is as follows:

![Screenshot 2024-06-05 104523](https://github.com/anuragverma108/SwapReads/assets/159511364/31a10e27-d733-4620-816f-8a2cbfa2ebca)
![Screenshot 2024-06-05 104548](https://github.com/anuragverma108/SwapReads/assets/159511364/5a8effaf-dcb3-4d8d-af17-59a45cacb960)

**Please add the gssoc and level labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
