### ISSUE TITLE
Feat: I want to add a favicon for this website

### ISSUE THREAD

**Issue by Sailesh3000** [anuragverma108/SwapReads#141]
### Describe the feature

I am a GSSOC'24 Contributor I want to add a favicon to the website please assign me this issue

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/126142666/09e58559-321c-48c2-9713-9e5c95cfaa94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Add a good favicon.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by KavyaBS123** [comment]
Hey @anuragverma108 can you please assign me this issue I would like to work on it
