### ISSUE TITLE
BUG: Aligning the Free E-Book title

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the heading "Free E-books" is not center aligned which doesnt look visually appealing 

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/a0f852db-7434-49fd-9cf5-c56963fe6b4e)

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/b39d9f6f-cb51-47c5-ba70-9e91861ba4cc)

i would like to fix this issue, please assign me this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108  @huamanraj  please assign me this issue under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
