### ISSUE TITLE
BUG: changes in styling of footer

### ISSUE THREAD

**Issue by Shreyaa173** [anuragverma108/SwapReads#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer is not well aligned
![image](https://github.com/anuragverma108/SwapReads/assets/144673309/580101d5-55b5-4ece-aae8-6afc033f68e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
