### ISSUE TITLE
DOC: Better documentation in about us 

### ISSUE THREAD

**Issue by Shreyaa173** [anuragverma108/SwapReads#1414]
### What's wrong with the existing documentation

It is very concise, not giving full information.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/144673309/0d79128d-94bc-4fa3-951b-f28beb408a5e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by Shreyaa173** [comment]
can you please add relevant label for this for score?
