### ISSUE TITLE
BUG: Favorite icon is not visible 

### ISSUE THREAD

**Issue by Shreyaa173** [anuragverma108/SwapReads#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The favorite icon is not visible in dark theme.
![image](https://github.com/anuragverma108/SwapReads/assets/144673309/91d706ec-6dc6-4bc3-b1dc-4846b24e9d5f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
