### ISSUE TITLE
Enhance the  social icons in footer in Home Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1417]
### Describe the feature

Hey @anuragverma108 

Currently, in the footer section of home page, the icons are squared and I would like to make them look like original icon which enhance the visual appearance.
 
**please add the gssoc and the required level labels and I would like to work on  it under GSSOC'24. Thank you!!**

### Add ScreenShots

Before making the changes:
![Screenshot 2024-06-05 123808](https://github.com/anuragverma108/SwapReads/assets/159511364/3ffa2c2e-e4e8-49f2-8d41-3f313e5cb4c4)
![Screenshot 2024-06-05 123818](https://github.com/anuragverma108/SwapReads/assets/159511364/06b2b970-86db-410b-b125-c516368b8d9a)

After making the changes:

![Screenshot 2024-06-05 123710](https://github.com/anuragverma108/SwapReads/assets/159511364/92f9d75f-b243-4088-91f9-ee9ec5b42c34)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
