### ISSUE TITLE
BUG: Bottom top button - alignment correction

### ISSUE THREAD

**Issue by 221fa04732** [anuragverma108/SwapReads#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello PA,
I have observed that the alignment of bottom top scroll button is not at the right place, that should be in the same alignment as message button 

### screensort
![Screenshot 2024-06-05 142640](https://github.com/anuragverma108/SwapReads/assets/140374924/165e3536-7215-42c8-999a-b9bab498fe2e)

this is my first contributation to this project and i really wanted to do this, so it's my humble request to you to please add all the required labels and assigne me this task

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
