### ISSUE TITLE
BUG: Enhancement the testimonial card

### ISSUE THREAD

**Issue by 221fa04732** [anuragverma108/SwapReads#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello PA,
I have observed that in the testimonials cards for every person, the description are qouted and the quotation in out of the card

### SCREENSORT
![Screenshot 2024-06-05 143606](https://github.com/anuragverma108/SwapReads/assets/140374924/db27d225-9b67-42e8-9985-ce1d8471586d)

If you found this issue helpful pleasd add all the required label and assign me this task

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by 221fa04732** [comment]
thanks for assigning me this issue, can you please add label to this issue
