### ISSUE TITLE
BUG: Navigation and Hero section are piled on top of each other

### ISSUE THREAD

**Issue by katarianikita2003** [anuragverma108/SwapReads#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It need some adjustment in margin and padding section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by katarianikita2003** [comment]
I want to work on this issue. Can you please assign it to me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by katarianikita2003** [comment]
![Screenshot 2024-06-05 152324](https://github.com/anuragverma108/SwapReads/assets/158465309/8f025bda-f20d-4451-a727-cba2dbea5faa)
![Screenshot 2024-06-05 152337](https://github.com/anuragverma108/SwapReads/assets/158465309/f5ad221c-8d32-47b2-90d1-614861d7f9b8)
 
These are before and after of  updating style.css

**Comment by katarianikita2003** [comment]
Before and After

![Screenshot 2024-06-05 223357](https://github.com/anuragverma108/SwapReads/assets/158465309/e666f4bd-0305-4813-aa40-92a238480b7d)
![Screenshot 2024-06-05 223759](https://github.com/anuragverma108/SwapReads/assets/158465309/7df28826-8d5f-4326-98d3-f47f2c37b365)
