### ISSUE TITLE
Feat:Want to Write Backend Of Contact US Page

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1421]
### Describe the feature

when user Send the request to contact his query should get delivered to you as well as user should also recieve confirmation mail that we will contact you soon or something like that

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/5b9566b4-9f75-4614-a666-551c9982b72e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by nishant0708** [comment]
Okay @huamanraj

**Comment by nishant0708** [comment]
Hey just asking @huamanraj why this is assigned level one . Or it is just for now and I well be categorised after reviewing pr ?

**Comment by huamanraj** [comment]
> Hey just asking @huamanraj why this is assigned level one . Or it is just for now and I well be categorised after reviewing pr ?

this is just the default will increase while reviewing PR!

**Comment by nishant0708** [comment]
Oo okay thanks 👍👍
