### ISSUE TITLE
BUG:Visiblity Issue in login page 

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/54c2f0b1-75ff-4211-9b8f-e57a7707c0c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
