### ISSUE TITLE
Feat:hover color different from Current Theme

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1425]
### Describe the feature

hover Color is different from current theme in more dropdowm

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/30a97f47-d200-4f2b-b1cc-25aaf49f5818)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
