### ISSUE TITLE
BUG: invalid email input is accepted

### ISSUE THREAD

**Issue by dnyandeepchute** [anuragverma108/SwapReads#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in footer subscribe section it is taking invalid inputs and automatically changing all lower case to higher case alphabets
![Screenshot 2024-06-05 160752](https://github.com/anuragverma108/SwapReads/assets/158272735/56d3e4a3-451d-4e75-a553-cdfacb2a34b0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
hey @anuragverma108 , please assign this to me, thank you.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
