### ISSUE TITLE
Feat: Adding Github in Social Links

### ISSUE THREAD

**Issue by pani2004** [anuragverma108/SwapReads#1428]
### Describe the feature

I can add Github icon in the footer section 

### Add ScreenShots

![Screenshot (48)](https://github.com/anuragverma108/SwapReads/assets/154724111/66710e86-7583-46e8-94f2-d91fbe255406)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> I can add Github icon in the footer section 
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot (48)](https://github.com/anuragverma108/SwapReads/assets/154724111/66710e86-7583-46e8-94f2-d91fbe255406)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
