### ISSUE TITLE
BUG: mode button is not in center and not moving on click

### ISSUE THREAD

**Issue by dnyandeepchute** [anuragverma108/SwapReads#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

mode button is not in center and not moving on click so it need to be position properly and make it clickable or change the icon
![Screenshot 2024-06-05 160913](https://github.com/anuragverma108/SwapReads/assets/158272735/aaee3df8-ac2d-4457-9d19-991716600327)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
hey @anuragverma108 , please assign this to me, thank you.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
