### ISSUE TITLE
BUG: Translator and dark mode button are overlapping

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The translator button and the dark mode button are overlapping, causing usability issues. This makes it difficult for users to access and use these features properly  in About Us page.
![image](https://github.com/anuragverma108/SwapReads/assets/168854094/e510e194-5904-43f4-9c5f-ffad3a1ecb88)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
