### ISSUE TITLE
Feat:Add hover color to buttons in the cookie section

### ISSUE THREAD

**Issue by AkhilaSunesh** [anuragverma108/SwapReads#1435]
### Describe the feature

Add hover color to buttons in the cookie section

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/140897461/12884ca2-9e01-4332-bc8b-b08258a28f2d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ![image](https://github.com/anuragverma108/SwapReads/assets/140897461/083ac628-26db-4a5e-a122-754e2cfc2589)
> I haven't started as I wasn't assigned with this issue.

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!
