### ISSUE TITLE
BUG: Minor bugs

### ISSUE THREAD

**Issue by Praneeth-2602** [anuragverma108/SwapReads#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/137754636/cb2f88a6-41ee-4ab9-b664-030f76022049)

The navbar after logging in needs fixing 

![image](https://github.com/anuragverma108/SwapReads/assets/137754636/4bce61c6-3549-4970-a12a-b1bd59bf13c7)

color mismatch in light mode and I also wanna add the custom cursor in this page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/137754636/cb2f88a6-41ee-4ab9-b664-030f76022049)
> 
> The navbar after logging in needs fixing 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/137754636/4bce61c6-3549-4970-a12a-b1bd59bf13c7)
> 
> color mismatch in light mode and I also wanna add the custom cursor in this page
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by Praneeth-2602** [comment]
is this gonna be level 1 only? Just gonna confirm. One of issue was level 2 but the pr was labelled level 1

**Comment by huamanraj** [comment]
> is this gonna be level 1 only? Just gonna confirm.

yes! the gssoc foundation has strictly given the guidelines about levels that only complex features changes can get high levels that requires logics and programing

**Comment by Praneeth-2602** [comment]
Thank you!!
