### ISSUE TITLE
Feat:  Enhancing Footer Design for Improved Aesthetics By Adding icons 

### ISSUE THREAD

**Issue by GitNinja-bcd** [anuragverma108/SwapReads#1438]
### Describe the feature

Consider removing the SwapReads text from the footer section and replacing it with icons for a cleaner look. Additionally, add the about of swapreads in another section separately to further enhance the website's visual appeal.

### Add ScreenShots

![new](https://github.com/anuragverma108/SwapReads/assets/158538244/4e06e219-ee96-41e8-b6de-12ad1b84fc33)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Consider removing the SwapReads text from the footer section and replacing it with icons for a cleaner look. Additionally, add the about of swapreads in another section separately to further enhance the website's visual appeal.
> 
> ### Add ScreenShots
> 
> ![new](https://github.com/anuragverma108/SwapReads/assets/158538244/4e06e219-ee96-41e8-b6de-12ad1b84fc33)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
I am the project mentor so you can always reach out to me for any help! 
Happy open-source contributing!

**Comment by GitNinja-bcd** [comment]
Okay!!
