### ISSUE TITLE
Feat: Alert Pop-up box After Submission Contact form

### ISSUE THREAD

**Issue by Che140401** [anuragverma108/SwapReads#144]
### Describe the feature

1. When user clicked on submit form user will get the pop up box 

### Add ScreenShots

When we clicked the submit button page is refreshing... but we havent got confirmation mail....

https://github.com/anuragverma108/SwapReads/assets/109230049/34ce59cc-d817-4e7f-9895-627b80251702

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ZegonDraikon** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor and
 I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @Che140401 
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Che140401** [comment]
Access dening @anuragverma108 when im trying to push with my branch

![Screenshot 2024-05-12 160612](https://github.com/anuragverma108/SwapReads/assets/109230049/89e2e2b1-3909-4ed8-af51-20cf1e150eea)

**Comment by Che140401** [comment]
Hey i have made PR Request please check
