### ISSUE TITLE
DOC: change readme, add how to get set up project

### ISSUE THREAD

**Issue by sakshii00** [anuragverma108/SwapReads#145]
### What's wrong with the existing documentation

I would like to add more to the readme on how to get on with the project and a section for contributors.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned !
Make sure to star the repo before working on it! Happy open-source contributing!
