### ISSUE TITLE
BUG: Back to top icon is aligned left 

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/44d4c273-7c6a-49b1-9430-07955fbefd0a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution! 🌻
