### ISSUE TITLE
BUG: Toggle button at navbar remains same for both dark and light mode

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/b843b270-5ab4-4fcc-85b8-4928168b4374)

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/57f43ecc-8102-4370-a99c-5e0e8dc2cad4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
