### ISSUE TITLE
BUG: About page has no styles

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anuragverma108/SwapReads#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/2e7f8beb-757d-4271-b77a-534b18703e49)

![image](https://github.com/anuragverma108/SwapReads/assets/153417476/712ed17b-dce5-49c8-8ee0-84d07b2e2284)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution! 🌻
