### ISSUE TITLE
Feat:Adding a Genre section 

### ISSUE THREAD

**Issue by vedanshipathak** [anuragverma108/SwapReads#146]
### Describe the feature

i would like to add a genre section with the description of each genre where user can select their favorite genre to talk about.
please assign me this task under GSSOC'24

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned !
Make sure to star the repo before working on it! Happy open-source contributing!
