### ISSUE TITLE
Feat: Implement length for message in Write me Anything

### ISSUE THREAD

**Issue by Aarzookhunger** [anuragverma108/SwapReads#1469]
### Describe the feature

In the write me anything form, a check over message length should be there such as length of message should be greater than 100.
It'll help to avoid receiving empty 1-2 character messages which others may send without any purpose.

This may help in decluttering the message piles being received.

Kindly assign this issue to me under GSSOC'24!
Thanks..

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/116306749/f28f1564-4cc9-4813-8d35-5958ec54f5b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
