### ISSUE TITLE
Feat: Scroll to the top button

### ISSUE THREAD

**Issue by dwivedishrey** [anuragverma108/SwapReads#147]
### Describe the feature

Want to add scroll to the top button to move to the top of the page easily.
Please assign this task to me

### Add ScreenShots

![Screenshot 2024-05-11 191417](https://github.com/anuragverma108/SwapReads/assets/97790062/5d982835-eb30-4aff-be34-c8c59aafabc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shrashti2004** [comment]
@dwivedishrey I want to contribute to the project  , please assign me this under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned @dwivedishrey 
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by G0HAN3** [comment]
Hello @anuragverma108 , could you please assign this issue to me? I believe my skills are well-suited to address it. Thank you!
