### ISSUE TITLE
Feat: Hover effect on read more button in Benefits section

### ISSUE THREAD

**Issue by Damini2004** [anuragverma108/SwapReads#1470]
### Describe the feature

Here the button in benefit section will appear like this in order to achieve more advancement in this website.

### Add ScreenShots

![Screenshot 2024-06-06 022353](https://github.com/anuragverma108/SwapReads/assets/119414762/165abc0d-a788-4ecd-8abf-87b7fa6771c0)

https://github.com/anuragverma108/SwapReads/assets/119414762/43a5f861-d847-4ca1-a6f6-eba2f56ddf71

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
