### ISSUE TITLE
BUG: Overlapping icons

### ISSUE THREAD

**Issue by Aarzookhunger** [anuragverma108/SwapReads#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/116306749/8c1a6f4b-c162-4259-a6e8-f701183ac092)
overlap of icons while we enter password.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution!  🌻
