### ISSUE TITLE
Feat: Add animate swapreads text 

### ISSUE THREAD

**Issue by divyansh2375** [anuragverma108/SwapReads#1473]
### Describe the feature

i want to add swap read animated text in homepage. can you please assign it to me ?

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/130889408/15a6f90c-3d1f-42ec-9c4e-1ced42862c30)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution! 🌻
