### ISSUE TITLE
BUG: Page Reload when we click on subscribe button in footer and there times inputs and buttons

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#1476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Page should not reload when we click on subscribe button.
There are two times showing of subscribe button.
![image](https://github.com/anuragverma108/SwapReads/assets/126322584/86b3b8f1-22df-462c-afe6-6a608e02b241)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Page should not reload when we click on subscribe button.
> There are two times showing of subscribe button.
> ![image](https://github.com/anuragverma108/SwapReads/assets/126322584/86b3b8f1-22df-462c-afe6-6a608e02b241)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
