### ISSUE TITLE
BUG: Some pages are not linked in nav bar and some pages does not have proper nav bar alligned

### ISSUE THREAD

**Issue by roushanverma23** [anuragverma108/SwapReads#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in the book recommendation page nav links are not properly added and also some pages are not opening

![image](https://github.com/anuragverma108/SwapReads/assets/137530796/2674c17f-d2d0-4f54-9e8d-69442e8dafe0)

![image](https://github.com/anuragverma108/SwapReads/assets/137530796/c3057664-645f-4154-9464-bbf67aaa8107)

![up](https://github.com/anuragverma108/SwapReads/assets/137530796/7bee4d21-6a39-40c5-998a-cd083026665f)

@huamanraj please assign this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
