### ISSUE TITLE
BUG: same text repeating alignment issue

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-06 123005](https://github.com/anuragverma108/SwapReads/assets/146661411/23be3f66-98ac-4655-8ef3-2999cd536a7e)
pricing word repeating side by side
make it in columns

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
