### ISSUE TITLE
Feat: Improve Navbar

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#1482]
### Describe the feature

Add Login/button
it it now normal <li> but i wish to make it a button and place it on second left from right. 

### Add ScreenShots

![Screenshot 2024-06-06 123126](https://github.com/anuragverma108/SwapReads/assets/146661411/f781e0ca-25e3-4299-9e5f-0ee0d9116b7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
appreciate your recommendation but not planned yet!
