### ISSUE TITLE
Feat: quick links missing in the E Book

### ISSUE THREAD

**Issue by Saipradyumnagoud** [anuragverma108/SwapReads#1483]
### Describe the feature

Adding all the quick links in the  E book section there are few quick links missing in the E Book section 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143107589/534169c6-35f3-4453-adf4-2de6ea3f9b0a)
quick link in home section 

![image](https://github.com/anuragverma108/SwapReads/assets/143107589/3e982c94-dab6-430e-af46-3bfcb5194f01)
quick links in E book section 
all Links are not present in the Ebook section 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned! but from next time dont create PR before assignment 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊

**Comment by Saipradyumnagoud** [comment]
Before 
![image](https://github.com/anuragverma108/SwapReads/assets/143107589/0b1a8608-6e6d-4473-8853-51ab0fec2d09)

After 
![image](https://github.com/anuragverma108/SwapReads/assets/143107589/918d7bc7-478a-4fda-87b4-7ca3e6a53268)

**Comment by Saipradyumnagoud** [comment]
> Assigned! but from next time dont create PR before assignment Make sure to attach before & after screenshots in your PR and include the issue number. i am the project mentor you can always reach out to me for any help!
> 
> Also, please star ⭐ the repo before working on it. Happy open-source contributing! 😊

Thank you 
I have added before and after screenshots in my pull request
