### ISSUE TITLE
BUG: Duplicate hover effect on navbar components 

### ISSUE THREAD

**Issue by Amruta7203** [anuragverma108/SwapReads#1484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a duplicate hover effect on the navbar components which is not required:
![image](https://github.com/anuragverma108/SwapReads/assets/116087736/7a9990d7-e70b-4146-ac77-98792986edc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
