### ISSUE TITLE
Feat: Adding favicon on the About page 

### ISSUE THREAD

**Issue by Amruta7203** [anuragverma108/SwapReads#1486]
### Describe the feature

There is no favicon on about page

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/116087736/870e2caa-2701-4cc1-ac7e-2da4b6247bad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution!
