### ISSUE TITLE
Feat: Adding more book recommendations 

### ISSUE THREAD

**Issue by Amruta7203** [anuragverma108/SwapReads#1487]
### Describe the feature

Adding More Book Recommendations for Enhanced User Experience

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/116087736/0e920641-62ab-40db-a04a-2e6a863b19d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure you include before and after screenshots in your PR. To avoid conflicts when creating your PR, you can pull all existing changes first. Happy open-source contribution! 🌻
