### ISSUE TITLE
BUG: Dark Mode Toggle Button Overlapped by Scrollbar on Desktop

### ISSUE THREAD

**Issue by Amruta7203** [anuragverma108/SwapReads#1488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dark mode toggle button on the website is positioned on the extreme right and is currently being obscured by the scrollbar on desktop devices. This can lead to a frustrating user experience as users may find it difficult to click or even see the button to switch between light and dark mode.

![image](https://github.com/anuragverma108/SwapReads/assets/116087736/61c1337f-9843-4b2b-8d6b-801f79c712ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
