### ISSUE TITLE
Feat:  Dark Mode Color Palette Needs Improvement

### ISSUE THREAD

**Issue by Amruta7203** [anuragverma108/SwapReads#1489]
### Describe the feature

The current color palette for dark mode on the website might not be optimal for user experience.  
This could be due to factors like:

Low contrast: Text or UI elements may be difficult to read due to insufficient contrast between foreground and background colors.
Eye strain: The color choices might cause eye strain for users, especially during extended use in low-light environments.
Lack of vibrancy: The color scheme might appear dull or unappealing, reducing the overall user experience.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/116087736/c8e8f85a-750f-4306-a084-a1e2902da9ee)

![image](https://github.com/anuragverma108/SwapReads/assets/116087736/4053d961-4706-4764-b1c9-ec08c529c197)
Many components are not visible in the dark mode
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishabhDhawad** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
