### ISSUE TITLE
Feat: Adding logo to website

### ISSUE THREAD

**Issue by KavyaBS123** [anuragverma108/SwapReads#149]
### Describe the feature

Brand Identity:  Your logo is the cornerstone of your brand's visual identity. It's the first impression visitors get and sets the tone for your entire website. A strong logo is memorable and instantly recognizable, making you stand out from competitors.

Builds Trust & Professionalism:  A well-designed logo conveys professionalism and legitimacy. It tells visitors you take your business seriously and are invested in quality. Conversely, a weak logo can create a negative impression and cause visitors to doubt your credibility.

### Add ScreenShots

![connect](https://github.com/anuragverma108/SwapReads/assets/148982177/e3cb4009-ea0b-41af-9bb6-34c30f84fa88)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nih1tGupta** [comment]
Please assign me this issue under gssoc'24, I would love to work on this issue.

**Comment by shrashti2004** [comment]
Hi I want to contribute , Please assign me this issue under gssoc'24,

**Comment by KavyaBS123** [comment]
@anuragverma108 can you please assign the issue

**Comment by anuragverma108** [comment]
Issue already exists
