### ISSUE TITLE
Feat: Separate the CSS for book recommendation page from style.css 

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1493]
### Describe the feature

There is only one CSS file which has almost styling for all the pages ,which is very hectic to find the styles for particular pages or components of a pages Because of which the contributors find it hard to search particulars for styling. like pages:
Recommendation page
Solution: 
By separating the files just make code modular and loosly coupled which will easy to all.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/34c967e9-f938-4cac-83c9-9416117d03af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@RishabhDhawad @huamanraj please assign me ...

**Comment by huamanraj** [comment]
> @RishabhDhawad @huamanraj please assign me ...
> 

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
