### ISSUE TITLE
Make book exchange hub section responsive

### ISSUE THREAD

**Issue by Ankesh2004** [anuragverma108/SwapReads#15]
Book Exchange Hub Section is **not responsive for mobile view.**
Kindly assign me this issue as a part of GSSOC'24
![11111111](https://github.com/anuragverma108/SwapReads/assets/65663130/34121653-e1fc-4772-b13e-72f438fed15d)

**Comment by anuragverma108** [comment]
Assigned @Ankesh2004

**Comment by anuragverma108** [comment]
Any Updates @Ankesh2004.  Are you working on the issue ??

**Comment by Ankesh2004** [comment]
> Any Updates @Ankesh2004.  Are you working on the issue ??

Yes, I am working on it. As the event will start from 7:00 p.m. today, I will create PR after 7:00 p.m.
