### ISSUE TITLE
Social links in mobile view are not properly aligned 

### ISSUE THREAD

**Issue by jayraj175coder** [anuragverma108/SwapReads#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have seen in mobile view all sections are proper .
But coming to the down social links and other links
![Screenshot_2024-05-11-21-13-18-941_com android chrome](https://github.com/anuragverma108/SwapReads/assets/135996214/4190ade6-ec16-451c-a215-8ccdcc80ae8d)
 are horizontal aligned.
This effect response of webpage.
Could you assigned this issue under gssoc24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned !
Yep 
Make the footer responsive.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by jayraj175coder** [comment]
Done this @anuragverma108 , Check pull request.
