### ISSUE TITLE
Enhance the footer in books Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1501]
### Describe the feature

Hey @anuragverma108 

When the book in literary realms are opened, the footer is not looking good. The footer need to be enhanced for the better visual appearance .

**Please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Currently, the footer looking like:

![Screenshot 2024-06-06 200523](https://github.com/anuragverma108/SwapReads/assets/159511364/3eb68ce2-fe35-45cc-b761-11746b034976)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
