### ISSUE TITLE
Include GitHub Icon in Footer of Login Section

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1504]
### Describe the feature

Hey @anuragverma108 

Enhance the footer of the Login Page by adding a GitHub icon that links to our GitHub repository. This will improve visibility and accessibility for users who want to explore our project's codebase or contribute to its development.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

currently, it looks like:

![Screenshot 2024-06-06 203623](https://github.com/anuragverma108/SwapReads/assets/159511364/6057cecf-203c-41ed-b733-0c50027b3db9)

The github icon need to be added in the icons section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
