### ISSUE TITLE
Add Social Icons to the Footer of the "About Us" Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1508]
### Describe the feature

Hey @anuragverma108 

Enhance the footer of the "About Us" page by adding social media icons for better user engagement and easier access to our social media profiles.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Currently, the footer of about us page looks like:

![Screenshot 2024-06-06 221155](https://github.com/anuragverma108/SwapReads/assets/159511364/41b01e16-ab8d-446a-97e2-13fbcb25b843)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
