### ISSUE TITLE
Enhance Social Icons in footer of "Free e-book Page"

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1509]
### Describe the feature

Hey @anuragverma108 

Currently, in the footer section of home page, the icons are squared and I would like to make them look like original icon which enhance the visual appearance.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Currently, it looks like:

![Screenshot 2024-06-06 221052](https://github.com/anuragverma108/SwapReads/assets/159511364/063289a0-040f-4ce9-b5d5-46ce1a088df8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
