### ISSUE TITLE
In mobile view, Log in section not aligned properly 

### ISSUE THREAD

**Issue by jayraj175coder** [anuragverma108/SwapReads#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to work with for implementation of ui where the section text and login container aligned properly in mobile view.
Could you assign this issue under gssoc24?
![Screenshot_2024-05-11-21-06-01-185_com android chrome](https://github.com/anuragverma108/SwapReads/assets/135996214/93d0c30d-9f44-4efb-ac55-6abec0119eb4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @jayraj175coder 
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by jayraj175coder** [comment]
Hey @anuragverma108 , I did this check the pull Request. Thnaks,.
