### ISSUE TITLE
BUG: The navbar on the books.html page is not aligned.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar on the books.html page is not aligned. The light/dark toggle button is lying one side. Please assign this issue to me under GSSOC'24.
![image](https://github.com/anuragverma108/SwapReads/assets/107904311/34e96769-f391-42c3-b3a9-4b4e66f0a210)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
