### ISSUE TITLE
BUG: Dark/Light toggle.

### ISSUE THREAD

**Issue by Aditii-1** [anuragverma108/SwapReads#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The toggle icon of dark and light mode is overlapping with the "More" in navbar.

Along with the mis-alignment, When clicked on the toggle, to change the mode, it doesn't change from sun icon to moon icon.

![a1](https://github.com/anuragverma108/SwapReads/assets/167450321/4711c941-5abc-4bdb-9191-2ab9bbcd0702)

![a3](https://github.com/anuragverma108/SwapReads/assets/167450321/98c4142c-47d0-47a5-89d2-ff301897dec9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊

**Comment by Aditi-Gopinath** [comment]
@huamanraj I have created a PR. Kindly review and approve it.
