### ISSUE TITLE
Feat: Replacing current favicons with transparent background ones

### ISSUE THREAD

**Issue by arpy8** [anuragverma108/SwapReads#1519]
### Describe the feature

The current favicon does not have a transparent favicons

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/74809468/e3849698-527c-4ccc-9980-23f545b86356)

![image](https://github.com/anuragverma108/SwapReads/assets/74809468/dfcc1bd0-c939-4f50-a51a-738fad6d8db2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊

**Comment by arpy8** [comment]
@huamanraj done!
