### ISSUE TITLE
Feat: Responsive website

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#152]
### Describe the feature

Currently the website is not responsive. I want to work on this. Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Madhuri36 
I think it is responsive.
Attach the screenshots to describe your issue more clearly.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Madhuri36** [comment]
![pic1](https://github.com/anuragverma108/SwapReads/assets/146222028/8e7c8a7e-d08c-44fc-b7d4-3dd20c0d6751)
@anuragverma108  the footer section of the website is not responsive and there is an overflow when viewing in mobile. I would like to work on this.

**Comment by anuragverma108** [comment]
Assigned!
Make sure to star the repo before contributing

**Comment by Madhuri36** [comment]
@anuragverma108 I submitted the pull request with the specific changes. Please allot the level label for this issue
