### ISSUE TITLE
BUG:Navbar code got overriden

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The changes I made to the navbar for tablet and mobile on PR #1217 and redid them in #1277 are overriden again by someone resolving conflicts and merging incorrectly.
Look at the video in #1217 for how the navbar was before.
Right now it looks like this:

tablet:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/f24595d1-7bcc-407f-9d11-363b4781de39)

mobile:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/781e08c9-3558-4c56-90f7-07b1f25844e4)

and its not even sticking to the top on scrolling down:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/c77ca27a-ac9c-46f4-a283-e890667facd5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
yes! there is a lot of PR we are merging and we made some mistakes in reviewing the code and now we can't figure it out where the mistake was! 

you can fix this you will get new PR merged!
