### ISSUE TITLE
DOC:Add License to this repository

### ISSUE THREAD

**Issue by Priyanshu2631** [anuragverma108/SwapReads#1523]
### What's wrong with the existing documentation

I want to add the MIT License to this repository, please assign this issue under GSSOC 24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor you can always reach out to me for any help! 

Also, please star ⭐ the repo before working on it. 
Happy open-source contributing! 😊
