### ISSUE TITLE
BUG:Links not working on Book_recommendation page

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/148524648/20aa8720-271c-4eba-9d34-16b9483b1765)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/148524648/20aa8720-271c-4eba-9d34-16b9483b1765)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

someone is working on this issue
