### ISSUE TITLE
Feat:Hamburger icon not working 

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#1527]
### Describe the feature

https://github.com/anuragverma108/SwapReads/assets/59639410/14391290-2e25-43f3-863c-cf735afa5547

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/59639410/80928338-a772-451e-a98f-1311a54fc836

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @huamanraj please assign this issue to me under gssoc 24

**Comment by huamanraj** [comment]
> Hello @huamanraj please assign this issue to me under gssoc 24

assigned
