### ISSUE TITLE
Feat: Google O auth

### ISSUE THREAD

**Issue by sum1t-here** [anuragverma108/SwapReads#153]
### Describe the feature

Let the user sign up directly using google account, something similar to the picture below where the user can login/signup using sma

### Add ScreenShots

<img width="284" alt="Screenshot 2024-05-11 at 10 00 23 PM" src="https://github.com/anuragverma108/SwapReads/assets/126807055/69e3c2ee-9f55-4994-ad63-5f7d705a0b0b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sum1t-here** [comment]
Hey @anuragverma108 assign me this issue under GSSOC'24

**Comment by Virucodes** [comment]
Hii @anuragverma108 i am experienced person with google authentication with firebase we can do it using firebase can you please assign me this task under GSSoC'24

**Comment by Rupalpy** [comment]
@anuragverma108 I can work on google authentication by using firebase service . Kindly assign me the task.

**Comment by sum1t-here** [comment]
Hey @anuragverma108 please ensure that the step below is enabled in your javascript console

![Screenshot_20240514-110826_Chrome.jpg](https://github.com/anuragverma108/SwapReads/assets/126807055/8d6aa897-d233-4b49-8939-e8fd3ea126a5)

**Comment by sum1t-here** [comment]
Hey @anuragverma108 please add the gssoc label as well
