### ISSUE TITLE
DOC:Missing Code Of Conduct file

### ISSUE THREAD

**Issue by Priyanshu2631** [anuragverma108/SwapReads#1530]
### What's wrong with the existing documentation

A code of conduct file is necessary for smoother contribution and collaboration, reducing conflicts which is missing in this repository. Please assign this issue under GSSOC '24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
there is a file under information folder
