### ISSUE TITLE
BUG: Design is not optimized for mobile devices.

### ISSUE THREAD

**Issue by Pranav0606** [anuragverma108/SwapReads#1532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The UI design is not responsive for small width devices.
![Screenshot_20240607_132024](https://github.com/anuragverma108/SwapReads/assets/97611449/c13a3f92-ef7e-4b02-b57e-9828856fa71a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on this! and try using a good approach
