### ISSUE TITLE
BUG: The More Option and Dark mode were Colliding

### ISSUE THREAD

**Issue by sailaja-adapa** [anuragverma108/SwapReads#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The More Option and darkmode  were Colliding which is causing to look clumsy 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The More Option and darkmode  were Colliding which is causing to look clumsy 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

issue assigned to someone else
