### ISSUE TITLE
Cookies frame 

### ISSUE THREAD

**Issue by RishiMehtaa** [anuragverma108/SwapReads#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cookies frame does not disappear on accepting/rejecting. I would like to work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned! @RishiMehtaa 
Make sure to attach before & after screenshots in your PR and include the issue number.
i am the project mentor you can always reach out to me for any help!

Also, please star ⭐ the repo before working on it.
Happy open-source contributing! 😊
