### ISSUE TITLE
Feat: Forget password

### ISSUE THREAD

**Issue by sum1t-here** [anuragverma108/SwapReads#154]
### Describe the feature

Let us create a route where one can change their password when they click on forget password

### Add ScreenShots

None

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sum1t-here** [comment]
hey @anuragverma108 assign this issue to me under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned @sum1t-here 
Make sure to star the repo before working on it! Happy open-source contributing!
