### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by vignesh-0512** [anuragverma108/SwapReads#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the deployed link footer is not responsive some contents are our of range, so I request you to assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by vignesh-0512** [comment]
Thanks for assigning this issue to me I will fix it as soon as possible and I will raise a pr
