### ISSUE TITLE
Feat: Making navbar sticky

### ISSUE THREAD

**Issue by harikasayani** [anuragverma108/SwapReads#1552]
### Describe the feature

I observed that navbar is not sticky.
I want to make it sticky.

### Add ScreenShots

![Screenshot (163)](https://github.com/anuragverma108/SwapReads/assets/143275265/e51a78d1-369d-49b6-a60e-fd99637844d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
i am the project mentor you can always reach out to me for any help!

Also, please star ⭐ the repo before working on it.
Happy open-source contributing! 😊
