### ISSUE TITLE
BUG:About Us page .

### ISSUE THREAD

**Issue by sristy17** [anuragverma108/SwapReads#1556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we use the website in dark mode n change options to About us page it does not change in existing dark mode automatically we need to on the dark mode manually.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
i am the project mentor you can always reach out to me for any help!

Also, please star ⭐ the repo before working on it.
Happy open-source contributing! 😊

**Comment by sristy17** [comment]
> Assigned!
> Make sure to attach before & after screenshots in your PR and include the issue number.
> i am the project mentor you can always reach out to me for any help!
> 
> Also, please star ⭐ the repo before working on it.
> Happy open-source contributing! 😊
> 
> 
 Thanks! Will reach you out, if needed!

**Comment by huamanraj** [comment]
> > Assigned!
> > Make sure to attach before & after screenshots in your PR and include the issue number.
> > i am the project mentor you can always reach out to me for any help!
> > 
> > Also, please star ⭐ the repo before working on it.
> > Happy open-source contributing! 😊
> > 
> > 
>  Thanks! Will reach you out, if needed!

great 👍

**Comment by sristy17** [comment]
> > > Assigned!
> > > Make sure to attach before & after screenshots in your PR and include the issue number.
> > > i am the project mentor you can always reach out to me for any help!
> > > 
> > > Also, please star ⭐ the repo before working on it.
> > > Happy open-source contributing! 😊
> > > 
> > > 
> >  Thanks! Will reach you out, if needed!
> 
> great 👍

Both the prs got merged cam close the issues?
