### ISSUE TITLE
BUG: Cookies's buttons : Accept , Reject are not working 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Accept" and "Reject" buttons on the cookie consent banner do not work. When clicked, nothing happens, and the banner stays on the screen. This prevents users from making a choice about cookies.

https://github.com/anuragverma108/SwapReads/assets/121204667/d5b3f27e-2ff1-4419-935a-80a5e10042a3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
i am the project mentor you can always reach out to me for any help!

Also, please star ⭐ the repo before working on it.
Happy open-source contributing! 😊
