### ISSUE TITLE
BUG: Position of the Move to Top Button Is Not Perfect

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Move to Top" button is not positioned correctly on the screen. Its placement can interfere with other elements and does not follow the expected design standards.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
i am the project mentor you can always reach out to me for any help!

Also, please star ⭐ the repo before working on it.
Happy open-source contributing! 😊
