### ISSUE TITLE
BUG:Negative pricing 

### ISSUE THREAD

**Issue by ananya-dhiman** [anuragverma108/SwapReads#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Book Exchange Hub has a pricing part where the number decrement  to negative values which is not realistic. So it can be limited to a certain minimum value.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @ananya-dhiman 
Make sure to star the repo before start working on!
