### ISSUE TITLE
BUG: Hovering over customers' review

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I hover my curser over the customers' review, the label flips to be :
![image](https://github.com/anuragverma108/SwapReads/assets/145102345/50cad0b1-801a-43b3-a6cf-f9b16532f3a4)
As can be seen, this is not the optimal appearance, and I will correct this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
I corrected this to:
![image](https://github.com/anuragverma108/SwapReads/assets/145102345/84d49c9d-d0a6-4bfb-954b-f698e831b181)

furthermore I also changed white background of card in light mode to black background:
![image](https://github.com/anuragverma108/SwapReads/assets/145102345/f90fd690-b262-4c27-a48c-5acf4af7ad72)

**Comment by anuragverma108** [comment]
Pull the existing changes.
Check it in the website whether it is bug there or not!

**Comment by VijaySamant4368** [comment]
@anuragverma108 I viewed the site in the following browsers:
Firefox, Opera, Chrome, Brave, Edge; and the problem is occurring only in Firefox browser for some reason.

I would recommend you to check the same in Firefox yourself.
(index.html file)

**Comment by VijaySamant4368** [comment]
@anuragverma108

**Comment by VijaySamant4368** [comment]
@anuragverma108 please do go over it
