### ISSUE TITLE
BUG: Navbar not same in light mode if we scroll

### ISSUE THREAD

**Issue by parikhitritgithub** [anuragverma108/SwapReads#1575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

if we scroll the page in light mode then popup nav bar not same as the light mode static nav bar 
![image](https://github.com/anuragverma108/SwapReads/assets/124444610/751f5aff-319d-4007-9d7e-68d7374d0320)
![image](https://github.com/anuragverma108/SwapReads/assets/124444610/61403b6b-4e32-4c69-81e9-26d33bd87a19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
