### ISSUE TITLE
Feat: Read more feature in literary realm is not working

### ISSUE THREAD

**Issue by vedanshipathak** [anuragverma108/SwapReads#158]
### Describe the feature

@anuragverma108 Currently if we click on the read more link in the literary realm ,it is not working. I can work on it so that when someone link on read more it shows all the description about that particular topic .

### Add ScreenShots

![Screenshot 2024-05-12 000722](https://github.com/anuragverma108/SwapReads/assets/141757766/2de7a12b-e055-48cb-96c4-2611ec9f5f5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@vedanshipathak Create new webpage for each read more. The UI should be same as of index.html
I will label your contribution under level 3 in GSSOC'24
Go ahead!

**Comment by RitiChandak** [comment]
@vedanshipathak  any updates?
