### ISSUE TITLE
Feat: Secure Sign-Up: Double-Check Your Password / Confirm Password field for registering new user 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1580]
### Describe the feature

Upon entering their desired password, users will be prompted to re-enter it in a  "Confirm Password" field. This will reduce input errors and will ensure the accuracy of user's  credentials, and  further in login section there is no need for this field.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/121204667/19e57a37-c93e-4f4b-aa98-1bd06e2a9770)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tomkndn** [comment]
Hey, if no one is currently there for this issue.
Kindly assign this issue to me.

**Comment by Tomkndn** [comment]
Have you tried "npm i" first?

**Comment by gudia18** [comment]
yes, even its showing that server is running on localhost 3000 but getting error of routings : cannot get/

**Comment by gudia18** [comment]
![error1](https://github.com/anuragverma108/SwapReads/assets/121204667/79373827-8fe0-49da-88c7-92ce25e676ed)


@RishabhDhawad  
@anuragverma108 
please help me in this error , dont  know why its showing like this
