### ISSUE TITLE
Book recommendation page not found error

### ISSUE THREAD

**Issue by Taniishaaa** [anuragverma108/SwapReads#1581]
The book recommendation page is missing. 
It shows 404_NOT_FOUND error when clicked on Book recommendations.
![Screenshot 2024-06-08 154611](https://github.com/anuragverma108/SwapReads/assets/155306736/f2c5e9dd-8ab4-421b-b467-6f34ad80c6d8)

**Comment by Taniishaaa** [comment]
please assign me this issue under gssoc levels @anuragverma108

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Taniishaaa** [comment]
@anuragverma108 do you want book recommendations page to open in new tab or the same tab?

**Comment by anuragverma108** [comment]
On same tab

**Comment by anuragverma108** [comment]
@Taniishaaa After doing the work! Show the screenshots to me on my discord anuragverma_108.

**Comment by Taniishaaa** [comment]
@anuragverma108  Sent the screenshot to you on discord and created a pull request.
