### ISSUE TITLE
BUG: Issues in navbar light/dark mode

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#1588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. navbar is not sticky.
2. In light mode, when scrolling, the navbar is becoming like dark mode which should not happen.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/a1a0d3c8-0e5c-4358-aa61-6e9695e0b676)

3. Toggle button is also not functioning properly.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/3a2ba422-e1c3-4838-b6f2-13aeec0853ea)
in light mode, a moon icon should be present to indicate "change to dark theme" but it is only a sun icon. Toggling of the icons is not happening.
I want to fix all these issues, @anuragverma108  @huamanraj  @RitiChandak Please assign to me under GSSoC'24.
Thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gaurav-Kushwaha-1225** [comment]
I want to contribute on this issue. Can you assign it to me ??

**Comment by Madhuri36** [comment]
@anuragverma108 @huamanraj @RitiChandak please look into this issue, as this has not been assigned yet, but a PR has been made.

**Comment by anuragverma108** [comment]
@Madhuri36 
Assigned!
Make sure to attach before & after screenshots in your PR.

**Comment by anuragverma108** [comment]
@Gaurav-Kushwaha-1225 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
