### ISSUE TITLE
BUG: Can change the title as it shows the wrong title

### ISSUE THREAD

**Issue by sweta-singh28** [anuragverma108/SwapReads#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The title on the login page currently displays "How to create Firebase login and register". I'd like to update it to simply say "Login/Register" to streamline the user experience. I'm interested in tackling this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this issue ?

**Comment by anuragverma108** [comment]
Assigned @sweta-singh28
