### ISSUE TITLE
Feat: Enhancing the UI of free e-books  page

### ISSUE THREAD

**Issue by Pranav0606** [anuragverma108/SwapReads#1591]
### Describe the feature

UI of free e-books looks not good, which may leads to poor user interaction. This PR will enhance the UI to make it look more better.

### Add ScreenShots

Current poor UI with improper alignment of elements:
![image](https://github.com/anuragverma108/SwapReads/assets/97611449/7aead6e9-3a72-4747-8bd1-ed87d8804e3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned 👍
