### ISSUE TITLE
ADDING A REMEMBER ME OPTION FOR CONSTANT READERS / VISITORS TO THE SITE AND AGREE TO TERMS AND CONDITIONS

### ISSUE THREAD

**Issue by AnushkaSharma04** [anuragverma108/SwapReads#160]
### Describe the feature

This feature will help the registered users to login easily without getting into the hassle of remembering credentials. The required changes will be made to the login page below.

### Add ScreenShots

<img width="698" alt="IMAG" src="https://github.com/anuragverma108/SwapReads/assets/145102276/b4f592c6-7d70-47c9-bb0f-eb88628baa99">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AnushkaSharma04** [comment]
@anuragverma108 Kindly assign this issue to me

**Comment by anuragverma108** [comment]
Assigned @AnushkaSharma04

**Comment by AnushkaSharma04** [comment]
@anuragverma108 Can u provide me with the terms and conditions to keep in that checkbox feature for the website or shall I do it on my own

**Comment by anuragverma108** [comment]
Do it your own!
Feel free to use your creativity!
Go ahead

**Comment by AnushkaSharma04** [comment]
@anuragverma108 What's the expected deadline to commit the changes

**Comment by anuragverma108** [comment]
1 week

**Comment by AnushkaSharma04** [comment]
<img width="352" alt="login" src="https://github.com/anuragverma108/SwapReads/assets/145102276/d36676d6-49c5-44b6-b748-15bf50bf4a5f">

@anuragverma108 I have added the remember me check box that will ensure easy access to users by storing info in local storage . Kindly check the screenshot

**Comment by anuragverma108** [comment]
Give some gap between check box and remember me. Also there should be in same alignment.

**Comment by AnushkaSharma04** [comment]
<img width="414" alt="login" src="https://github.com/anuragverma108/SwapReads/assets/145102276/12a55a5e-c10b-4470-94a3-2c943130c496">
@anuragverma108  Is it better now ?

**Comment by anuragverma108** [comment]
Yess.
Raise PR
