### ISSUE TITLE
BUG: Back to top button alters navbar styling

### ISSUE THREAD

**Issue by arpy8** [anuragverma108/SwapReads#1605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the back to top button is pressed, it changed the navbar from white to black. I wish to fix this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned 👍

**Comment by arpy8** [comment]
i guess this issue has been resolved
