### ISSUE TITLE
BUG: Extra email input area in home page footer

### ISSUE THREAD

**Issue by arpy8** [anuragverma108/SwapReads#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's an extra input area for entering email address in home page's footer.

Attaching screenshot for reference:
![image](https://github.com/anuragverma108/SwapReads/assets/74809468/f5590fbc-86b2-45e6-9133-0aa3b28caef7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by root-0101** [comment]
Hey @anuragverma108  Please assign me this issue

**Comment by root-0101** [comment]
I have done the change and review my code
