### ISSUE TITLE
Modify Buy Now button

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1609]
It would be great if we replace the "Buy Now" button hover effect with the same as for "send now" and "connect with reader" as the existing hover effect is not visually appealing

![Screenshot 2024-06-09 023127](https://github.com/anuragverma108/SwapReads/assets/142779809/a26ac4dc-8bd5-40b6-ab55-369c805acb5b)

**Comment by shagungarg645** [comment]
I would like to work on this project. please assign it to me.

**Comment by swetak1103** [comment]
I would like to work on this project. Please assign it to me.
