### ISSUE TITLE
Quick links hover effect

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1610]
As of now the hover effect is not good. It fades out on hovering and hard to read. so, modifying the hover effect will enhance the user experience

![Screenshot 2024-06-09 034703](https://github.com/anuragverma108/SwapReads/assets/142779809/c6fb3810-ae9a-40e7-8f79-0588da28aba9)

**Comment by swetak1103** [comment]
I would like to work on this project. Please assign it to me.

**Comment by TBorundia** [comment]
@root-0101 How you have opened multiple PR at the same time? Can you please tell me?

**Comment by root-0101** [comment]
I raise the PR again and follow all the important instructions please review my PR
