### ISSUE TITLE
Testimonials card

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1611]
As the background of the testimonials card for dark is also white. so, modifying the card according to the dark theme will be great and the next and previous buttons color are also not as per the theme they must be of red color

![Screenshot 2024-06-09 023425](https://github.com/anuragverma108/SwapReads/assets/142779809/7c1ac3e9-3ae3-4bf9-b09a-499f7bfbf8eb)

**Comment by swetak1103** [comment]
I would like to work on this project. please assign to me.
