### ISSUE TITLE
BUG:  To resize the Button

### ISSUE THREAD

**Issue by jfhgshg** [anuragverma108/SwapReads#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The button in the Free-E-Book section has shifted to right. And I want to reduce the size of the button Add to Read Later 

@anuragverma108 Please assign this issue to me

<img width="887" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/130148234/80b92757-835f-4ce1-b456-d33fa1405a77">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@jfhgshg Assigned!

**Comment by jfhgshg** [comment]
@anuragverma108 I am unable to start the project as the nodemon is not working for me. What should I do to fix it ?

**Comment by anuragverma108** [comment]
@jfhgshg to run nodemon.
Just clone the repo & do changes in your local host.
