### ISSUE TITLE
BUG: subscribe to our newsletter has two Email address inputs.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The subscribe to our newsletter has two input fields asking for the same input i.e. email address. This needs to be fixed.
![image](https://github.com/anuragverma108/SwapReads/assets/107904311/db0f5d6b-3b6a-4537-83fd-216aeef4036f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gaurav-Kushwaha-1225** [comment]
I want to work on this issue. 
Can you please assign it to me?
