### ISSUE TITLE
Feat: Adding error 404 page

### ISSUE THREAD

**Issue by taneeshaa15** [anuragverma108/SwapReads#1630]
### Describe the feature

I will add error 404 page to inform the user about wrong url or removed pages.

### Add ScreenShots

![md](https://github.com/anuragverma108/SwapReads/assets/157527085/97653461-cbe9-429d-8809-8355c5a5fd0a)
It will look like this (NOT EXACTLY)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@anuragverma108 Please assign me this issue under gssoc'24 level 2.

**Comment by taneeshaa15** [comment]
@RishabhDhawad @anuragverma108 Please assign me this issue under gssoc'24 level 2

**Comment by taneeshaa15** [comment]
@RitiChandak @anuragverma108  Ig this is a level 2 issue, please change the labels if required.

**Comment by huamanraj** [comment]
> @huamanraj @RitiChandak @anuragverma108  Ig this is a level 2 issue, please change the labels if required.

Dont worry this is just the default level if we felt like L2 or L3 during code review we will change it!

**Comment by taneeshaa15** [comment]
okay
