### ISSUE TITLE
BUG:Position of mode change button is not proper.

### ISSUE THREAD

**Issue by Coding-Charvi** [anuragverma108/SwapReads#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/73227727/14e88522-4081-4af8-8463-8e8f2834bfa2)

Here as we seen button needs to give proper margin and fix this position.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
i fix this issue already

**Comment by Gamerking177** [comment]
see this pr bro #1658

**Comment by huamanraj** [comment]
Assigned 👍
