### ISSUE TITLE
BUG:In footer some copyright content written two times.

### ISSUE THREAD

**Issue by Coding-Charvi** [anuragverma108/SwapReads#1632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/73227727/05a8f46f-7b26-4e09-beb4-ab197ee93500)

Here as we seen this text is written two times.
I will fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned 👍
