### ISSUE TITLE
Feat: Enhancing the book recommendation page

### ISSUE THREAD

**Issue by Archiesachin** [anuragverma108/SwapReads#1634]
### Describe the feature

The book recommendation feature right now  only suggest book with the chosen  genre. 

We can enhance this by adding an author selection column as well which will not be compulsary but will enhance the recommendation by tailoring the books with matched genre and author. 

### Add ScreenShots

![Screenshot (1076)](https://github.com/anuragverma108/SwapReads/assets/103347688/53240e2d-5330-4b51-a655-cdccfa64f540)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned 👍
