### ISSUE TITLE
BUG: Multiple issues on about us page, read later page.

### ISSUE THREAD

**Issue by Aarzookhunger** [anuragverma108/SwapReads#1635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/116306749/627943bb-1530-4d1a-bc14-abdea429ab85)

Social media links are not working.
Email validation hasn't been provided in subscription of newsletter on both about us and read later page.
In free e-books section the github logo has been put twice.
![image](https://github.com/anuragverma108/SwapReads/assets/116306749/64fb1888-75a5-4e03-a76c-f868f249c365)

@anuragverma108 sir do you want me to work on these  issues together and level it accordingly or shall I raise separate issue for each?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swetak1103** [comment]
I would like to work on this project. Please assign it to me.

**Comment by huamanraj** [comment]
Assigned! @Aarzookhunger 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
