### ISSUE TITLE
BUG: Missing js code for the cursor in both the index.html files

### ISSUE THREAD

**Issue by Praneeth-2602** [anuragverma108/SwapReads#1637]
## Issue Description

The custom cursor, which should be present on the homepage, is currently missing. This affects the user experience as the intended cursor design is not being displayed. The homepage HTML files need to be reviewed and updated to include the custom cursor.

### Expected Behavior
The custom cursor should be displayed when navigating the homepage.

### Actual Behavior
The default cursor is displayed on the homepage, And the custom cursor is stuck .

## Possible Solution

1. Verify that the custom cursor files are correctly linked in the homepage HTML files.
2. Ensure that the CSS defining the custom cursor is properly applied to the relevant elements on the homepage.
3. Check for any overriding CSS rules that might be preventing the custom cursor from appearing.

## Additional Information
![image](https://github.com/anuragverma108/SwapReads/assets/137754636/275bc232-f782-4c3a-a9b1-292d694bbd1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

---

**Comment by huamanraj** [comment]
we have removed the cursor!
