### ISSUE TITLE
BUG: Double copyrights

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#1644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are 2 copyrights in the footer section.
![2 copyrights](https://github.com/anuragverma108/SwapReads/assets/146114938/92140779-43d8-43fa-8010-d31a5ac8de91)

Assign this issue to me under GSSoC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
the issue is already opened
