### ISSUE TITLE
BUG: Preloader timeout

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#1645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Preloader taking too long to load pages, which reduces effectiveness of the website and makes it look unattractive.

Assign me to fix this issue under GSSoC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
