### ISSUE TITLE
BUG: Cookie update

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two issue I'd like to work on:
1. There are 2 cookie content, one should be removed.
2. The cookie content is fixed and cannot be removed from the page, it should be removed with a click.

![cookie](https://github.com/anuragverma108/SwapReads/assets/146114938/755bf80c-62fb-4ce1-b90e-0675bec6ebb7)

Assign these 2 issue to me under GSSoC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
ship this changes asap! 
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!

**Comment by dishathakurata** [comment]
@huamanraj I'm working on two issues here, so can you label it with level2?
