### ISSUE TITLE
BUG: Double subscribe button

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are 2 subscribe buttons.

![subscribe](https://github.com/anuragverma108/SwapReads/assets/146114938/972073ae-a143-4e85-945f-e218d0081e46)

Assign this issue to me under GSSoC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> There are 2 subscribe buttons.
> 
> ![subscribe](https://github.com/anuragverma108/SwapReads/assets/146114938/972073ae-a143-4e85-945f-e218d0081e46)
> 
> Assign this issue to me under GSSoC.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

preopend issue!
