### ISSUE TITLE
Feat:Add Progress Ring around Scroll to Top button.

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#1648]
### Describe the feature

I want to add Progress ring around scroll to top button.
progress ring show how much is your page scrolled.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/dcf5db4d-af64-43dd-a3f1-80945fef1e68)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@RishabhDhawad Please assign this also

**Comment by huamanraj** [comment]
not planned
