### ISSUE TITLE
BUG: Pagination button not visible in dark mode

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The pagination buttons numbers/index are not visible when switch to the dark mode

![Screenshot 2024-06-09 225359](https://github.com/anuragverma108/SwapReads/assets/142779809/324d1ddb-6cca-45d8-93b3-93fae8c194f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
