### ISSUE TITLE
modigy team card

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1651]
the cards under team category are not of equal size and also the alignment of images of the card is not at the center

![Screenshot 2024-06-09 225410](https://github.com/anuragverma108/SwapReads/assets/142779809/f888c221-6ece-4c6d-9ad0-aac178d8e2de)

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
