### ISSUE TITLE
BUG: Unnecessary CSS code appearing in the footer section of the About Us page

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Observe the unwanted CSS code displayed in the footer of about us page.
![image](https://github.com/anuragverma108/SwapReads/assets/168854094/d8e49019-201b-4cee-95d7-0f747145fb6c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
