### ISSUE TITLE
BUG: Duplicate Cookie Consent Message Displayed on Webpage

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cookie consent message is being displayed twice on the webpage, causing redundancy and a poor user experience.
![image](https://github.com/anuragverma108/SwapReads/assets/168854094/c76493df-3136-4109-b1be-f2b2230731a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
preopend issue
