### ISSUE TITLE
Sign up page issue

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Describe the bug
Sign up page is not properly center aligned.
Sign up button is poorly developed.
It is not interactive, looks like poorly developed.

To Reproduce

Go to 'Login/Signup'
See error
Expected behavior
It must be on the centralized properly.

Screenshots
![329316470-c6751979-f33b-4d76-bdff-f889b0caf1d1](https://github.com/anuragverma108/SwapReads/assets/73558583/dfc7a0dc-2bf2-446d-8c9d-5e1889f24420)

Desktop (please complete the following information):

OS: Windows 11
Browser Microsoft Edge
Version 124.0.2478.80
Smartphone (please complete the following information):

Additional context
I'm a GSSoC'24 contributor please assign me this work. Since before this I made a pull request which was properly merged so I know everything about this project. I will develop an interactive signup page with proper validation.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@pankaj-bind Don't change UI of the login page. It is fine. Just focus on its center alignment & responsiveness.

**Comment by pankaj-bind** [comment]
Ok
