### ISSUE TITLE
Feat: Changing the logo of the website.

### ISSUE THREAD

**Issue by shilpalatiyare** [anuragverma108/SwapReads#1660]
### Describe the feature

The logo of the website can be made more bold and colorful which suits the overall design of the website.

### Add ScreenShots

<img width="411" alt="Screenshot 2024-06-10 at 12 27 18 AM" src="https://github.com/anuragverma108/SwapReads/assets/100855418/b4dc617c-bb71-482b-8713-65b1d54b0e15">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shilpalatiyare** [comment]
@anuragverma108 @huamanraj please assign this issue to me, I will do my best.

**Comment by huamanraj** [comment]
> @anuragverma108 @huamanraj please assign this issue to me, I will do my best.

great 👍 but first get your design approved!

**Comment by shilpalatiyare** [comment]
@huamanraj These are some of the designs , I prefer the last one. 

<img width="528" alt="Screenshot 2024-06-10 at 2 42 01 PM" src="https://github.com/anuragverma108/SwapReads/assets/100855418/149682ec-35be-4875-bb4a-b99506ce1aa5">
<img width="528" alt="Screenshot 2024-06-10 at 2 42 48 PM" src="https://github.com/anuragverma108/SwapReads/assets/100855418/4591f294-cc5d-49f1-9738-fe261d3a0a7b">
<img width="528" alt="Screenshot 2024-06-10 at 3 05 48 PM" src="https://github.com/anuragverma108/SwapReads/assets/100855418/6e01aa0c-e2bb-4ec0-b57d-8fdb62eb5e47">
