### ISSUE TITLE
BUG: Duplicate GitHub Icon in Footer

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#1661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the footer section of the website, the GitHub icon is appearing twice. This is likely due to a duplicate entry in the HTML code. The issue needs to be resolved by removing one of the duplicate icons.
![image](https://github.com/anuragverma108/SwapReads/assets/168854094/cc54e122-d3bf-4673-b775-374ec2747b60)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it.
I am the project mentor so you can always reach out to me for any help!
Happy open-source contributing!
