### ISSUE TITLE
Feat: Making a new css file for index.html

### ISSUE THREAD

**Issue by Saipradyumnagoud** [anuragverma108/SwapReads#1669]
### Describe the feature

In the index.html there are lot of internal css so i want to create a new css file to make the index.html to view properly due to internal css the code is very clumsy so i want to create a new  css file for the index.html 
   

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143107589/fd2ab7fe-404c-457d-8077-f29ddfd81465)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
