### ISSUE TITLE
BUG: Read more option visibility issue

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The **read more** option in the benefits container is not completely visible in dark mode due to the the hover effect this hampers the readability of the site .

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/6b2b541c-ffa6-4cb4-9fbc-8fa5e8a6bd5f)

I would like to work on this issue please assign it to me under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108  @huamanraj  please assign this issue to be under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned!
