### ISSUE TITLE
BUG: NavBar Styling

### ISSUE THREAD

**Issue by matinshaikh31** [anuragverma108/SwapReads#1673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

###The Black Spot in Nav bar
###The The margin above the Nav Bar Make Nav Bar not sticky to header

[
![Screenshot 2024-06-10 105155](https://github.com/anuragverma108/SwapReads/assets/118182648/094b44bc-0b25-4ea5-b999-92d4fee70816)
](url) 

###In Drak Mode the Button of Dark mode Change Postion it should be in center

![Screenshot 2024-06-10 105301](https://github.com/anuragverma108/SwapReads/assets/118182648/0552cee4-2af9-4523-a9fe-adb15bd1a056)

###in Mobile view the size of nav bar is too big and also dark mode btn change postion
![Screenshot 2024-06-10 110738](https://github.com/anuragverma108/SwapReads/assets/118182648/f9828ed6-afa3-43c5-a907-863b22e5dc4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by matinshaikh31** [comment]
@anuragverma108  please assign this issue to be under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
