### ISSUE TITLE
BUG: Overlapping of contents in pricing page

### ISSUE THREAD

**Issue by Pranav0606** [anuragverma108/SwapReads#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/97611449/b1acbb25-8158-4879-9d52-c48cad3481a0)
In above screenshot we can see that the contents of the page are overlapping with navbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
