### ISSUE TITLE
BUG: Email Validation required in 'Subscribe to our Newsletter' field

### ISSUE THREAD

**Issue by Tanishka023** [anuragverma108/SwapReads#1683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/120386924/20024739-b7b4-404e-a54f-2e00e0cfd912)
Form validation is required in 'Subscribe to our Newsletter' field.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
