### ISSUE TITLE
Feat:Update the bg color of progress bar in dark mode

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#1690]
### Describe the feature

The background colour in dark mode of progress bar is white, I want to match it with dark mode's colours.
@huamanraj @RitiChandak @anuragverma108 please assign this to me under GSSoC'24.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/146222028/68fc8925-e1a9-4d81-b983-953c4998e82c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
