### ISSUE TITLE
BUG:Two Github logo in footer.

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/c40fa584-29f4-434d-b0bc-750a72e5b3be)

There are two logo of github present.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@huamanraj @anuragverma108 @RishabhDhawad please assign me i will make PR.
don't accept PR of @dsaikiran01 it is my issue.

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by zalabhavy** [comment]
@RitiChandak Sure !
