### ISSUE TITLE
BUG: Color Mismatch of Subscribe Button with Theme Color

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The color of the Subscribe button on the website does not match the theme color, causing inconsistency and affecting the overall aesthetics. The button color needs to be adjusted to align with the theme color scheme of the website.

![subscribe](https://github.com/anuragverma108/SwapReads/assets/129402285/7bb65cdf-95f9-4f70-8f81-41f03c4d4a6e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo
before working on it. While creating your PR, ensure you pull all existing changes
beforehand to avoid conflicts.
Happy open-source contributing!
