### ISSUE TITLE
Feat: feature improvement

### ISSUE THREAD

**Issue by JanitKumar** [anuragverma108/SwapReads#1695]
### Describe the feature

quick links can come in centre of the page it will look better and the social media handles can have hover effect and can be aligned horizontally which is followed by other websites also
It is on every page of website.

### Add ScreenShots

![Screenshot 2024-06-10 181712](https://github.com/anuragverma108/SwapReads/assets/126192349/63e01064-f605-47d8-b7da-86737153390c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by JanitKumar** [comment]
![Screenshot 2024-06-12 231209](https://github.com/anuragverma108/SwapReads/assets/126192349/77e8c63a-e101-4ecc-93dc-b39c1428ca99)
It was already done so there was no need for it now
![Screenshot 2024-06-10 181712](https://github.com/anuragverma108/SwapReads/assets/126192349/c8b8106b-5cf0-4467-b1ae-32c90ae233ee)
