### ISSUE TITLE
video animation of books is not working

### ISSUE THREAD

**Issue by VarshaPednekar** [anuragverma108/SwapReads#17]
hello 
I'm Contributor under gssoc'24 . The home section will look amazing with the video animation 
kindly assign this task to me under gssoc'24

**Comment by anuragverma108** [comment]
Assigned @VarshaPednekar

**Comment by anuragverma108** [comment]
Any Updates @VarshaPednekar

**Comment by nishantharkut** [comment]
Dear Sir @anuragverma108 , I have updated the video section that you assigned to me but still the gssoc'24 label is not been given to me

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.
