### ISSUE TITLE
Feature to read books using api

### ISSUE THREAD

**Issue by paulkrishanu4** [anuragverma108/SwapReads#1702]
### Describe the feature

want to create a page where users can search books and read them. Data of books can be fetched using api of open library. like this

### Add ScreenShots

![Screenshot_10-6-2024_2268_www gutenberg org](https://github.com/anuragverma108/SwapReads/assets/169196836/0b2a1e30-6cc6-4b32-b5ed-9000d88e863a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
