### ISSUE TITLE
BUG: email is taking in valid input

### ISSUE THREAD

**Issue by dnyandeepchute** [anuragverma108/SwapReads#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-10 230222](https://github.com/anuragverma108/SwapReads/assets/158272735/7a5f3a3e-64ff-45e4-8a92-9601f308b991)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by dnyandeepchute** [comment]
@RitiChandak please assign this to me.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
