### ISSUE TITLE
BUG: The length of the subject and the message does not get updated as we write

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/4b1e5095-a430-4e2e-81f9-6904f560f40d)
As we enter some subject and some message in the write me anything section, the length being shown says 0/100 and 0/250 respectively. I want to work on this issue.

Also the user is able to write any length of subject and message. I will also ensure that only upto 100 and 250 characters are entered in the fields. For any greater than the limits are entered, a message will be shown "Message limit exceeded" and the further characters will be ignored. You may assign level 2 or 3 if you deem it fit.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
