### ISSUE TITLE
BUG:Dublicate icons and subscribe newslater

### ISSUE THREAD

**Issue by Gamerking177** [anuragverma108/SwapReads#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is twitter and github logo two times and subscribe button is also two times in login/signup page

![image](https://github.com/anuragverma108/SwapReads/assets/130808542/c922cc4b-2276-4264-858f-805109ffae07)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
