### ISSUE TITLE
BUG: Like Button on the books.html page does not work.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On clicking on the like button on the books.html page, the page gets navigated to # but rather it should be liked and unliked. 

https://github.com/anuragverma108/SwapReads/assets/107904311/ec14de8f-441b-4f21-b87a-95d951f25012

Kindly assign appropriate level to this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
