### ISSUE TITLE
Feat: Buttons in Pricing Section violates color scheme of website

### ISSUE THREAD

**Issue by AbhinayBhadauria99** [anuragverma108/SwapReads#171]
### Describe the feature

Buttons in Pricing Section are blue in color and blue color is not used in entire website .Secondly they are very basic and looks very odd  in website. I would like to work on them by changing colors, hovering effect ,size etc. @anuragverma108 Please assign this task to me .I am working under GSSOC'24.

### Add ScreenShots

# Buttons in pricing section
<img width="922" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/113773196/0feb0171-f202-46ab-ae3b-418283030178">

# Other Buttons
<img width="839" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/113773196/44822ac5-9273-4736-8cbe-8cce7bceaecb">
<img width="602" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/113773196/76844023-ae8a-45be-84a8-0c111814fb62">
<img width="454" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/113773196/56dd4559-8b0d-49b8-82a8-d940b0ce33b4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by RitiChandak** [comment]
@AbhinayBhadauria99 any updates?
