### ISSUE TITLE
BUG: Duplicate Content and Logo in Free eBook Section Header

### ISSUE THREAD

**Issue by DebapriyaJha** [anuragverma108/SwapReads#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Free eBook section of the website, the header section contains duplicate content and a repeated logo, resulting in a cluttered and visually unappealing display.

Screenshot:
![navbar](https://github.com/anuragverma108/SwapReads/assets/111692420/18616cd4-d984-45d5-a721-89c0bd6f0c74)

@anu Please add the GSSOC and appropriate level label to this issue and assign this to me. I would love to contribute.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by DebapriyaJha** [comment]
Thankyou @huamanraj  for assigning the issue to me. I will work according to the guidelines.
