### ISSUE TITLE
BUG: Unnecessary black circle on https://swapreads.vercel.app/assets/html/index.html#faqq

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is another black circle on the top left of the page. I have checked this is due to issue in html/book_recommend.html, html/freebooks.html, html/index.html, html/login.html. I can fix this.
![image](https://github.com/anuragverma108/SwapReads/assets/107904311/efa6a20e-9c63-440f-85ef-1f1cb5bdba2c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
