### ISSUE TITLE
BUG: Instructions for password are not visible on the login/signup page.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text is there but one can read it only on hovering. this need to be fixed.

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/86fd05e5-6545-40e0-9c73-1821a43278dd)

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/b41acb19-80e5-4b8c-b3dc-b6161ad8c58f)

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/311d3498-b346-44d6-9fd9-0e96e514c37f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
