### ISSUE TITLE
BUG: The forgot password page has significant layout issues.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/98e52761-1be7-426f-a443-e5ec3a5261b0)
The page's css needs to be corrected. It has Misaligned Elements and broken layout.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
