### ISSUE TITLE
BUG: Positioning of the Quotation marks in testimonial section 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Quotation marks don't fit inside the flip card which makes it look visually unappealing 
 this issue could be cause of position error

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/1ae86d4b-9fae-4282-8fec-f5b1bb5b774e)

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/1fcb3fa4-ed6b-43fd-b11f-f0b67c40b8e6)

i would like to work on this issue please assign this issue to me under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
