### ISSUE TITLE
BUG: About us page visibility issue in dark mode 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some elements like the **page number** in the contributor section and the **paragraphs** in mission and values are not visible well in dark mode.

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/9abba1e3-00e4-471b-8fe8-c1bc3c5bc5f8)

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/e727a5e4-e5d1-4197-a9b1-4e22a06b1016)

i would like to work on this issue please assign this issue to me under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108 @huamanraj please assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
