### ISSUE TITLE
BUG: Adding LinkedIn in the footer section of About Us page

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the footer section is missing the LinkedIn social icon and some of the social icon like Twitter and Instagram don't work.

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/155fa44e-3e36-484a-9cd3-9677e8d1622d)

i would like to work on this issue, please assign it to me under GSSOC'24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108 @huamanraj please assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
