### ISSUE TITLE
BUG:  Password creation on register page does not enforce character requirements, allows  any weak passwords without error

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Despite having conditions for creating passwords for new users, if I enter any random password . for example:  only alphabets, it does not show any error or warning. Instead, it leads to another login page.

https://github.com/anuragverma108/SwapReads/assets/121204667/a1005db2-35f3-4493-bf26-80d0ace6b6a7

**Steps to Reproduce:**

1. Go to the 'Register ' page.
2. Enter a password that contains only alphabets (e.g., "password").
3. Submit the form.
4. Observe that no error or warning message is displayed.
5. Notice that you are redirected to another login page instead of seeing a password requirement error.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
