### ISSUE TITLE
Feat: Add a close button for users who do not want to accept or reject cookies

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1726]
### Describe the feature

The current cookie consent banner requires users to either accept or reject cookies. However, some users may prefer to dismiss the banner without making a choice. I propose adding a close (×) button to the cookie consent banner, allowing users to temporarily dismiss it without taking action. This would enhance user experience by providing more flexibility.

[

### Add ScreenShots

![cooke](https://github.com/anuragverma108/SwapReads/assets/121204667/8a33ee94-a37c-4090-b22f-cedbc2c1e10b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
