### ISSUE TITLE
BUG:Issue in login page footer

### ISSUE THREAD

**Issue by ImmidiSivani** [anuragverma108/SwapReads#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In login/signup page at footer twitter and github symbols are repeated and clicking on twitter it is not redirecting to correct page . I would like to work on this issue.

![Screenshot (146)](https://github.com/anuragverma108/SwapReads/assets/147423543/b69a7e93-9772-4294-86db-5320b98c58ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
