### ISSUE TITLE
BUG: Login page has footer issue

### ISSUE THREAD

**Issue by MuraliDharan7** [anuragverma108/SwapReads#1728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the footer the logo for GitHub and X exist twice. This should be looked into.

![image](https://github.com/anuragverma108/SwapReads/assets/130668745/6a0b2f08-3397-458f-bac6-983d24197259)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
