### ISSUE TITLE
BUG: The header font color should be changed

### ISSUE THREAD

**Issue by MuraliDharan7** [anuragverma108/SwapReads#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/130668745/da2d4bcd-d7e3-42ed-91ee-c104f24a08ce)

This contact section has the header in white color which is not visible. The color of the text should be changed and also, I can add one border for that particular section alone.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
