### ISSUE TITLE
BUG: Hover effect color on navbar's elements are not properly aligned.

### ISSUE THREAD

**Issue by shnwz-solves** [anuragverma108/SwapReads#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When navbar's elements are hovered, it shows an unaligned hover effect on the elements. This needs to be fixed for better UX.

![Screenshot 2024-05-12 103442](https://github.com/anuragverma108/SwapReads/assets/126380641/4895278b-7bf2-44b7-9c2e-a93a10809c57)

Please assign me this task, I would like to contribute. Thankyou!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by shnwz-solves** [comment]
> Assigned!

Thankyou PA,I will try to do it asap 😊

**Comment by Nitin1-singh** [comment]
attemp / BUG: Hover effect color on navbar's elements are not properly aligned. #173

**Comment by shnwz-solves** [comment]
> attemp / BUG: Hover effect color on navbar's elements are not properly aligned. #173 

I already mentioned this issue 6 hours ago then Why you have raised a similar issue and solved it, 
This is not a good practice! 👎

**Comment by shnwz-solves** [comment]
> attemp / BUG: Hover effect color on navbar's elements are not properly aligned. #173 

It is still not fixed.
PA has assigned me this issue to solve.
Keep calm and don't raise similar issues from now onwards.

**Comment by Manaswini123456** [comment]
Please assign me with this issue. I would like to collaborate and provide my insights regarding the same.
