### ISSUE TITLE
BUG: DARK MODE IS NOT APPLY ON NAVBAR MORE SECTION ,AND REVAMP FOOTER SECTION ALIGNMENT OF QUICK LINKS

### ISSUE THREAD

**Issue by AbhinaySngh** [anuragverma108/SwapReads#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-11 224000](https://github.com/anuragverma108/SwapReads/assets/162811933/19ce8f6b-92bb-44a7-b993-532282c511da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhinaySngh** [comment]
@RitiChandak please assign me this issue.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
