### ISSUE TITLE
BUG: navbar not working

### ISSUE THREAD

**Issue by paulkrishanu4** [anuragverma108/SwapReads#1736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/169196836/23da0e7d-d22d-4c0a-9f24-5b547b09d8d2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChanchalTolani** [comment]
Please assign me this issue
