### ISSUE TITLE
Add User Profile Section to Corner of Page

### ISSUE THREAD

**Issue by ChanchalTolani** [anuragverma108/SwapReads#1737]
### Describe the feature

We need to add a user profile section to the top-right corner of our webpage. This section should display the user's profile picture, name, and a dropdown menu with user-related options. This enhancement will improve user experience by providing quick access to profile settings and related functionalities.Please assign me this issue @anu

### Add ScreenShots

!
![image-processing20200329-14345-gqvpt5-1024x768](https://github.com/anuragverma108/SwapReads/assets/130171236/e2cc5411-f054-442e-ac78-4abe78c63426)
![Screenshot (5)](https://github.com/anuragverma108/SwapReads/assets/130171236/f67df5fe-65c6-4791-8c32-119d57b8055f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@ChanchalTolani Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by ChanchalTolani** [comment]
Yes
