### ISSUE TITLE
Introduce dark mode for reading books

### ISSUE THREAD

**Issue by ChanchalTolani** [anuragverma108/SwapReads#1738]
### Describe the feature

We need to introduce a dark mode feature in our reading books application. Dark mode will provide a more comfortable reading experience in low-light environments and reduce eye strain for users. This feature should be easily toggled on and off by the user and should ensure a consistent and visually appealing design. @anuragverma108 Please assign me this issue

### Add ScreenShots

![Screenshot (6)](https://github.com/anuragverma108/SwapReads/assets/130171236/0e1d2ded-1fbd-4ff7-b08b-3ccc036b7df4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR.
