### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [anuragverma108/SwapReads#174]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by anuragverma108** [comment]
It already exists.
You just make it properly to help contributors to contribute easily.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by suhanipaliwal** [comment]
Could you please label this issue to appropriate level like level 1, 2 or 3 for GSSOC'24.
