### ISSUE TITLE
BUG: transition in footer social media icons is very slow

### ISSUE THREAD

**Issue by ayush-jsrt** [anuragverma108/SwapReads#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the transition in the footer section social media icons are very slow when hover over
need to make them snappy as possible
![Screenshot 2024-06-12 044456](https://github.com/anuragverma108/SwapReads/assets/136156977/3f6dc6a4-4dbc-46f2-af73-18325239ccd3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-jsrt** [comment]
please assign me this issue

**Comment by bhuvangoel04** [comment]
Please assign me this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
