### ISSUE TITLE
in about us section text is not appearing and there is hover effect

### ISSUE THREAD

**Issue by jayanththalla** [anuragverma108/SwapReads#1748]
### Describe the feature

In the footer section of the About US, the text of the quick link does not appearing the text hovering is not good

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/121346142/f5bceeac-7322-49b1-ab5d-1301b032cc24)

please assign me @pa
please label it under gssoc and level

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
