### ISSUE TITLE
BUG: Improvement in the contact page in Css.

### ISSUE THREAD

**Issue by agrwal697** [anuragverma108/SwapReads#1749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I think if the contact section had a fixed alignment in every text item and by adding max-width, border-radius so it would have better UI.
Please Assign me this issue with the label of GSSOC.

screenshots:
before:

![image](https://github.com/anuragverma108/SwapReads/assets/128716726/8fd878f3-e4af-460d-8744-ce6b67c98e46)

After:

![image](https://github.com/anuragverma108/SwapReads/assets/128716726/472c63de-ca91-48f1-ab3c-32012cc66696)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
