### ISSUE TITLE
DOC: Creating a appealing Alert

### ISSUE THREAD

**Issue by Nehayp21242929** [anuragverma108/SwapReads#175]
### What's wrong with the existing documentation

I would like to make this Alert more interesting and appealing,
please assign this task to me under GSSoC'24.

### Add ScreenShots

![Screenshot 2024-05-12 114025](https://github.com/anuragverma108/SwapReads/assets/167680713/607d3883-81ee-40a1-a567-554ef44d16c4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Vedant285** [comment]
The content and share link are bot placed perfectly 
@anuragverma108 assign me this issue to solve it.
![Screenshot_2024-05-12-12-26-57-748_com android chrome](https://github.com/anuragverma108/SwapReads/assets/91669901/05d55b3b-d7f9-4dc6-afc0-70ba12ab1ba3)
