### ISSUE TITLE
Feat: Adding a Book Blog/Feedback Page

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#1753]
### Describe the feature

I want to add a new feature for a complete review of book which can be very useful for reader to decide the next book to be read or swapped.

### Add ScreenShots

Some thing like this...

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/78aa81f2-b16e-4bb8-b41c-af7b9076cdef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@huamanraj @RitiChandak Can you please assign this to me?

**Comment by anuragverma108** [comment]
@Maheshwari-Love Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
