### ISSUE TITLE
CARDS CSS

### ISSUE THREAD

**Issue by GauriGA** [anuragverma108/SwapReads#1754]
### Describe the feature

I would like to change the css of the cards on the homepage

### Add ScreenShots

![WhatsApp Image 2024-06-12 at 12 01 04_55c6c83a](https://github.com/anuragverma108/SwapReads/assets/118062523/0be93c62-056e-4067-b588-d79f3795a1ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@anuragverma108 Can you assign me this issue under the gssoc'24 label?

**Comment by GauriGA** [comment]
@anuragverma108 pls respond

**Comment by anuragverma108** [comment]
Assigned!

**Comment by GauriGA** [comment]
@anuragverma108 I have made the changes and created a pull request.
