### ISSUE TITLE
BUG: Some sections not responsive between 920px to 1200px 

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#1757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Pricing section is not responsive in between 920px to 1200px .
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/05f22e0e-84c9-4cb5-b6bb-624a878b9d99)

2. Some sections like Book Exchange hub , FAQ and footer are not occupying full width in 920px to 1200px.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/c1e8e4a1-6417-4470-85bb-d0b4d8b2fa95)

![image](https://github.com/anuragverma108/SwapReads/assets/146222028/cc4bc8b5-6724-4c8c-b31e-ce5db76b7ce0)

I want to fix these. @anuragverma108  @RishabhDhawad @RitiChandak @huamanraj  Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
