### ISSUE TITLE
BUG: Issues in Booklist Swapping page

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#1758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. There is some unwanted text on the Booklist swapping page.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/31274ddd-6b6b-4ef8-b1d3-ab6241409e38)

2. There are 2 email-address boxes.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/dd4d618a-1190-4d56-b472-2470196770c1)

I want to fix these issues. @anuragverma108  @RishabhDhawad @RitiChandak @huamanraj  Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
