### ISSUE TITLE
BUG: Fix Pricing Section

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/129655645/7d6a568c-7751-49ed-bc0a-5194312878f2)
Fix this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vedant285** [comment]
We can open this box in new tab so people can explore your website too meanwhile they do payment. 
If you assign me me this then I will try my 100% to make it more good

**Comment by huamanraj** [comment]
> Yes there is an issue 
> Is someone uses gpay or UPI then ? 
> If someone don't have card then how can they do payment so there should be an option of UPI 
> Please assign me this issue so that I can work on it @anuragverma108 

Work on it!
