### ISSUE TITLE
BUG: Navbar overriden in Free-ebooks section

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-12 145753](https://github.com/anuragverma108/SwapReads/assets/85826117/1f0f167d-65a1-4c4a-baf8-c2127336ab8e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
