### ISSUE TITLE
BUG: Re-styling of signup/login in dark mode just like  light mode

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#1764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-12 145946](https://github.com/anuragverma108/SwapReads/assets/85826117/e1ee1263-7985-4bc7-b407-4f6698b86309)
![Screenshot 2024-06-12 150104](https://github.com/anuragverma108/SwapReads/assets/85826117/b91cd7c8-cbeb-469e-88d7-afef491498e8)

![Screenshot 2024-06-12 150129](https://github.com/anuragverma108/SwapReads/assets/85826117/f647079f-fb7a-47fa-9c2a-2929fa06f99a)

![Screenshot 2024-06-12 150142](https://github.com/anuragverma108/SwapReads/assets/85826117/1ced7f19-ac84-46af-874f-b55c2ac96934)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
