### ISSUE TITLE
Update Copyright Year Dynamically in Footer

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108, the current footer in index.html contains a hardcoded copyright year. To ensure that the copyright year is always up-to-date, it would be beneficial to update it dynamically. This can be achieved by implementing a mechanism that automatically updates the year to the current year. **Please assign the GSSOC label and I would like to work on it.** Thank you!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Work on it!!
