### ISSUE TITLE
Feat: Separate file of Javascript  from  index.html

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1770]
### Describe the feature

Make index.js file  for better  maintainability of the codebase. Separating the JavaScript code from the HTML file can improve readability and make it easier to manage and update the code in the future. 

### Add ScreenShots

![js](https://github.com/anuragverma108/SwapReads/assets/121204667/4d3d29d8-037a-4d77-9c3b-0e4c8c697529)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amna-Hassan04** [comment]
Can I work on this issue?

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
