### ISSUE TITLE
BUG:The contents in more section navbar are misplaced 

### ISSUE THREAD

**Issue by DiwareNamrata23** [anuragverma108/SwapReads#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1280" alt="Screenshot 2024-06-12 at 3 54 40 PM" src="https://github.com/anuragverma108/SwapReads/assets/142529986/22f3341c-2130-42fd-a4f3-b970bea80654">
<img width="881" alt="Screenshot 2024-06-12 at 3 54 49 PM" src="https://github.com/anuragverma108/SwapReads/assets/142529986/9a5af67d-9e8b-46cd-abc3-331c6003c90b">
<img width="1317" alt="Screenshot 2024-06-12 at 3 55 02 PM" src="https://github.com/anuragverma108/SwapReads/assets/142529986/3bacd29f-a2b3-4b58-8aa5-bf7eeccb4f2d">
<img width="1412" alt="Screenshot 2024-06-12 at 3 55 23 PM" src="https://github.com/anuragverma108/SwapReads/assets/142529986/31a19b86-2110-489e-90dd-c72efd09265b">
These contents from the more section on the navbar are misplaced . I will make sure to make this contents to align properly in navbar . Please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
