### ISSUE TITLE
BUG: : when logging into the website, dark and light mode options are dysfunctional and not working as a single button 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dark and light mode options in the navbar do not work properly when logging into the website. They are not functioning as a single button, and they are getting out of the navbar.

https://github.com/anuragverma108/SwapReads/assets/121204667/e93dd7bf-0ea6-4878-9910-c1c70d23fa26

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
