### ISSUE TITLE
Feat: Add Logout Button to Webpage 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1780]
### Describe the feature

Upon logout from the webpage, there is no button or relevant option for logging out; instead, a prompt for logging out appears when clicking on the login/sign-up button after already being logged in.

### Add ScreenShots

![log out](https://github.com/anuragverma108/SwapReads/assets/121204667/a49b5b66-0af6-4afd-afee-56d81d4d3080)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
