### ISSUE TITLE
BUG: Irrelevent spack above of footer 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've noticed an issue where an unexpected space is appearing above the footer. This space seems to be unrelated to the layout or content of the page and appears as an anomaly.

![footer](https://github.com/anuragverma108/SwapReads/assets/121204667/4f8eaeb0-d9d4-4d85-a7e8-f207bf874fde)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @gudia18
