### ISSUE TITLE
BUG:  Chatbot Content Not Fully Visible Due to Limited Width  

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content of the chatbot on the website is not fully visible due to its limited width. To address this issue and improve user experience, I suggest adding a marquee effect to the chatbot content, similar to news headlines. This will ensure that all content is visible to users, even within the constrained width of the chatbot.

![chatbot](https://github.com/anuragverma108/SwapReads/assets/121204667/18415f7f-0401-4371-a662-d939fc958396)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@gudia18 @anuragverma108

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
