### ISSUE TITLE
Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [anuragverma108/SwapReads#1790]
### Describe the feature

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

Preview of proposed Website Visitor:
![Screenshot 2024-06-12 143634](https://github.com/anuragverma108/SwapReads/assets/113301503/2c1cf84c-fc1b-4fff-9e88-d7cd8e13493b)

**Please assign this issue to me under the gssoc label**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
