### ISSUE TITLE
BUG: Footer alignment issue in contact us form

### ISSUE THREAD

**Issue by PrachiJadhav2310** [anuragverma108/SwapReads#1792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the contact us form , the footer of the page is not aligned properly. All rights reserved page should be at bottom . It should be aligned properly.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
