### ISSUE TITLE
Feat: Improving the Flipcard

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#1793]
### Describe the feature

Currently the flip cards are flipping weirdly. When they flip, their background become colorless.
I checked the problem in different browsers for PC. The problem is occurring only in Mozilla Firefox.
I will correct the to have a solid background for better enhancement.
I had raised the issue earlier, but was closed saying that the issue is already solved. But the issue persists.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/145102345/a6dbb862-b9fe-43b6-bb28-de78133bf2f3)
(Mozilla Firefox)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
