### ISSUE TITLE
Feat: chat and back to top button should be aligned

### ISSUE THREAD

**Issue by JanitKumar** [anuragverma108/SwapReads#1796]
### Describe the feature

I will align them in a straight line

### Add ScreenShots

![Screenshot 2024-06-12 231947](https://github.com/anuragverma108/SwapReads/assets/126192349/a1323993-ee6a-4d0d-9bd4-8d7fa7da1f1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
