### ISSUE TITLE
Request for Backend Development Contributions

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#18]
Dear Contributors,

We're excited about the progress we've made on our website so far, but to take it to the next level, we need to focus on building out the backend functionalities. Currently, our backend is incomplete, and we're seeking skilled developers to contribute their expertise to enhance our website's functionality.

**Comment by anuragverma108** [comment]
Assigned @fazil-syed

**Comment by fazil-syed** [comment]
What should I get started on?

**Comment by anuragverma108** [comment]
The idea is that when the user fills out the form to sell his book, his data should be stored in the backend. As soon as he finds a buyer, it should automatically send him an email.

**Comment by fazil-syed** [comment]
Can I know the instructions to set up the project on my local system?

**Comment by fazil-syed** [comment]
I see that the frontend part of the book exchange is still incomplete but what I assume that the form will be used to send the data to the backend the userId/email, the book name, email and listing price. Based on this I will work on implementing this by storing the above data inside the database and after a buyer is interested in purchasing the book. an email will send to the seller.

**Comment by fazil-syed** [comment]
I see that this project has files that use express backend and also has firebase. Can I know which I am supposed to implement the above feature in?

**Comment by anuragverma108** [comment]
You can use any backend tech stack in which you are comfortable to implement the idea

**Comment by fazil-syed** [comment]
> Can I know the instructions to set up the project on my local system?

I have been unable to get the project working on my local system so can you add instructions here or in the learn.md file so that other contributors also can use it
