### ISSUE TITLE
BUG:footer ui  enhancement

### ISSUE THREAD

**Issue by parikhitritgithub** [anuragverma108/SwapReads#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Quick links not properly visible 
![image](https://github.com/anuragverma108/SwapReads/assets/124444610/7330db92-3add-4301-89ba-8c803543b55d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Salma-Mamdoh** [comment]
@parikhitritgithub Please assign this issue to me and add suitable labels

**Comment by anuragverma108** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/129655645/aa10c76f-367a-4a28-9ccf-3e42546f0834)
It is visible!
