### ISSUE TITLE
Feat: add three more genre cards

### ISSUE THREAD

**Issue by shruti110503** [anuragverma108/SwapReads#1808]
### Describe the feature

The 12 genre cards present in the website do not cover genres like young adult fiction, children's fiction and dystopian. These are some interesting genres that attract lots of readers and I think they should be added.

### Add ScreenShots

I want to add these genre cards.
Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
