### ISSUE TITLE
BUG: repeating content in free ebooks section

### ISSUE THREAD

**Issue by shruti110503** [anuragverma108/SwapReads#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-13 130608](https://github.com/anuragverma108/SwapReads/assets/118251562/549249c6-6cb4-43fe-8594-4b1f2ca99716)
There are repeating books in the free ebooks section. 
I can fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
