### ISSUE TITLE
The login form requires improvement!!

### ISSUE THREAD

**Issue by Anjaliavv51** [anuragverma108/SwapReads#181]
![image](https://github.com/anuragverma108/SwapReads/assets/154777864/fc3c00f9-efe0-4fb2-9bab-23da0d5f56bc)
Above login form looks dull without proper alignment & also there no info about forget password

I would like to add forget password , with backend.I hope u assign this issue to me under GSSOC'24 
Thank You

**Comment by G0HAN3** [comment]
Hello @anuragverma108 , could you please assign this issue to me? I believe my skills are well-suited to address it. Thank you!

**Comment by Nehakumari1208** [comment]
Please assign this to me

**Comment by AshishKumarSamantaray** [comment]
I want to contribute. Please assign this to me

**Comment by Anjaliavv51** [comment]
Thank You , I will start the work

**Comment by Anjaliavv51** [comment]
please add Labels for PR #361 
And merge the code files.
