### ISSUE TITLE
BUG: Duplicate Content in Free ebook copyright section in smaller screen

### ISSUE THREAD

**Issue by DebapriyaJha** [anuragverma108/SwapReads#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Free eBook section of the website, the copyright section contains duplicate content in smaller screen layouts, resulting in a visually unappealing display.

Screenshot:
![copyright](https://github.com/anuragverma108/SwapReads/assets/111692420/a738f4a8-5bcf-4271-8405-7d107f175277)

@anu Please add the GSSOC and appropriate level label to this issue and assign this to me. I would love to contribute.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by DebapriyaJha** [comment]
@RishabhDhawad Why the PR is not merged? Is there any mistake

**Comment by RishabhDhawad** [comment]
This issue is already been solved earlier by someone else. There I marked this as duplicate and closed it.

**Comment by DebapriyaJha** [comment]
Yes, I have seen it. But as this issue was assigned to me so to make my PR valuable I have added the copyright policy and privacy notice part beneath the footer similar to the rest of the website and also made little changes in the newsletter part by adding a responsive email box. @RishabhDhawad Please if you can have a look at these and consider my PR.
