### ISSUE TITLE
[FEATURE] : Contact Us Section Enhancement

### ISSUE THREAD

**Issue by bharat-c27** [anuragverma108/SwapReads#1823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Contact Us Section Enhancement:**

**Hover Effects (Name, Subject, Message Input Boxes)** - This issue describes the desire to add hover effects to the name, subject, and message input boxes for improved visual appeal.

**Missing Rounded Corner (Email Input Box)** - This issue reports the inconsistency where the email input box lacks rounded corners compared to the other inputs.

**Refine Message Input Hover Effect** - This issue details the undesired spread of the box-shadow on hover for the message input box and proposes its removal.

**Update Contact Us Section Heading** - This issue suggests replacing the current headings "Write me anything" to "Have a Question?" with a clearer and more descriptive option like "Contact Us".

@anuragverma108 , @huamanraj please consider the number of issues I am solving and assign the labels according. Thank you for understanding.

![Screenshot 2024-06-13 185644](https://github.com/anuragverma108/SwapReads/assets/125469847/fcf69ef3-ea9a-4f7f-bd05-c0f853982bcd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bharat-c27** [comment]
![Screenshot 2024-06-13 195508](https://github.com/anuragverma108/SwapReads/assets/125469847/3d845226-6bab-4551-98dd-fe8a0d900272)

**This is CONTACT US SECTION**

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by bharat-c27** [comment]
Thank you @huamanraj, I will do as you mentioned.

Please consider the **number of improvements** I am solving in a **single ISSUE** so can you please assign the **level-2 label** according. Thank you for understanding.

**Comment by huamanraj** [comment]
> Thank you @huamanraj, I will do as you mentioned.
> 
> Please consider the **number of improvements** I am solving in a **single ISSUE** so can you please assign the **level-2 label** according. Thank you for understanding.

will be updated after code review if felt deserving!

**Comment by bharat-c27** [comment]
Hello @huamanraj and @anuragverma108,

Sorry to say that 
1) There are multiple files of css and html for each section (eg : styles.css and style.css) . 
2) And in a single CSS file the same code is repeated more than 1 time. 
3) And I am working on CONTACT section, and this section has input (email) and someone has added the style for the input. But I was thinking that why this styles are not added to the input element and after 2-3 hours I got to know that someone who was assigned to work on Subscribe to Newsletter section has used css type selector and these rules are overriding the rules specified for the CONTACT section, because this below rule is applied to all email type input and hence selecting email from CONTACT section.

input [type="email"] {
     css properties.....
}

The proper formating should be below one, so that it will not override contact section email type input

.social-links input [type="email"] {
     css properties.....
}

There is a lot mess in the CSS file, so please review the PR that the changes made are proper or not 

Thank you!!!
