### ISSUE TITLE
BUG: Testimonial text is not visible in light mode

### ISSUE THREAD

**Issue by dsaikiran01** [anuragverma108/SwapReads#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The testimonials section text, on hover, is visible in dark mode. But in light mode it is superimposing on the picture and not visible.

![Screenshot (234)](https://github.com/anuragverma108/SwapReads/assets/108150261/ee60c8a6-7f84-4c4a-b8e1-477cbf4b04dd)

I can fix it by adding a white background for the testimonial text. 
Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
