### ISSUE TITLE
BUG: Duplicate About Us html file 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two about us html files 
-about.html 
-about1.hmtl 

Duplicate pages can create confusion and make it harder for users to navigate 

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/629bb897-db4b-4de7-a80a-2a8d26b7b634)

https://github.com/anuragverma108/SwapReads/assets/169146901/f17c63a3-a1c9-448a-9bc3-26837747d080

i would like to work on this issue please assign it to me under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108  @huamanraj  @RitiChandak please assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
