### ISSUE TITLE
making the navbar similar in all the pages

### ISSUE THREAD

**Issue by nandani-goyal** [anuragverma108/SwapReads#1834]
### What's wrong with the existing documentation

the navbar of the About us and the signup pages are different from the rest of the pages.Please assign me this issue under gssoc'24.I can makes the navbar of all the pages similar.

### Add ScreenShots

![Screenshot 2024-06-14 120632](https://github.com/anuragverma108/SwapReads/assets/152094228/e5bec7db-2bfc-4786-8575-06cf64bde411)
![Screenshot 2024-06-14 120649](https://github.com/anuragverma108/SwapReads/assets/152094228/7cf5ac62-8695-4212-980e-51e6b97bb86b)
navbar of about us
![Screenshot 2024-06-14 120730](https://github.com/anuragverma108/SwapReads/assets/152094228/6dff41ac-3b9c-4565-a195-ea9c5937cc0e)
navbar of login page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
