### ISSUE TITLE
# read later link missing in the more option on Free E-book section # navbar is repeating#google translation missing

### ISSUE THREAD

**Issue by nandani-goyal** [anuragverma108/SwapReads#1835]
### Describe the feature

1)in the more option on the Free E-books page read later link is not visible.
2) also I can add the google translation element in the navbar.
3)also the navbar is repeating due to some error in the code.
i can solve these issues.Please assign me this work under gssoc'24.

### Add ScreenShots

![Screenshot 2024-06-14 124416](https://github.com/anuragverma108/SwapReads/assets/152094228/a03c92ca-0db8-4b17-a8bf-20e716662402)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
