### ISSUE TITLE
BUG:what  our customer Say Hover problem

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/3215655d-7328-49de-a411-eb623e2141f1)
when i hover on card the image gettin disappeared.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
