### ISSUE TITLE
Feat:Social Integration

### ISSUE THREAD

**Issue by sakshiiiii26** [anuragverma108/SwapReads#184]
### Describe the feature

Reader can share his favourite book on social media this will helf in marketing of website. Also rating features could be added.

### Add ScreenShots

![Share on social media_20240512_124756_0000](https://github.com/anuragverma108/SwapReads/assets/157235573/f927196d-5f68-46af-9559-3103d41a0672)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshiiiii26** [comment]
Hello!! @anuragverma108 please assign me this task..

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
