### ISSUE TITLE
#Adding a "trending book" section in the "book recommendation" section.

### ISSUE THREAD

**Issue by nandani-goyal** [anuragverma108/SwapReads#1840]
### Describe the feature

we can also add a trending book section in the book reccommendations web page that can make the page more informative.or we can also create a new "trending book" webpage which can be accessed through more option.

please assign me this under gssoc'24.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/152094228/4e193df6-64f4-45b5-a2df-144ba525e592)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
