### ISSUE TITLE
BUG: CSS of home page in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [anuragverma108/SwapReads#1841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/142989448/edb4f137-df69-4d95-bd23-c1e56716c2ae

i would like to fix css of page in mobile view

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by dhairyagothi** [comment]
@RishabhDhawad please add gssoc and level label in PR merged
