### ISSUE TITLE
#Improving the "rate us" webpage

### ISSUE THREAD

**Issue by nandani-goyal** [anuragverma108/SwapReads#1843]
### Describe the feature

I want to improve the rate us section.Please assign me this issue under gssoc'24.

### Add ScreenShots

![Screenshot 2024-06-14 152937](https://github.com/anuragverma108/SwapReads/assets/152094228/07f144f5-be2e-458b-b6c3-973db6641f64)
this is the existing rate us section
I think creating a rate us page like below can help us even know about the reviews of the user which one of the aim of the website
![Screenshot 2024-06-14 152900](https://github.com/anuragverma108/SwapReads/assets/152094228/123d5de2-b2be-45eb-b692-7d0c2370b36d)
![Screenshot 2024-06-14 152835](https://github.com/anuragverma108/SwapReads/assets/152094228/02cb1f91-a0d1-497a-8fa4-1aba6803257a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
