### ISSUE TITLE
Add Social Icons to Footer Section of Read Later Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1844]
### Describe the feature

Hey @anuragverma108 

The footer section of the read later webpage currently lacks social media icons, which are essential for connecting with our audience. Adding social icons to the footer will enhance the user experience by providing easy access to our social media profiles. This issue involves integrating social media icons into the footer section, ensuring they are appropriately styled and linked to the respective social media pages.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Currently, the footer section of read later page looks like:
![Screenshot 2024-06-14 155537](https://github.com/anuragverma108/SwapReads/assets/159511364/3987f4dd-3d5d-44a7-9105-1fdcf32465f4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@anuragverma108 @SaiTejaswaniBikkasani

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number.
Also, please star the repo before working on it. Happy open-source contributing!
