### ISSUE TITLE
#adding a preview button in the Free E-books webpag

### ISSUE THREAD

**Issue by nandani-goyal** [anuragverma108/SwapReads#1845]
### Describe the feature

we can add a preview button below each of the books which on being clickes open up a iframe through which users can a small preview of the entire book.Please assign me this under gssoc'24.

### Add ScreenShots

![Screenshot 2024-06-14 160038](https://github.com/anuragverma108/SwapReads/assets/152094228/0a1d40a8-79a6-4b85-9f60-82a7e4724f4d)
![Screenshot 2024-06-14 160140](https://github.com/anuragverma108/SwapReads/assets/152094228/efc86bc8-88fa-4fbb-9c4f-713745562084)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
