### ISSUE TITLE
Remove Duplicate Email Newsletter Subscription on Swap Booklist Page and enhance Email box

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#1848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 

The Swap Booklist page currently displays duplicate email newsletter subscription fields, which can be confusing and clutter the page. This issue involves identifying and removing the redundant email subscription field to streamline the user experience and maintain a clean, organized layout. The input of email address is not visible and need enhancement.

The image related to the issue is as follows:
![Screenshot 2024-06-14 161852](https://github.com/anuragverma108/SwapReads/assets/159511364/df0c66b4-65e5-4818-b4c3-71134e88b754)

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
i ffix it

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
