### ISSUE TITLE
About the newsletter form in footer

### ISSUE THREAD

**Issue by Ajita369** [anuragverma108/SwapReads#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are few issues with the email box in the newsletter form in the footer.
1-  It is taking input in capital letters which is not correct , emails can have lowercase letters as well .
2- It is giving message 'Thank you for subscribing!' even if I entered wrong email address which is not correct , it should provide the user the correct message if the email is valid or not . 
3- The alignment of the confirmation message is not aligned properly .

Screenshot :  
![image](https://github.com/anuragverma108/SwapReads/assets/162597493/792c2de3-c9d9-487c-96e4-72412a760df3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
