### ISSUE TITLE
BUG: CSS text visible at top

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/39bb5c94-f2af-4506-9426-fa1cb2593998)
There is some css text visible in the deployed site. This shouldnt be there.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @vansh-sardana
