### ISSUE TITLE
BUG: In rate us page  the navbar has benefits and home above each other

### ISSUE THREAD

**Issue by Garimas10u** [anuragverma108/SwapReads#1861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The UI for the rate us page navbar is distorted in the rate us page
![Screenshot 2024-06-14 220739](https://github.com/anuragverma108/SwapReads/assets/130840612/743cd956-04d2-43a9-9e35-67541cc0d6e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Garimas10u** [comment]
Please assign me the issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Garimas10u** [comment]
Thank you for assigning the issue
