### ISSUE TITLE
BUG: Back to top arrow not working in login/signup page

### ISSUE THREAD

**Issue by Maana-Ajmera** [anuragverma108/SwapReads#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Back to top arrow is not working in login/signup page.

https://github.com/anuragverma108/SwapReads/assets/162733812/75420b42-cbb7-4479-9b8b-d74917f3762c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@anuragverma108 @huamanraj please assign me the issue
