### ISSUE TITLE
Feat:Audio Playback 

### ISSUE THREAD

**Issue by sakshiiiii26** [anuragverma108/SwapReads#187]
### Describe the feature

Integrate audio narration for users who prefer listening to ebooks rather than reading them visually.

### Add ScreenShots

Progress tracking features could also be added which is like bookmark.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshiiiii26** [comment]
Hello @anuragverma108 please assign me this task!

**Comment by sakshiiiii26** [comment]
Hello @anuragverma108 my audio play code is connected but to add this I need page of books  where it opens but till now website doesn't show any book link

**Comment by sakshiiiii26** [comment]
@anuragverma108 Can I do this task of making available link of books on website or this task is assigned to someone else??

**Comment by sakshiiiii26** [comment]
Hello @anuragverma108 <https://github.com/anuragverma108> my audio play
code is ready but to add this I need page of books where it opens but till
now website doesn't show any book link
 Can I do this task of making available link of books on website or this
task is assigned to someone else??

**Comment by RitiChandak** [comment]
@sakshiiiii26 any update?

**Comment by sakshiiiii26** [comment]
@RitiChandak Yess my code is ready to push but I have asked for something but @anuragverma108 didn't respond yet

**Comment by RitiChandak** [comment]
no the task is not assigned to anyone else

**Comment by RitiChandak** [comment]
@sakshiiiii26 if you want you can work and before creating pr push the changes then create pr

**Comment by sakshiiiii26** [comment]
Okay, Please give me time till tomorrow, I have an exam tomorrow, I will push it by tomorrow night.
