### ISSUE TITLE
BUG: Cookie consent banner "Learn more" link lacks a "show less" option

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I click on the "Learn more" link in the cookie consent banner, it expands to show more content. However, there is no option to collapse this expanded content or to go back to the original, shorter banner text. This means that once the user clicks "Learn more," they are stuck with the expanded content unless they refresh the page or interact with the banner in some other way like accept or reject.

https://github.com/anuragverma108/SwapReads/assets/121204667/6730c247-abd0-4a8c-9558-910afcff4dd5

**Steps to reproduce:**
1. Open the website with the cookie consent banner.
2. Click on the "Learn more" link within the cookie consent banner.
3. Observe that the content expands to show more information.
4. Notice that there is no option to collapse this content or return to the original state.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
