### ISSUE TITLE
Feat: Add a community forum for  like minded users to interact 

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#1871]
### Describe the feature

Adding community forum to the SwapReads project. This forum will serve as a space for users to interact, share ideas, discuss books, and help each other with book recommendations and swaps.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
