### ISSUE TITLE
BUG: dark mode toggler position not fixed and also icons are not there

### ISSUE THREAD

**Issue by Gamerking177** [anuragverma108/SwapReads#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

dark mode toggler position not fixed and also icons are not there

https://github.com/anuragverma108/SwapReads/assets/130808542/cdeb4635-5420-4315-bb84-9a7fa0f94d4e

like this

https://github.com/anuragverma108/SwapReads/assets/130808542/0ab3b2da-5632-4a95-b661-62da8d1e7288

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
