### ISSUE TITLE
BUG:testimonial next previous color

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/16987473-c659-453d-ab6d-58c4fd9fa719)
the color of next prev is not according to theme

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
