### ISSUE TITLE
BUG: Repeting books in free e books webpage and extra "rights reserved" line in footer section of same page .

### ISSUE THREAD

**Issue by ANKeshri** [anuragverma108/SwapReads#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

books were repeated in free e book page so it should be replaced with variety of further books and there was an extra rights reserved line in footer of same page .
![image](https://github.com/anuragverma108/SwapReads/assets/159682348/d300a2cd-d299-4524-899e-66f3cf7e00ec)

![image](https://github.com/anuragverma108/SwapReads/assets/159682348/4bcf506f-4a08-43d8-becd-9eaf39fca8f7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@anuragverma108 I have fixed this issue and created a pull request for the same . Please assign this issue to me and merge my pull request under gssoc label .

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by ANKeshri** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

Added before and after screenshot in my pr and issue no and star has already been done .
