### ISSUE TITLE
[BUG]: Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#1883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Missing Responsive in the `mobile` site

[Screencast from 2024-06-15 07-56-43.webm](https://github.com/anuragverma108/SwapReads/assets/121082414/46e9a54d-1adb-41e6-8d11-40a78a237100)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
