### ISSUE TITLE
[Enhancement] : Nav Bar Not work `mobile` site

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#1885]
### Describe the feature

- In this project `nav` Doesn't work .
- I will ready for work on this project..
- please assign me.... :rocket: 

### Add ScreenShots

[Screencast from 2024-06-15 08-57-01.webm](https://github.com/anuragverma108/SwapReads/assets/121082414/d661bada-e72b-4ccc-91e6-c7a37d03ec3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
