### ISSUE TITLE
Feat: Turn Off text selection in website

### ISSUE THREAD

**Issue by thevijayshankersharma** [anuragverma108/SwapReads#1886]
### Describe the feature

Turn Off text selection in website
text selection has to be turned off

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/109781385/aa5768c0-7139-4c31-af5d-521c958cfb5e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
