### ISSUE TITLE
Enhance User Experience and Dynamically Update Copyright Year.

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#189]
### Describe the feature

Hey @anuragverma108 , Currently, the Login page on the website uses "Register" as both the button label and for heading, but for better clarity and user experience, we should change the heading to "Create Account". Additionally, to improve the visual appeal of the buttons, we should increase the font-size of the buttons' text to 1.5 rem from the current 1 rem.

Furthermore, the footer of the website contains a hardcoded copyright year. To ensure that the year is always up-to-date, we should update it dynamically so that it reflects the current year.

**I would like to work on this under GSSOC'24, so please add the labels and assign this work to me. Thank you!!**

### Add ScreenShots

Additionally, the footer of the website contains a hardcoded copyright year set to 2023 to illustrate that the code is hardcoded. This should be updated to dynamically display the current year for the copyright information.

Before making the changes: 
![Screenshot 2024-05-12 125529](https://github.com/anuragverma108/SwapReads/assets/159511364/851ff0ea-51d0-4e4f-aaf2-81e41bffbd5d)

After making the changes: 
![Screenshot 2024-05-12 125651](https://github.com/anuragverma108/SwapReads/assets/159511364/d54bf512-8e18-459d-b541-089d29088587)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on it @SaiTejaswaniBikkasani
