### ISSUE TITLE
Feat: Confirm Password option for auth

### ISSUE THREAD

**Issue by codercake** [anuragverma108/SwapReads#1891]
### Describe the feature

The "Confirm Password" feature in an authentication system is a common security measure used to ensure that users accurately enter their desired password during account creation or password change processes. 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/117517206/049e8a99-6f61-4436-a340-f20a4579a7bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by codercake** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

sure thing.
