### ISSUE TITLE
Feat: Implement Email Notification on Subscribing to newsletter

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1892]
### Describe the feature

Currently, clicking the "Subscribe" button on our website's subscription form does not trigger any action, leading to a poor user experience. To enhance functionality and improve user engagement, we propose implementing a back-end feature that sends an automatic email notification to users upon clicking the "Subscribe" button. This email will confirm their subscription with a message such as "Thanks for subscribing."

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/3a565c12-1462-496c-981b-b28b005c92e2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
