### ISSUE TITLE
BUG: Fading the instructions once they are fulfilled in create password page.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before:
![image](https://github.com/anuragverma108/SwapReads/assets/107904311/5e599ce6-c507-4774-9971-71fb9fe1506a)

After:
since the uppercase and lowercase are already satisfied so its color fades.
The same will be followed for all the four instructions
![image](https://github.com/anuragverma108/SwapReads/assets/107904311/decd9518-03ef-4591-9a35-0568d5fb4e8a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
