### ISSUE TITLE
BUG: Dark mode not working in literary realms.

### ISSUE THREAD

**Issue by vansh-sardana** [anuragverma108/SwapReads#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Steps to reproduce:
1. On the home page, click on the hamburger icon.
2. select literary realms
3. Check the buttons. Neither its css is correct nor they are functional

![image](https://github.com/anuragverma108/SwapReads/assets/107904311/ca830232-3543-4a29-ae29-1bb0b405d635)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
