### ISSUE TITLE
cookies to improve your card button is not responsive

### ISSUE THREAD

**Issue by kartikmehta18** [anuragverma108/SwapReads#1896]
cookies to improve your card button is not responsive see
@anuragverma108  plz assign me

![image](https://github.com/anuragverma108/SwapReads/assets/125860170/d04643fa-5147-437b-b2d2-ffacdfeb9606)

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by kartikmehta18** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

https://github.com/anuragverma108/SwapReads/pull/1916 plz review this  

![image](https://github.com/anuragverma108/SwapReads/assets/125860170/34cb4a0a-c38d-4078-b78c-5d922e5efbd4)
