### ISSUE TITLE
Feat:Place Holder text in subscribe to newsletter

### ISSUE THREAD

**Issue by Saipradyumnagoud** [anuragverma108/SwapReads#1900]
### Describe the feature

The place holder text in the subscribe to newsletter , The first letter is not capital

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143107589/c434b4d8-2eba-4b89-bdf0-4c883cb9ad95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
