### ISSUE TITLE
Enhancement of the forms

### ISSUE THREAD

**Issue by madhurima316** [anuragverma108/SwapReads#191]
In the Book Exchange Hub part , after submitting the filled out form , the form still contains the data , so I want to update it so that after submitting , the form becomes blank again . I want to update this part for the Contact section too.

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoc24

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
