### ISSUE TITLE
BUG: share links are not perfectly aligned 

### ISSUE THREAD

**Issue by Vedant285** [anuragverma108/SwapReads#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Share buttons are not aligned 
![Screenshot_2024-05-12-14-29-50-213_com android chrome](https://github.com/anuragverma108/SwapReads/assets/91669901/49b07ac1-5021-4a6c-9e33-7525f34ba295)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
solved now!!
