### ISSUE TITLE
Feat: Add FAQs in The nav bar

### ISSUE THREAD

**Issue by Saipradyumnagoud** [anuragverma108/SwapReads#1924]
### Describe the feature

Previously there is no FAQ in the nav bar i want to add the FAQs in the nav bar

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143107589/5aed6756-0bff-4ed3-a412-b6db1521c706)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Saipradyumnagoud Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Assigned!
> Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
> Happy open-source contributing!
> 

yes I have added before and after screen shot please check

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Assigned!
> Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
> Happy open-source contributing!
> 

also pulled all existing changes
