### ISSUE TITLE
Submit Rating Feat: Rate us page must also have a button called submit .

### ISSUE THREAD

**Issue by Rupalpy** [anuragverma108/SwapReads#193]
### Describe the feature

submit the rating must be there otherwise one can do it again and again .

### Add ScreenShots

![Screenshot_20240512_142448](https://github.com/anuragverma108/SwapReads/assets/121295967/8623c027-e25d-4d80-b066-0d655beb9001)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to star the repo before starting Open Source Contribution.

**Comment by AditiJeena** [comment]
Can you please assign me this issue

**Comment by RitiChandak** [comment]
completed by #220
