### ISSUE TITLE
BUG: Fix the form - Write me anything , Contact section

### ISSUE THREAD

**Issue by madhurima316** [anuragverma108/SwapReads#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After submitting the filled 'Write me anything' form , there appears an error message and the entire form clears out instead of only the field that has problem. Infact the error message appears everytime , so I want to fix it and would like to add the feature so that upon submission there is some confirmation message and the form becomes blank again. 

![Screenshot 2024-06-17 011132](https://github.com/anuragverma108/SwapReads/assets/145414858/52eec796-3dec-4ba7-805e-5dc3b965b125)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by madhurima316** [comment]
Please assign me this issue under GSSOC'24.

**Comment by anuragverma108** [comment]
@madhurima316 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
