### ISSUE TITLE
BUG: username not visible after signin

### ISSUE THREAD

**Issue by Subhams-GIT** [anuragverma108/SwapReads#1938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

after sign in instead of signin/signup username should be visible 
![Screenshot (336)](https://github.com/anuragverma108/SwapReads/assets/143584912/26bed7da-9bac-4847-9051-fa7b1b3c4fbc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Subhams-GIT Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
