### ISSUE TITLE
Feat:To Add copyright and privacy policies of SwapReads.com

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/SwapReads#194]
### Describe the feature

Hello @anuragverma108 
I hope this message finds you well! I'm reaching out regarding an important addition to our project, SwapReads.com. As we continue to develop and refine our platform, it's essential that we prioritize legal compliance and user trust. To that end, I propose the inclusion of comprehensive copyright and privacy policies.

Why is this important?

Legal Compliance: By having clearly defined copyright policies, we ensure that the intellectual property rights of all stakeholders, including content creators and users, are respected and upheld within the bounds of the law.

User Trust: Privacy policies are crucial for fostering trust with our users. They demonstrate our commitment to protecting their personal information and outline how we handle data, enhancing transparency and accountability.

How Can You Contribute?

Review and Feedback: Your expertise and insight would be invaluable in crafting policies that are not only legally sound but also align with the ethos of our platform. Your review and feedback on the drafted policies would greatly enrich the process.

Legal Expertise: If you have a background in law or experience in drafting similar documents, your direct contribution to the creation of these policies would be immensely beneficial.

Next Steps:

Collaborative Drafting: We can establish a collaborative space within our GitHub repository specifically for drafting these policies. This will allow for transparent communication and version control throughout the process.

Community Input: Once initial drafts are prepared, we can open the discussion to the wider community for input and suggestions. This not only ensures inclusivity but also enhances the quality and comprehensiveness of the policies.

Timeline:

I propose that we aim to have the initial drafts ready for review within the next [insert timeframe], with subsequent iterations and finalization to follow based on feedback received.

Your contribution to this endeavor would not only strengthen the legal foundation of SwapReads.com but also reinforce our commitment to ethical and responsible practices in the digital domain.

Looking forward to your thoughts and collaboration on this matter.

Warm regards,
Priya Ghosal

### Add ScreenShots

![Screenshot (53)](https://github.com/anuragverma108/SwapReads/assets/162816363/4b12074b-8812-4b79-8ab1-37608ab64e4c)
I want to add this copyright and privacy policy in the footer section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @PriyaGhosal 
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by anuragverma108** [comment]
Any Updates @PriyaGhosal 
Please do the work within 1 week , if you didn't responded then I will assign it to some other contributor.

**Comment by RitiChandak** [comment]
@PriyaGhosal Any update or I will close it by tomorrow EOD

**Comment by PriyaGhosal** [comment]
@RitiChandak @anuragverma108 Not able to do this due to upcoming University exam.Will do after 19th June .

**Comment by RitiChandak** [comment]
@PriyaGhosal For right now we are closing this issue you can raise again if you want.
