### ISSUE TITLE
Feat: Update toggle button in About us page

### ISSUE THREAD

**Issue by Bhumika1312** [anuragverma108/SwapReads#1940]
### Describe the feature

I want to add sun and moon icons to the toggle button on the "About Us" page to enhance its appearance

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/115869626/3341cb60-15f5-4792-a1c3-f5470731f712)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by Bhumika1312** [comment]
@anuragverma108 Can you please assign this issue to me

**Comment by anuragverma108** [comment]
@Bhumika1312 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
