### ISSUE TITLE
BUG: Github is missing some footer page

### ISSUE THREAD

**Issue by GAVINESHWAR** [anuragverma108/SwapReads#1943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Github icon is missing in some footer page but present in another page , it leads to user to feel github is not available.
![image](https://github.com/anuragverma108/SwapReads/assets/124431955/0f4181ae-5f82-4482-b79c-ce0fa7835834)
Here Github is missing
![image](https://github.com/anuragverma108/SwapReads/assets/124431955/4f4fd67c-e599-488c-b2d1-bb7b6858508d)
But present here

Assign me this issue @anuragverma108 to resolve the  issue and make contribution to the project
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@GAVINESHWAR Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
