### ISSUE TITLE
Feat: Making proper alignment of Login page and Make proper justification of text in home page

### ISSUE THREAD

**Issue by GAVINESHWAR** [anuragverma108/SwapReads#1944]
### Describe the feature

In the Login page the alignment of sign in with google is not aligned properly it is places completely  left and the alignment of the text in the home page was aligned as center being a description it should be justified properly  

Assign me this issue @anuragverma108 to make contribution to the project
Thank you

### Add ScreenShots

Here the size of the email input also different with respect to password
![image](https://github.com/anuragverma108/SwapReads/assets/124431955/e5b4428b-dfc4-4148-9c19-6cecece4ff4c)

instead of making center it is align justify.
![image](https://github.com/anuragverma108/SwapReads/assets/124431955/7c1d0883-58a9-46ac-b345-66fab1c968ad)
![image](https://github.com/anuragverma108/SwapReads/assets/124431955/9af167fe-d7ff-408e-875d-fb977b926bda)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@GAVINESHWAR Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
