### ISSUE TITLE
BUG: mprove Password Creation Feedback on Signup

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When users are signing up and creating a password, the criteria checks (e.g., minimum 8 characters, at least one uppercase letter, etc.) become light when they are met. This makes it difficult for users to understand which criteria have been satisfied. To improve user experience, the criteria should be marked with a green check icon when they are met.

![login](https://github.com/anuragverma108/SwapReads/assets/129402285/c7a4888f-e005-41d2-af46-888f67c5c068)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Saksham2k3s Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
