### ISSUE TITLE
BUG: Ensure Password and Email Input Fields Have the Same Length

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The length of the password input field and the email input field should be consistent for a uniform user interface. Currently, there is a discrepancy in their lengths, which affects the visual balance of the form.
![length](https://github.com/anuragverma108/SwapReads/assets/129402285/b7b5d456-df0e-434a-a787-5008540ed591)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

M

**Comment by anuragverma108** [comment]
Make single PR for issue #1945 & #1946
