### ISSUE TITLE
BUG: Add a Confirm Password Field on Signup

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To enhance security and user experience, there should be a confirm password field on the signup form. This field will help users ensure that they have entered their password correctly by requiring them to type it twice.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
