### ISSUE TITLE
Feat: Adding Books of different genres in the literary realms 

### ISSUE THREAD

**Issue by Archiesachin** [anuragverma108/SwapReads#1957]
### Describe the feature

To connect the genres with its specific books in the literary realms section. 
Currently only Romance books redirect to its particular books page. 
Adding the same functionalities to all other genre cards. 

## This does not redirect to any dedicated book page
![Screenshot (1100)](https://github.com/anuragverma108/SwapReads/assets/103347688/05882e57-447a-4f0a-b90d-a34a1ebd1509)

## Redirecting all the genre books to their specified pages (like this romance genre page)

![Screenshot (1099)](https://github.com/anuragverma108/SwapReads/assets/103347688/6bf62258-477f-42a2-8015-5bff09ac05da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Archiesachin Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Archiesachin** [comment]
Hey @anuragverma108 someone has already worked on this issue that was assigned to me.
