### ISSUE TITLE
Providing transition for FAQ section.

### ISSUE THREAD

**Issue by Viole07** [anuragverma108/SwapReads#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey Anurag!

I noticed that there is no transition used for the FAQ section, it just comes into view on click and disappears when clicked again. So I thought a transition for this would make the things feel better.

![Screenshot 2024-05-12 153949](https://github.com/anuragverma108/SwapReads/assets/149924641/dd6c83fa-e972-473e-aff5-a832657a10ec)

Please assign me this task, I would like to contribute. Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
