### ISSUE TITLE
nav bar hover color is no good in dark mode can we change this in to cream color

### ISSUE THREAD

**Issue by kartikmehta18** [anuragverma108/SwapReads#1965]
nave bar hover color (red ) is no good  an eye catchy in dark mode can we change this in to cream color
![image](https://github.com/anuragverma108/SwapReads/assets/125860170/f88c01fc-87df-4371-9b5b-70133fda8e54)
****

**Comment by anuragverma108** [comment]
@kartikmehta18 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Gamerking177** [comment]
@anuragverma108  sir all time logo will be changing pls set a default logo sir

**Comment by kartikmehta18** [comment]
https://github.com/anuragverma108/SwapReads/pull/1970 plz review @anuragverma108
