### ISSUE TITLE
Feat: Add view profile button to contributors

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#1974]
### Describe the feature

It would be a great feature if we add a view profile button in the contributor's card 

### Add ScreenShots

![Screenshot 2024-06-19 143348](https://github.com/anuragverma108/SwapReads/assets/142779809/887eae7e-2425-46d5-bb56-7d7007bc7e72)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
