### ISSUE TITLE
Feat: Adding color and transition to Hovering of social icons in home page and fixing footer of about us section

### ISSUE THREAD

**Issue by Maana-Ajmera** [anuragverma108/SwapReads#1977]
### Describe the feature

- Adding color to hover of social icons 
- Fixing footer of about us section

### Add ScreenShots

Before:
![image](https://github.com/anuragverma108/SwapReads/assets/162733812/cde3980a-2ef9-4f89-9f78-1298eee5fa96)

After:
Added hover color to icons
Fixed the allignment of footer

https://github.com/anuragverma108/SwapReads/assets/162733812/743d554a-4764-458f-b5a1-33169a98ed00

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @huamanraj @RishabhDhawad Please assign me this issue , I want to work on it

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @huamanraj @RishabhDhawad Please review my PR and merge it under gssoc .

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
