### ISSUE TITLE
BUG: Color of the cards in the pricing section 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The card color for pricing section cards is different from all the other section cards which looks visually unappealing, we could make it the same color as the other to make it cohesive with the overall theme of the site 

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/6038dc3e-8070-45b5-9a1a-3120e0ed801b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108  @huamanraj  pls assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
