### ISSUE TITLE
BUG: About page footer fix

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#1980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-19 200242](https://github.com/anuragverma108/SwapReads/assets/146661411/00bc03bb-c89a-4332-b63b-037efb021518)
random css, and repititive text

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
