### ISSUE TITLE
Feat: Deleting chat history in chatbot

### ISSUE THREAD

**Issue by DevNandini02** [anuragverma108/SwapReads#1983]
### Describe the feature

The chatbot chats are not getting deleted after a conversation. 

https://github.com/anuragverma108/SwapReads/assets/124669890/ee30e056-042f-4ae8-b58f-9ff37973a3f7

To begin a new conversation each time there should be a feature to delete the chat history.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/124669890/179b87cb-b7a6-4c61-8cc3-6177de0f88cb

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
