### ISSUE TITLE
BUG:navigation not remain same in all pages

### ISSUE THREAD

**Issue by Varsani2520** [anuragverma108/SwapReads#1984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in home page 
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/ee99ee26-870b-4ff4-af32-c93fc45ab93b)

in about page 
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/d9969267-ff2e-4c40-a1d2-3232de35989f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@anuragverma108 ,please assign this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Varsani2520** [comment]
ok @huamanraj

**Comment by meenakshiiyer2531** [comment]
Hello @huamanraj  ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
