### ISSUE TITLE
Feat: Add a carousel to the library realms section

### ISSUE THREAD

**Issue by DevNandini02** [anuragverma108/SwapReads#1985]
### Describe the feature

There are many cards in the library realm section which is taking too much space. The UI should be a bit compact where same kind of things can be scrolled side by side like a carousel of cards.

![bug6](https://github.com/anuragverma108/SwapReads/assets/124669890/e1f0d6a4-f24d-4251-942b-baa64bc47fef)

### Add ScreenShots

![sliders](https://github.com/anuragverma108/SwapReads/assets/124669890/82334ea5-9da4-40c4-9d14-3352dcc7dff3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
