### ISSUE TITLE
BUG: Textarea of Book Exchange Hub 

### ISSUE THREAD

**Issue by Dishaaa-T** [anuragverma108/SwapReads#1986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text area is not correctly defined for the form which is confusing and visually unappealing

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/d7cb174d-cefd-4c6b-aa83-945d57bc6182)

![image](https://github.com/anuragverma108/SwapReads/assets/169146901/d595d6fe-b942-462c-9425-eb1bdebf0a09)

i would like to work on this issue please assign me this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dishaaa-T** [comment]
@anuragverma108 @huamanraj please assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
