### ISSUE TITLE
Navbar disappearing on scrolling down

### ISSUE THREAD

**Issue by DevNandini02** [anuragverma108/SwapReads#1987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is vanishing when scrolled down. It should be made sticky such that it is static for complete website and users can go to navbar tabs from any where on website. They don't need to scrolled up.

https://github.com/anuragverma108/SwapReads/assets/124669890/c143192c-03c6-4204-a7bf-717a4244e1d7

The navbar is like this right now. 

After changes it would look like this.

https://github.com/anuragverma108/SwapReads/assets/124669890/5896103f-8d8c-4099-a4e1-b004f89b25e9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
