### ISSUE TITLE
Feat: Add a downwards carousel to Genre section

### ISSUE THREAD

**Issue by DevNandini02** [anuragverma108/SwapReads#1988]
### Describe the feature

Since there are a number of cards in the genre section, we can add a downwards carousel that expands downwards on clicking the down arrow.

### Add ScreenShots

![bottomcarousel](https://github.com/anuragverma108/SwapReads/assets/124669890/1bd4188d-ea4e-4781-976a-ae883dbf6b7f)

Like this on clicking the arrow other cards will expand downwards.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
