### ISSUE TITLE
Feat:want to fix ui of frequntly Asked Question

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1992]
### Describe the feature

want to fix ui of frequntly Asked Question

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/101548649/c188b911-cac9-4e5d-8e23-233be9dcb6c0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
