### ISSUE TITLE
Feat:DarkMode Not working

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#1993]
### Describe the feature

I can Fix Dark Mode

### Add ScreenShots

Dark  mode  is not working

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
