### ISSUE TITLE
BUG: The nav bar and some part of sites are not properely responsive

### ISSUE THREAD

**Issue by bhumii-ka** [anuragverma108/SwapReads#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The following are the bugs found in responsiveness -
- #### The nav options can't be closed in screen sizes between 575px to 990px. It will lead to the genre section when cross button is clicked. It is also not properely visible.
![image(1)](https://github.com/anuragverma108/SwapReads/assets/151030407/88e6c073-7ed3-4080-82e1-cb74351e389a)

- #### The back to top button is not properely aligned for screen size <575px
![image](https://github.com/anuragverma108/SwapReads/assets/151030407/8d25e8cc-46f4-47a0-b339-f1396d6b51a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bhumii-ka** [comment]
Please assign this issue to me and also look at the level assigned, it is a level 3 issue.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by bhumii-ka** [comment]
Sir please increase the level of the issue.
