### ISSUE TITLE
BUG:Hover effect on navbar

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#1997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hover effect  on navbar is not placed correctly below the navbar element

https://github.com/anuragverma108/SwapReads/assets/146806880/118b074b-978a-4205-8ca2-5920f4b5e113

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
pls assign me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
