### ISSUE TITLE
Feat: Added Thrilling Adventures page

### ISSUE THREAD

**Issue by Maana-Ajmera** [anuragverma108/SwapReads#1998]
### Describe the feature

Added new page "thrilling adventures" linked from literary realms.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/162733812/9fd95468-728e-42c8-a8ed-3e0e68f3965f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @RishabhDhawad @huamanraj I want to work on this issue please assign it to me and review my PR , If you like my work please merge it under gssoc

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @RishabhDhawad @huamanraj I have created the PR , please review and merge it under gssoc
