### ISSUE TITLE
Broken Signup/Signin UI

### ISSUE THREAD

**Issue by nandu-99** [anuragverma108/SwapReads#2]
The signup/signin page UI in our project is broken, hindering user experience. I'd like to take ownership of fixing this issue. Please assign it to me, i would love to work on this issue

**Comment by bhavanishanker-png** [comment]
i would like to work on this project please this to me

**Comment by Paromita-maji** [comment]
Hello, I am a GSSoC contributor , I would like to work on this project ,can you please assign me this project.

**Comment by kamalesh-og** [comment]
Hi, 
I'm one of the contributors for the GSOCC'24, I would love to take up this issue and work on this UI.
I have experience in Web Design and I can assure you that I make this UI more attractive and good-looking with proper formatting fonts and design of the page.
Can you please assign this issue to me
Thank you!

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by nandu-99** [comment]
Thank you so much
