### ISSUE TITLE
Card issue

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#20]
**Describe the bug**
Cards given in "Unleash the Magic of Book Swapping!", "Pricing based on their version" section and the form do not have border-radius like others.
It is looking quite odd.

**To Reproduce**
1. Go to 'home page'
2. Scroll down to 'Unleash the Magic of Book Swapping!' & 'Pricing based on their version'
3. See error

**Expected behavior**
All the cards should have proper border-radius to maintain uniformity.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 124.0.2478.80

**Smartphone (please complete the following information):**

**Additional context**
I'm a GSSoC'24 contributor please assign me this work.

**Comment by nishant0708** [comment]
hey i can fix this issue
