### ISSUE TITLE
BUG: Absence of "Scroll Down Bar' in "About Us" page

### ISSUE THREAD

**Issue by MastanSayyad** [anuragverma108/SwapReads#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a Scroll dwon progress bar in the home page but when we navigate to the about us page there is not progress bar

https://github.com/anuragverma108/SwapReads/assets/101971980/6b02bfc7-39a4-4add-8166-d2989912b39a

For navigation consistency I would like to add the progress bar in missing pages such as About Us

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
