### ISSUE TITLE
BUG: Want to fix the navbar position in the About Us page

### ISSUE THREAD

**Issue by tanyagupta01** [anuragverma108/SwapReads#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1466" alt="Screenshot 2024-06-20 at 1 30 15 PM" src="https://github.com/anuragverma108/SwapReads/assets/156044894/ca8fdbad-c7b7-4726-95d4-41e73e4e29d4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
