### ISSUE TITLE
Feat: Display Confirmation Message After Form Submission

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2008]
### Describe the feature

Implement a feature that displays a confirmation message to users after they successfully submit a newsletter form. This message should confirm that their submission has been received.

### Add ScreenShots

![Screenshot 2024-06-20 144528](https://github.com/anuragverma108/SwapReads/assets/168854094/81dfee71-20e9-418d-b54f-57a2768dfd2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@anuragverma108 @huamanraj  @RishabhDhawad Sir please assign this issue to me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
