### ISSUE TITLE
BUG: Button Hover CSS Issue in Cookie Consent Popup

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The buttons in the cookie consent popup have a CSS issue where the sign/icon on hover decreases and the button is touching the border. The button styling needs to be adjusted to prevent these issues and improve user experience.

https://github.com/anuragverma108/SwapReads/assets/168854094/6cf43f7c-4914-4685-9f25-323abc44c294

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@anuragverma108 @huamanraj @RishabhDhawad Sir please assign this issue to me.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
