### ISSUE TITLE
Feat: Add genres

### ISSUE THREAD

**Issue by tanyagupta01** [anuragverma108/SwapReads#2010]
### Describe the feature

I want to add a few genres namely : autobiography, humour and mystery.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
