### ISSUE TITLE
BUG: Large space in the list of 'more' icon

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Their is a large space in the list of 'more' icon. I can solve this issue.

![image](https://github.com/anuragverma108/SwapReads/assets/168854094/0b567d6e-65ce-45f4-9f63-b1ecae1c28cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@anuragverma108 @huamanraj @RishabhDhawad Sir please assign this issue to me.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
