### ISSUE TITLE
BUG: theme changer does not work

### ISSUE THREAD

**Issue by Gamerking177** [anuragverma108/SwapReads#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

theme changer does not work in Home Page

https://github.com/anuragverma108/SwapReads/assets/130808542/aa2357c0-40b5-4115-aa96-9dc85d19ae26

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
