### ISSUE TITLE
BUG: The Accept and Reject Cookies Buttons are not properly aligned

### ISSUE THREAD

**Issue by kashvi9** [anuragverma108/SwapReads#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The **Accept** and **Reject** Cookies Buttons are misaligned.

Here's a screenshot,
![image](https://github.com/anuragverma108/SwapReads/assets/169376061/177633e6-84b1-4d01-ba1d-6e4f89e2bd23)

These Buttons can be aligned inside this cookie box.

Hey PA @anuragverma108 
Please assign me this issue under GSSOC24.
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on it also add some padding and bg colour to cross button!!

**Comment by kashvi9** [comment]
> work on it also add some padding and bg colour to cross button!!

Sure!

**Comment by kashvi9** [comment]
> work on it also add some padding and bg colour to cross button!!

Sir by padding you mean?
Do you mean that the cross button should be aligned to right?

**Comment by kashvi9** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/169376061/843fb140-3a6b-49a6-9c2a-7bca90067b88)

It looks like this...what else changes you want me to make before I submit this PR?
