### ISSUE TITLE
BUG: Navigation missing in responsive

### ISSUE THREAD

**Issue by dhruv8433** [anuragverma108/SwapReads#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108 

check this out,
![image](https://github.com/anuragverma108/SwapReads/assets/114583978/9b349dc3-56dd-4934-a610-5603b2fa70e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this

**Comment by dhruv8433** [comment]
@anuragverma108

please assign me
