### ISSUE TITLE
🐞 BUG: Footer Links are not working in Some Pages

### ISSUE THREAD

**Issue by MastanSayyad** [anuragverma108/SwapReads#2028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 and @huamanraj 

The links in footer are not working in some pages either they do not navigate to the dedicated pages else they show 404 page not found error

https://github.com/anuragverma108/SwapReads/assets/101971980/1b9a437d-69d1-4dab-8f5d-223880d9a438

I would like to take on this task could you please assign this issue to me under GSSOC?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this

**Comment by MastanSayyad** [comment]
Hey @anuragverma108 and @huamanraj please assign this issue to me.
