### ISSUE TITLE
🐞 BUG: No Navigation Link to "SwapReads Logo" in "More Menu" Pages.

### ISSUE THREAD

**Issue by MastanSayyad** [anuragverma108/SwapReads#2030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 and @huamanraj

There is no navigation link for back to home in SwapReads Website Logo in More menu section All Pages 

https://github.com/anuragverma108/SwapReads/assets/101971980/21c30b49-ad43-4e94-8bb1-2207c7bc6941

To maintain consistency across the website I would like to add the navigation link of home page to the logo

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MastanSayyad** [comment]
Hey @anuragverma108 and @huamanraj please assign this issue to me??

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
