### ISSUE TITLE
🐞BUG:  Footer is Missing in "Book Recommendation" Page

### ISSUE THREAD

**Issue by aslams2020** [anuragverma108/SwapReads#2035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
Hey @anuragverma108 , @huamanraj 
The website contains multiple navigating pages accessible through the navbar, one of which is the "Book Recommendation" page accessible via the "More" button.
Unlike other navigating pages, **the "Book Recommendation" page lacks a footer**, leading to an inconsistent user experience.

**Steps to reproduce :**
- Click on the "More" button in the navbar and select "Book Recommendation" from the dropdown.
- Observe that the footer is missing on the "Book Recommendation" page.

here as you can see - 

https://github.com/anuragverma108/SwapReads/assets/131389695/aa1354a0-c8e5-4fe8-bc9a-2eb326964874

**Expected Behavior**
The "Book Recommendation" page should have a footer consistent with the rest of the navigating pages, providing users with access to additional information and navigation options.

@anuragverma108 / @huamanraj  ,By addressing this issue, we can ensure a consistent and complete user experience across all pages of the website.
So, Could you please assing me this issue under GSSoC'24 ?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this

**Comment by aslams2020** [comment]
@anuragverma108 , @huamanraj 
i want to work on this issue..Please assing me

**Comment by aslams2020** [comment]
@huamanraj ..It looks like someone already resolved the issue I raised a few days ago before it assigned to me today.

thank you for assigning but unfortunately now the issue is resolved already by someone.
