### ISSUE TITLE
Feat: Improving UI of trending bookd section

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#2038]
### Describe the feature

Hello @anuragverma108 , I would like to improve the UI of trending books section in book recommendation page. 
Kindly assign me this issue under GSSoC'244, I'll do my best.

### Add ScreenShots

![Screenshot 2024-06-21 165737](https://github.com/anuragverma108/SwapReads/assets/100590445/59b986c4-2fe7-4742-b63d-24810cddd64f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
