### ISSUE TITLE
BUG: The Social Media links do not work in the footer

### ISSUE THREAD

**Issue by AkhilaSunesh** [anuragverma108/SwapReads#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I click on the social media links none of them seem to work. The path provided for this purpose is incorrect.

Allow me to resolve this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
There are not any social media handles of SwapReads. That's why it is been redirected to the socials website only.
