### ISSUE TITLE
BUG: Improve the Navbar alignment 

### ISSUE THREAD

**Issue by JagjeetChauhan** [anuragverma108/SwapReads#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is not aligned with the page.
Kindly assign this task to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
please assign it to me I want to work on this

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
