### ISSUE TITLE
Feat: improvement in UI 

### ISSUE THREAD

**Issue by heli0707** [anuragverma108/SwapReads#2050]
### Describe the feature

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/bfeaace7-a1fa-445f-8c1e-52ec2d1f69d9)

To improve the UI, I'll adjust the text color and background to enhance visibility. This will ensure that the address and accompanying text are clearly readable and visually appealing. Let's proceed with updating these elements for better clarity.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/2e75414e-509e-48cd-bedd-9006b70e8b23)

make something look like this 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
please assign it to me I want to work on this

**Comment by heli0707** [comment]
@huamanraj assign this issue to me
