### ISSUE TITLE
BUG: Cookies option  box got cut 

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#2060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-22 210557](https://github.com/anuragverma108/SwapReads/assets/146806880/95154ab2-82c0-49f5-aa08-0d04d8ca2382)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
sir pls assign this issue to me
