### ISSUE TITLE
making the navbar responsive

### ISSUE THREAD

**Issue by H1mang1** [anuragverma108/SwapReads#2074]
### Describe the feature

Making the navbar responsive for all devices.

### Add ScreenShots

![Screenshot (262)](https://github.com/anuragverma108/SwapReads/assets/123282807/3524a5c5-2c31-41ed-9884-f1d984866aee)
![Screenshot (263)](https://github.com/anuragverma108/SwapReads/assets/123282807/e8ac3b4a-63c7-4b2e-bfc4-96c132335466)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@H1mang1 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by mrunal1309** [comment]
@anuragverma108 Can you please assign me this issue?

**Comment by SHRAVANIc01** [comment]
@anuragverma108  I want to contribute,can you please assign me ?
