### ISSUE TITLE
Feat:adding the  tilty efect to all cards in about us section.

### ISSUE THREAD

**Issue by happyrao78** [anuragverma108/SwapReads#2078]
### Describe the feature

Using the react-tilty library i would like to  add the tilt effect to all cards  in about us section.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/138770813/dd194dec-8aef-4b91-b03b-d61e39294d70

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@happyrao78 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
