### ISSUE TITLE
Feat: Rate us Section Updation

### ISSUE THREAD

**Issue by Damini2004** [anuragverma108/SwapReads#2079]
### Describe the feature

Rate us section updation 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/119414762/0c104992-8e11-4f3a-8a93-1cc578a99bb3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @Damini2004
