### ISSUE TITLE
Feat: Implement backend logic to get the listed books by sellers

### ISSUE THREAD

**Issue by fazil-syed** [anuragverma108/SwapReads#208]
### Describe the feature

After the seller lists a book and receives a confirmation email, he assumes that a buyer will be able to view his listing. but this feature is not available as of now. I suggest implementing a backend API that will fetch all the listings that are available and then return the same to the frontend to be displayed. 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/84120587/a470be44-03d8-4467-8a3e-f315b3b61cdc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by fazil-syed** [comment]
Please assign this issue to me under gssoc'24

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
