### ISSUE TITLE
DOC: Wrong order and bad documentation clarity in contributing.md

### ISSUE THREAD

**Issue by H1mang1** [anuragverma108/SwapReads#2080]
### What's wrong with the existing documentation

Keep the contribution part at the start then make another heading how to contribute and delete the getting started and how to create pull requests  part as it creates confusion.Under how to contribute keep star repo, fork repo, clone repo, cd  SwapReads, npm install  and then keep the same order of other commands that are under how to create pull request .

### Add ScreenShots

![Screenshot (264)](https://github.com/anuragverma108/SwapReads/assets/123282807/7c815327-2f22-4a32-871c-81d9a96cdd1b)
![Screenshot (265)](https://github.com/anuragverma108/SwapReads/assets/123282807/2a884b9f-9505-40bd-8803-a074a02550f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@H1mang1 Assigned!
