### ISSUE TITLE
BUG: Form Alignment and Formatting Issues in Book Exchange Hub

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are noticeable alignment and formatting issues in the form displayed within the website.
1. Misaligned Labels and Input Fields: Labels are not properly aligned with their corresponding input fields, causing a cluttered appearance.
2. Inconsistent Spacing: There is inconsistent spacing between form elements, making the form look unorganized.
3. Overflowing Text: Some text elements overflow their designated areas, leading to readability issues. 

https://github.com/anuragverma108/SwapReads/assets/168854094/82cf5e28-6b7d-466d-989d-5169688bcdca

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@huamanraj Sir please assign this issue to me

**Comment by anuragverma108** [comment]
@TBorundia Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
