### ISSUE TITLE
Feat: Implement Loading Animation with Logo During Page Navigation

### ISSUE THREAD

**Issue by Amishachoudhary22** [anuragverma108/SwapReads#2091]
### Describe the feature

To enhance the user experience and provide a more polished look to the website, I propose implementing a loading animation that displays the website's logo during page navigation. This feature will offer a smoother transition between pages and maintain user engagement while content is being loaded.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/103454929/4c95c0aa-80bd-4b3a-8752-ca9660331a53

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Amishachoudhary22 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
