### ISSUE TITLE
BUG: Rate us link is missing in Quick Links portion of Footer section.

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/SwapReads#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108 
I hope this message finds you well. I wanted to bring to your attention an observation regarding our GitHub project's footer section.

Upon reviewing the Quick Links portion of the footer, I noticed that the "Rate Us" link seems to be missing. This link is important as it provides users with the opportunity to provide feedback and rate our project, which in turn can help us improve and gauge user satisfaction.

Adding a "Rate Us" link to the Quick Links section of the footer would not only enhance user experience but also encourage users to share their thoughts and opinions about our project. This feedback can be invaluable in guiding future developments and enhancements.

I believe addressing this issue will contribute positively to our project's engagement and overall user satisfaction. Please let me know if you require any further information or assistance in implementing this change.

Thank you for your attention to this matter.

Best Regards,
Priya Ghosal

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @PriyaGhosal

**Comment by RitiChandak** [comment]
Completed by #365
