### ISSUE TITLE
BUG: Unnecessary elements in footer section of Free books section

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are Unnecessary elements in footer section of Free books section like below.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/c0be558a-f1cd-4ae9-90ba-7bd526519563)

Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer
