### ISSUE TITLE
BUG: Elements not centred in free books section

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#2118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Elements are not centred in the free books section.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/fe6fcb15-be67-47c0-a93e-22bc43fc403e)
Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by debasmi** [comment]
kindly assign me this issue
