### ISSUE TITLE
BUG:Unwanted double quote in the homepage

### ISSUE THREAD

**Issue by Brinda-07** [anuragverma108/SwapReads#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I came through your website and trust me its really very appealing, thus scrolling through it I just found that there is an unwanted double quote at the last of a paragraph in the home page.

I really want to contribute to GSsoc'24 thus,
Please assign the issue 
![Screenshot 2024-05-12 173204](https://github.com/anuragverma108/SwapReads/assets/154052901/9604adc2-7fe9-4470-9e39-d70d6f0a27dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
