### ISSUE TITLE
BUG:Navbar not visible before 990px.

### ISSUE THREAD

**Issue by meetarora10** [anuragverma108/SwapReads#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is not visible before 990px. Assign this task to me and I will add required styling so that navbar is properly visible in different devices.
![Screenshot (504)](https://github.com/anuragverma108/SwapReads/assets/143121854/16c50a2c-f668-469b-b480-705f51891b04)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by debasmi** [comment]
kindly assign me this issue
