### ISSUE TITLE
BUG: read more is not allign 

### ISSUE THREAD

**Issue by Aman91667** [anuragverma108/SwapReads#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

read more is not align is same line. i want to correct it. @anuragverma108 
![Screenshot_24-6-2024_172841_swapreads vercel app](https://github.com/anuragverma108/SwapReads/assets/142434400/3c5aeedb-7a34-4567-935c-1cecbbaede35)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
assigned 🪖

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@huamanraj
