### ISSUE TITLE
BUG: Want to enhance the login Footer section

### ISSUE THREAD

**Issue by Bhumika1312** [anuragverma108/SwapReads#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer is too large and takes up too much space. I want to make it more presentable.

![image](https://github.com/anuragverma108/SwapReads/assets/115869626/5f8285b6-d5e6-40e7-a9cd-cad252a61cc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @anuragverma108 ,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by jayanththalla** [comment]
i will add the discord assign me

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@huamanraj
