### ISSUE TITLE
DOC: Creating google icon

### ISSUE THREAD

**Issue by Aman91667** [anuragverma108/SwapReads#2134]
### What's wrong with the existing documentation

want to create a google icon instead of a long google bar.
![Screenshot_25-6-2024_151141_swapreads vercel app](https://github.com/anuragverma108/SwapReads/assets/142434400/3e02b717-0a02-4dac-93a0-192fdcfc74aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
is the issue still open? I want to work on it
