### ISSUE TITLE
Feat: Adding hover effect to social media icons

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2163]
### Describe the feature

Change in color according to their logo to the icons in footer section.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/168854094/d35ff66e-56eb-462b-a7a4-a39359ced258

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@anuragverma108  @huamanraj Sir please assign this issue to me

**Comment by nikhilnishadoo7** [comment]
@anuragverma108 @huamanraj i want to work on this issue so can you please assign this issue to me

**Comment by TBorundia** [comment]
@RitiChandak Mam, but this issue was raised by me and done by someone else. https://github.com/anuragverma108/SwapReads/issues/2163
And you have assigned him this issue

**Comment by TBorundia** [comment]
@huamanraj  @RitiChandak , but this issue was raised by me and someone had mentioned my issue number and raised PR #2163
