### ISSUE TITLE
Feat: Enhancing the Free E-Books section 

### ISSUE THREAD

**Issue by theutkarshpatel** [anuragverma108/SwapReads#2173]
### Describe the feature

The options of download and add to read later are not aligned perfectly . I want to add some styles and align the buttons perfectly. @anuragverma108 please assign this issue to me under GSSOC'24. I will try my best.

### Add ScreenShots

<img width="1470" alt="Screenshot 2024-06-26 at 10 43 56 PM" src="https://github.com/anuragverma108/SwapReads/assets/112273162/570ae0c4-c82c-40cd-8f4c-89cb9c2e1aaf">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@anuragverma108

**Comment by RitiChandak** [comment]
Assigned !

**Comment by nikhilnishadoo7** [comment]
I would like to work on this issue , please assign this to me.
