### ISSUE TITLE
BUG: login page darkmode issue

### ISSUE THREAD

**Issue by Aman91667** [anuragverma108/SwapReads#2180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The sign in with google button is disturbed while it is in dark mode. i want to correct it. @anuragverma108 
![Screenshot_27-6-2024_165924_swapreads vercel app](https://github.com/anuragverma108/SwapReads/assets/142434400/b32d197f-75ee-4e8b-8656-bcddc00f2195)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
i want to work on this issue can u plz assign me
