### ISSUE TITLE
Feat:Adding design in the background of rate us and login page

### ISSUE THREAD

**Issue by ananya-dhiman** [anuragverma108/SwapReads#219]
### Describe the feature

The rate us and login page look a little empty so adding books to the background would make the design appealing. The design of the books can be done according to the logo and feel of the website. Below is just an example of the idea.

### Add ScreenShots

![Screenshot 2024-05-12 180429](https://github.com/anuragverma108/SwapReads/assets/145692647/f511baf8-201a-482f-a3bf-336bbc4e1477)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before and after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Maheshwari-Love** [comment]
@anuragverma108  @huamanraj  it has been 2 weeks now for this issue, can you please assign this task  to me?

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> The rate us and login page look a little empty so adding books to the background would make the design appealing. The design of the books can be done according to the logo and feel of the website. Below is just an example of the idea.
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-12 180429](https://github.com/anuragverma108/SwapReads/assets/145692647/f511baf8-201a-482f-a3bf-336bbc4e1477)
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

any update @ananya-dhiman ?

**Comment by Maheshwari-Love** [comment]
@huamanraj I start working on this...

**Comment by ananya-dhiman** [comment]
@huamanraj  Sorry I wasnt able to complete it due to exams .
![image](https://github.com/anuragverma108/SwapReads/assets/145692647/b25142f7-eff9-4f02-9583-1476cc90ce0a)
This is the final preview of the background in the login page.Should I go ahead and add it or make some modifictaion.
