### ISSUE TITLE
BUG: Newsletter and message not clear after some time after some time input filed and message should be clear.

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#2194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/6a93eab8-171e-4b2d-bed2-db3c61064898)

I will add that java script for clear input filed and message of thank you after submit.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@huamanraj @anuragverma108 @RishabhDhawad @RitiChandak Can anyone please assign me !

Also I have an issue my previous PR #2160 is merged but i don't get labels so please provide labels on that so my points will be count.

**Comment by huamanraj** [comment]
> @huamanraj @anuragverma108 @RishabhDhawad @RitiChandak Can anyone please assign me !
> 
> Also I have an issue my previous PR #2160 is merged but i don't get labels so please provide labels on that so my points will be count.

there is no level for some too basic changes!!.

**Comment by zalabhavy** [comment]
@huamanraj in PR #2160 i have added **40+** lines of code for every size of screen it is and you called that is basic ?
**I think you should consider my efforts.
Thank You !**

**Comment by huamanraj** [comment]
> @huamanraj in PR #2160 i have added **40+** lines of code for every size of screen it is and you called that is basic ?
> **I think you should consider my efforts.
> Thank You !**

sorry i thought of other PR and judged without looking at it! it was our mistake that we haven't given any level!

**Comment by zalabhavy** [comment]
@huamanraj It's Ok !

**Thank You !**
