### ISSUE TITLE
Improve Footer of the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#22]
**Is your feature request related to a problem? Please describe.**
I want to improve the footer of the website as it is not looking good.

**Describe the solution you'd like**
I want to add social links and short description of the website and the navlinks properly .

Please assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
Do one more thing when we are click on links in footer it is not redirecting to that particular section. So fix that too

**Comment by harshmishra19** [comment]
Plz assign me this issue under GSSOC.'24 
I can improve the footer of the website.

**Comment by Abdal192003** [comment]
Hi anuragverma108,
Could you please assign me this issue under gssoc'24.
Try my best to solve this issue.
Thanks

**Comment by Madhu-mac** [comment]
@anuragverma108 if anyone failed to wrk on this issue  Assign me this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 Please assign me this issue
