### ISSUE TITLE
BUG: Footer of free-e-books not proper

### ISSUE THREAD

**Issue by Maana-Ajmera** [anuragverma108/SwapReads#2209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer of free-e-books is not proper.

Before : 
![image](https://github.com/anuragverma108/SwapReads/assets/162733812/9131efa7-1bb6-4462-9298-e8025f099ed7)

After:
![image](https://github.com/anuragverma108/SwapReads/assets/162733812/4896e838-8557-4c9d-ae5f-27e0b4aee580)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @RitiChandak @RishabhDhawad @huamanraj I want to work on this issue please assign it to me and review my PR , If you like my work please merge it under gssoc

**Comment by anuragverma108** [comment]
@Maana-Ajmera Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
