### ISSUE TITLE
Feat:The quick links color

### ISSUE THREAD

**Issue by Brinda-07** [anuragverma108/SwapReads#221]
### Describe the feature

**Feature Description:**
The quick links and social in the footer section,when switched to dark mode are not very catchy.
The color grey with black background is not agreeable.
**How to solve:**
If we change the color from grey to white it will solve the problem.

**Please assign this to me

### Add ScreenShots

![Screenshot 2024-05-12 175755](https://github.com/anuragverma108/SwapReads/assets/154052901/496e9e9e-85b2-47af-9410-95e2cf96bf7f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , the quick link section in the footer is not quite visible in the dark mode.
please assign this issue to @Brinda-07 or I'm also available to work on this one.

**Comment by Brinda-07** [comment]
Yes plz @anuragverma108 assign this issue to me

**Comment by huamanraj** [comment]
@Brinda-07 work on it!!
