### ISSUE TITLE
Feat: adding git hub link to cards of team members in about us and copyright policy and privacy notice not visible in dark mode of read later

### ISSUE THREAD

**Issue by ANKeshri** [anuragverma108/SwapReads#2211]
### Describe the feature

- adding github link to team members as it is not present anywhere in  website .
- in dark mode privacy notice and copyright policy is not visible in read later page .

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/159682348/29cb87a9-8905-4ee9-b101-3e7c457ed3fe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@ANKeshri Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
