### ISSUE TITLE
Dark mode Enhancement

### ISSUE THREAD

**Issue by tanu-agarwal0101** [anuragverma108/SwapReads#222]
### What's wrong with the existing documentation

![image](https://github.com/anuragverma108/SwapReads/assets/162132053/ce383c3a-4d25-424d-a7ef-cebca35d9b5b)
![image](https://github.com/anuragverma108/SwapReads/assets/162132053/385dfe54-ccce-4ed2-96da-96c013930165)

The border of cards are not visible clearly. I would like to work on this issue.
Please assign me this under GSSOC,24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
@tanu-agarwal0101  work on it!! but take care of theme consistency  and try playing with hover effect and add some screenshot with PR!! 

i am the mentor of this project for any help react out to me!!

**Comment by Manaswini123456** [comment]
@huamanraj Hello, please assign me with this issue, I would like to provide my insights and solutions too.
