### ISSUE TITLE
Feat: Adding an edit profile page and enable profile avatar change

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#2221]
### Describe the feature

There will be a profile edit page where user will be able to change their avatars, which then will get reflected to their homepage 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/defe49ca-05c1-4ce1-ae43-493baddfd73b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@huamanraj This wont be a level1 issue. But will it still get maked as level1??

**Comment by huamanraj** [comment]
> @huamanraj This wont be a level1 issue. But will it still get maked as level1??

it is default level will get increased during PR based on code

**Comment by ayush-848** [comment]
@huamanraj I have requested a PR for it
