### ISSUE TITLE
DOC: Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [anuragverma108/SwapReads#223]
### What's wrong with the existing documentation

Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , please assign this issue to me.

**Comment by huamanraj** [comment]
> hey @anuragverma108 , please assign this issue to me.
@jinx-vi-0 hello, 

add Dynamic readme keep all the content precisely and add contributors and admin and mentor section!

**Comment by jinx-vi-0** [comment]
ok

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , I've created a pr please check it and let me know for any feedback.
