### ISSUE TITLE
BUG: the buy now all three cards not visible completely , the position of copyright policy and privacy notics not aligned and also not visible in dark mode

### ISSUE THREAD

**Issue by ANKeshri** [anuragverma108/SwapReads#2233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the buy now all three cards not visible completely , the position of copyright policy and privacy notics not aligned and also not visible in dark mode

https://github.com/anuragverma108/SwapReads/assets/159682348/861e4283-ed92-47de-b664-f9a31849c22a

![image](https://github.com/anuragverma108/SwapReads/assets/159682348/864e14f2-0ef1-4712-905e-d2d07e99d43e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@anuragverma108 @ritu713 @huamanraj please assign me this issue under gssoc labels i want to work on it

**Comment by nikhilnishadoo7** [comment]
@anuragverma108 @ritu713 @huamanraj @RishabhDhawad please assign me this issue under gssoc labels i also want to work on this issue
