### ISSUE TITLE
BUG: FAQ section is too large in size

### ISSUE THREAD

**Issue by nisargaa20** [anuragverma108/SwapReads#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 FAQ section is too large in size . We if decrease the width it will look better

Kindly assign me this issue under #gssoc'24.

![SwapReads - Google Chrome 12-05-2024 18_53_24](https://github.com/anuragverma108/SwapReads/assets/125184228/d2810d32-fd5d-4ab6-8ed7-b720323ba0f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
