### ISSUE TITLE
Feat: Add form to help icon

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2248]
### Describe the feature

Add the input in the help icon so that  people could send their query or doubt to us.
Also adding address and contact details to it.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/168854094/cf5ded29-b7fa-4df5-9522-1a9704bcf25f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@huamanraj Sir, please assign this issue to me.
Thank You!

**Comment by RitiChandak** [comment]
Hi @TBorundia We already have contact us section so we anyone need help he/she can contact us there 
i don't think there's a need of help icon

**Comment by TBorundia** [comment]
> Hi @TBorundia We already have contact us section so we anyone need help he/she can contact us there i don't think there's a need of help icon

@RitiChandak Mam,
this drop down already contains help icon.
what is to be added to make it functional can you suggest , I want to work on it under GSSoC'24.
![image](https://github.com/anuragverma108/SwapReads/assets/168854094/25c1f5d5-5c60-471d-a8b5-17c4c577930b)
