### ISSUE TITLE
Feat: Back to Top button

### ISSUE THREAD

**Issue by jinx-vi-0** [anuragverma108/SwapReads#225]
### Describe the feature

I propose adding a "Back to Top" button to enhance user experience and facilitate navigation on the website.

Details:
- Location: The "back to top" button will be located in the bottom-right corner of the webpage.
- Functionality: When clicked, the button will smoothly scroll the page back to the top.
- Visibility: The button will only appear when the user scrolls down the page, ensuring it doesn't obstruct content unnecessarily.
- Design: The button design will be minimalistic, blending seamlessly with the website's aesthetic.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/120160355/979c981b-a613-48c9-a70c-9603cfa514f7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , please assign this issue to me.

**Comment by Madhuri36** [comment]
@anuragverma108  I would like to work on this issue. Please assign it to me under GSSoC'24

**Comment by anuragverma108** [comment]
Assigned @jinx-vi-0
