### ISSUE TITLE
changes in the css of cookie display button

### ISSUE THREAD

**Issue by anujagarwal28** [anuragverma108/SwapReads#2255]
### Describe the feature

![old](https://github.com/anuragverma108/SwapReads/assets/113621090/36be4a1c-afbb-42fa-bffc-c3e5c57d5606)
this is the old screenshot with the issue where the cross button size is imperfect

### Add ScreenShots

![new](https://github.com/anuragverma108/SwapReads/assets/113621090/da79ade9-ca3d-406d-8653-34c6f5866ebf)
Here I have fixed the issue of the button size which was imperfect and also the text size and border radius

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anujagarwal28** [comment]
@anuragverma108 I want to work on this issue please assign it to me.

**Comment by RitiChandak** [comment]
@anujagarwal28 , the issue has not been assigned to you yet. Please do not start working on it until it is officially assigned to you.
This is the last time i am considering it

**Comment by anujagarwal28** [comment]
Okay. I didn't read the guidelines. I'll take care next time.
