### ISSUE TITLE
Feat: personal story section

### ISSUE THREAD

**Issue by nisargaa20** [anuragverma108/SwapReads#226]
### Describe the feature

After pricing section . We can add personal story section so that users can share thier views or thoughts.

Kindly assign me this issue under #gssoc'24.

### Add ScreenShots

![Uploading SwapReads - Google Chrome 12-05-2024 18_58_41.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by krati234** [comment]
assign this please
