### ISSUE TITLE
Feat:Improve the navbar of the homepage.

### ISSUE THREAD

**Issue by meetarora10** [anuragverma108/SwapReads#2260]
### Describe the feature

Navbar's alignment seems improper as the screen size reduces.Also the hamburger icon on click does not displays anything.

### Add ScreenShots

![Screenshot (564)](https://github.com/anuragverma108/SwapReads/assets/143121854/d8532032-a9dc-4c12-bced-a5793dcbda73)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@meetarora10 Assigned!
