### ISSUE TITLE
Feat: To make the settings page

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#2268]
### Describe the feature

In the setting the user will have option to change the current password, profile visibility and he can download the profile data. 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/8b08f6c8-e205-4348-9c3f-782e654ee76e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@huamanraj Please assign this issue to me

**Comment by RitiChandak** [comment]
@ayush-848 assigned

**Comment by ayush-848** [comment]
> @ayush-848 assigned

@RitiChandak it will not be a level 1 PR
will it get updated based on my work???

**Comment by RitiChandak** [comment]
yup
