### ISSUE TITLE
UI: rate us section is looking stretched vertically, n looking ugly 

### ISSUE THREAD

**Issue by Devvart1** [anuragverma108/SwapReads#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/78067388/8ca4aec4-0f43-4f73-93d6-814ca984fc21)
this can be impoved

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2262
