### ISSUE TITLE
Feat: UI Improvements Required in Login/Register 

### ISSUE THREAD

**Issue by shaanrxx** [anuragverma108/SwapReads#227]
### Describe the feature

Hello @anuragverma108 ,

When navigating the website, I noticed a few UI issues on the login/register modal that I believe need attention:

Font Consistency: The font used in the modal doesn't match the main website's font. This inconsistency might affect the user experience of the platform.

Modal Layout: The 'Register' button seems to extend beyond the expected boundaries of the modal box. 

I would like to contribute to resolving these issues. Would it be possible to be assigned to this issue?

Thank you for considering my suggestions.

### Add ScreenShots

![Screenshot 2024-05-12 143446](https://github.com/anuragverma108/SwapReads/assets/62669918/54dc63c7-ef37-4cf1-8b8c-9fbea8d3f684)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by shaanrxx** [comment]
Thank you for assigning me this!
