### ISSUE TITLE
BUG:lack of margin in literary realms page

### ISSUE THREAD

**Issue by nikhilnishadoo7** [anuragverma108/SwapReads#2270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

text is not visible due to lack of margin in literary realms page

![Screenshot 2024-06-30 235323](https://github.com/anuragverma108/SwapReads/assets/155576040/79e73cbf-5556-479f-8c30-7e08a36c67c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
i want to work on this issue please assign me ? 
@huamanraj

**Comment by RitiChandak** [comment]
it looks great to me 
![image](https://github.com/anuragverma108/SwapReads/assets/96969496/1978205e-e4e4-425f-9846-f922349e6313)
please explain what's the issue clearly

**Comment by nikhilnishadoo7** [comment]
Hi @RitiChandak,

Could you please check again, not on the home page but in the literary realms section? Thank you so much!

Best regards,
Nikhil NIshad

video-

https://github.com/anuragverma108/SwapReads/assets/155576040/7a0dc42c-9699-48c2-b903-49cb87151643

**Comment by RitiChandak** [comment]
Hi @nikhilnishadoo7 I'll contact you regarding this

**Comment by nikhilnishadoo7** [comment]
can i work on this issue @RitiChandak @huamanraj

**Comment by RitiChandak** [comment]
hi @nikhilnishadoo7 as there are 2 same pages delete one and raise the new PR
