### ISSUE TITLE
BUG: Grammatical mistake.

### ISSUE THREAD

**Issue by ParasGarg2k** [anuragverma108/SwapReads#2288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

"Settings" should be written in place of "Setting".

![Screenshot 2024-07-01 221645](https://github.com/anuragverma108/SwapReads/assets/115867501/0b6c6365-6010-4c3d-922f-f607f033fabc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
this issue already exists #2287
