### ISSUE TITLE
BUG: Enhancing the UI experience.

### ISSUE THREAD

**Issue by ParasGarg2k** [anuragverma108/SwapReads#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

UI for following buttons can be improved.
![Screenshot 2024-07-01 221846](https://github.com/anuragverma108/SwapReads/assets/115867501/863f79d5-13c8-4b7e-89ff-f4ca9cbb7772)
![Screenshot 2024-07-01 221832](https://github.com/anuragverma108/SwapReads/assets/115867501/a9cec2f6-cb1f-406d-87e1-1f56a8baabad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2286 this issue already exists
