### ISSUE TITLE
Search and filter functionality 

### ISSUE THREAD

**Issue by Dharmil03** [anuragverma108/SwapReads#229]
### Describe the feature

Would like to add search and filter functionality in backend 

### Add ScreenShots

There's no search functionality and filtering features 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Dharmil03** [comment]
thank you for assigning i have added routes for search and filter functionality now it can be used in frontend
