### ISSUE TITLE
BUG:there is no google translate button in Pricing.html page drop  down menu is different for different pages.

### ISSUE THREAD

**Issue by slytechiefrommagentashore** [anuragverma108/SwapReads#2293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

there is no google translate button in the pricing page 
![image](https://github.com/anuragverma108/SwapReads/assets/97241435/b19d0fb5-a1c3-4bc8-8554-b7cec0a9400e)
I would like to fix that and 
There are other issues like, drop down menu has different options in different pages. I'll review and check the drop down menu section for each page. I would like work on these issues 
the readlater page has no google translate button 
![image](https://github.com/anuragverma108/SwapReads/assets/97241435/ec3a511c-668c-4b8d-96a5-06f1221d9aef)

drop down menu for index 
![image](https://github.com/anuragverma108/SwapReads/assets/97241435/d60f794a-0ea3-4380-aac6-61796493c4e2)
drop down menu for read_later page 
![image](https://github.com/anuragverma108/SwapReads/assets/97241435/c5c00fe1-ff49-4678-87a7-48a58442abab)
drop down menu is different for different pages.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@slytechiefrommagentashore Assigned
