### ISSUE TITLE
BUG: Background Container is not properly taking the element

### ISSUE THREAD

**Issue by BCA-444-9758-Ketan** [anuragverma108/SwapReads#2294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-07-02 174731](https://github.com/anuragverma108/SwapReads/assets/146806880/bdbb5458-d111-420d-8b08-e821a02f6378)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ketanop321** [comment]
> @Ketanop321 please attach the ss

@RitiChandak now check it
