### ISSUE TITLE
Feat: redesign about us page

### ISSUE THREAD

**Issue by heli0707** [anuragverma108/SwapReads#2297]
### Describe the feature

Enhance the page UI to be more interactive by incorporating dynamic elements and user-friendly features. Implement animations where necessary to improve user engagement and provide a smoother experience. Assign this task to me for completion.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/07e674bc-9599-400e-a78d-00a402c3b528)

enhance the UI of this page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@heli0707 please explain in detail what kind of feature and animation you will use?

**Comment by heli0707** [comment]
https://github.com/anuragverma108/SwapReads/assets/95361125/096818c0-3719-4fa8-a3c1-39ea5451c44c

add this type of animation in the text also make 2 sides one side image and one side this type of text

**Comment by RitiChandak** [comment]
nope i don't think it will look good and other idea?
