### ISSUE TITLE
Feat: Change the whole footer and make it more interactive

### ISSUE THREAD

**Issue by heli0707** [anuragverma108/SwapReads#2298]
### Describe the feature

the footer to include interactive elements such as hover effects, expandable sections, and animated transitions. This will improve user engagement and provide a more dynamic experience.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/cb3fad74-9148-4fc8-a5b6-243f4377f652)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Hover effects have been applied to certain elements, and some include transitions.Be specific what you are going to add and where

**Comment by heli0707** [comment]
@RitiChandak 

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/95711a7c-86f4-4e0d-b85e-ac8e4d5a3a58)

I want to design this type of standard design of footer
also, the change hover effect 

https://github.com/anuragverma108/SwapReads/assets/95361125/86b33087-c842-45a7-bdc4-156852ea9ae2
something like this

**Comment by RitiChandak** [comment]
Don't change footer design but consider adding a hover effect. Ensure it is applied across the entire website to maintain uniformity and that it complements the overall website design.
