### ISSUE TITLE
Feat: Update old logo to new one in navbar on login page

### ISSUE THREAD

**Issue by heli0707** [anuragverma108/SwapReads#2302]
### Describe the feature

Update the logo on the login page to replace the old logo with the new one on the navbar. 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/95361125/19760b45-667a-491d-8311-4a00115d7ee5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@heli0707 Assigned!
Ensure all pages are checked and applied universally.
