### ISSUE TITLE
BUG:  Clicking on Contact Us in the footer section is not opening the Contact us page.

### ISSUE THREAD

**Issue by amrit03b** [anuragverma108/SwapReads#2308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 Clicking on Contact Us in the footer section is not opening the Contact us page instead it is staying on the same page and no action is performed.
It should be redirecting to Contact Us Page.  
Also I want to add some more sections/Questions in Contact Us page making it more efficient for the website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@amrit03b Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
