### ISSUE TITLE
BUG: navbar elements are not aligned properly

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Elements in the navbar section are not aligned properly. 
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/1308e455-1ceb-4c5b-b3c9-ef896f5e3443)
Home tab is very near to the logo and the spacing between each nav-element is not uniform.
I want to work on this. 
@anuragverma108 Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubhra-Narang** [comment]
Hello, I'm a GSSOC'24 contributor
I would like to work on the same. Can you please assign this to me.

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
And the website should be responsive tooo.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Madhuri36** [comment]
I tired aligning the navbar elements but due to the "SwapReads" text, proper alignment is not working. So I thought of adding "SwapReads" just below the logo. But the logo doesn't really match the website's moto and so that is why I thought of the following changes:
![logoPic](https://github.com/anuragverma108/SwapReads/assets/146222028/e1641784-010b-4072-89e1-8c6b167fa8bc)

and when I make these changes on my laptop, the nav bar elements are aligned.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/1da7652c-4494-42d7-b0f3-a4e23f3d442e)
Should I make these changes @anuragverma108 ?

**Comment by anuragverma108** [comment]
Perfect.
Raise PR

**Comment by Madhuri36** [comment]
@anuragverma108 something is wrong with the main branch.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/b8ef3f94-1f72-490d-b9d6-5ac92a094c4b)
