### ISSUE TITLE
BUG: Dark mode not working in booklist for swapping

### ISSUE THREAD

**Issue by Maana-Ajmera** [anuragverma108/SwapReads#2311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Dark mode is not working in booklist for swapping page

https://github.com/anuragverma108/SwapReads/assets/162733812/868e672b-eb5b-4ba1-9225-4bdaefb01143

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@anuragverma108 @huamanraj @RitiChandak @RishabhDhawad 

I want to work on this issue please assign it to me.

**Comment by RitiChandak** [comment]
@Maana-Ajmera This is the problem with lots of pages please correct all

**Comment by Maana-Ajmera** [comment]
@RitiChandak sure
