### ISSUE TITLE
BUG: Icon on header are overlapping each other

### ISSUE THREAD

**Issue by ananyag309** [anuragverma108/SwapReads#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 Icon on header are overlapping each other, can i fix it?
![organise](https://github.com/anuragverma108/SwapReads/assets/145869907/649e62db-1446-4b38-951e-53e65f54bbaa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@ananyag309 for which page?

**Comment by ananyag309** [comment]
@RitiChandak about us
