### ISSUE TITLE
BUG: Hover effect on `PRICING`

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#2319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is hover effect issue on pricing title

https://github.com/anuragverma108/SwapReads/assets/146806880/2c76ef0c-df63-4f7d-a5f0-248198360a16

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
pls assign me

**Comment by RitiChandak** [comment]
@Ketanop321 what you want to do remove it or correct it

**Comment by Ketanop321** [comment]
> @Ketanop321 what you want to do remove it or correct it

@RitiChandak  I want to correct it

**Comment by RitiChandak** [comment]
how?
