### ISSUE TITLE
Feat:  forgot password 

### ISSUE THREAD

**Issue by POORVI2303** [anuragverma108/SwapReads#232]
### Describe the feature

Forgot Password feature is missing, can add forgot password  and continue with google/facebook

### Add ScreenShots

![login](https://github.com/anuragverma108/SwapReads/assets/132765791/4dc5ecbb-6748-4145-934b-b5417aeaf583)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by POORVI2303** [comment]
please assign this to me

**Comment by huamanraj** [comment]
@POORVI2303  work in it!!

**Comment by roushanverma23** [comment]
Hi @POORVI2303 I want to collaborate and work on this issue. @huamanraj, please assign

**Comment by roushanverma23** [comment]
Thank you @huamanraj

**Comment by roushanverma23** [comment]
@RitiChandak From today I'm working on it  because of my exams I'm unable to focus on this side
