### ISSUE TITLE
BUG: Make Navbar and Footer Consistent And Responsive

### ISSUE THREAD

**Issue by RitiChandak** [anuragverma108/SwapReads#2321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In every page footer and navbar is not consistent 

![image](https://github.com/anuragverma108/SwapReads/assets/96969496/d0c16de7-1baa-4168-8228-64b26f4bda61)
![image](https://github.com/anuragverma108/SwapReads/assets/96969496/86e12b0c-11b8-47c4-84fe-7a69ec812747)

- Make the entire website Responsive 

This is an open issue. Anyone who is interested in working in this issue can comment on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by aarushi-taori** [comment]
I want to work on this issue

**Comment by RitiChandak** [comment]
Hi @aarushi-taori, you need to ensure the entire website is responsive.
