### ISSUE TITLE
Feat: Improve UI of the scroll bar

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#233]
### Describe the feature

As of now the scroll bar looks very basic, I want to make it appealing and match it to the website's UI. @anuragverma108 please assign me this under GSSoC'24.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/146222028/5da7f8e9-ed87-45a1-8644-6fce1c5d8f16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
