### ISSUE TITLE
BUG: Improve the color of footer elements in dark mode

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer elements in dark mode are not readable due to dark colours.
I would like to work on this. @anuragverma108 please assign this to me under GSSoC'24.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/290a7eb7-09b6-4bd8-abba-c3a61e362167)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on it!!
