### ISSUE TITLE
BUG: Login/signup page not visible properly due to the navbar.

### ISSUE THREAD

**Issue by meetarora10** [anuragverma108/SwapReads#2348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login/signup main container is not visible completely and it is overlapping with the navbar.
Assign this task to me and I can fix this issue.
![Screenshot (621)](https://github.com/anuragverma108/SwapReads/assets/143121854/338d66c4-3361-46d7-8f3e-14da3290f3b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankita685** [comment]
assign me this issue under gssoc24
