### ISSUE TITLE
BUG: about us Navbar issue

### ISSUE THREAD

**Issue by MuraliDharan7** [anuragverma108/SwapReads#2350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

Navbar is having error at showing 'More' section, there exists an image to render that near to login hyperlink.

## Screenshot

![image](https://github.com/anuragverma108/SwapReads/assets/130668745/0c66c447-b562-4065-b3cb-fa2a4acf0ba2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2321
