### ISSUE TITLE
BUG: Fix position of toogle buttons

### ISSUE THREAD

**Issue by ananyag309** [anuragverma108/SwapReads#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The toggle switch keeps of overlapping icons on header. can i fix its  position?

![toggle](https://github.com/anuragverma108/SwapReads/assets/145869907/4d99da97-7a0f-44aa-831c-7cff7404fa43)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2321
