### ISSUE TITLE
Bug: Implement a fixed size for input box

### ISSUE THREAD

**Issue by UtkarshBirla28** [anuragverma108/SwapReads#2356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

input box size is not fixed 

Uploading 05.07.2024_18.37.32_REC.mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by UtkarshBirla28** [comment]
@huamanraj sir I didn't got the points in leaderboard point's didn't got updated

**Comment by huamanraj** [comment]
> @huamanraj sir I didn't got the points in leaderboard point's didn't got updated

as mentioned there is no level for some too basic changes!! you have just added 1 line

**Comment by UtkarshBirla28** [comment]
@huamanraj are i get it but there were 2 issues naa

**Comment by huamanraj** [comment]
> @huamanraj are i get it but there were 2 issues naa 

but why the number of issues Matter? the changes you made are too basic !
