### ISSUE TITLE
BUG: Duplicate rate us card

### ISSUE THREAD

**Issue by theutkarshpatel** [anuragverma108/SwapReads#2363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two rate us cards on the website page out of which only one is functional . @anuragverma108 I want to work on this , please assign this issue to me under GSSOC'24. I will try my best!

First 'Rate Us' card (after book exchange hub) :

<img width="1426" alt="Screenshot 2024-07-06 at 12 25 28 PM" src="https://github.com/anuragverma108/SwapReads/assets/112273162/da463e6e-07b5-4483-9c60-cd52552b6300">

Second 'Rate Us' card which is not working (after contact us section )  : 

<img width="1426" alt="Screenshot 2024-07-06 at 12 25 43 PM" src="https://github.com/anuragverma108/SwapReads/assets/112273162/abebe170-ad2c-4cdb-8476-83bce00386e9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by root-0101** [comment]
Hey @anuragverma108 as the button of rate us card is also not as per the theme, It have no hover effect as other buttons have please assign me this issue
