### ISSUE TITLE
BUG: Fix all the cards to be responsive

### ISSUE THREAD

**Issue by Utsavladia** [anuragverma108/SwapReads#2365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/124615886/a8f71d31-1066-4268-9210-f11fd100e2d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2321
