### ISSUE TITLE
BUG:Footer nav list  not working in dark mode

### ISSUE THREAD

**Issue by shelar1423** [anuragverma108/SwapReads#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nav list in the footer does not change its theme when turned into dark mode:
Screenshot below:

![image](https://github.com/anuragverma108/SwapReads/assets/82649533/1498b1ab-67ad-43c9-9535-ee28352bc674)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shelar1423** [comment]
@anuragverma108 kindly add gssoc and level label to this and assign it to me ,thank you

**Comment by huamanraj** [comment]
issue is already opened in [#221](https://github.com/anuragverma108/SwapReads/issues/221)
