### ISSUE TITLE
Feat: Adding Video in About Us Section

### ISSUE THREAD

**Issue by Vin205** [anuragverma108/SwapReads#2372]
### Describe the feature

Adding a video in 'About Us' section about working of website and how easily users can make travelling plans with a help of website will improve user experience and users can easily understand website features

### Add ScreenShots

![Screenshot 2024-06-18 215845](https://github.com/anuragverma108/SwapReads/assets/138381350/db57bd62-bb78-4d40-9839-328a901e871c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
dont put video file in repo just upload on yt and embed it on about us page!!
