### ISSUE TITLE
Feat: adding join now hyperlink

### ISSUE THREAD

**Issue by shelar1423** [anuragverma108/SwapReads#238]
### Describe the feature

Adding a joiin now hyper link at the landing page which redirects to signup and login page

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/82649533/bbd32132-d976-4f49-ac28-3fa159d4fc4a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shelar1423** [comment]
@anuragverma108  kindly assign gssoc and level label to this issue and kindly assign it to me

**Comment by shelar1423** [comment]
@huamanraj

**Comment by huamanraj** [comment]
> @huamanraj 

work on it!

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
