### ISSUE TITLE
Enhancement of  UI of footer

### ISSUE THREAD

**Issue by Akshat0908** [anuragverma108/SwapReads#2385]
### Describe the feature

I recently visited the Swap Reads website and noticed an opportunity for improvement in the footer UI. The current design doesn't fully align with the site's overall aesthetic and could benefit from a more cohesive and visually appealing layout. By enhancing the footer UI, I aim to provide a more polished and user-friendly experience for visitors. Proposed improvements include aligning the footer design with the site's branding, simplifying and organizing navigation links, incorporating attractive social media icons, and ensuring the footer is responsive across all devices. Additional features like a newsletter signup form and quick contact information could add further value. These changes will make the Swap Reads website more engaging and user-friendly, reinforcing its commitment to quality and accessibility. I am eager to contribute to Swap Reads and help improve the overall user experience through these footer enhancements.

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-07-08 at 8 33 17 PM" src="https://github.com/anuragverma108/SwapReads/assets/114748641/d21aa031-1357-4918-bbf3-e4f99d1a15e0">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ManjariRathore** [comment]
please assign me this issue if it is not assigned already <3.
