### ISSUE TITLE
DOC: Adding border around chapter-cards

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#239]
### What's wrong with the existing documentation

In dark mode, all the cards look less appealing. Adding a pink margin around each card (pink because the theme is pink, suggest any other color if you want) would make it more attractive.

![pink](https://github.com/anuragverma108/SwapReads/assets/146114938/ac6bd856-b8f1-41ea-9229-8527aacc1fac)

Assign this issue to me under GSSoC '24, I already started working on this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gauravkh31** [comment]
Hey Aman! I also want to resolve the same issue, yes! if a border is added to the cards, it will look more attractive. As a UI/UX designer, i can make it more beautiful according to the user's experience, please assign the issue to me.

**Comment by huamanraj** [comment]
sorry @dishathakurata &  @gauravkh31 but  this issue is already assigned in [issue #222](https://github.com/anuragverma108/SwapReads/issues/222)
