### ISSUE TITLE
Feat: Want to enhance the page not found page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#2403]
### Describe the feature

I want to enhance the page not found page like when i opening the any other page then it is showing only a container with white background so i want to enhance it 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/118350936/a9aa4300-9372-4572-b170-87a286231b35)

like that 
![image](https://github.com/anuragverma108/SwapReads/assets/118350936/669b8247-a0ac-4543-8dd5-86fcb7181043)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!!
