### ISSUE TITLE
Mode Switching Lag and State Retention Issue

### ISSUE THREAD

**Issue by gudia18** [anuragverma108/SwapReads#2406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When switching between dark and light modes, the application exhibits lag, and upon refreshing, it does not consistently retain the selected mode.
1. Switching modes causes a noticeable lag.
2. After refreshing the page, the mode does not change as expected , it took some time  remains in the previous state then in required mode.

**Steps to Reproduce:**

1. Change the mode from dark to light or vice versa.
2. Refresh the page.

https://github.com/anuragverma108/SwapReads/assets/121204667/79041b35-11a0-4a67-8a36-64ea974517ff

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
