### ISSUE TITLE
Login text not visible

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#2411]
The content of the Login card is not properly visible

![Screenshot 2024-07-10 004931](https://github.com/anuragverma108/SwapReads/assets/142779809/052c478e-d4fc-488a-a7cf-c9c677c0f0ec)

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
