### ISSUE TITLE
BUG: Chatbot not present in About us page and login page

### ISSUE THREAD

**Issue by Riddhi162** [anuragverma108/SwapReads#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As seen from the screenshot the chatbot is absent in about us page and login page which breaks the consistency of the webiste.
![Screenshot 2024-07-10 150641](https://github.com/anuragverma108/SwapReads/assets/135015856/9585afb5-1632-4c52-8aa4-2adae1f61cba)
![image](https://github.com/anuragverma108/SwapReads/assets/135015856/8f1dd80a-a577-466a-b1dd-85ad6b46d1b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
