### ISSUE TITLE
Feat:Make the backdrop behind the privacy notice blur and Improve its UI

### ISSUE THREAD

**Issue by Riddhi162** [anuragverma108/SwapReads#2420]
### Describe the feature

We can make the background blur when the privacy notice appears to make it look more noticeable.
Its Ui can be improved by giving it some hover effect and a moving border.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/135015856/a729b17f-2d1f-4b7c-9101-d4d44fc384da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Riddhi162** [comment]
@anuragverma108 @huamanraj @RitiChandak @RishabhDhawad Please anyone assign me this task !

Thank You !

**Comment by anuragverma108** [comment]
@Riddhi162 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
