### ISSUE TITLE
Feat: Improve the UI of recommendation books and make the book 3d

### ISSUE THREAD

**Issue by Riddhi162** [anuragverma108/SwapReads#2422]
### Describe the feature

In the recommended book section we can make the book 3d and when opened the book it displays the details of the book.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/135015856/c46fcb4d-d8ed-423a-ba38-156c813ff636)
![Screenshot 2024-07-10 154206](https://github.com/anuragverma108/SwapReads/assets/135015856/59df0b4a-df82-4391-8d19-bd18d4b407ce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Riddhi162** [comment]
@anuragverma108 @huamanraj @RitiChandak @RishabhDhawad Please anyone assign me this task !

Thank You !

**Comment by anuragverma108** [comment]
@Riddhi162 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
