### ISSUE TITLE
Feat : Add a progress bar on the romantic escapes page.

### ISSUE THREAD

**Issue by meetarora10** [anuragverma108/SwapReads#2428]
### Describe the feature

Progress bar is present in home page but not on the romantic escapes page.
I can add this similar to the home page.
Kindly assign this issue to me.

### Add ScreenShots

![Screenshot (678)](https://github.com/anuragverma108/SwapReads/assets/143121854/8d717669-7bc0-4051-ac3a-50289f0b0e8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉

**Comment by meetarora10** [comment]
@huamanraj thanku for assigning.
