### ISSUE TITLE
Add new genre for phycological

### ISSUE THREAD

**Issue by mahek0620** [anuragverma108/SwapReads#2431]
### What's wrong with the existing documentation

Add new genre for phycological

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
