### ISSUE TITLE
Feat:Make changes to Login/register page

### ISSUE THREAD

**Issue by sakshii00** [anuragverma108/SwapReads#244]
### Describe the feature

The UI for the Login/Register page can be improved. Here are the changes I propose:-

- Change the font of the above text
- Change the close icon
- Make the forgot password, reset here a little more visible
- Make the register section a little bit better since the corners of login seem to be showing when it comes up as shown below

![image](https://github.com/anuragverma108/SwapReads/assets/92578876/5df2d0a9-724e-480e-b692-d8f886b6997b)

Please assign me this issue under GSSOC'24

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/92578876/cc233084-9499-4f48-b1bf-a4b5621ebaaf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshii00** [comment]
Please add label ggsoc and assign me this issue

**Comment by aditikhare16** [comment]
I am a gssoc contributor, please assign me this issue.
