### ISSUE TITLE
DOC: Adding hover effect

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#245]
### What's wrong with the existing documentation

FAQ section looking boring and less attractive. Adding hover effect will be appealing. (I chose rose pink color, you can suggest any other color if you want)

Assign this issue to me under GSSoC '24.

### Add ScreenShots

![pink](https://github.com/anuragverma108/SwapReads/assets/146114938/1047853e-e9f8-4617-9c95-03faefed82ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by ParthNakum21** [comment]
Hello @anuragverma108, I'm interested in contributing to the project by adding hover effects. Could you please assign this task to me under GSSoC with appropriate level?
