### ISSUE TITLE
BUG: Footer Issue

### ISSUE THREAD

**Issue by MuraliDharan7** [anuragverma108/SwapReads#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
 The footer differs for home page and other pages, this should be resolved and made same as home page.

## Screenshots
1. Home Page
![image](https://github.com/anuragverma108/SwapReads/assets/130668745/9ae243ca-87f0-4ef9-aa19-640e4fa22552)

2. Login/Signup page
![image](https://github.com/anuragverma108/SwapReads/assets/130668745/2171e121-208e-48e7-be25-b4fd207bf63f)

3. About us Page
![image](https://github.com/anuragverma108/SwapReads/assets/130668745/a8216123-3b0d-4105-9cd5-f6a4ea768711)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
#2321
