### ISSUE TITLE
Feat: Add Responsiveness in about page's videos+margin from bottom+ two times heading

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#2458]
### Describe the feature

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/d7c8236b-a001-498c-95cd-f9d4da175258)

![image](https://github.com/anuragverma108/SwapReads/assets/126322584/ccd20baa-061d-447d-a827-d5189bdf3df4)

**I will make this about section video responsive+ make it stylish + solve two times heading**

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@huamanraj @anuragverma108 @RitiChandak @RishabhDhawad Please assign me this task !

Thank You !

**Comment by RitiChandak** [comment]
#2321
