### ISSUE TITLE
DOC: Add automatic copyright 

### ISSUE THREAD

**Issue by dishathakurata** [anuragverma108/SwapReads#247]
### What's wrong with the existing documentation

Existing copyright is manual which needs to be changed every year. I can add automatic copyright which does not need any manual work every year.

Assign me this issue under GSSoC '24. I already started working on this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
