### ISSUE TITLE
Feat: Improving Rate us feature

### ISSUE THREAD

**Issue by MuraliDharan7** [anuragverma108/SwapReads#2472]
### Describe the feature

I would like to improve and enhance the rateus feature of this website.

### Add ScreenShots
![image](https://github.com/user-attachments/assets/f25e710b-b175-4581-a14c-683ef97d7be2)

I would add some emoji based on the rating and improving the section at the same.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@MuraliDharan7 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
