### ISSUE TITLE
BUG: Testimonials in LOL.HTML

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#2473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The review-card is overfilling its pinkish round borders.
![image](https://github.com/user-attachments/assets/d0dd1ce3-8e36-4fe8-95a5-4844ebb44b9e)
![image](https://github.com/user-attachments/assets/1f11eb5e-13d9-4c05-9c23-21a6bb9b2210)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@VijaySamant4368 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
