### ISSUE TITLE
BUG: Garbage or Repeating Code in many files

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#2474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Many of the files have a lot of repeated blocks of code, or some code that gets overshadowed immediately by some other piece of code. This patter is noticeably common in CSS files, and can be the cause for difficulties in Debugging. I can improve these files, by removing such unrequired code in CSS files.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
