### ISSUE TITLE
BUG: Improper alignment of scrolling cards

### ISSUE THREAD

**Issue by GAVINESHWAR** [anuragverma108/SwapReads#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the home at Literacy Realms section the alignment of the scrolling cards are not aligned properly, At a time 3 or 4 cards should be Visible  but 4th card is visible half of its width, It is not looking proper , makes bad  user interface. I would like resolve the bug and make  the proper alignment of cards.

![image](https://github.com/user-attachments/assets/22890a6f-7e9c-424d-b27f-06ea5a6a4092)
here starting half of the only viewed.

@anuragverma108 , assign me this issue to make contribution to the project.

Thank you 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@GAVINESHWAR Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
