### ISSUE TITLE
BUG: Text visibility of submit button in feedback form in dark mode

### ISSUE THREAD

**Issue by srilekha279** [anuragverma108/SwapReads#2477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I switched to dark mode and click on feedback, the text inside the submit button is not visible properly. 

Screenshots:

![image](https://github.com/user-attachments/assets/5af6b3f5-fecb-4673-bc1e-86b4bd669769)

 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@srilekha279 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
