### ISSUE TITLE
BUG:Book Reccomendation text cannot be Read 

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#2479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-07-13 174221](https://github.com/user-attachments/assets/76545d26-8bf2-4c65-96bc-08ed78711ede)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
pls assign it to me

**Comment by anuragverma108** [comment]
@Ketanop321 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
