### ISSUE TITLE
Feat: Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [anuragverma108/SwapReads#248]
### Describe the feature

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/50082154/127884a5-3054-4170-b8a4-f5cea19ac3b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Okay Assigned!
In the message ask everyone to star the repo.
Project Admin will assign you issue soon!

**Comment by sanmarg** [comment]
Could you please give the level considering its technicalities?
