### ISSUE TITLE
Feat: Making the 'help' Dropdown content

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#2480]
### Describe the feature

Making the 'help' Dropdown content and adding required content such as redirecting to contact form or faqs

### Add ScreenShots

![image](https://github.com/user-attachments/assets/85df2b14-d4e5-4316-b04c-a4eb67a4b21a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@huamanraj please assign this issue to me

**Comment by anuragverma108** [comment]
@ayush-848 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
