### ISSUE TITLE
BUG: `pricing` section height cannot proper 

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#2481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this project `pricing`  section cannot proper height.
- fixed to `max-height:55rem;`
- please assign me..

[Screencast from 2024-07-13 21-03-35.webm](https://github.com/user-attachments/assets/110b377c-67d1-45bd-90b4-873e24e73e77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by sivaprasath2004** [comment]
@anuragverma108 I'll add the before and after screen recording please merge the PR
