### ISSUE TITLE
BUG: THEME CHANGER POSITION NOT FIXED IN READ LATER

### ISSUE THREAD

**Issue by Gamerking177** [anuragverma108/SwapReads#2483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

THEME CHANGER POSITION NOT FIXED IN READ LATER

https://github.com/user-attachments/assets/824cf01e-0e59-478c-a9c0-f341ef1d4f12

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Gamerking177 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
