### ISSUE TITLE
Feat: Add new genre of "Satire"

### ISSUE THREAD

**Issue by PradnyaGaitonde** [anuragverma108/SwapReads#2485]
### Describe the feature

Satire uses humor and irony to critique and ridicule societal issues, aiming to provoke reflection and change through clever and often witty commentary.

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@PradnyaGaitonde Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
