### ISSUE TITLE
Feat: Want to enhance the login page

### ISSUE THREAD

**Issue by Bhumika1312** [anuragverma108/SwapReads#2486]
### Describe the feature

I want to improve the header and footer of the login page to enhance its appearance.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a78e8eec-e60e-44a7-823b-32a40f4c5207)

![image](https://github.com/user-attachments/assets/2cea3939-b2ca-4e0c-800f-af3763823aae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Bhumika1312 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
