### ISSUE TITLE
[BUG]: `About Us`  Navigation cannot proper approach

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this project `About Us` page `Navigation` cannot proper accessable .
- please assign me.

[Screencast from 2024-07-14 12-45-04.webm](https://github.com/user-attachments/assets/36d28bad-0ab3-4c8b-b381-a9487bed7400)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @sivaprasath2004 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
