### ISSUE TITLE
Make navbar goes up out of the screen when scroll up to have better view of page

### ISSUE THREAD

**Issue by Utsavladia** [anuragverma108/SwapReads#2493]
### Describe the feature

The navbar shoudl go out of screen upside when start scrolling up and should come back when start scrooling down instantly.

### See the demo of navbar below-

https://github.com/user-attachments/assets/5773b8cb-e8b8-4129-826f-ed6557dc714a

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2dd2aaa2-0b01-4f93-a6d3-25621957790a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
