### ISSUE TITLE
FIX Pricing card responsiveness to have better readability on all devices

### ISSUE THREAD

**Issue by Utsavladia** [anuragverma108/SwapReads#2494]
### Describe the feature

It should be well sized for all devicess

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9182af5a-1ad8-4649-ab53-790a85008b62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
