### ISSUE TITLE
Dark theme for dropdown too

### ISSUE THREAD

**Issue by Utsavladia** [anuragverma108/SwapReads#2495]
### Describe the feature

Dark theme should also be applied on the drop down to match the theme

### Add ScreenShots

![image](https://github.com/user-attachments/assets/00b9a28a-6686-4203-af68-444e1cc57261)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
