### ISSUE TITLE
Hover effect for cards

### ISSUE THREAD

**Issue by Bhattu-Anitha-07** [anuragverma108/SwapReads#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello PA,

The hover effect for the cards displayed in the "Pricing based on their version" and "Explore Different Genres" sections appears a little odd. I would like to make changes to the hover effect for these cards and increase the blur effect for the box shadow.

Please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Bhattu-Anitha-07** [comment]
And I want to add transition effect to the cards.
Please assign this issue to me @anuragverma108

**Comment by Bhattu-Anitha-07** [comment]
@anuragverma108 please assign this issue to me..
I will work this.

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
