### ISSUE TITLE
UI issues under Benefits section, boxes are not equal sizes

### ISSUE THREAD

**Issue by michellecordovi** [anuragverma108/SwapReads#25]
**Describe the bug**
Small UI issue, under the Benefits section, the box for Personalized Reading Experience appears larger than the rest.

**To Reproduce**
1. Go home page
2. Click on 'Benefits'
3. Minimize screen width until Benefits section is 2 columns

**Expected behavior**
All boxes would ideally be the same size for best UI/aesthetic

**Screenshots**
![swapReadsLayoutIssue](https://github.com/anuragverma108/SwapReads/assets/165519977/790eec4d-2d6a-40e7-be92-0beea4fb72fa)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser:chrome
 - Version 124.0.6367.119

**Comment by michellecordovi** [comment]
I would like to be assigned this issue to contribute to GSSOC'24. I can fix this issue

**Comment by anuragverma108** [comment]
Assigned!
