### ISSUE TITLE
Feat: Adjusting Sidebar Size for Improved Accessibility on Small Devices

### ISSUE THREAD

**Issue by dhruv389** [anuragverma108/SwapReads#250]
### Describe the feature

The feature involves adjusting the size or height of the sidebar on our website to ensure that all sections are adequately displayed, especially on small devices. Currently, the sidebar is too short to contain all options, leading to certain sections being inaccessible or hidden on smaller screens. By resizing the sidebar, we aim to improve accessibility and usability for users browsing the website on mobile devices or smaller screens.

### Add ScreenShots

![Screenshot 2024-05-13 021412](https://github.com/anuragverma108/SwapReads/assets/117587892/6f02f922-1f87-4a09-bb4d-afb3ba871cfc)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by anuragverma108** [comment]
Make sure to star the repo before working on it! Happy open-source contributing!
