### ISSUE TITLE
BUG:`navbar` in community chat page 

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#2505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Elements are getting outside of the navbar container and also it is not aligned correctly
![Screenshot 2024-07-16 003229](https://github.com/user-attachments/assets/a05ebb57-a390-4bd5-8740-3d290075f72d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
