### ISSUE TITLE
Feat: Enhancing Navbar Design and Adjusting Size with Border Radius

### ISSUE THREAD

**Issue by dhruv389** [anuragverma108/SwapReads#252]
### Describe the feature

The feature entails revamping the design of the navbar to make it more visually appealing and engaging. This includes implementing changes to the size and border radius to enhance the overall aesthetic and user experience. By enhancing the navbar design, we aim to create a more attractive and modern appearance that aligns with the website's theme and enhances navigation for users.

**Please assign me this issue**

### Add ScreenShots

Now Looks Like :
---
![image](https://github.com/anuragverma108/SwapReads/assets/117587892/cd2f5ef5-5d6a-42bc-8b7a-7cbff54bf799)

After Changes It will look like:
---
![Screenshot 2024-05-13 022410](https://github.com/anuragverma108/SwapReads/assets/117587892/bc0045b4-f95c-447c-8fb6-8c0b03f5992d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @dhruv389 
Make sure to star the repo before working on it! Happy open-source contributing!
