### ISSUE TITLE
BUG: footer alignment and size is different in pages

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#2523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer is not same in all pages
![Screenshot 2024-07-17 184111](https://github.com/user-attachments/assets/0a5b5f9e-8630-4d80-b65d-a0bd6afc07bd)
![Screenshot 2024-07-17 184041](https://github.com/user-attachments/assets/9270a8f7-6ef0-4f48-9804-acf43d72da34)

i will make all the footer same and also improve its UI with suitable colors

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
