### ISSUE TITLE
Feat: Logout 

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2526]
### Describe the feature

Adding Logout pop-up or page while logout icon is clicked and making it responsive too.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/425c2827-9186-492f-9102-6192bc8c575c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@anuragverma108 @huamanraj Sir,
Please assign this issue to me under GSSoC'24.
Thank You!

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. 
i am the project mentor you can reach out to me for any help!
Happy open-source contributing! 🎉
