### ISSUE TITLE
Feat:add genre of "Musical"

### ISSUE THREAD

**Issue by AmruthaPariprolu** [anuragverma108/SwapReads#2537]
### Describe the feature

Musical: A genre in which songs sung by the characters are interwoven into the narrative, often involving dance sequences.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
`WARNING` : you have created multiple similar issues this comes under SPAMING the issues so please close all of your issues and create a single issue for all changes otherwise we have to take some action!!
