### ISSUE TITLE
Feat:add genre of "autobiography"

### ISSUE THREAD

**Issue by AmruthaPariprolu** [anuragverma108/SwapReads#2538]
### Describe the feature

Autobiography: A non-fiction account of a person's life written by that person, offering personal insight and reflection on their experiences.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by UtkershBasnet** [comment]
I would like to work on this issue
