### ISSUE TITLE
Feat: Addition of a Live chat feature

### ISSUE THREAD

**Issue by Helios-snd** [anuragverma108/SwapReads#254]
### Describe the feature

Monitor and chat with the visitors on your website

### Add ScreenShots

I''ll Provide it in due time 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
 Make sure to star the repo before working on it! Happy open-source contributing!
