### ISSUE TITLE
BUG: The nav-bar of Login page

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#2550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nav-bar of the login page is very different, and worse than the home page. There should be consistency
Home Page:
![image](https://github.com/user-attachments/assets/75e1730a-7d8c-49f5-8af7-0f1949a20452)

Login Page:
![image](https://github.com/user-attachments/assets/3894904b-79c0-4a84-a440-3fc080fb6e7f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@huamanraj can you please kindly tell the reason for closing this issue?

**Comment by huamanraj** [comment]
> @huamanraj can you please kindly tell the reason for closing this issue?

this issue is solved now by someone else!
