### ISSUE TITLE
BUG: Profile Page is showing a default user details 

### ISSUE THREAD

**Issue by mehrun171** [anuragverma108/SwapReads#2583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Without logging in or signing up the profile section is showing some xyz user Profile which should be resolved
assign me this issue @anuragverma108 
![Screenshot 2024-07-21 131006](https://github.com/user-attachments/assets/623cf054-a068-4ceb-bc93-89065f335aa5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sachan13harshit** [comment]
@anuragverma108 @huamanraj
Kindly assign this issue to me
