### ISSUE TITLE
BUG: Seperating Javascript and styles form index.html

### ISSUE THREAD

**Issue by Kiran-pande-30** [anuragverma108/SwapReads#2585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. The index.html page is filled with Scripts and CSS, making index.js difficult to ready.
2. Would like to clean the code in the index.html, separating scripts and css.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mayank1365** [comment]
@Kiran-pande-30 please assign this issue to me

**Comment by Kiran-pande-30** [comment]
@huamanraj , Can u please assign this issue to me.

**Comment by huamanraj** [comment]
> @huamanraj , Can u please assign this issue to me.

work on this but please make sure any components and pages should not get broken or affected and take care of readability
