### ISSUE TITLE
BUG: fix back-to-top button

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#2592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are multiple pages for which back to top button is not visible properly

![Screenshot 2024-07-21 170404](https://github.com/user-attachments/assets/59859f5e-dd4a-4dd2-b02d-bd3d80bffee0)
![Screenshot 2024-07-21 170425](https://github.com/user-attachments/assets/1c98d392-2832-43ce-8a9f-be25f141d440)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanadas45** [comment]
I can help in solving this issue. Please assign it to me.
