### ISSUE TITLE
BUG: The Instagram icon on the footer of various pages is redirecting users to Home Page instead of Instagram.

### ISSUE THREAD

**Issue by PRASANNA-THE-PRASANN1** [anuragverma108/SwapReads#2597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Instagram icon in the social media section of various pages currently links to the home page of the website instead of directing users to the correct Instagram profile.
I will update the link, so that it directs to correct place.
Kindly assign this issue to me @anuragverma108 @huamanraj 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Indrajeety993648** [comment]
@PRASANNA-THE-PRASANN1  I  would like to solve this issue  please  assign it to me
