### ISSUE TITLE
BUG: "Your Price (50% Off)" inproper box spacing

### ISSUE THREAD

**Issue by jain-anshika** [anuragverma108/SwapReads#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Kindle assign this issue to me i would like to work on this issue!!

![image](https://github.com/anuragverma108/SwapReads/assets/115166105/ae25e599-a4dc-4498-8093-27a59522bdad)

The currency drop down box has inproper spacing in Book Exchange Hub section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by dhruv389** [comment]
Hello @anuragverma108 ,

**can you tell me that what is meaning of level1 ,level2 , level3 tags on issues , and what is benefits to solve it???**

**Comment by jain-anshika** [comment]
Before- The dropdown menu had unexpected black border which was looking odd, I also adjusted the padding.

![image](https://github.com/anuragverma108/SwapReads/assets/115166105/9c5da9ee-cd65-4ca7-aea2-3ad976f1f6c8)

After-  Now the animation effect looks more accurate.

![image](https://github.com/anuragverma108/SwapReads/assets/115166105/83d5226a-f603-470c-8727-fca489528f57)
