### ISSUE TITLE
Feat: Better Hamburger, that works

### ISSUE THREAD

**Issue by VijaySamant4368** [anuragverma108/SwapReads#2603]
### Describe the feature

The hamburger right now looks very ugly, and doesn't even works. I can make a much better Hamburger menu.

### Add ScreenShots

Current Hamburger
![image](https://github.com/user-attachments/assets/5931b8cc-14c7-4ab9-b2fd-a7680976f646)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@anujagarwal28 @huamanraj please check this out

**Comment by VijaySamant4368** [comment]
Something like this:

https://github.com/user-attachments/assets/db4578fe-9dc6-4331-a48e-3aafa7afa3f7

**Comment by VijaySamant4368** [comment]
@anujagarwal28 @huamanraj please check this out

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
