### ISSUE TITLE
Feat: Optimise the community chat 

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#2604]
### Describe the feature

Hello @anuragverma108 , I would like to optimise the community chat section and correct the images linked to the page. Iwould like to add loader when a user is typing and want  to change UI.                                                                                                                                      

Kindly assign me this issue under GSSoC'24. I'll do my best.

### Add ScreenShots

![Screenshot 2024-07-23 012255](https://github.com/user-attachments/assets/e0e59167-0a4a-4f51-9464-e868db4f61dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!

**Comment by Dilpreet0501** [comment]
Sure Sir
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. i am the project mentor so you can always reach out to me for any need!! Also, please star the repo and do share on socials before working on it. Happy open-source contributing!

**Comment by Dilpreet0501** [comment]
Hello @RitiChandak , @huamanraj , There is some problem with chat section, it is not able to authenticate firebase. Kindly guide me  regarding this.  As I can't optimise chat section without authentication as it is not visible.

![Screenshot 2024-08-02 010606](https://github.com/user-attachments/assets/6cb96703-c5d5-4a77-b9fb-91b6c529c9cc)

**Comment by huamanraj** [comment]
just try to change css and dont so anything with html classes and ids! if still not works then leave for now!!

**Comment by Dilpreet0501** [comment]
Okay Sir
