### ISSUE TITLE
BUG: Dark Mode Title Color on Book Recommendation Page

### ISSUE THREAD

**Issue by Monika5S** [anuragverma108/SwapReads#2605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the book recommendation page the color of "Trending books" and "book recommendation" title is not changing in dark mode which is inconsistent from the dark mode UI design. 
I can work on resolving this issue.

In Light Mode
<img width="506" alt="image" src="https://github.com/user-attachments/assets/2778c581-a7b6-48ce-8a26-714f5d36a1a8">

<img width="640" alt="image" src="https://github.com/user-attachments/assets/ab6fd660-a1a7-4bd2-8864-55ea06568d49">

In Dark Mode
<img width="626" alt="image" src="https://github.com/user-attachments/assets/7250ab1e-a9a1-4bc3-9b70-06b86cb72d5b">

<img width="650" alt="image" src="https://github.com/user-attachments/assets/b713d029-24e8-451c-a658-52c513dc3cfb">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanadas45** [comment]
I can help in solving this issue. Please assign it to me.

**Comment by huamanraj** [comment]
Assigned! @Monika5S 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!

**Comment by huamanraj** [comment]
> I can help in solving this issue. Please assign it to me.

hey ,
the issue creator wants to work on this issue so 
you can create your own issue then i will assign that to you!
