### ISSUE TITLE
Enhance Rate Us 

### ISSUE THREAD

**Issue by sailaja-adapa** [anuragverma108/SwapReads#2606]
### Describe the feature

Hello Project Admin
I would like to Enhance Rate us container so that instead of Stars I will add Emojis and also hover Effect and Toastify Message tooo
Can you assign me this issue under GSSOC'24  @anuragverma108 

### Add ScreenShots

![IMG_20240723_113532](https://github.com/user-attachments/assets/e5654abf-0b0c-41f2-8391-c621bf12de48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
