### ISSUE TITLE
Allignment of Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [anuragverma108/SwapReads#2608]
### Describe the feature

Hello Project Admin
I would like to Allign Navbar Perfectly so that it will Enhance User Experience
As you can see in below image it is not perfectly Alligned I will move it to Right side
Can you assign me this issue under GSSOC'24 @anuragverma108 

### Add ScreenShots

![IMG_20240723_113615](https://github.com/user-attachments/assets/f269cf4d-3cdb-4f9b-8067-820830774850)

![IMG_20240723_113545](https://github.com/user-attachments/assets/6407ba25-d13e-411b-afff-0533eccaff42)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
