### ISSUE TITLE
[Feature]: `/profile` page cannot proper responsive

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#2609]
### Describe the feature

- In this project `/profile` page mobile site it cannot proper responsive, because the container will be used on the `fixed `.
- please assign me.

### Add ScreenShots

[iPhone-13-PRO-vermillion-sunshine-40461e.netlify.app-kGEoI1qqog.webm](https://github.com/user-attachments/assets/058b42b6-9108-4bcf-a3a2-951779ddd7e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
