### ISSUE TITLE
Feat: "Literary Realms we've covered" animation enhancement of card component

### ISSUE THREAD

**Issue by jayesh2474** [anuragverma108/SwapReads#261]
### Describe the feature

Add animation in card component for better look when we hover on this.
Please assign this issue me to under Gssoc'24 , i would like to work on this

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/115784462/65260c50-ea2e-4bc8-8abe-bf26278465af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
