### ISSUE TITLE
BUG: Unnecessary  image on about us page

### ISSUE THREAD

**Issue by ImmidiSivani** [anuragverma108/SwapReads#2612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Those 2 images(book lover,myprofile) are unnecessary here which are covering  the content.I would like to remove this 2 images.
![image](https://github.com/user-attachments/assets/972b9bc8-a360-44a9-b094-c3e15f52a132)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanadas45** [comment]
I can help in solving the issue of unnecessary images on the about page.

**Comment by Sanjanadas45** [comment]
@ImmidiSivani please assign this to me.

**Comment by huamanraj** [comment]
Assigned! @ImmidiSivani 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
