### ISSUE TITLE
Feat: The footer links not visible 

### ISSUE THREAD

**Issue by CoderGirl2844** [anuragverma108/SwapReads#2616]
### Describe the feature

The footer links are not visible in dark mode. Please assign me this issue

### Add ScreenShots

![Screenshot 2024-07-24 011355](https://github.com/user-attachments/assets/dfa7a12c-fecd-40a7-8b23-467efd68b123)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
