### ISSUE TITLE
Feat: Email validation should be added

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [anuragverma108/SwapReads#2618]
### Describe the feature

In email part there should be '@' and 'gmail.com'

### Add ScreenShots

![Screenshot 2024-07-24 144418](https://github.com/user-attachments/assets/3cd06cbf-500f-472c-852f-870d13d048a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SarthakPaandey** [comment]
Kindly assign this issue to me.

**Comment by Ishitamukherjee2004** [comment]
@anuragverma108 @huamanraj Please assign this issue

**Comment by huamanraj** [comment]
Assigned! @Ishitamukherjee2004 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
