### ISSUE TITLE
Feat:Additon of page refresher

### ISSUE THREAD

**Issue by Anjaliavv51** [anuragverma108/SwapReads#2619]
### Describe the feature

To refresh the page incase. Below the preview.

### Add ScreenShots

https://github.com/user-attachments/assets/887442d1-c073-4f8d-b465-05eb4a3395bf

@huamanraj please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjaliavv51** [comment]
@huamanraj please attach level label 2 if u like the feature

**Comment by huamanraj** [comment]
> @huamanraj please attach level label 2 if u like the feature

will update after PR review

**Comment by Anjaliavv51** [comment]
@huamanraj please review the PR.
