### ISSUE TITLE
DOC: Adding table of contents and featured in section to readme

### ISSUE THREAD

**Issue by SpaciousCoder78** [anuragverma108/SwapReads#262]
### What's wrong with the existing documentation

We can add a table of contents section to make navigation of docs easier as well as my feature recommendation is to add a featured in section to show the open source programmes that this project got featured in.

I worked on the same issue on other projects of gssoc too and I can do this work under 15 minutes if I'm assigned to this task under GSSoC 24

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/88923986/e0cffb9a-e1a1-403f-b503-13d03f56280e)

I can add something like this to the readme

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
