### ISSUE TITLE
Feat:Add Google Language Translator

### ISSUE THREAD

**Issue by codercake** [anuragverma108/SwapReads#2629]
### Describe the feature

One challenge I've noticed is the language barrier that many readers face when exploring books and content in different languages. To make the platform more inclusive, adding the Google Language Translator can effortlessly translate book descriptions, reviews, and other content into your preferred language. This makes SwapReads.com a more welcoming and accessible place for book lovers around the world, breaking down language barriers and enriching the reading experience for everyone.

### Add ScreenShots

NOT REQUIRED. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by codercake** [comment]
@anuragverma108 kindly look at this specific feature request!

**Comment by huamanraj** [comment]
Assigned! @codercake ! but make sure it must be user friendly and good designed! 
also 
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
