### ISSUE TITLE
BUG:   Center Donation Card on the Donate Books to School Page

### ISSUE THREAD

**Issue by sachan13harshit** [anuragverma108/SwapReads#2637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The donation card on the "Donate Books to School" page appears to be off-center, which affects the overall aesthetic and user experience of the page. The card should be horizontally centered on the page to create a more balanced and visually appealing layout.

**Expected Behavior**
The donation card should be horizontally centered within the viewport, creating a balanced and visually appealing layout.

**Actual Behavior**
The donation card is currently not centered, which detracts from the overall look and feel of the page.

**Screenshot**
![image](https://github.com/user-attachments/assets/f2e39062-f17e-4421-a4d8-bcabfc0a0cb0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sachan13harshit** [comment]
@anuragverma108 @huamanraj
Kindly assign this issue to me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
i am the project mentor so you can always reach out to me for any need!! 
Also, 
please star the repo and do share on socials before working on it. 
Happy open-source contributing!
