### ISSUE TITLE
BUG:Login Page NavBar does not follow theme

### ISSUE THREAD

**Issue by shelar1423** [anuragverma108/SwapReads#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login page nav bar in dark mode does not switch its theme .

screenshot:

![image](https://github.com/anuragverma108/SwapReads/assets/82649533/8d6c88a3-e747-4422-b966-6eddba1288dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shelar1423** [comment]
@huamanraj kindly assign this issue to me and add gssoc and level label ,thank you

**Comment by tikaram1912** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by lassmara** [comment]
Please assign me this issue.
