### ISSUE TITLE
Feat:  Include blogs and articles 

### ISSUE THREAD

**Issue by Vin205** [anuragverma108/SwapReads#2643]
### Describe the feature

Include book-related blog and articles to inspire and motivate users  to develop a better reading culture. 

### Add ScreenShots

![Screenshot 2024-06-14 221113](https://github.com/user-attachments/assets/d8e19407-8d60-4e31-9420-dde6107f1652)
![Screenshot 2024-06-14 221055](https://github.com/user-attachments/assets/acc40d1c-b378-4dcd-8c50-f4679b8d97cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Vin205 Assigned
