### ISSUE TITLE
Feat:  Include Author Spotlights  

### ISSUE THREAD

**Issue by Vin205** [anuragverma108/SwapReads#2644]
### Describe the feature

Include feature authors with interviews, articles, and reading recommendations. This will improve the learning community of swapreads.

### Add ScreenShots

![Screenshot 2024-06-14 221055](https://github.com/user-attachments/assets/7c637a03-f366-48de-98b7-96042a4eab3a)
![Screenshot 2024-06-14 221113](https://github.com/user-attachments/assets/61f86e6a-6ff1-4706-a4a1-b0f61570e454)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @Vin205
