### ISSUE TITLE
BUG: Buy now button not visible on hover

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

on hovering over the buy now button the text inside the button is not visible

![Screenshot 2024-07-27 021905](https://github.com/user-attachments/assets/20cbb62f-6946-4945-baab-cd50cc1f2de7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @root-0101
