### ISSUE TITLE
Feat: Improve the Navbar DropDown in the Mobile View

### ISSUE THREAD

**Issue by suraj-9849** [anuragverma108/SwapReads#265]
### Describe the feature

on exploring this website I saw it in the mobile view then I noticed that the The Toggle button (light/Dark) is not visible perfectly so I would like to fix it . So can u please assign this to me under @gssoc'24 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/146669517/832bad94-86e7-47cf-9585-fb0372ff8f09)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv389** [comment]
this issue already taken and assigned #250 , first always confirm the issue in issue list already mentioned or not.
