### ISSUE TITLE
Feat: Interactive quizzes and challenges

### ISSUE THREAD

**Issue by Vin205** [anuragverma108/SwapReads#2653]
### Describe the feature

Include Interactive quizzes on various literary topics to engage users for an engaging platform and learning community.

### Add ScreenShots

![Screenshot 2024-06-14 221055](https://github.com/user-attachments/assets/93d9d9c5-94f5-403e-952b-9c45ed1b87c4)
![Screenshot 2024-06-14 221113](https://github.com/user-attachments/assets/780b6257-c8cd-4184-be5a-820b45e5d329)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @Vin205
