### ISSUE TITLE
BUG: Links issue

### ISSUE THREAD

**Issue by gollaanusha249** [anuragverma108/SwapReads#2656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Footer for the buttons Instagram,facebook and github the links are not provided properly.
And also in main page the 3 buttons instagram,facebook,youtube, the links are not placed correctly where they should go.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gollaanusha249** [comment]
@anuragverma108  Please assign me this issue

**Comment by anuragverma108** [comment]
Assigned @gollaanusha249
