### ISSUE TITLE
BUG: Ph Number validation should be added

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [anuragverma108/SwapReads#2659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-07-27 192732](https://github.com/user-attachments/assets/31174915-7313-445a-9c39-22ec40e7e98d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjanaynvsdl** [comment]
Hey @Ishitamukherjee2004 can you please assign this issue to me

**Comment by anuragverma108** [comment]
Assigned @Ishitamukherjee2004
