### ISSUE TITLE
Feat:Complete redesiginig of Ratings page

### ISSUE THREAD

**Issue by shelar1423** [anuragverma108/SwapReads#266]
### Describe the feature

adding a better and complete UI completely changing the current one 

1. adding proper nav bar
2. images
3. clean look
4. better color scheme

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/82649533/685d9212-1ffc-46e6-a72e-12dcf85d8e1c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shelar1423** [comment]
@huamanraj kindly assign this to me and lable it under level 3 gssoc as the whole page needs to be changed,thank you

**Comment by shelar1423** [comment]
hey @huamanraj if you could assign it to me i can start working on it , thank you ,also  add the gssoc label as well as level 3 for this as whole design needs to be changed

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
