### ISSUE TITLE
BUG: Literary realms not responsive

### ISSUE THREAD

**Issue by nagalakshmi08** [anuragverma108/SwapReads#2671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cards in Literary realms are not responsive. In smalls , full width is not appearing.

![image](https://github.com/user-attachments/assets/2b7ffa1c-afd3-4006-9af5-c8d1f978a971)

Please assign me this issue. I want to contribute to this project under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @nagalakshmi08
