### ISSUE TITLE
BUG: Heading for genres is not centered.

### ISSUE THREAD

**Issue by nagalakshmi08** [anuragverma108/SwapReads#2672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The heading for genres section is not in center for large screens.

![image](https://github.com/user-attachments/assets/91aa5519-c570-47ab-a59b-ead4f68a1bbf)

Please assign me this issue. I would like to contribute to this project under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Jash2606** [comment]
Hey @anuragverma108 I would like to work on this issue. It would be great if you could assign me to this issue. Thanks.
