### ISSUE TITLE
Add new genre True Crime.

### ISSUE THREAD

**Issue by Vaishnavigunti2801** [anuragverma108/SwapReads#2673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello PA,
Adding new genre True Crime based on true stories like documentaries . Basically users like to read and shows interest on true stories.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaishnavigunti2801** [comment]
@anuragverma108 
Please assign me the task .

**Comment by UtkershBasnet** [comment]
I'd like to resolve this issue
