### ISSUE TITLE
BUG: The subscribe button is not functional

### ISSUE THREAD

**Issue by samarsajad** [anuragverma108/SwapReads#2676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The subscribe button for the news letter in the footer section is not working. I would like to add an email container and add functionality to subscribe button

https://github.com/user-attachments/assets/69d4672f-e1a6-4466-951e-477f34fb7645

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Please assign this issue to me @anuragverma108

**Comment by anuragverma108** [comment]
Assigned @samarsajad
