### ISSUE TITLE
Feat: Improve Cookie Consent Container

### ISSUE THREAD

**Issue by kosuri-indu** [anuragverma108/SwapReads#2682]
### Describe the feature

Improving the cookie consent container which appears on the left bottom section

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f63cd5e4-f43d-47e5-b6b8-d5868f1e5865)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @kosuri-indu
