### ISSUE TITLE
BUG: Contact Us page UI issue

### ISSUE THREAD

**Issue by amit429** [anuragverma108/SwapReads#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The contact us form not very user friendly right now with no proper input boxes getting displayed.
Only the place holders are getting displayed but not the input boxes as such. It looks like text on the website and doesn't give any UI experience of the form
![image](https://github.com/anuragverma108/SwapReads/assets/68067897/e6a2915d-9ff8-4f7d-83c2-7301d7421108)

i would like to restructure the ui to get a more better form filling experience for the user.
I am a GSSOC'24 contributor , please assign me this issue so i can start the UI design

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amit429** [comment]
@anuragverma108 please assign me this issue

**Comment by aditikhare16** [comment]
I am a GSSOC contributor, I humbly request you to please assign this issue to me.

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this !
