### ISSUE TITLE
Feat: To Add Two more different Genres

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/SwapReads#2692]
### Describe the feature

Hi @anuragverma108  

There are total 19 genres in Genre Section . I want to add two more genres. Kindly assign me it under GSSOC'24

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9a7140bf-21cb-48ad-903f-76b88085ec86)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
