### ISSUE TITLE
Feat: To Add More Unique Different Genres

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/SwapReads#2695]
### Describe the feature

There genres like Cyberpunk so I want to add them and make it more ellaborative.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ce335ce0-f226-4663-9e92-43891ba994bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @PriyaGhosal

**Comment by anuragverma108** [comment]
Good Work @PriyaGhosal
