### ISSUE TITLE
Feat: To Create a New Web Page - "Motto of SwapReads"  

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/SwapReads#2697]
### Describe the feature

Hi @anuragverma108 ,

I am  planning to create a new webpage dedicated to describing the vision and motto of SwapReads.com. To enhance the user experience and clearly communicate our mission, we need to add a link to this new page in the footer of our website.

**Details:**

- **Link Text:** "Our Vision"
- **URL:** [Insert URL for the new vision page]
- **Footer Location:** Add this link to the footer of the homepage and all other relevant pages.
- **Purpose:** The new page will detail the motto and vision behind SwapReads.com, emphasizing our commitment to connecting book enthusiasts and fostering a community where readers can exchange books and share literary adventures.

**Acceptance Criteria:**

- The new link should be clearly visible and well-integrated into the footer.
- The URL should direct users to a newly created page that contains a description of our website’s motto and vision.
- Ensure the link design aligns with the current footer style and overall website aesthetics.

**Additional Notes:**

Please coordinate with the team responsible for content creation to ensure that the new page accurately reflects our website’s vision and motto.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/cff7ad08-9db1-4935-aa7b-3b5fe5765174)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @PriyaGhosal
