### ISSUE TITLE
BUG: Center Donation Card on the Donate Books to Library Page and Organisation page 

### ISSUE THREAD

**Issue by sachan13harshit** [anuragverma108/SwapReads#2706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The donation card on the "Donate Books to School" and "Donate books to Organisation" page appears to be off-center, which affects the overall aesthetic and user experience of the page. The card should be horizontally centered on the page to create a more balanced and visually appealing layout.

**Expected Behavior**
The donation card should be horizontally centered within the viewport, creating a balanced and visually appealing layout.

**Actual Behavior**
The donation card is currently not centered, which detracts from the overall look and feel of the page.

**Screenshot**
![Screenshot from 2024-07-30 19-15-51](https://github.com/user-attachments/assets/5ef72584-4595-44b0-bef8-ccc54977cc05)
![Screenshot from 2024-07-30 19-17-18](https://github.com/user-attachments/assets/586f47c5-5698-4f01-a771-3f17f3156b06)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sachan13harshit** [comment]
@anuragverma108 @huamanraj
Kindly assign this issue to me

**Comment by RitiChandak** [comment]
this issue is already assigned to someone else

**Comment by sachan13harshit** [comment]
@RitiChandak that issue for  Center Donation Card on the Donate Books to School page. This is a different issue
