### ISSUE TITLE
BUG: FAQ in  all pages of literary realms are not visible

### ISSUE THREAD

**Issue by samarsajad** [anuragverma108/SwapReads#2709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

FAQs in  all pages of literary realms are not visible. Only the heading is visible
![image](https://github.com/user-attachments/assets/9f98f66a-69e4-4877-9911-2d71f7c592a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Please assign this issue to me @anuragverma108

**Comment by RitiChandak** [comment]
@samarsajad assigned
