### ISSUE TITLE
Improvement the hover effect on nav tabs and change the UI of swapreads to look more attractive 

### ISSUE THREAD

**Issue by ankitgupta143** [anuragverma108/SwapReads#271]
### Describe the feature

I want to work on the UI and hover effect of button and UI
I am GSSoC contributor
@anuragverma108 please assign the Issue

### Add ScreenShots

![Screenshot 2024-05-13 111146](https://github.com/anuragverma108/SwapReads/assets/114281117/3a8b5e04-0be4-49d2-a9b0-1aea6483c886)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
