### ISSUE TITLE
BUG: the picture in my profile and its menu is not visible 

### ISSUE THREAD

**Issue by samarsajad** [anuragverma108/SwapReads#2710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/d32f9de6-e5c9-4641-938a-dc4fc1e792bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@samarsajad Assigned
