### ISSUE TITLE
BUG: Fix dark mode of login page

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#2712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/f7270e31-ab0b-4667-8ee0-ea6d7fbab327)
dark mode not applied

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned @sau-mili

**Comment by vivi2004** [comment]
Hey  @anuragverma108   I wants to contribute in  login page  of dark mode   Would please assign me the work so that I can contribute in itn
