### ISSUE TITLE
BUG: Contact section not working 

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#2737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108 , The contact section is not working properly as on clicking send button  it is showing message length less than 50 even the message length is 250 words.  I would like to work on this issue, and also would like to work on sending email through email js.

Also would like to change the contact section  styling.
Kindly assign me this issue under GSSoC'24. I'll do my best.

**Screenshot**

![Screenshot 2024-08-02 151925](https://github.com/user-attachments/assets/42ef3f1b-97df-410b-9d33-b4db184c70a8)

For contact section - I can style it like this , with image changing over time

![Screenshot 2024-08-02 160459](https://github.com/user-attachments/assets/2a5c2042-d5b7-42ab-b73c-a9ccaadf683a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dilpreet0501** [comment]
Hello @huamanraj ,which email should i use for making account in email.js?

**Comment by huamanraj** [comment]
> Hello @huamanraj ,which email should i use for making account in email.js, also email.js will verify the email?


just write the code i will enter the keys !

**Comment by Dilpreet0501** [comment]
> > Hello @huamanraj ,which email should i use for making account in email.js, also email.js will verify the email?
> 
> just write the code i will enter the keys !

Okay Sir
