### ISSUE TITLE
Feat: Adding Google Authentication using Firebase

### ISSUE THREAD

**Issue by Ojas-Arora** [anuragverma108/SwapReads#2746]
### Describe the feature

@anuragverma108 @huamanraj I want to add Google Authentication using Firebase. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9a06c2cf-f93d-429e-8d46-b7669447f323)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ojas-Arora** [comment]
@huamanraj @anuragverma108 I have alreday done the same  in the previous PR i.e https://github.com/anuragverma108/SwapReads/pull/2752   and This is assigned after that so kindly increase the level of that PR or assign some level to this PR. Thank u

**Comment by Ojas-Arora** [comment]
@huamanraj From assigning the issue level sir I will not get any points. Should I make a random Pr and get level from it so that I can get points for the same?

**Comment by huamanraj** [comment]
> @huamanraj From assigning the issue level sir I will not get any points. Should I make a random Pr and get level from it so that I can get points for the same?
> 

you will get the score of that pr! and this is the issue for that previous pr so why you need to have 2 pr?

**Comment by Ojas-Arora** [comment]
@huamanraj Actually sir I had made 2 issues adding google authentication and  adding facebook authentication but due to mistake I added both the authentications in the same issue Pr that's why I am asking for that . If you don't think this issue to  be provided any level pr then no issue. Thanks Sir.

**Comment by huamanraj** [comment]
> @huamanraj Actually sir I had made 2 issues adding google authentication and  adding facebook authentication but due to mistake I added both the authentications in the same issue Pr that's why I am asking for that . If you don't think this issue to  be provided any level pr then no issue. Thanks Sir.

you got the point as PR complexity! 
please share that pr number i want to review!

**Comment by Ojas-Arora** [comment]
https://github.com/anuragverma108/SwapReads/pull/2752

And Sorry Sir Again for that mistake.

**Comment by huamanraj** [comment]
> @huamanraj 
> https://github.com/anuragverma108/SwapReads/pull/2752
> 
> And Sorry Sir Again for that mistake.



its okay but go and edit the title of the PR i have leveled it as L3!

**Comment by Ojas-Arora** [comment]
@huamanraj Ok sir Thank u very much
