### ISSUE TITLE
BUG:Alert box for reset password

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- When you go to login page and reset password and enter an email never registered it still says: 
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/29d1ba21-cafe-4752-add3-a5497930a090)

- It should prompt an alert saying no user exists with that email.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by Stiffpixels** [comment]
I am working on it.
