### ISSUE TITLE
Feat:Hover effect on the connect with a reader button

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#277]
### Describe the feature

A hover effect on the button will make it more eye catching to the visitors and help locate the form more easily increasing number of swap readers.

### Add ScreenShots

* current version: 
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/54a53103-60dd-4cb9-9c1d-ea632815219b)

* something like this but not limited to this could be added:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/dc60e73a-8d9e-4458-aedf-4fe3970ccd28)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> A hover effect on the button will make it more eye catching to the visitors and help locate the form more easily increasing number of swap readers.
> 
> 
> 
> ### Add ScreenShots
> 
> * current version: 
> ![image](https://github.com/anuragverma108/SwapReads/assets/32983571/54a53103-60dd-4cb9-9c1d-ea632815219b)
> 
> * something like this but not limited to this could be added:
> ![image](https://github.com/anuragverma108/SwapReads/assets/32983571/dc60e73a-8d9e-4458-aedf-4fe3970ccd28)
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it!
