### ISSUE TITLE
Feat: Add a review box

### ISSUE THREAD

**Issue by aditikhare16** [anuragverma108/SwapReads#279]
### Describe the feature

Users can give reviews on the book which might be helpful for the new readers.
Please assign me this issue.

### Add ScreenShots

Giving reviews on books is very helpful amongst the readers. It will help them know about the book better.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by Hitesh4278** [comment]
Hi, @anuragverma108  can you assign this issue to me as I have already worked on this feature on my personal project?

**Comment by aditikhare16** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

Sir I have developed this feature, and will update you ASAP after adding a few enhancements!

**Comment by chitraa-cj** [comment]
if this issue is still open I would like to work on it
