### ISSUE TITLE
Feat: Add discord link to footer

### ISSUE THREAD

**Issue by srilekha279** [anuragverma108/SwapReads#2796]
### Describe the feature

I would like to request the addition of a Discord channel link to the footer of the website, alongside the existing social media icons. This will provide users with easy access to Discord server, which is a valuable platform for community engagement and interaction.

### Add ScreenShots

![Screenshot (923)](https://github.com/user-attachments/assets/80af85df-4092-4b24-84fc-49056990fd47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
we dont have a server !
