### ISSUE TITLE
An Interactive And UI Friendly Pop-Up when clicked on Connect with a reader section

### ISSUE THREAD

**Issue by nishantharkut** [anuragverma108/SwapReads#28]
**Is your feature request related to a problem? Please describe.**
⇾ Problem : I'm, As a viewer, it is completely not visually appealing that such a nice UI website gives a very unaesthetic pop-up which degrades the website.
![Image](https://github.com/anuragverma108/SwapReads/assets/156298209/74ab36cc-d606-4921-8454-d0fe0001acba)

**Describe the solution you'd like**
I would make a completely Aesthetic Pop-up for this section and various other sections that enhances these websites for users.

**Describe alternatives you've considered**
As an Alternative, we can remove the Connect with the reader button when the user clicks on it when submitting and then display "Thank you for your interest".
![image](https://github.com/anuragverma108/SwapReads/assets/156298209/355b067f-c8ad-4fb0-a379-4932eeb93500)

**Comment by anuragverma108** [comment]
Issue already created!
