### ISSUE TITLE
on dark mode some part is not visible 

### ISSUE THREAD

**Issue by Reshma-2301** [anuragverma108/SwapReads#280]
### Describe the feature

hello sir ! i have visited your website and if i do the dark mode then some parts is not visible ...i want to change that .....please assign @anuragverma108  that task to me 

### Add ScreenShots

![dark mode](https://github.com/anuragverma108/SwapReads/assets/162494882/cb5b1829-6246-429b-ab7c-c9b2f9dcab6e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tikaram1912** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
