### ISSUE TITLE
BUG: Increase the Size of Social Media Icons on Mobile View

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#2800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The social media icons appear too small on mobile devices, making them difficult to see and interact with. The size of these icons should be increased for better visibility and user experience on mobile viewports.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by charanbhatia** [comment]
@Saksham2k3s i want to work on this. Please assign to me.
