### ISSUE TITLE
BUG: Enhance Slider Left/Right Buttons in Client Review Section

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#2801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current left and right buttons in the client review section's slider are not visually appealing and may be difficult to use. Enhance these buttons to improve their design, size, and responsiveness for a better user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
