### ISSUE TITLE
BUG: "Get in Touch" Text in Contact Section Not Visible on Dark Mode

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Get in Touch" text in the contact section is not properly visible when the website is in dark mode. Adjust the text color or background to ensure it is easily readable for users in dark mode.

![get](https://github.com/user-attachments/assets/49770303-9cb0-49ff-bf43-d71f2e306e24)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
