### ISSUE TITLE
Feat:Audio Book Support

### ISSUE THREAD

**Issue by Vin205** [anuragverma108/SwapReads#2812]
### Describe the feature

Integrate audiobook support, allowing users to listen to books directly on the platform.

### Add ScreenShots

![Screenshot 2024-06-14 221055](https://github.com/user-attachments/assets/5fbb34a7-2f1a-46b4-b0bc-4bc2f441fc7f)
![Screenshot 2024-06-14 221113](https://github.com/user-attachments/assets/bd659f8e-c1fe-493e-b7d7-9aa3a19ad302)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by charanbhatia** [comment]
@sanjay-kv please assign to me

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!   @Vin205
