### ISSUE TITLE
BUG: align the community spotlight page with the main website

### ISSUE THREAD

**Issue by samarsajad** [anuragverma108/SwapReads#2815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/38de77f8-a71b-4a74-9df8-fe974d097257)
This is not aligned with the theme of the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Please assign this issue to me @anuragverma108

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
