### ISSUE TITLE
BUG: fixing Navbar (community spotlight and profile )

### ISSUE THREAD

**Issue by Anshuaman2001** [anuragverma108/SwapReads#2817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BUG: community spotlight and profile  are overlapping each other  at navbar
[
![Screenshot 2024-08-09 004828](https://github.com/user-attachments/assets/bf4f3366-ad5d-444f-9f93-b74bb2292a4d)
]

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by singhshikha01** [comment]
please assign me this issue i can fix this

**Comment by Anshuaman2001** [comment]
I submitted my pr
