### ISSUE TITLE
BUG: Improve Footer

### ISSUE THREAD

**Issue by kosuri-indu** [anuragverma108/SwapReads#2818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Improves the footer by fixing the alignment and placing
![image](https://github.com/user-attachments/assets/87c54bc7-c02c-4468-81ec-206758d9e6ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
