### ISSUE TITLE
Feat: Adding genres.

### ISSUE THREAD

**Issue by aditikhare16** [anuragverma108/SwapReads#282]
### Describe the feature

Books come in a variety of genres - fiction, thriller, etc. Users should be able to filter and access books as per their preference.

### Add ScreenShots

While uploading book information, genres should be added too so that the new readers can filter according to their interests. 
Additionally, users should be able to search by their preferred authors. There can be sections such as - books for kids, old people, religious books, study books, etc. Its about categorizing books for different ages, according to genres, authors, etc. Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Work on it!! @aditikhare16 

i am the mentor of the project reach out for any help!!

**Comment by aditikhare16** [comment]
> Work on it!! @aditikhare16
> 
> i am the mentor of the project reach out for any help!!

Thank you so much sir for the opportunity.

**Comment by lassmara** [comment]
Please assign me this issue.
