### ISSUE TITLE
Feat: Enhance the look of Feedback Form in Dark-Mode

### ISSUE THREAD

**Issue by kashvi9** [anuragverma108/SwapReads#2822]
### Describe the feature

The feedback form in Dark mode doesn't go well with the dark theme.

Hello PA @anuragverma108 ,
I can alter the colors of this form according to the dark mode theme if assigned this issue under GSSOC24.
Thank You!

### Add ScreenShots

Here's how it looks,
![image](https://github.com/user-attachments/assets/0805ac1c-4194-4772-8abe-11a4eebcdb22)
![image](https://github.com/user-attachments/assets/b2ba6f58-ea8d-44ee-a65a-34c75a061378)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
