### ISSUE TITLE
Feat: Community Spotlight Page issue

### ISSUE THREAD

**Issue by TBorundia** [anuragverma108/SwapReads#2823]
### Describe the feature

Adding similar header and footer like main page.
Improving UI to match website theme.
Making page responsive too.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ffdc5790-dd36-48a9-bcb7-d3c5668c5958)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@huamanraj @anuragverma108 Sir, 
Can you please assign this issue to me under GSSoC'24. Thank You!

**Comment by huamanraj** [comment]
assigned 👍
