### ISSUE TITLE
added toast for notification

### ISSUE THREAD

**Issue by Dharmil03** [anuragverma108/SwapReads#283]
### Describe the feature

added a toast feature for notification on login ,register and while reset password and previously it was just alert 

### Add ScreenShots

![Screenshot (67)](https://github.com/anuragverma108/SwapReads/assets/115447681/84b7d315-d6e5-4e58-ad34-bc6fed0ce9ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dharmil03** [comment]
assign me this @anuragverma108

**Comment by Sonalisngr** [comment]
@huamanraj , i want to work on the issue #283 under Gssoc2024

**Comment by huamanraj** [comment]
> @huamanraj , i want to work on the issue #283 under Gssoc2024

work on it but take care of the theme and design and responsive page!

**Comment by Dharmil03** [comment]
@huamanraj i had made a made pull request of same @anuragverma108 has rejected that It was not assigned by a project admin

**Comment by Dharmil03** [comment]
Done
