### ISSUE TITLE
Feat: Create a checkout page that opens on clicking buy now option in home page

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#2831]
### Describe the feature

When buy now is clicked, this page will open

### Add ScreenShots

Will add once done

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
