### ISSUE TITLE
BUG: previous and next button is overlapping at cards

### ISSUE THREAD

**Issue by singhshikha01** [anuragverma108/SwapReads#2833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when images are scrolling the buttons are lie over the image

https://github.com/user-attachments/assets/57fcae86-b8e7-4176-96b2-eb8292546e11

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
