### ISSUE TITLE
BUG: Scroll Indicator disappearing while scrolling

### ISSUE THREAD

**Issue by Sourabh782** [anuragverma108/SwapReads#2835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While scrolling the scroll indicator on the top disappears

https://github.com/user-attachments/assets/adfc6ea0-ecdb-4591-abee-11b019ad637d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Sourabh782** [comment]
Sure @huamanraj
