### ISSUE TITLE
Feat: notification for user login or subscribing to any social media platform in return get coupons(like 10%off)

### ISSUE THREAD

**Issue by Chelseasingla1** [anuragverma108/SwapReads#284]
### Describe the feature

I would like to add a feature before going through website user get to login or subscribing to social media platform to get in return coupons like 10% off etc.

### Add ScreenShots

Something like this:
![image](https://github.com/anuragverma108/SwapReads/assets/129886894/efa3c308-3ab9-4547-ba4a-abc651a7f26c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
> ### Describe the feature
> I would like to add a feature before going through website user get to login or subscribing to social media platform to get in return coupons like 10% off etc.
> 
> ### Add ScreenShots
> Something like this: ![image](https://private-user-images.githubusercontent.com/129886894/329967538-efa3c308-3ab9-4547-ba4a-abc651a7f26c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODY4ODQsIm5iZiI6MTcxNTU4NjU4NCwicGF0aCI6Ii8xMjk4ODY4OTQvMzI5OTY3NTM4LWVmYTNjMzA4LTNhYjktNDU0Ny1iYTRhLWFiYzY1MWE3ZjI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNzQ5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTlmZTU1YjE0MzQzNzZjODBhMjA2MDI2Zjk4MTJmZjBiZjQ4YTM5NDA4ZDAwODc1ZWJlNWU4ZTExZTBiZWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sRv58v4P1anzecEbsR4gCVoHBhhcH13WPgrr_dPekMM)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Please assign me this issue under GSSoC'24.

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Chelseasingla1** [comment]
> Assigned! Make sure to attach before & after screenshots in your PR and include the issue number. Also, please star the repo before working on it. Happy open-source contributing!

@anuragverma108 okay sir Thankyou for assigning this issue and i have already star the repo
