### ISSUE TITLE
social media icon animation's time should be same.

### ISSUE THREAD

**Issue by crazyshrut** [anuragverma108/SwapReads#2852]
### Describe the feature

The time of animation is fast in sticky left panel than the footer, it should be same for better user experience.

### Add ScreenShots

Video for reference:
 
[Screencast from 2024-08-15 17-05-23.webm](https://github.com/user-attachments/assets/26e7a517-1f67-4289-99e5-f0aa31035a1a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by crazyshrut** [comment]
hey @anuragverma108, I would like to work on this issue kindly assign this to me.

**Comment by SatyaJaiss** [comment]
@sanjay-kv, I would like to contribute to this project to fix error, kindly assign it to me.

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108 - Project Admin & (ur github id) - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
