### ISSUE TITLE
BUG:Play now button is not working

### ISSUE THREAD

**Issue by Riteshkrdivedi** [anuragverma108/SwapReads#2853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in the home screen a play button is present but it is not working . whatever its functionality is maybe a bg song or something else but it is not clickable and not working

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prvn-kumar01** [comment]
hey @Riteshkrdivedi , I would like to fix this issue Please assign it to me

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024 and gssoc-ext

**Comment by sailaja-adapa** [comment]
@Pariyul create new issue on this
