### ISSUE TITLE
Feat: Improving the User Experience and Website flow.

### ISSUE THREAD

**Issue by atharvamulam** [anuragverma108/SwapReads#2855]
### Describe the feature

There are many styling issues and bugs in the website such as a seperate div was created which was not getting used and the alignment of Contact cards and closing the translate modal was not proper. I have fixed all these issues with necessary changes. I have also identified many routes in the website that lead to a completely different page and are not connected with the main website and provide almost no functionality. I am interested on working on them as well. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/621028dc-b6fb-4f52-a57c-d475bca8063e)
![image](https://github.com/user-attachments/assets/8d234460-4f48-4237-acf0-24526eebcfa5)
![image](https://github.com/user-attachments/assets/d4e17ec9-9909-4f96-a298-991c4de6999d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by darshitdudhaiya** [comment]
hey @atharvamulam i explored your project and also having some better ui changes in that which can help to improve the user experince in your site can you assign me the issue so i can do contribute in it and please add hacktoberfest lable in that issue.

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
