### ISSUE TITLE
Feat:Updating the navbar and contact us.

### ISSUE THREAD

**Issue by ankurrrrr7** [anuragverma108/SwapReads#2858]
### Describe the feature

Changing the design of the navbar and the the contact us form to make it user friendly

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fb6b6b73-e19c-4157-a97e-06289bb2b689)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankurrrrr7** [comment]
@anuragverma108 assign please

**Comment by monishkumardvs** [comment]
can u assign me

**Comment by Swarali1107** [comment]
would like to contribute for improving navbar...can you please assign me
