### ISSUE TITLE
BUG:Allowing special characters in the password field can lead to client-side injection attacks, such as XSS, which poses a security vulnerability

### ISSUE THREAD

**Issue by pand-coder** [anuragverma108/SwapReads#2860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description:
The password field currently allows the input of special characters (e.g., `<`, `>`, `<script>`), which can lead to client-side injection attacks like Cross-Site Scripting (XSS). This poses a security risk as it allows malicious scripts to be executed on the client side.

### Expected Behavior:
Special characters such as `<`, `>`, and `script` tags should be disallowed in the password field to prevent injection attacks.

### Actual Behavior:
Special characters are allowed, and malicious scripts can be executed.

### Fix:
- I would like to incorporate proper javascript Input Handling to prevent this type of client side injection or cross scripting attack

**Please assign me this issue as i would like to contribute regarding this issue with respect secure aspects of coding principles**

### Screenshot:
![image](https://github.com/user-attachments/assets/7246bb6e-09e8-4849-96fb-95ece642e5f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Charul00** [comment]
i liked it can you please assigned to me

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
