### ISSUE TITLE
BUG: Unsuitable White Bar Visible

### ISSUE THREAD

**Issue by Shahid6174** [anuragverma108/SwapReads#2861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/bcbcbcbb-bc72-44bd-84ad-88846c14ca67)

There is a white horizontal container with a cross symbol below **Rate Us** container and above **Contact Us** container.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shahid6174** [comment]
Assign me this issue

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
