### ISSUE TITLE
Feat:Add the discord logo in the footer 

### ISSUE THREAD

**Issue by Risheendra183** [anuragverma108/SwapReads#2862]
### Describe the feature

In the footer there is no discord logo and the all icons are in one color but instagram is not in same color 
please assign me @pa

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c609c101-f824-4aaa-bdb6-5c6a8d37466c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by smog-root** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24

**Comment by Acrto3Hil3** [comment]
@Risheendra183 Hii can you assign this issue to me??
