### ISSUE TITLE
BUG: Accidental Page Refresh Due to Hover Action on Hanging Book Icon

### ISSUE THREAD

**Issue by rahmathkhasim** [anuragverma108/SwapReads#2863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the profile page is opened, if the mouse accidentally hovers over the hanging book icon (which is currently functioning as a page refresher), the website refreshes automatically without any user action. This can disrupt the user experience, especially if it happens unintentionally.

suggest fix:
The book icon should be repositioned to avoid accidental hovering, or it should only trigger a page refresh when clicked, not on hover.
![Screenshot 2024-10-01 220513](https://github.com/user-attachments/assets/c42b8f2d-c4f2-4b72-a096-5fe5dc3968c0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rahmathkhasim** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by rahmathkhasim** [comment]
Thankyou for assigning . i will start working on this

**Comment by rahmathkhasim** [comment]
I submitted a pull request. Could you please review it and let me know if I did it correctly?
