### ISSUE TITLE
BUG: Unnecessary Arrows on Both Sides of the Picture

### ISSUE THREAD

**Issue by rahmathkhasim** [anuragverma108/SwapReads#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are unnecessary arrows visible on both the left and right sides of the image in the UI, which are not needed and clutter the design. These arrows don't seem to serve any functional purpose and can confuse the user. This affects the visual appearance of the page and might distract users from the main content.

suggested fix:
Remove the unnecessary arrows from both sides of the image to improve the design and user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rahmathkhasim** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24

**Comment by devarsheecodess** [comment]
Please assign this to me with gssoc-extd label. i can do this for you

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by rahmathkhasim** [comment]
Thankyou !! i will be working on this immediately.
