### ISSUE TITLE
BUG: Translation Box Remains Visible After Language Selection

### ISSUE THREAD

**Issue by rahmathkhasim** [anuragverma108/SwapReads#2865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a user selects a translation language, the translation box remains visible until the cross mark is clicked. Ideally, the box should disappear immediately after a language is selected to avoid unnecessary clutter and improve user experience.

Suggested Fix:
Automatically hide the translation box once the user selects a language, without requiring them to manually click the cross mark.
![Screenshot 2024-10-01 221608](https://github.com/user-attachments/assets/051f0189-82ae-41d6-95b0-ebc70e63628a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rahmathkhasim** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by rahmathkhasim** [comment]
Thankyou ..i will be working on it !!
