### ISSUE TITLE
BUG: Improve navbar text and styling 

### ISSUE THREAD

**Issue by shivamy009** [anuragverma108/SwapReads#2866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

make navbar item text more interactive and make navbar sticky

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Devanshu1603** [comment]
please assign it me under gssoc extended

**Comment by Uhalatha5** [comment]
Hi, I would love to work on this issue as a GSSOC'24 contributor! Could you please assign it to me? I'll make sure to improve the navbar text and styling as required. Thanks!

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?
