### ISSUE TITLE
BUG: Chatbot and Translate icons overlaps with each other

### ISSUE THREAD

**Issue by Vd7905** [anuragverma108/SwapReads#2867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="429" alt="vermillon" src="https://github.com/user-attachments/assets/4ae31511-7bd5-4afd-b561-4b6003e9f268">
The chatbot and translate icons overlaps this can be fixed to make the overall ui better.
@anuragverma108 could you assign this to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
