### ISSUE TITLE
BUG:dropdown symbol in Frequently asked questions section 

### ISSUE THREAD

**Issue by Bhanuprakash842** [anuragverma108/SwapReads#2868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dropdown symbol in the frequently asked questions section is not centered in the Questions Boxes.
![Screenshot 2024-10-02 000041](https://github.com/user-attachments/assets/bc04a4fa-b8d4-4278-a00d-6258e653172a)
I would be grateful if you consider this issue and assign to me.My github username @Bhanuprakash842 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
