### ISSUE TITLE
Feat: Book Search & Filters

### ISSUE THREAD

**Issue by shreyaslal** [anuragverma108/SwapReads#287]
### Describe the feature

This feature helps users find books available for swapping by letting them search by title, author, or genre. They can refine their search by selecting genres or age ranges, and filter books by publication year. The interface is user-friendly, with easy-to-use dropdown menus and input fields.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143954783/bcc9ece4-2756-4beb-9ae4-b86861e6fa7d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyaslal** [comment]
Please assign me this issue as GSSoC'24 contributor @anuragverma108 @huamanraj

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
