### ISSUE TITLE
BUG : Drop-down option button not working 

### ISSUE THREAD

**Issue by Devanshu1603** [anuragverma108/SwapReads#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we are clicking on dropdown button more it's not showing the listed options

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Devanshu1603** [comment]
please assign this me under gssoc so the i could fix this issue.

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?

**Comment by Codersweta7** [comment]
@sailaja-adapa 
Please assign this issue to me

**Comment by sailaja-adapa** [comment]
@Codersweta7 @Pariyul  work on new issues since it is already assigned

**Comment by Codersweta7** [comment]
@sailaja-adapa Is there any issue which is kept untouched or something on which I can work upon

**Comment by sailaja-adapa** [comment]
Work on responsiveness of get in touch page when viewed on mobile @Codersweta7

**Comment by Codersweta7** [comment]
@sailaja-adapa 
Hii I think the pages are already responsive if some page is left please let me know

**Comment by Codersweta7** [comment]
@sailaja-adapa 
Is there anything else I can do in your repository ...
Please suggest me something 🙂

**Comment by sailaja-adapa** [comment]
I think all issues taken up

**Comment by Codersweta7** [comment]
@sailaja-adapa 
I got one thankyou for being active

**Comment by sailaja-adapa** [comment]
Welcome @Codersweta7
