### ISSUE TITLE
Feat:Problem with visitors count

### ISSUE THREAD

**Issue by Saketh1714** [anuragverma108/SwapReads#2873]
### Describe the feature

The visitor count is always changing when we refresh it the count should be the same when we refresh.

### Add ScreenShots

Before refresh
![Screenshot 2024-10-02 110359](https://github.com/user-attachments/assets/341a275a-2588-45e3-92d6-6f03bc525cb0)
After refresh
![Screenshot 2024-10-02 110409](https://github.com/user-attachments/assets/7a34d0c3-1268-48b8-8c59-f830294dfa34)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saketh1714** [comment]
Can you please this issue to me

**Comment by Saketh1714** [comment]
no its by mistake

**Comment by Saketh1714** [comment]
Can you please assign this issue under GSSOC extd'24

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
