### ISSUE TITLE
BUG: overlapping text and icons on homepage

### ISSUE THREAD

**Issue by dalvishruti14** [anuragverma108/SwapReads#2874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![overlapping text](https://github.com/user-attachments/assets/b8622787-0412-424b-9199-a9bb6b22676a)
social media icons are overlapping with text.
I would like to work on this issue
@anuragverma108 please assign it to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
