### ISSUE TITLE
Feat: Book Exchange hub 

### ISSUE THREAD

**Issue by Vivisteria11** [anuragverma108/SwapReads#2877]
### Describe the feature

the UI of the feature does not look very appealing ,I would like to improve the UI.

### Add ScreenShots

![Screenshot 2024-10-02 144817](https://github.com/user-attachments/assets/140f749d-9d15-4bc7-bd1f-0b8382422c1c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vivisteria11** [comment]
I would like to work on the issue

**Comment by sailaja-adapa** [comment]
Thanks for creating the issue in *SwapReads*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXT. 2024*! 🎉  
Don't forget to follow @anuragverma108  - Project Admin & @sailaja-adapa  - Project Mentor on GitHub for more updates.

Happy open-source contributing! 🚀
