### ISSUE TITLE
Bug Report: Community Section Footer Alignment

### ISSUE THREAD

**Issue by Shiv13jm** [anuragverma108/SwapReads#2885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Report: Community Section Footer Alignment

**Description:**
The footer section in the community section has improper alignment for quick links, social media icons, and the newsletter signup. This misalignment gives the footer an unprofessional and cluttered appearance.
![Screenshot 2024-10-02 194339](https://github.com/user-attachments/assets/93dcc031-67de-4651-8add-7229a3dd5f71)

1. Navigate to the community section of the website.
2. Scroll down to the footer section.
3. Observe the alignment of the quick links, social media icons, and newsletter signup.

**Expected Behavior:**
The footer should have a clean and professional layout with properly aligned elements:
- Quick links should be neatly organized.
- Social media icons should be evenly spaced.
- The newsletter signup should be clearly positioned.

**Actual Behavior:**
The footer elements are misaligned, making the section look weird and unprofessional.

**Proposed Fix:**
I will update the footer section to improve the alignment:
1. Organize quick links into a neat list.
2. Ensure social media icons are evenly spaced.
3. Properly position the newsletter signup form.

**Labels:**
- bug
- gssoc24
- hactoberfest
- enhancement

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ADeshmukh80** [comment]
Please assign this task to me

**Comment by sambedan1** [comment]
Issue: The Community Section footer is misaligned, causing inconsistencies in the overall design.
Proposed Fix:
Review and adjust the alignment of elements within the Community Section footer for a more cohesive look.
Ensure that all text, icons, and links are evenly spaced and properly aligned with other sections of the footer.
Test the adjustments across different screen sizes to ensure consistency and responsiveness.

**Comment by Bhavya445** [comment]
hi i want to work on this

**Comment by Harshitraaaj** [comment]
assign this role to me , I think i fix this issue . Also kindly  add hactoberaccepted label

**Comment by Kawaljeet-943** [comment]
I would like to work on this issue as part of GSSoC Extended 2024 and Hacktoberfest. Please assign me this issue if it's available. I will ensure to fix the footer alignment as described.

**Comment by Sarthakkashyapp** [comment]
Hi @anuragverma108 I would like to work on this issue

**Comment by Kaif9999** [comment]
hi , I have done a few projects like this and have a good command in frontend, I would like to work on this issue kindly assign me to this under gssoc-ext, level1

**Comment by Kavish-Paraswar** [comment]
I would like to work on this

**Comment by momithalasya** [comment]
I would love to take on this task to ensure the footer has a clean and professional layout. Please let me know if you can assign this to me.
Thank you for your time, and I look forward to your response!
Regards.

**Comment by Avansh2006** [comment]
Hii @anuragverma108 !!
I have read your requirements and I understand what you want to be updated. 
I want to work on this issue, Please assign me the issue...
