### ISSUE TITLE
Make SignUp/Login Page responsive

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#29]

**Comment by kanikaa-3018** [comment]
please assign me this issue for GSSoc'24

**Comment by anuragverma108** [comment]
Assigned

**Comment by Sahil21dev** [comment]
Dear Authors , I request to work over this issue as i'm aware of the codebase very well. Please assign this issue to me .

**Comment by urgetolearn** [comment]
hello @anuragverma108 can i please collaborate with the assigned person to work on this issue, I can work on this issue

**Comment by anuragverma108** [comment]
Any Updates @kanikaa-3018

**Comment by kanikaa-3018** [comment]
sorry sir, not right now, ill send the PR soon
