### ISSUE TITLE
BUG: Alignment issue in contact us and address section 

### ISSUE THREAD

**Issue by iking07** [anuragverma108/SwapReads#2906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-03 113311](https://github.com/user-attachments/assets/75d4e5dc-3a7d-4c1c-97c4-ba759569f3b4)

Also the address section is causing cluttering in the right side of the page in this section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vishal1078** [comment]
i also want to work on this issue please assign it to me as well
