### ISSUE TITLE
BUG:Align Social Media and GitHub Icons in a Single Row on Login Page

### ISSUE THREAD

**Issue by kundana29** [anuragverma108/SwapReads#2908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the login page, the social media icons (LinkedIn, Facebook, X, Instagram, YouTube) are placed in one row, while the GitHub icon is positioned separately below. For a more consistent and visually appealing design, all icons should be aligned in a single row. This adjustment will enhance the overall layout and user experience.

![Screenshot 2024-10-03 123125](https://github.com/user-attachments/assets/ce733b8e-687b-4a57-a671-fc49a5824ad3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ark0078** [comment]
hi,I'm a contributor in GSSoc'24 extnd program and i can fix this issue.Can you assign me this?

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?
