### ISSUE TITLE
Event page theme does not match to website them 

### ISSUE THREAD

**Issue by anuza08** [anuragverma108/SwapReads#2918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the event page layout is plain and does not go with the website theme.

![{DC5EAE33-4ADA-47CB-BFF3-8E812B44A4E3}](https://github.com/user-attachments/assets/ef6a9eeb-5090-44c2-af4b-6ca2b2f7c73f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024 and gssoc-ext
