### ISSUE TITLE
Feat: the visitor icon is overlapping with the price card .

### ISSUE THREAD

**Issue by shubhamjh15** [anuragverma108/SwapReads#2923]
### Describe the feature

the visitor icon is overlapping with the price card and its an design issue

### Add ScreenShots

![Screenshot 2024-10-03 230957](https://github.com/user-attachments/assets/fec76f81-17d7-466a-8747-4841a3605c98)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?
