### ISSUE TITLE
BUG :Icon Overlap Issue

### ISSUE THREAD

**Issue by AnuragPrasad003** [anuragverma108/SwapReads#2926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have identified a bug where the Translate and Chat icons are overlapping on the website. This overlap not only affects the visual layout but also hinders user experience, making it difficult for users to interact with these features effectively.

![Screenshot (301)](https://github.com/user-attachments/assets/d559c93c-c1c9-4b0b-8789-04b928492aa1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?
