### ISSUE TITLE
BUG: logout  page not working properly

### ISSUE THREAD

**Issue by PREM-A261** [anuragverma108/SwapReads#2931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the logout page is not appers properly
![image](https://github.com/user-attachments/assets/8a045d49-8ac9-479f-b75c-7076c3ffabc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Janhavi078** [comment]
i want to work with this project under gssoc 24 ext can you assign me this @anuragverma108
