### ISSUE TITLE
BUG: Redesign of NavBar

### ISSUE THREAD

**Issue by Gaurav075** [anuragverma108/SwapReads#2933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I think the navbar is not up to the mark. I will redeign it and make it look more attractive. Assign this issue to me @anuragverma108 
![Screenshot (320)](https://github.com/user-attachments/assets/6692e90e-ef9d-4b68-954a-36b15a5f03ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Samyak137** [comment]
Shall I do it?
