### ISSUE TITLE
ADD social links In the left side SOCIAL media icons

### ISSUE THREAD

**Issue by pankajsaini1** [anuragverma108/SwapReads#2934]
### Describe the feature

I want to add social media links in the left side social media icons present in the site.

### Add ScreenShots

![{9984F880-D6B9-48B3-8378-EC19A55E4A7A}](https://github.com/user-attachments/assets/1fc460ad-9b0d-4de5-acf7-2e1e8efa649e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?
