### ISSUE TITLE
BUG: Excessive padding on the left side of images in the cards on the free e-books page

### ISSUE THREAD

**Issue by BaraniVA** [anuragverma108/SwapReads#2936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is too much padding on the left side of the images in the cards on the free e-books page. This causes the images to appear misaligned and affects the overall visual appeal and user experience of the page.

Steps to Reproduce
Navigate to the free e-books page on SwapReads.com.
Observe the padding on the left side of the images in the cards.
Expected Behavior
The images should have minimal padding on the left side, aligning properly within the cards.

Actual Behavior
The images have excessive padding on the left side, causing them to appear misaligned.

Additional Information
This issue impacts the visual alignment of the page.
It may affect user engagement due to the misaligned images.

![image](https://github.com/user-attachments/assets/a3b7121e-5925-4b58-9123-cfe99cb9c653)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ark0078** [comment]
Hi,Can you please assign this issue to me?
