### ISSUE TITLE
BUG: Validation of email is not there in "Write me anything"

### ISSUE THREAD

**Issue by divyalaldinani** [anuragverma108/SwapReads#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/82147067/ef0a280a-25aa-4149-ae13-ea4cd2374009)
Message sent successfull even if the email is not valid.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by divyalaldinani** [comment]
@anuragverma108

**Comment by anuragverma108** [comment]
@divyalaldinani 

Assigned!

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by divyalaldinani** [comment]
> @divyalaldinani
> 
> Assigned!

actually i created a pr 2 days ago and you closed it becoz ui of alert box(becoz i didn't add css) was not good, should i create another one adding some css.

**Comment by ParthNakum21** [comment]
Hello @anuragverma108, I'm interested in contributing to the project by email validation. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by RitiChandak** [comment]
@divyalaldinani any updates

**Comment by divyalaldinani** [comment]
Your repo is giving PR run failed everytime I raise a PR and I don't know how to solve that

**Comment by divyalaldinani** [comment]
is there any project mentor for this project? and can you tag him here?

**Comment by RitiChandak** [comment]
yes there are project mentor and i am one of  them

**Comment by RitiChandak** [comment]
whats the error

**Comment by divyalaldinani** [comment]
> whats the error

![image](https://github.com/anuragverma108/SwapReads/assets/82147067/2dbccb42-57e5-4c70-9b9e-56a7942d99cd)

**Comment by RitiChandak** [comment]
@divyalaldinani i don't think so it will create problem while raising the pr

**Comment by divyalaldinani** [comment]
> @divyalaldinani i don't think so it will create problem while raising the pr

tbh i opened 2 PR in this repo and none of them got merged coz both of them had issues, so idk if anything will solve it
