### ISSUE TITLE
BUG: footer section icons in home page

### ISSUE THREAD

**Issue by Bhanuprakash842** [anuragverma108/SwapReads#2946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There should be some gap between the subscribe button and icons because they are overlapping when hovered.The problem is shown in below screenshot.
![image](https://github.com/user-attachments/assets/b177aec6-121d-4ab5-a289-049c736938c3)
I would be grateful if you consider this issue and assign to me.My github username @Bhanuprakash842

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivam8112005** [comment]
bro i have already opened this issue before you
