### ISSUE TITLE
BUG: Lack of Login/Signup before a reader connects with another reader to exchange a book.

### ISSUE THREAD

**Issue by divyalaldinani** [anuragverma108/SwapReads#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/8969421a-24c2-4320-8118-c566ebb461a5)

Suppose i am the one who wants to exchange a book with someone, my data(email/password) is not saved in the site and i submit the form for exchange of a book named '3 mistakes of my life', **how will you be able to contact me**, if someone is interested to exchange my book. Thus, **login/signup is mandatory** before a user can fill for "EXCHANGE OF A BOOK"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @divyalaldinani 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by divyalaldinani** [comment]
I am thinking of adding an alert box if user fills the form 'book exchnage hub' correctly and is not logged-in, in that alert box, we will display 'Log In/Signup to continue' and there will be two button 'Continue', and 'Cancel', if he clicks on continue, then we will redirect it to login/signup page, else if he clicks on 'Cancel' we will go back to the section 'book exchange hub'
