### ISSUE TITLE
The footer is incomplete without the website logo

### ISSUE THREAD

**Issue by kanduru-abhiram** [anuragverma108/SwapReads#2963]
### Describe the feature

Hi @anuragverma108 ,

The footer is incomplete without the website logo. Lemme try adding the logo to the website by adding the logo in the place of Website title text.

Kindly assign me this issue under Hacktoberfest 2024.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7ec22fd7-efa3-4f5f-bf65-c90cd944515b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kanduru-abhiram** [comment]
I'm also a Contributor of GSSoc 2024. Please add labels of gssoc2024, thanks for accepting my contribution.

**Comment by sailaja-adapa** [comment]
@kanduru-abhiram  gssoc extd  label will be enough
