### ISSUE TITLE
Improve About page

### ISSUE THREAD

**Issue by Pushpa472** [anuragverma108/SwapReads#2974]
@anuragverma108 we have to keep padding for more better appearances.
Please assign me and add labels
![image](https://github.com/user-attachments/assets/0205bb30-1426-4e90-9281-e33c5777bbe2)

**Comment by Pushpa472** [comment]
Can i start the work

**Comment by Pushpa472** [comment]
Please also add gssoc, hacktoberfest

**Comment by AbhinabPalei** [comment]
Can you please assign me this issue @anuragverma108

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024 and gssoc-ext
