### ISSUE TITLE
BUG:Can add a border in email address in the footet

### ISSUE THREAD

**Issue by monishkumardvs** [anuragverma108/SwapReads#2992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Uploading image.png…]()

can add a border to the email address so it will be in proper visibility 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024 and gssoc-ext
