### ISSUE TITLE
Improve Login and Sign Up Page UI

### ISSUE THREAD

**Issue by nishantharkut** [anuragverma108/SwapReads#30]
Dear Authors, The login and sign up page UI is not matching up with the whole website.
### **Kindly, Assign this issue to me under GSSoC'24**

**Comment by anuragverma108** [comment]
Assigned!

**Comment by anuragverma108** [comment]
Any Updates @nishantharkut

**Comment by nishantharkut** [comment]
Dear sir, I would make the changes by tomorrow morning, the GSSoC'24 contributions will start from today 8 pm.
Thank You sir for the patience and sorry sir for the delay.
Will give PR's by tomorrow

**Comment by anuragverma108** [comment]
Okay!
