### ISSUE TITLE
responsiveness of pages when viewed on mobile screen

### ISSUE THREAD

**Issue by HS202022** [anuragverma108/SwapReads#3009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The website is not having a good experience in mobile screen 
![Screenshot_20241006_114647](https://github.com/user-attachments/assets/c79c332f-54f6-4f4b-aa21-1335b5af9d97)
![Screenshot_20241006_114629](https://github.com/user-attachments/assets/e84dcc1d-15c7-4633-afbc-48c1fc22757b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HS202022** [comment]
Please give level 2

**Comment by sailaja-adapa** [comment]
I already given you level 2 while merging

**Comment by HS202022** [comment]
> I already given you level 2 while merging

thank you so much

**Comment by sailaja-adapa** [comment]
Welcome :)
