### ISSUE TITLE
FIXING THE NAV BAR AND CONTACT SECTION

### ISSUE THREAD

**Issue by RAJIV81205** [anuragverma108/SwapReads#3017]
THE NAV BAR IS SOPHISTICATED IN A SMALL PLACE AND THE CONTACT SECTION IS SPOILED , ASSIGN ME TO FIX IT 
![image](https://github.com/user-attachments/assets/0bb47cc5-7805-431a-8d49-b2762d6c002d)

**Comment by eshalshaikh07** [comment]
![373937101-0bb47cc5-7805-431a-8d49-b2762d6c002d](https://github.com/user-attachments/assets/6f9ad055-2e21-4288-b635-9036df79c1ea)
This navbar and entire page when navbar opens need to be aligned and some aesthetic animations can make it look way better, would like to contribute n this!

**Comment by HarjotSH** [comment]
I can solve this issue @anuragverma108 , Please assign it to me ASAP.
