### ISSUE TITLE
Add icons to navbar 

### ISSUE THREAD

**Issue by Devaki01** [anuragverma108/SwapReads#3019]
Hello,
Can I contribute by adding attractive icons to the NavLinks present on the navbar section.

![image](https://github.com/user-attachments/assets/1b8f51cc-0fa8-452d-9426-07bd031d6f42)

Please assign me this issue under ggsoc'24 and hacktoberfest.
Thank you

**Comment by Devaki01** [comment]
Thank you

**Comment by Pariyul** [comment]
Hey I want to contribute in this . Kindly Assign me this under hacktoberfest2024 and gssoc-ext
