### ISSUE TITLE
Improvement to login page of SwapReads

### ISSUE THREAD

**Issue by s0wjanyaa** [anuragverma108/SwapReads#3031]
I will be improving the login page by making the following changes:

1.  Changing the "Submit" button text to "Login."
2.  Adjusting the length of the login card so the user won't need to scroll while logging in.

These changes will enhance the page's usability and user experience.
@anuragverma108 please assign this to me

**Comment by uvenkatateja** [comment]
by using antd and shadcn
 i will improve and better login page

@anuragverma108 please assign this to me
