### ISSUE TITLE
Update 'Contact Us' page

### ISSUE THREAD

**Issue by sammy0318** [anuragverma108/SwapReads#3037]
By looking at current 'Conatact Us' , i want to update and solve some problems related to it .

![Screenshot (771)](https://github.com/user-attachments/assets/bfbce617-ef66-45ed-adda-cd7e730b7e4b)
  
@sanjay-kv , @anuragverma108, @sailaja-adapa 
Please provide me a chance to update the page .

**Comment by Codersweta7** [comment]
Please assign this issue to me , if it is not done yet
