### ISSUE TITLE
maintain the navbar

### ISSUE THREAD

**Issue by Anju-Narnolia** [anuragverma108/SwapReads#3042]
![image](https://github.com/user-attachments/assets/b66d3ffe-52fb-4f79-b81f-48f4aa572960)
I want to change the serial of the section of the navbar. These do not match the body of the website.
@anuragverma108 please assign it to me

**Comment by Pariyul** [comment]
Hey I want to contribute in this . Kindly Assign me this under hacktoberfest2024 and gssoc-ext

**Comment by Anju-Narnolia** [comment]
I am working on it.
