### ISSUE TITLE
Footer UI updation ,new feature Newsletter

### ISSUE THREAD

**Issue by siddhanttomar2003** [anuragverma108/SwapReads#305]
### Describe the feature

The previous one footer's rightmost part not looks good ,the icons are very much smaller .
Newsletter feature has been added in this newone.
Attaching the before after image .
Plz assign me this and label this gssoc level1

### Add ScreenShots

<img width="938" alt="Screenshot 2024-05-13 165648" src="https://github.com/anuragverma108/SwapReads/assets/141900451/fc84a749-29e1-4676-b140-21194540f08c">
<img width="946" alt="Screenshot 2024-05-13 165900" src="https://github.com/anuragverma108/SwapReads/assets/141900451/2456491f-accf-4831-8d3e-d27c82582f11">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by siddhanttomar2003** [comment]
hlo @huamanraj plz check this updation and assign it to me

**Comment by anuragverma108** [comment]
Assigned! @siddhanttomar2003 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
