### ISSUE TITLE
BUG: security concerns and improvements in codebase

### ISSUE THREAD

**Issue by moroii69** [anuragverma108/SwapReads#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[server.js](https://github.com/anuragverma108/SwapReads/blob/main/server.js)
### description
while reviewing the codebase, several security concerns and areas for improvement were identified. these include storing passwords in plain text, exposing sensitive information, lack of robust error handling, and potential latency issues with email sending. addressing these issues will enhance the security, performance, and maintainability of the application.

### Suggestions for Resolution
1. **hash passwords**: implement [password hashing](https://crypto.stanford.edu/pwdhash/) using a library like [bcrypt](https://www.npmjs.com/package/bcrypt) to enhance security.
2. **secure sensitive information**: use environment variables to store sensitive information like database connection strings and email credentials.
3. **improve error handling**: implement robust error handling for database operations and email sending to provide informative responses and aid in debugging.
4. **optimize email sending**: consider implementing an [asynchronous email queue system](https://www.mailgun.com/blog/email/set-up-message-queue-asynchronous-sending/) to avoid blocking the main thread during email sending.
5. **enhance logging**: utilize a logging library for better logging capabilities and monitoring.
6. **environment configuration**: externalize configurations into environment variables for improved portability and security.
7. **testing**: implement unit and integration tests to ensure reliability, especially for critical functionalities.
8. **code organization**: organize code into separate modules or files for better readability and maintainability.
9. **scalability**: ensure application architecture is scalable, considering distributed databases for handling increased load.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @moroii69 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
