### ISSUE TITLE
Feat: UI/UX Improvement for Login and Sign-Up Pages

### ISSUE THREAD

**Issue by ritiksingh-01** [anuragverma108/SwapReads#3072]
### Describe the feature

I can enhance the UI/UX of both the login and sign-up pages. Currently, the design of the eye button and the size of the other buttons are not well-optimized. I will redesign them to ensure a better, more polished user interface.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

Thank You!!

### Add ScreenShots

![login page](https://github.com/user-attachments/assets/ecd968cb-79bc-4523-8f49-dbb7908ea832)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
@ritiksingh-01 work on new issue on fixing footer with good allignment create new issue 

![hi](https://github.com/user-attachments/assets/6deecb35-e295-44d1-816a-be203ae859aa)
