### ISSUE TITLE
BUG: inconsistent scroll behavior due to unsupported property in firefox

### ISSUE THREAD

**Issue by moroii69** [anuragverma108/SwapReads#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### issue description
[scroll.js](https://github.com/anuragverma108/SwapReads/blob/main/assets/js/scroll.js)
#### problem
the code uses `document.body.scrollTop` to determine the scroll position, which is not supported in firefox. fhis can lead to inconsistent behavior across different browsers.

#### solution
replace `document.body.scrollTop` with `document.documentElement.scrollTop` for better cross-browser compatibility.

### code snippet
```javascript
// get the button element
var scrollToTopBtn = document.getElementById("scrollToTopBtn");

// when the user scrolls down 20px from the top of the document, show the button
window.onscroll = function () {
  if (document.documentElement.scrollTop > 20) {
    scrollToTopBtn.style.display = "block";
  } else {
    scrollToTopBtn.style.display = "none";
  }
};

// when the user clicks on the button, scroll to the top of the document
scrollToTopBtn.onclick = function () {
  // smooth scroll to the top
  window.scrollTo({
    top: 0,
    behavior: "smooth"
  });
};
```

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @moroii69 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
