### ISSUE TITLE
BUG: lack of error handling in authentication functions

### ISSUE THREAD

**Issue by moroii69** [anuragverma108/SwapReads#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[login.js](https://github.com/anuragverma108/SwapReads/blob/main/assets/js/login.js)

### description:
the `signup()` and `login()` functions in the authentication module lack proper error handling. currently, they don't handle errors from the fetch requests, which could lead to a poor user experience if network failures or server errors occur.

### recommendations:
1. **error handling**: implement error handling in both functions to gracefully handle network failures, server errors, or other unexpected issues that may arise during the authentication process.
   
2. **feedback to user**: Provide informative error messages or feedback to the user in case of failures, helping them understand what went wrong and how to resolve the issue.

3. **logging**: consider logging errors to aid in debugging and monitoring application health.

4. **testing**: thoroughly test the error handling mechanisms to ensure they work as expected in various scenarios and environments.

### example improvement:
example of how error handling could be added to the `signup()` function:

```javascript
async function signup() {
    try {
        // existing signup code...

        // handle response errors
        if (!response.ok) {
            throw new Error('Failed to sign up');
        }

        // existing success handling code...
    } catch (error) {
        console.error('Signup error:', error);
        // handle error, show a message to the user, etc.
    }
}
```

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @moroii69 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
