### ISSUE TITLE
Missing video in the Hero Section

### ISSUE THREAD

**Issue by nishantharkut** [anuragverma108/SwapReads#31]
The Video Is not Playing in the hero section of the website
### **Please assign to me under GSSoC'24**

**Comment by yashisrani** [comment]
@anuragverma108 kindly assign me this issue under #gssoc'24 ..

**Comment by anuragverma108** [comment]
Assigned @yashisrani @nishantharkut

**Comment by anuragverma108** [comment]
Any Updates @yashisrani @nishantharkut

**Comment by nishantharkut** [comment]
Dear sir, I would make the changes by tomorrow morning, the GSSoC'24 contributions will start from today 8 pm.
Thank You sir for the patience and sorry sir for the delay.
Will give PR's by tomorrow

**Comment by nishantharkut** [comment]
Dear sir, Please assign to me under GSSoC'24 so that i can commit the changes and get the desired points.
Thank you

**Comment by Madhu-mac** [comment]
@anuragverma108 Assign this issue to me under GSSoc'24 and add lables to it,  so that i can work on it
