### ISSUE TITLE
DOC: Issue in the header file and dark/light theme not working

### ISSUE THREAD

**Issue by Khanishsuresh** [anuragverma108/SwapReads#310]
### What's wrong with the existing documentation

the padding of the dark and light theme made the header file to look as such
by making changes in the mode icons. the header section would be looking nice
and the dark/light theme is not working, only the icon is been changed 
the entire page is not been changed

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/136162512/a020cc24-86f0-4938-b4d7-69624b4ee621)

Light mode
![image](https://github.com/anuragverma108/SwapReads/assets/136162512/c08f6cb8-8527-4aee-8ba6-b1169e9d9b10)

Dark mode
![image](https://github.com/anuragverma108/SwapReads/assets/136162512/3aa288b2-3bd5-4430-a82e-07f466994f07)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @anuragverma108 ,

i have worked on this issue. i would like to contribute to the project
would u please assign me to this issue under GSSOC'24

**Comment by AmruthaPariprolu** [comment]
hi can you assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned! @Khanishsuresh

**Comment by Khanishsuresh** [comment]
Hii @anuragverma108 ,

PR #377 
The issue has been solved.
Please accept my PR
