### ISSUE TITLE
BUG: The Navigation bar is covering up the whole page

### ISSUE THREAD

**Issue by alrightdeepak** [anuragverma108/SwapReads#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the navigation bar is too big, covering up the whole page making the website unreadable.
![image](https://github.com/anuragverma108/SwapReads/assets/130627252/78b28f9d-28b2-4284-a87e-444e2a176009)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by alrightdeepak** [comment]
hi @anuragverma108 , i'm a GSSOC'24 contributor please assign this to me.

**Comment by Rahul-Sahani04** [comment]
Hi @anuragverma108, I'm a GSSOC'24 contributor and I have resolved this issue. Please assign this to me.

**Comment by BhumikaRahwani** [comment]
Hi!! @anuragverma108  I am Bhumika Rahwani, contributor in GSSoC'24. I would like to address this issue and make the respective changes.

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
