### ISSUE TITLE
Not responsive design 

### ISSUE THREAD

**Issue by NitinChakrawarti** [anuragverma108/SwapReads#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

website design is not responsive in different devices. cropped elements  are visible which makes user experience very horrible and is not good for UX .

![Screenshot 2024-05-13 194840](https://github.com/anuragverma108/SwapReads/assets/149225785/b282ac67-96bc-45fa-a63d-b1aba135e5c8)
![Screenshot 2024-05-13 194900](https://github.com/anuragverma108/SwapReads/assets/149225785/2b6b23b2-7cd6-4dc3-88b8-a34f2ed1a1aa)

@anuragverma108  please this issue to me , and don't forget to add label  for GSSoC'24 and level of issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on it and make responsive navbar also in both phone and pc!! @NitinChakrawarti

**Comment by NitinChakrawarti** [comment]
For sure I will do that as soon as possible.
