### ISSUE TITLE
Improvement in UI of login signup page

### ISSUE THREAD

**Issue by Shubham-Yadav003** [anuragverma108/SwapReads#3136]
I can improve the UI of login signup page to look more stylish with similar colour grading.

**Comment by ritiksingh-01** [comment]
This issue #3072  has already been assigned to me, so I kindly request that it be closed.

**Comment by sailaja-adapa** [comment]
@Shubham-Yadav003  work on new issue on fixing footer with good allignment create new issue

![hi](https://github.com/user-attachments/assets/ccd2cb89-784d-4d1f-895d-4cbda686c52d)
