### ISSUE TITLE
BUG: the buttons to change between what customers say is overlapping with other icons

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [anuragverma108/SwapReads#3151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the buttons to switch between what our customers are saying are overlapped by other buttons on both the left and right ends of the page, improve make the buttons closer to the div so they are easily seen and accessible to the user and better aesthetically pleasing

![issue2](https://github.com/user-attachments/assets/a9a32aff-9c03-4696-a7d9-b6fcdca97cc2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
@Shreya-Pandey-01  , resolve the issue . and create pr .
