### ISSUE TITLE
Chat.html backend

### ISSUE THREAD

**Issue by Codersweta7** [anuragverma108/SwapReads#3162]
@sailaja-adapa 
Please assign me chat.html backend part ...
I will do using javascript and node to start conversation

**Comment by sailaja-adapa** [comment]
@Codersweta7 not will assign automatically

**Comment by Codersweta7** [comment]
@sailaja-adapa 
I can see that user can send message what about response , how user will get response ...please tell me about the development made in this part

**Comment by sailaja-adapa** [comment]
@Codersweta7 For this ask @anuragverma108 since I don't know full implementation behind it

**Comment by Codersweta7** [comment]
@anuragverma108 
Can you please elaborate about development made on chat part

**Comment by Codersweta7** [comment]
@huamanraj 
Where this backend his hosted ?

**Comment by Codersweta7** [comment]
@anuragverma108 why you all didnt use mondodb (mongoose)

**Comment by huamanraj** [comment]
> @anuragverma108 why you all didnt use mondodb (mongoose) 

it was done by a contributor! 
and for mongo we need our own server right now it is serverless
