### ISSUE TITLE
BUG: Unneccessary white box covering image in home page, acting as an external link to youtube

### ISSUE THREAD

**Issue by divyalaldinani** [anuragverma108/SwapReads#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/82147067/e9e2873c-be55-4056-8926-3dab3a53605d)

This white box is covering the book-image in home page and on clicking that white box, youtube is getting opened.

Without it, image will look like:
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/fb9c0a53-73bd-4001-986a-4fbb304da3c8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by divyalaldinani** [comment]
@anuragverma108 
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/a62d4b04-83dc-4484-995b-69696a331296)
is this intentionally embedded?

**Comment by anuragverma108** [comment]
@divyalaldinani 
I am going to create an issue to change that image with a new one which clearly depicts the Swap Reads.
