### ISSUE TITLE
contact us

### ISSUE THREAD

**Issue by abhi200446** [anuragverma108/SwapReads#3182]
### Describe the feature

 the screenshot which i shared is not done correctly I will enhance and modify it please assign @anuragverma108

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9919e6e4-0ec1-417a-904f-4a62e1aa09e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sourav349** [comment]
Hey @abhi200446 I am interested in this issue, can you assign this issue too me.

**Comment by sourav349** [comment]
To enhance email user experience, center images for a balanced look and use a clean, simple design with ample white space. Ensure mobile-friendliness, maintain consistent branding, and include clear, prominent calls-to-action. Personalize content for different audience segments and regularly test layouts to optimize engagement and effectiveness
