### ISSUE TITLE
add footer section in EDIT PROFILE menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [anuragverma108/SwapReads#3189]
### Describe the feature

assign me to make a footer section in the edit profile menu which will enhance your UI/UX. and also you can get more user engagement and it also used for branding of your product or company.
please
assign me to make the footer section of EDIT PROFILE menu.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by abhi03ruchi** [comment]
ok work on the issue and raise pr .
