### ISSUE TITLE
BUG: Enhancement of the Calendar page

### ISSUE THREAD

**Issue by Jazz-45** [anuragverma108/SwapReads#3193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The color of the date block is too light to be distinguished on hovering. Whenever we hover on a particular date the background color become blue but a very light shade. This leads to bas user experience . I will improve the over all color schema of the calendar and will produce a contrasting background color. 

![Screenshot 2024-10-10 120057](https://github.com/user-attachments/assets/1b465af1-e92c-4958-ba05-b3c3155cd199)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
@Jazz-45 ,  ,work on the issue . 

add footer to the page , similar to the one on other pages . enhance the UI too .
