### ISSUE TITLE
Feat: Add a dark mode toggle on the profile page

### ISSUE THREAD

**Issue by aditiverma18** [anuragverma108/SwapReads#3197]
### Describe the feature

Dark Mode Toggle: Allow users to switch between light and dark modes for better accessibility and user preference.

### Add ScreenShots

<img width="626" alt="image" src="https://github.com/user-attachments/assets/76f85354-a611-400e-b16c-36c1edf9144a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok @aditiverma18 , work on the issue .
