### ISSUE TITLE
Missing Social Media Handles Links

### ISSUE THREAD

**Issue by nishantharkut** [anuragverma108/SwapReads#32]
Dear Authors, the LINK to the social media handles is not been linked at the social media buttons in the footer section.
Kindly make the note of it and **Assign to me UNDER GSSoC'24**

**Comment by anuragverma108** [comment]
Assigned!

**Comment by anuragverma108** [comment]
Any Updates @nishantharkut

**Comment by nishantharkut** [comment]
Dear sir, I would make the changes by tomorrow morning, the GSSoC'24 contributions will start from today 8 pm.
Thank You sir for the patience and sorry sir for the delay.
Will give PR's by tomorrow

**Comment by nishantharkut** [comment]
Sir, I have made the required changes.
Please tag me under **GSSoC'24** with the required conditions for the points
Thank you.

**Comment by Mastermind730** [comment]
Dear Authors, the LINK to the social media handles is not been linked at the social media buttons in the footer section. This needs to be fixed
Kindly make the note of it and Assign to me UNDER GSSoC'24

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , links in the footer section are still not working. please assign it to me. I will add all the required links.
