### ISSUE TITLE
The newsletter section in the about us page is static

### ISSUE THREAD

**Issue by ThunderShadows** [anuragverma108/SwapReads#3229]
The Styling and the responsiveness of the newsletter section in the about us page is static.

@anuragverma108 

I shall make the newsletter section more interactive to the users and more responsive for the text area input and the button by adding animations and CSS Styling to it.

**Comment by abhi03ruchi** [comment]
@ThunderShadows  , the newsletter in the about us page has a bug , on hovering it black background appears . 

work on this issue .
