### ISSUE TITLE
Update README.md forking steps

### ISSUE THREAD

**Issue by amroodh** [anuragverma108/SwapReads#323]
The steps required for forking required more instructions for new open source contributors.
Please assign this task to me under GSSOC 24.

**Comment by rishmiiee26** [comment]
Can you please assign me this task. Being a GSSoC'24 & a Front-end developer, I really want to contribute and fix the problem. Thank You.

**Comment by anuragverma108** [comment]
@rishmiiee26 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by Iamkg11** [comment]
I'd like to work on this issue. Please assign it under GSSOC

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
