### ISSUE TITLE
change fevicon

### ISSUE THREAD

**Issue by abhi200446** [anuragverma108/SwapReads#3230]
### Describe the feature

for a website the logo of  navbar and favicon must be same  here it is different 
can I proceed with it @sailaja-adapa 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/08223165-95dd-41d4-a282-80de1890a449)

<img width="43" alt="image" src="https://github.com/user-attachments/assets/37c38fc0-75e7-45bc-80c6-b32d1b16335d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lakshmirajvagu** [comment]
@abhi200446 i would like to work on it please assign me
