### ISSUE TITLE
Add footer section on HELP CENTER menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [anuragverma108/SwapReads#3233]
### Describe the feature

Assign me to make an attractive footer section for your HELP CENTER menu, which will enhance your UI/UX  and also help us to increase the user engagement. A good footer section is also helpful in the branding of the company/product

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok @Pranjalsinha110 , work on this issue . 
add footer section to this page , similar to the one in other pages .
