### ISSUE TITLE
Feat: Adding TWITTER social media icon in the Home page along with other icons

### ISSUE THREAD

**Issue by Adityazzzzz** [anuragverma108/SwapReads#3249]
### **Is there an existing issue for this?**

**What happened?**
There is a missing social media icon. Adding twitter social media icon will allow more people to connect with us.
I want to add TWITTER icon at the left side of home page. @anuragverma108 please assign me this task.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3a75722e-efed-4473-b4b5-2aa0c8ef3cf7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
