### ISSUE TITLE
BUG:  (URGENT Lvl. 03) :  Password field is disabled in login page find the bug and make it enable.  

### ISSUE THREAD

**Issue by huamanraj** [anuragverma108/SwapReads#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BUG:  (URGENT Lvl. 03) :  Password field is disabled in login page find the bug and make it enable.  
have a look at ZOD and firebase code!! 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abhinav-Sharma06** [comment]
Hi @huamanraj assign me this task under gssoc 2024 .

**Comment by huamanraj** [comment]
> Hi @huamanraj assign me this task under gssoc 2024 .
> 

work on it buddy!

**Comment by Abhinav-Sharma06** [comment]
@huamanraj sir exactly where is the bug as I am successfully able to login in to the website?
