### ISSUE TITLE
Add footer section in AUDIO BOOK menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [anuragverma108/SwapReads#3266]
### Describe the feature

assign me to make an attractive footer section for AUDIO BOOK menu which will enhance your UI/UX and also help you to get intract with your users.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by Pranjalsinha110** [comment]
already attached i am done this work yesterday
