### ISSUE TITLE
I want to remove SOCIAL MEDIA SIDEBAR in the website.

### ISSUE THREAD

**Issue by pankajsaini1** [anuragverma108/SwapReads#3273]
### Describe the feature

I want to remove SOCIAL MEDIA SIDEBAR in the website it does not looks good

### Add ScreenShots

![Screenshot 2024-10-12 002731](https://github.com/user-attachments/assets/e874c979-a91f-4b32-a88c-dc8f45a9b58c)
![Screenshot 2024-10-12 002845](https://github.com/user-attachments/assets/28372681-7931-4cae-a56d-98505cc19fb2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
