### ISSUE TITLE
BUG: navbar and social media icons bar not aligned correctly

### ISSUE THREAD

**Issue by Riyachauhan11** [anuragverma108/SwapReads#3279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Misalighment of navbar and social media icons bar on left. Their positions need to be corrected with respective to the whole website.
![image](https://github.com/user-attachments/assets/eb1d8a5f-64f7-4953-9479-a97945bb5684)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
