### ISSUE TITLE
BUG: Overlapping Elements on About Us Page

### ISSUE THREAD

**Issue by priyachau12** [anuragverma108/SwapReads#3288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
 On the "About Us" page, the theme button and the logo are overlapping, creating an alignment issue that affects the visual layout.

Expected Behavior: 
The theme button and the logo should be properly aligned without overlapping, ensuring a clean and organized appearance.

Additional Context: This alignment issue can hinder the user experience and may give an unprofessional appearance to the website. Ensuring that all elements are visually distinct and properly aligned will enhance the overall aesthetic and usability.

![image](https://github.com/user-attachments/assets/43cb1f5a-5b94-47d5-8e5c-e3495584ddb8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
in the about us page , the toggle has been removed by someone . 
u can add the toggle back and create dark mode for the page . 

work on the issue and create a new pr.

**Comment by abhi03ruchi** [comment]
in the about us page , the toggle has been removed by someone . 
u can add the toggle back and create dark mode for the page . 

work on the issue and create a new pr.
