### ISSUE TITLE
BUG: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @pankaj-bind 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
