### ISSUE TITLE
Improve Header UI

### ISSUE THREAD

**Issue by nishantharkut** [anuragverma108/SwapReads#33]
The current UI is not matching up with the theme and is not user friendly as it is same as the footer. 
**CHANGES**-:
- MAGAZINE STYLE HEADER - this type of header goes with the theme of the website.
- CLASSIC HEADER - this also goes with the website theme but it is not so aesthetic as today's new-gen websites

**Comment by urgetolearn** [comment]
Can i please work on this issue. please assign this task to me

**Comment by officialhemant511** [comment]
hey @anuragverma108 can you assign this issue to me ..

**Comment by anuragverma108** [comment]
Assigned!

**Comment by anuragverma108** [comment]
Any Updates @nishantharkut
