### ISSUE TITLE
BUG: Replace Dark Mode Button with SVG or Icon

### ISSUE THREAD

**Issue by SougataXdev** [anuragverma108/SwapReads#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When browsing the codebase, I noticed that there is an image being used as a button for toggling dark mode. This could pose accessibility issues for users who rely on screen readers or have visual impairments. To enhance accessibility and maintain consistency, it's advisable to replace the image with an SVG or icon that can be styled accordingly for both light and dark modes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SougataXdev** [comment]
@anuragverma108 assign this task to me

**Comment by huamanraj** [comment]
>  @huamanraj  assign this task to me 

work on it !

**Comment by SougataXdev** [comment]
@huamanraj remote: Permission to anuragverma108/SwapReads.git denied to SougataXdev.
fatal: unable to access 'https://github.com/anuragverma108/SwapReads/': The requested URL returned error: 403 ... Give me permission to push my code

**Comment by huamanraj** [comment]
> @huamanraj remote: Permission to anuragverma108/SwapReads.git denied to SougataXdev.
> fatal: unable to access 'https://github.com/anuragverma108/SwapReads/': The requested URL returned error: 403 ... Give me permission to push my code
> 

you have to fork and make changes then push code then create a PR! you cant push directly to this repo
