### ISSUE TITLE
Footer social media icons are in light colour i would like to make them dark.

### ISSUE THREAD

**Issue by pankajsaini1** [anuragverma108/SwapReads#3302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer social media icons are in light colour i would like to make them dark.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by Codersweta7** [comment]
@github-actions , if the task is not done assign that to me .
