### ISSUE TITLE
BUG: Want to change the layout of the Login page in Dark Mode...It looks seriously outdated

### ISSUE THREAD

**Issue by ark0078** [anuragverma108/SwapReads#3306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (249)](https://github.com/user-attachments/assets/20ecb8de-d2ef-42d8-a4ad-8bb033b3efee)
Not looking good in Dark Mode

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
