### ISSUE TITLE
Upgrade your Footer section of EVENT menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [anuragverma108/SwapReads#3323]
### Describe the feature

assign me to Upgrade the footer section of EVENT menu the new footer section contain more detail about your product/company and also increases your UI/UX, which help  you to gain new User and also helps you to gain more User Engagement

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok @Pranjalsinha110  , work on the issue , add footer similar to the one on other pages .
