### ISSUE TITLE
BUG:The cards are improper 

### ISSUE THREAD

**Issue by Sathya-reddy1658** [anuragverma108/SwapReads#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the heights of the cards are improper 
![image](https://github.com/anuragverma108/SwapReads/assets/154568696/88ecbf16-88c2-44a4-a722-8da70ca1b418)
please assign me issue and ill work on it 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Work on it !!

**Comment by harshcodesit** [comment]
@huamanraj 
I can align the cards properly, I have worked on the same issue with the benifits card 
it has been 2 weeks since you assigned the contributor

please reassign me the issue
