### ISSUE TITLE
Feat: to add light and dark mode toggle 

### ISSUE THREAD

**Issue by sv410** [anuragverma108/SwapReads#3343]
### Describe the feature

to add the toggle dark and light mode

### Add ScreenShots

![WhatsApp Image 2024-10-12 at 11 19 35 PM (1)](https://github.com/user-attachments/assets/a7847d0b-1083-4920-b24f-b12b451fd13f)
![WhatsApp Image 2024-10-12 at 11 20 20 PM (1)](https://github.com/user-attachments/assets/95872a1f-6fea-4136-bd91-352eeb9477c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
some pages dont have toggle button , u can add button on those pages . chk website . 
add button and create dark mode . 

work on the issue and raise pr .
