### ISSUE TITLE
The "Download" button under Explore Our Free E-Books gives 404 error

### ISSUE THREAD

**Issue by bhumika-1127** [anuragverma108/SwapReads#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108  I would like to add downloadable links of the pdf of the book for those download buttons. I am a GSSOC contributor. Assign me this task @anuragverma108 .
![image](https://github.com/anuragverma108/SwapReads/assets/137604220/7adf9fc6-2239-4578-b32d-a6989ac3211a)

![image](https://github.com/anuragverma108/SwapReads/assets/137604220/cc4c9485-2af1-4015-813d-4b5ad494f6f4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
