### ISSUE TITLE
Feat:Make a forum for user discussion

### ISSUE THREAD

**Issue by AnshhSingh** [anuragverma108/SwapReads#3370]
### Describe the feature

We should make a forum for users to discuss and post about books the forum can have threads based on genres present on https://swapreadsconnect.netlify.app/#genre  

### Add ScreenShots

we can shift the forum on subdomain forums.swapreadsconnect.netlify.app/

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok @AnshhSingh , work on this issue . and create a pr.

**Comment by AnshhSingh** [comment]
I have started working on this already

**Comment by AnshhSingh** [comment]
@abhi03ruchi will create the pr once some pages are done within 2-4 days
