### ISSUE TITLE
Feat: Load more option in "Explore different Genres"

### ISSUE THREAD

**Issue by satyamra1** [anuragverma108/SwapReads#3374]
### Describe the feature

We have over 20 different genres available, but to keep the interface clean and user-friendly, we will initially display only 8 genres. Once the user interacts with the 'Load More' button, all the remaining genres will become visible. This feature ensures that users are not overwhelmed by too many options at first but can still access the full list if needed.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3eb3ae03-986f-4466-9b6f-6ce0a732989e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok , nice . 
work on this issue . and create a new pr .
