### ISSUE TITLE
DOC: Add Code of Conduct

### ISSUE THREAD

**Issue by officeneerajsaini** [anuragverma108/SwapReads#338]
### What's wrong with the existing documentation

We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by officeneerajsaini** [comment]
@anuragverma108  , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by officeneerajsaini** [comment]
@anuragverma108, a screenshot is required for UI changes. I will add a new document to the repository. What should I show in the screenshot?
