### ISSUE TITLE
Feat: Subscribe to Newsletter

### ISSUE THREAD

**Issue by haseebzaki-07** [anuragverma108/SwapReads#3381]
### Describe the feature

On filling name and valid email to the input fields in the "Subscribe to our Newsletter" section. A email should be received by the user.

### Add ScreenShots

![Screenshot 2024-10-13 172522](https://github.com/user-attachments/assets/dd31ecb3-4da8-48e1-b395-9dbaf856d965)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
@haseebzaki-07  , work on the issue and create a pr.

**Comment by haseebzaki-07** [comment]
@abhi03ruchi sure
