### ISSUE TITLE
BUG:Translate button is not working properly in "ABOUT US" section

### ISSUE THREAD

**Issue by ark0078** [anuragverma108/SwapReads#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (258)](https://github.com/user-attachments/assets/0e7528c9-0621-4f07-834a-ea94bbe1d584)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the translate button doesnt work . Neither in the About Us page nor in the Login Page (footer button) . Fix the issue , create another pr .
