### ISSUE TITLE
Adding a Rate us page

### ISSUE THREAD

**Issue by Aashi19234** [anuragverma108/SwapReads#34]
**Is your feature request related to a problem? Please describe.**
A rating page is important for a website because it collects feedback, builds trust, improves SEO, helps enhance products/services, fosters engagement, and boosts conversion rates.

**Describe the solution you'd like**
I would like to add a rating page ,which would allow users to give a star-rating based on their experience.

**Describe alternatives you've considered**
I would be using HTML,CSS, JAVASCRIPT to fulfill this.

**Additional context**
Please assign this issue to me under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned!

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.

**Comment by anuragverma108** [comment]
Any Updates @Aashi19234
