### ISSUE TITLE
BUG:No proper alignment in quick links

### ISSUE THREAD

**Issue by SalehaTabassum** [anuragverma108/SwapReads#3403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In footer in quick links the icon and text are not properly aligned.
![Screenshot 2024-10-13 234954](https://github.com/user-attachments/assets/1eaebd65-d6cf-45d6-a348-c007efa72a6c)
Assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sujal942** [comment]
Hey, can you assign it to me? I'd like to work on this.
