### ISSUE TITLE
BUG: Toggle button misalignment on ligin/signup page

### ISSUE THREAD

**Issue by Sourabh782** [anuragverma108/SwapReads#3424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dark/light mode toggle is not properly aligned in login/signup page

https://github.com/user-attachments/assets/9b781dc3-6ea0-454a-bfe1-24be717217e6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the navbar of the login page is misaligned and toggle button is also not visible . correct the issue .
