### ISSUE TITLE
BUG: Contact form validation

### ISSUE THREAD

**Issue by krishna-singha** [anuragverma108/SwapReads#344]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Issue:

The current implementation of the contact form in you website lacks validation checks for input fields such as name, email, subject, and your message content. Users can submit the form with minimal input, including just one character in each field, which can lead to inaccurate or incomplete submissions.

## Expected Behaviour:

Validation should be implemented on the contact form to ensure that all required fields contain appropriate and sufficient information before submission. This includes but is not limited to:

**Name field:** Should require at least three characters.
**Email field:** Should validate for a valid email format.
**Subject field:** Should require at least five characters.
**Your Message field:** Should require a minimum length of characters.

## Additional Notes:

Consider providing informative error messages to users if validation fails, indicating which fields require attention and what specific criteria they need to meet.

## Screenshot:

<img width="1317" alt="Screenshot 2024-05-14 at 1 14 35 AM" src="https://github.com/anuragverma108/SwapReads/assets/128041532/c5fb6b1a-083e-4d39-b6bc-b577cc136382">

I can fix that
@anuragverma108 please assign this issue to me , and don't forget to add label for GSSoC'24 and level of issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @krishna-singha 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by krishna-singha** [comment]
Ok thank you for assigning this issue to me.

**Comment by RitiChandak** [comment]
@krishna-singha any updates?
