### ISSUE TITLE
Feat: testimonial section

### ISSUE THREAD

**Issue by Anamika-Ratna** [anuragverma108/SwapReads#345]
### Describe the feature

addition of testimonial section after "explore our free e book" section

### Add ScreenShots

![Screenshot (669)](https://github.com/anuragverma108/SwapReads/assets/122286548/b4f475c4-f1f7-4852-97b0-6ff4b3fca874)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @Anamika-Ratna 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Anamika-Ratna** [comment]
Hi @anuragverma108 ,
Kindly review my changes.
#744

**Comment by anuragverma108** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/129655645/2e251fae-f871-484b-aa36-45e73e84a14b)
The dark mode button in the RHS is by default on and when one turn it one it is going out of button.

![image](https://github.com/anuragverma108/SwapReads/assets/129655645/3ff76894-ba0b-400e-87b2-a8623d94655d)


See this.
Fix this & raise PR again
