### ISSUE TITLE
Adding going back to home button in edit profile

### ISSUE THREAD

**Issue by Aditijainnn** [anuragverma108/SwapReads#3450]
### Describe the feature

![image](https://github.com/user-attachments/assets/68bb470e-3149-4129-ad15-c682636c5db6)
in this there is no option of going back to home without editing profile so adding that

### Add ScreenShots

assign this to me under gssoc ext and hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by achalcipher** [comment]
I noticed that there is no option to return to the home page without editing the profile. To improve user navigation, I suggest adding a "Back to Home" option.

Task:

Add a "Back to Home" link or button on the profile editing page.

Additional Information:

This feature will make it easier for users to navigate without unnecessary steps.

Please assign this task to me under GSSoC Extended and Hacktoberfest labels.
