### ISSUE TITLE
BUG: Translate popup appears too far away from the translate button

### ISSUE THREAD

**Issue by LaibaKhalil61** [anuragverma108/SwapReads#3454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When Translate button is clicked, it's pop up instead of appearing beside the translate button itself , appears too far away from it. This is making the UI appear bad.

Image for reference : 
![Screenshot from 2024-10-14 20-32-36](https://github.com/user-attachments/assets/ad4b4515-2500-4114-a510-81c92ae58180)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this is irrelevant issue . 

the translate button is only on the homepage . add the (red translate button) and feature on all  pages .

u can work on this issue( that i have stated above) and raise a pr .
