### ISSUE TITLE
Feat: Allow Hovering effects for 'Scroll To Top' Button

### ISSUE THREAD

**Issue by chhavx1618** [anuragverma108/SwapReads#346]
### Description
The 'Scroll to Top' button at the right bottom corner of the website needs a hover effect. This would make it more integrated with the site, as almost all buttons/sections have some sort of hover effect.

Also, we can add an elegant indicator to show how much of the page has been scrolled through and how much is left. 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/152146397/39d76f7f-e6df-4f4b-9a70-5038fbec3f2e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chhavx1618** [comment]
I want to work on this issue under GSSOC'24, kindly assign it to me and I will make the improvements.

**Comment by rishmiiee26** [comment]
@anuragverma108 For the hover effect it need some changes, 'Scroll to Top' button at the right bottom corner of the website. Kindly assign me the task.
