### ISSUE TITLE
NAVIGATION BAR IS NOT PERFECTLY ALIGNED and your profile icon is also not at correct place

### ISSUE THREAD

**Issue by Shobhit1729Aryan** [anuragverma108/SwapReads#3462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I CAN ADD FLOATING EFFECT IN DIVS AND ALSO PROFILE PIFCTURE IS AT WRONG PLACE

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by achalcipher** [comment]
Hey People,

I have a couple of suggestions to enhance the website:

Floating Effect in Divs: Adding a floating effect can make the interface more dynamic and visually engaging.

Profile Picture Misplacement: The profile picture is currently positioned incorrectly. This needs to be fixed for a better user experience.

Could you please assign me this task? I'd also appreciate it if you could tag it for GSSoC and Hacktoberfest.

**Comment by Shobhit1729Aryan** [comment]
@anuragverma108 CAN YOU HELP ME WHAT IS THE CONFLICT IN THIS REPOSITORY ,IF NOT THEN PLEASE CONSIDER TO MERGE
