### ISSUE TITLE
BUG: The navigation bar text are not visible when responsiveness is checked and the scroll button is not working

### ISSUE THREAD

**Issue by Archisman141** [anuragverma108/SwapReads#3463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While checking the responsiveness of the website I found that the nav bar text are not visible when view from phone or tablet. I can fix this issue. Also the scroll button on the webpage of the website is not working

![Screenshot 2024-10-15 004402](https://github.com/user-attachments/assets/589ecf7b-c516-41e3-a24a-64c2b83fdf89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
yes , the scroll effect is not working in case of mobile view . 

work on this issue and raise a pr.

**Comment by Archisman141** [comment]
@anuragverma108 Sir I have created my PR, please merge my PR.
