### ISSUE TITLE
Feat:Fix the icon on navbar of book page

### ISSUE THREAD

**Issue by Sudhanshu248** [anuragverma108/SwapReads#3468]
### Describe the feature

In the book page, icon are not at accurate place.

I can improve it.

@anuragverma108 Kindly assign me this issue under the label of hacktoberfest'24, hacktoberfest-accepted, level-2

### Add ScreenShots

![Screenshot 2024-10-15 091701](https://github.com/user-attachments/assets/0dfdbd23-312a-4ecb-8fdd-4f82f83cc030)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this issue is there on other pages as well .
work on this issue and raise a pr.
