### ISSUE TITLE
Add NavBar to the 'Rate Us' Page

### ISSUE THREAD

**Issue by chhavx1618** [anuragverma108/SwapReads#347]
### Description

The Rate Us page should contain the NavBar for easier shift from the rate us page to any other page. Currently, it only leads to home, forcing the user to first go to the home page then scrolling/moving to any other page or section. Adding navbar to the rate us page would help users to skip this step, making their visit to the site more efficient.

### Screenshots

![image](https://github.com/anuragverma108/SwapReads/assets/152146397/8229c303-45d0-4eba-9dcf-3c1fa1f40d6b)
![image](https://github.com/anuragverma108/SwapReads/assets/152146397/16b15f93-4400-4a13-b5cd-621c35577e77)

**Comment by khushizz** [comment]
I'd like to work on this issue under GSSOC. Could you please assign it to me.

**Comment by pallabisneha** [comment]
i want to work for fix this issue in Girl script summer code(GSSoC). I am really grateful if you kindly assign it to me.

**Comment by chhavx1618** [comment]
I want to work on this issue under GSSOC'24, kindly assign it to me and I will make the improvements.

**Comment by anuragverma108** [comment]
@khushizz @pallabisneha 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by Shivani-Hiremath** [comment]
I would like to work on this feature as a GSSOC contributor. Please assign it to me so that I can contribute to the project.

**Comment by chhavx1618** [comment]
Thank you @anuragverma108 ! I'll make sure to get this working asap :)
