### ISSUE TITLE
Enhancement: Change the scroll to top button to a icon

### ISSUE THREAD

**Issue by sum1t-here** [anuragverma108/SwapReads#348]
### Describe the feature

To maintain the simplicity of the website, change the scroll to top button to an icon

### Add ScreenShots

<img width="209" alt="Screenshot 2024-05-14 at 2 37 37 AM" src="https://github.com/anuragverma108/SwapReads/assets/126807055/ea7ad8fc-29a2-4ba1-87b1-585b08b4d398">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sum1t-here** [comment]
Hey @anuragverma108 please assign this issue to me under GSSOC'24

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
