### ISSUE TITLE
BUG:Cookie Box Not Scrollable, Accept/Reject Buttons Not Visible

### ISSUE THREAD

**Issue by Chitrakadyan2005** [anuragverma108/SwapReads#3487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cookie consent box on the homepage is not scrollable, preventing users from seeing or interacting with the "Accept" or "Reject" buttons. This issue hinders users from making their cookie preferences, affecting their browsing experience.
Expected Behavior: The cookie consent box should allow scrolling or size should increase so that users can view and click the "Accept" or "Reject" buttons to set their preferences.

i would like to work on it please it to me under GSSOC'24EXTD, hacktoberfest'24 and level labels.
@anuragverma108 

https://github.com/user-attachments/assets/2f2446b4-8ea8-43e2-bf52-33ae749bb203

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chitrakadyan2005** [comment]
@sailaja-adapa 
You closed the issue but i didn't get any update about my pr you said u will merge it can you please tell me about the pr update i just wanna know to do better next time.

**Comment by Chitrakadyan2005** [comment]
@abhi03ruchi 
please update me about my pr on this issue

**Comment by sailaja-adapa** [comment]
Oh I am sorry @Chitrakadyan2005 I didn't seen msg
When coming to this PR the issue has already been done and it was now perfectly fine try to work on new issue like social icons were colliding with Navbar
