### ISSUE TITLE
BUG: Redirect the forget password to another page

### ISSUE THREAD

**Issue by sum1t-here** [anuragverma108/SwapReads#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When i click on reset here in forgot password, it shows a pop up message. 
<img width="1440" alt="Screenshot 2024-05-14 at 2 42 33 AM" src="https://github.com/anuragverma108/SwapReads/assets/126807055/0ce2aedf-f02b-4bb8-b6d0-e21bf4c01229">
So let the user be redirected upon clicking, reset here, where one email field will be present and the and a button to send the link to email

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sum1t-here** [comment]
Hey @anuragverma108 please assign me this issue under gssoc'24

**Comment by anuragverma108** [comment]
Assigned! @sum1t-here 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
