### ISSUE TITLE
BUG: Testimonial Scroll Arrows are Misaligned and Congested with Other Buttons

### ISSUE THREAD

**Issue by abhivyakti2** [anuragverma108/SwapReads#3490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:**
The testimonial section's scroll arrows are not optimally positioned. They are placed too far from the testimonial content and are congested between other buttons in the UI, leading to a cluttered and confusing interface.

**Steps to Reproduce:**
Navigate to the testimonial section of the page.
Observe the placement of the scroll arrows.
Notice that the arrows are either too far from the testimonials or too close to other buttons, causing visual congestion.

**Expected Behavior:**
The testimonial scroll arrows should be positioned closer to the testimonials they control, with ample spacing to avoid crowding other UI elements.
There should be a clear distinction between the testimonial arrows and other buttons to enhance usability.

**Actual Behavior:**
The scroll arrows appear far from the testimonial content and are squeezed between other buttons, making it harder for users to navigate and distinguish the purpose of the arrows.

**Proposed Solution:**
Adjust the positioning of the testimonial scroll arrows to be closer to the testimonial section while ensuring adequate spacing from nearby buttons.
Ensure that the arrows are prominent and clearly distinguishable from other buttons for better user interaction.

**Additional Context:**
Improving the layout and positioning of the testimonial scroll arrows will enhance both the aesthetics and functionality of the testimonial section, offering a more user-friendly experience.

@anuragverma108 Kindly assign me this issue and **add labels : hacktoberfest-accepted, gssoc-ext, any level label suitable**

**Screenshot of issue**
![image](https://github.com/user-attachments/assets/fa5d07f5-8797-41e5-8457-ce7efcdab0d7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok , work on this issue and raise a pr .
