### ISSUE TITLE
Enhancing the UI of book exchange hub

### ISSUE THREAD

**Issue by AlaynaShaheen** [anuragverma108/SwapReads#35]
Feature request:
The UI of book exchange hub can be made better and visually appealing

Solution:
We can add padding and also border to it to improve its appearance

![Screenshot 2024-05-10 081404](https://github.com/anuragverma108/SwapReads/assets/111679498/0e224153-bc50-4db9-920f-76210fe5dd7b)

I am a contributor at GSSoC'24. I have a good experience in development. I can resolve this issue. Please assign this to me.

**Comment by anuragverma108** [comment]
Assigned !
Make it responsive too.

**Comment by AlaynaShaheen** [comment]
Thank you for assigning this to me @anuragverma108. I will make those changes and will raise a PR soon.

**Comment by AlaynaShaheen** [comment]
@anuragverma108 can you please send me your discord id for project discussion

**Comment by anuragverma108** [comment]
My discord id  - anuragverma_108

**Comment by AlaynaShaheen** [comment]
@anuragverma108 Can you please add a label to this issue so that it will be counted in leaderboard.

**Comment by AlaynaShaheen** [comment]
![Screenshot 2024-05-11 100050](https://github.com/anuragverma108/SwapReads/assets/111679498/b5d05cfa-3837-4cfb-b57e-fe92a0c8efe3)
@anuragverma108 I have made some changes and it is responsive too. Do let me know if there are any changes so that I can raise a PR.
