### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [anuragverma108/SwapReads#3517]
### Describe the feature

I want to add a page to showcase all the contributors of this website

### Add ScreenShots

@anuragverma108 can you assign me this issue please.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
You can start working @T-Rahul-prabhu-38

**Comment by T-Rahul-prabhu-38** [comment]
will this be given a higher level.
