### ISSUE TITLE
Adding a Hamburger icon to the navbar 

### ISSUE THREAD

**Issue by sahithinandikula** [anuragverma108/SwapReads#3525]
### Describe the feature

The navbar looks too clumsy since there are multiple elements present on it . Adding a hamburger and keeping only relevant elements appear makes it clear and simple

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d01b652c-2b4e-4db0-8781-ec6f89973feb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
work on the issue and raise a pr.
