### ISSUE TITLE
Feat:Replace rate us page with a modal 

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#353]
### Describe the feature

A modal is like a pop box that does not require user to go to a different webpage. This makes more sense with the single page layout of the website. It would also improve user experience as users will not have to switch pages to rate the website.

### Add ScreenShots

example of a modal:
![maxresdefault](https://github.com/anuragverma108/SwapReads/assets/32983571/3b81807c-a692-4492-a925-7486e728593e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Stiffpixels** [comment]
@huamanraj please assign this feature to me if its good.

**Comment by anuragverma108** [comment]
Assigned! @Stiffpixels 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by anuragverma108** [comment]
@Stiffpixels 
See show me the screenshots or video demo first. If I liked it then I will surely merge it.

**Comment by Stiffpixels** [comment]
> @Stiffpixels See show me the screenshots or video demo first. If I liked it then I will surely merge it.

okay
