### ISSUE TITLE
Page for genre 

### ISSUE THREAD

**Issue by NitinChakrawarti** [anuragverma108/SwapReads#354]
### Describe the feature

In website there is no page in which we can find books of specific genre.

### Add ScreenShots

![Screenshot 2024-05-14 091604](https://github.com/anuragverma108/SwapReads/assets/149225785/92e879c1-4689-4770-88f3-f456b361704f)

In this we can add a button for books of that specific genre and onclick that button user will be taken to a page in which they find all book ( static  data )  of that genre.

I can create that assign this issue me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
the similar issue is asigned to someone else have a loot at issues first!!
