### ISSUE TITLE
BUG:the accept section of the page is not alligned properly

### ISSUE THREAD

**Issue by Abhinavagarwa** [anuragverma108/SwapReads#3545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the accept section of the page is not alligned in a manner
![Uploading Screenshot 2024-10-16 at 5.37.11 PM.png…]()
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
which section , image is not visible ?  please provide a detailed explanation of the issue u want to resolve .
