### ISSUE TITLE
Improve the rate us page 

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#355]
### Describe the feature

I want to improve rate us page.
Firstly by adding navbar and footer.
By adding the rating content by emojis and message.

### Add ScreenShots

![fcb7d0d2990765ef9d092712a79baab8](https://github.com/anuragverma108/SwapReads/assets/145490348/2bea6825-a290-4993-9662-3007c744a62d)

Please assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by varshithar12** [comment]
Can you please assign me the issue ?

**Comment by huamanraj** [comment]
@Sneha123-zudo work on it! but firstly change the design as our website theme!!
