### ISSUE TITLE
BUG:Social links not working

### ISSUE THREAD

**Issue by paridhi1509** [anuragverma108/SwapReads#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The links to the various social accounts direct the user back to the top of the page. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by ritikaguptaa** [comment]
@anuragverma108 Please assign this task to Me.

**Comment by paridhi1509** [comment]
Hey
I needed the links to the social accounts to add them to the respective
icons since i couldn't find the accounts.
Thank you!

**Comment by paridhi1509** [comment]
Can i have the links for the socials @anuragverma108
