### ISSUE TITLE
BUG: Login/Signup Heading is not visible at dark mode

### ISSUE THREAD

**Issue by Manishar55** [anuragverma108/SwapReads#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hii @anuragverma108 
As you can see the login/signup page heading in dark mode is not visible because both have the same color
I want to fix this issue, can you please assign this issue to me under gssoc24
![Screenshot 2024-05-14 095907](https://github.com/anuragverma108/SwapReads/assets/154615478/5eca4f8a-9879-4bc6-964c-d1a16e3ba774)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
Work on it !!
