### ISSUE TITLE
Feat: integrate Apple iOS login 

### ISSUE THREAD

**Issue by REHAN-18** [anuragverma108/SwapReads#3585]
### Describe the feature

Integrating Apple iOS login allows users to sign in to your app using their Apple ID, providing a seamless and secure authentication experience 

### Add ScreenShots

![Uploading Screenshot 2024-10-17 at 1.23.29 AM.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by REHAN-18** [comment]
pls give level 2 label !!!

**Comment by abhi03ruchi** [comment]
> pls give level 2 label !!!

github bot assigns these label by default . 
when u create pr then we will review it , assign label and merge pr based on ur work .
