### ISSUE TITLE
UI of Book section

### ISSUE THREAD

**Issue by Devanshu1603** [anuragverma108/SwapReads#3589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the UI of Donate book section need to be improved. 

https://github.com/user-attachments/assets/a5a92a5b-6f5b-435f-8f4d-87c6ffad5fee

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Devanshu1603** [comment]
@dipak2005  but this issue was assigned to me , you shouldn't raise PR on another issue. it's against community contribution guidlines. Hope you will understand it , please close your PR.

**Comment by abhi03ruchi** [comment]
this issue is resolved now .
 but in dark mode the text in the cards of book section is not visible . 

u can work on fixing this bug , create a new issue and raise pr .
