### ISSUE TITLE
Loginpage alignment

### ISSUE THREAD

**Issue by kdanjana** [anuragverma108/SwapReads#36]
The login page is not aligned properly, there is not enough space between login box and end of page. I would also like to modify home page button. I will put the whole login box at the center of the page. I want to include the header/navbar and footer present in the home page to login page also , so that there will be continuous flow for the web page.
Please assign this to me. 
GSSoC 24.

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by anuragverma108** [comment]
Assigned!
