### ISSUE TITLE
#Enhance UI with Box Shadows for Improved Depth and Visual Appeal

### ISSUE THREAD

**Issue by prakruthiprasad20** [anuragverma108/SwapReads#3600]
To enhance the overall visual appeal and create a sense of depth within the UI, box shadows should be applied to specific elements. This will improve the user experience by making the interface look more modern, polished, and visually engaging.
Please review the issue,
Thank You.

**Comment by abhi03ruchi** [comment]
please provide a detailed explanation of the issue u want to resolve . 
Be specific .
