### ISSUE TITLE
Dark Mode Button is not properly styled

### ISSUE THREAD

**Issue by kalpesh-patel-20** [anuragverma108/SwapReads#3608]
The dark mode button lacks the centering of circle inside it and also proper styling is required.
![image](https://github.com/user-attachments/assets/5fd03628-61de-4e86-ad2b-d0377f5936a6)

Please assign this issue to me and add the gssoc and hacktoberfest labels.

**Comment by ishivansmishra** [comment]
@anuragverma108 @kalpesh-patel-20  please assigne me this issue
