### ISSUE TITLE
Feat: Adding images of relevant books in literary realms section

### ISSUE THREAD

**Issue by Vedanshi-Arya** [anuragverma108/SwapReads#362]
### Describe the feature

1. Including images will catch the user's attention
2. It will make it more attractive and interesting
3. I will add the image of the most famous book in that domain.
@anuragverma108 please assign me this issue 

### Add ScreenShots

![Screenshot 2024-05-14 110817](https://github.com/anuragverma108/SwapReads/assets/142818538/24c4ae2e-9b33-4d9b-a46e-a725a0db33bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @Vedanshi-Arya 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by anuragverma108** [comment]
Make sure all the boxes should be of same size after addition of images & responsive too
