### ISSUE TITLE
Feat:After submit form their is no message for user  

### ISSUE THREAD

**Issue by rahulbamnuya** [anuragverma108/SwapReads#3624]
### Describe the feature

I will add some good message so when user submit it they will get this message

### Add ScreenShots

![Screenshot (207)](https://github.com/user-attachments/assets/79793ed2-54d1-4e80-a3ed-facb4165c661)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Codersweta7** [comment]
I can do this work , if not done yet .

**Comment by abhi03ruchi** [comment]
ok , u can work on the issue.

**Comment by abhi03ruchi** [comment]
> I can do this work , if not done yet .

ok , u can work on the issue.

**Comment by abhi03ruchi** [comment]
work on the issue and raise a pr .
will review the pr and assign level based on ur work there .
