### ISSUE TITLE
Feat:Improvement of social link to share button view .

### ISSUE THREAD

**Issue by Anjaliavv51** [anuragverma108/SwapReads#366]
### Describe the feature

Feature i want to improve for share option:

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/abbf18c9-2a23-4bcf-a50f-83788511dacc

It reduces space and also looks attractive due it's transform.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/154777864/77ed861d-deac-4dbd-b05e-f7ce0dfa52f4)

Looks Dull and no proper alignment!!!
I will change my change button feature colors relevent to our website , I asure that!!!
 
Please assign this under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
i dont think this is going good with the design!!

**Comment by Anjaliavv51** [comment]
Okay
