### ISSUE TITLE
Adding "My Favorites" Feature and Sign-out option

### ISSUE THREAD

**Issue by Varshi45** [anuragverma108/SwapReads#37]
**Is your feature request related to a problem? Please describe.**
Current Site does not offer any need for user to login/register. So adding option to list their favorites or at least select those available will make user to register to site. Also if there is a sign in option there should be a sign out option as well. 

**Describe the solution you'd like**
My suggestion is to put in place a user authentication system with choices for creating, logging in, and out of accounts. Users would be able to save favorites or selections and therefore customize their experience. Moreover, incorporating a sign-out feature would improve user privacy and security.

**Comment by Varshi45** [comment]
I'm one of the contributors at GSSoC'24. I've a good experience in Web development. I can resolve this issue. Please assign this to me.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.

**Comment by anuragverma108** [comment]
Assigned!

**Comment by cpratik1307** [comment]
Assigned!



> Assigned!

@anuragverma108 Sir, Please let me know to whom you have assigned this task.

**Comment by sahithinandikula** [comment]
@anuragverma108 I want to work on this project, please assign this issue to me. I hope my request is considered

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by shamayitadatta** [comment]
I've a good experience in Web development and a newbie in this open source platform. So I want work in this and Mark it as my first contribution ,I can resolve this issue and make the website more appealing. Please assign this to me
