### ISSUE TITLE
Feat: Add functionality to Send Now button in Contact section. 

### ISSUE THREAD

**Issue by GauravGupta993** [anuragverma108/SwapReads#371]
### Describe the feature

I have gone through the code of the project and it seems to me on pressing the Send Now button in the Contact section, only an alert message is displayed and nothing happens except it. What I want to do is send a mail to a particular Gmail account. 

### Add ScreenShots

I am talking about this section. 
![image](https://github.com/anuragverma108/SwapReads/assets/123398315/bbaf9b98-1b71-48b3-bd3e-eded3f3bd8c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
work on it!! @GauravGupta993

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by chitraa-cj** [comment]
Please assign this to me I will complete this.
