### ISSUE TITLE
Alignment of Written Font 

### ISSUE THREAD

**Issue by 1754riya** [anuragverma108/SwapReads#3712]
Is there an existing issue for this?
 I have searched the existing issues
What happened?
Alignment of written, so that it provide better visual 
![Screenshot (338)](https://github.com/user-attachments/assets/ffb506fb-a19c-44d1-a1be-13741ceae284)

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
please assign me this under Gssoc'24 Ext, Hacktoberfest.

**Comment by ambarmishraa** [comment]
Assign me this task.
