### ISSUE TITLE
Adding color effect

### ISSUE THREAD

**Issue by 1754riya** [anuragverma108/SwapReads#3713]
Is there an existing issue for this?
I have searched the existing issues
What happened?
Alignment of  color,so that it provides better visual as  uneven doesn't look good.
![Screenshot (339)](https://github.com/user-attachments/assets/5062cc3d-e8c6-4db0-bc4f-a003941d4e85)

Record
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue
please assign me this under Gssoc'24 Ext, Hacktoberfest.

**Comment by ambarmishraa** [comment]
Assign me this task.
