### ISSUE TITLE
Alignment of "Send Message"

### ISSUE THREAD

**Issue by 1754riya** [anuragverma108/SwapReads#3714]
Is there an existing issue for this?
I have searched the existing issues
What happened?
Alignment of send message, so that it provides better visual .
![Uploading Screenshot (340).png…]()

Record
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue
please assign me this under Gssoc'24 Ext, Hacktoberfest.

**Comment by ambarmishraa** [comment]
Assign me this task.
