### ISSUE TITLE
BUG: Login Button Hover Effect Fails on Mobile Devices

### ISSUE THREAD

**Issue by chikatlarakesh** [anuragverma108/SwapReads#3716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 The login button's hover effect is not functional on mobile devices due to the absence of hover state support. This results in inconsistent user experiences across different platforms.

Steps to Reproduce:
Open the dark mode login page on a mobile device.
Try interacting with the login button — notice that no visual effect occurs when pressed.

Expected Behavior: A visual feedback effect (like a subtle color change or scale) should be displayed when the login button is tapped on mobile.

Possible Fix:
Implement a :active or :focus state for mobile devices to mimic the hover effect.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ambarmishraa** [comment]
Assign me this task.
