### ISSUE TITLE
BUG: Translate button is not working

### ISSUE THREAD

**Issue by Mayanksaininh** [anuragverma108/SwapReads#3722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Translate button is not working, It should change the exist language into selected language
![Screenshot (55)](https://github.com/user-attachments/assets/da625eed-62ce-47a2-9825-700a91e4271f)
![Screenshot (56)](https://github.com/user-attachments/assets/9e2eb403-5745-40ee-9c14-5d154e158928)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayanksaininh** [comment]
Please assign this to me

**Comment by abhi03ruchi** [comment]
translate button is working here . Check again .

**Comment by abhi03ruchi** [comment]
<img width="1408" alt="Screenshot 2024-10-19 at 12 30 28 AM" src="https://github.com/user-attachments/assets/986ac0cb-50ae-45b6-8bbe-a704b8ef433a">
the translate button in footer of other pages ( like login etc...) doesnt work . 
And some pages of the website don't have translate button . 
U can work on this issue .

**Comment by Mayanksaininh** [comment]
@abhi03ruchi thanks for addressing me
