### ISSUE TITLE
BUG: Translate button drop down menu css is not working properly

### ISSUE THREAD

**Issue by im-AyanRoy** [anuragverma108/SwapReads#3723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-18 233325](https://github.com/user-attachments/assets/73cadee2-fdb6-4839-9b58-5aa75f5fd292)

css is not applied properly

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the translate button is only on the homepage , not on all pages . 

U can work on this issue and raise pr .
