### ISSUE TITLE
Adding testimonials.

### ISSUE THREAD

**Issue by sharmi4590** [anuragverma108/SwapReads#374]
Hey @anuragverma108 
### Describe the feature

Adding testimonials which is placed above the footer , always makes user experience much better and user always searches for reviews before making a purchase . So a pleasant testimonials will make the website much better.By this we can also give rating to the books as well.

### Add ScreenShots

This is my previous work regarding testimonials.
![Screenshot (387)](https://github.com/anuragverma108/SwapReads/assets/102676949/262e4eee-39c1-40ec-8b76-2e8b15f6fb84)
![Screenshot (388)](https://github.com/anuragverma108/SwapReads/assets/102676949/e0e924a3-82cd-450a-b89c-890966ca3eb4)
On placing cursor on each testimonial will flip it and show the review.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
the idea is good but design is not going with the theme so please make a good design which goes well with theme!!

**Comment by souravgope** [comment]
i will make best ui on the testimonials  please assign me

**Comment by anuragverma108** [comment]
@sharmi4590 
Great contribution to GSSOC'24! 🎉
