### ISSUE TITLE
Feat: Swap History & Achievements

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [anuragverma108/SwapReads#3742]
### Describe the feature

Gamify the platform by awarding badges or rewards based on swapping history or reaching milestones. can add this option after user login successfuly

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
are u working on the issue? 

how will u implement this feature.

**Comment by SanikaBhalerao1345** [comment]
i will add this option bubble at the side here.
![image](https://github.com/user-attachments/assets/65c802bf-305d-416b-9dd4-d6eb032236ba)
and will create a new webpage where I will add badges information (some cool badges image and when user can unlock them)  and at bottom of page will create a bottom that asks user to login to see your achievement history

**Comment by abhi03ruchi** [comment]
in profile avatar there is my profile , u can add there . 

u can also enhance the page .

**Comment by abhi03ruchi** [comment]
acheivement of user will be based on number of contributions they have made in the website ?

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi ok in pofile avatar i will check. 
and i was just thinking of stating the information about generalized badges(achievements) on new web-page and on clicking the button user will be directed to login page.
there will be no connection btw contributors to this section... is that ok?

**Comment by abhi03ruchi** [comment]
the information about generalized badges(achievements) on new web-page . what achievement ?

**Comment by SanikaBhalerao1345** [comment]
like for starting with new book user will get a star like badge, as he complete 5 books he will earn another badge, likewise for various operations like for sharing, commenting finishing x books in minimum days user will earn badges( which will add up their points) 
and if user achieves specified points he/she can get premium services or any additional service for specified time.
@abhi03ruchi likewise I will display it on web-page
