### ISSUE TITLE
Feat: Can add a loading page with nice loader

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [anuragverma108/SwapReads#3745]
### Describe the feature

as the user visits the home page, some website loading is taking place I can add a creative loader for view enhancement of  the website

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
are u working on this issue?

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi yes will raie pr till Eve 
Thanks

**Comment by SanikaBhalerao1345** [comment]
@abhi03ruchi okk
