### ISSUE TITLE
BUG: Navbar Alignment and Spacing Issue

### ISSUE THREAD

**Issue by MadhavDhatrak** [anuragverma108/SwapReads#3746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar currently has several design issues affecting its usability and visual alignment. These problems negatively impact the user experience, especially on different screen sizes or when navigating the menu.

### Problems:

1. **Inconsistent Spacing Between Menu Items:**
   - The spacing between menu items like "Home", "About Us", "Benefits", etc., is uneven or too cramped, making the text harder to read and the layout look cluttered.

2. **Misaligned Icons:**
   - The avatar/profile image on the far right is not aligned properly with the text and other icons. This creates an unbalanced visual layout in the navbar.

3. **Text Overflow:**
   - The "Audiobooks" text is being cut off or overflowing next to the toggle icon, reducing clarity and causing confusion. This seems like a width or padding issue in the CSS.

4. **Inconsistent Font Sizes:**
   - Some menu items like "Rate Us" and "Login" have smaller font sizes compared to others, like "Community Spotlight" and "Benefits", resulting in an uneven visual hierarchy.

5. **Lack of Padding on Outer Elements:**
   - The logo and profile avatar are too close to the edges of the navbar, which makes the layout feel crowded.

### Desired Solution:

1. **Adjust Spacing:**
   - Ensure even and consistent spacing (using `margin` or `padding`) between all the menu items to make the layout visually balanced and readable.

2. **Align Icons Correctly:**
   - Use flexbox or proper alignment techniques (e.g., `vertical-align: middle;` or `display: flex; align-items: center;`) to make sure the profile image and other icons are aligned with the text elements.

3. **Fix Text Overflow:**
   - Adjust the width, padding, or text wrapping to prevent the "Audiobooks" text from being cut off, ensuring it remains fully visible at all screen sizes.

4. **Standardize Font Sizes:**
   - Ensure all menu items use the same font size for consistency across the navbar.

5. **Add Padding to Outer Elements:**
   - Add appropriate padding to the logo and profile image so they don't appear too close to the edges of the navbar, improving the overall layout.

### screenshot
![Screenshot (480)](https://github.com/user-attachments/assets/3fdc699b-af84-4443-afd5-726c346e46a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratikpawar13** [comment]
@anuragverma108 sir please assign me this issue.

**Comment by HarshKumar1121** [comment]
i have previously work on same problems would you like to assign this to me .
