### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by abhi200446** [anuragverma108/SwapReads#3766]
### Describe the feature

the image and the toogle button are went outside page assign @sailaja-adapa 
![image](https://github.com/user-attachments/assets/184a42b6-9683-4832-a2e9-36cd3e720508)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fe6f5cbe-89da-4503-b08a-8737c58d65e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sameer-soni** [comment]
can i get assigned to this issue? I will fix it today
