### ISSUE TITLE
Feat: Profile picture and theme switch toggle button are overlapped.

### ISSUE THREAD

**Issue by Adityadhiman0** [anuragverma108/SwapReads#3778]
### Describe the feature

Profile picture and theme switch toggle button are overlapped in Explore New Worlds page.

### Add ScreenShots

![Screenshot 2024-10-20 024159](https://github.com/user-attachments/assets/72322e73-133d-4136-ad17-718025514931)

![Screenshot 2024-10-20 023254](https://github.com/user-attachments/assets/be5076cf-9936-431f-aeb5-0ee807d8f68c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sameer-soni** [comment]
Can i get assigned to this issue?

**Comment by abhi03ruchi** [comment]
raise a pr for the issue, it will be reviewed and level will be assigned there based on ur work . 

here , github bot assigns issue by default .
