### ISSUE TITLE
Feat: Add icons in contact page.

### ISSUE THREAD

**Issue by Adityadhiman0** [anuragverma108/SwapReads#3779]
### Describe the feature

I want to add icons on contact page before labels.

### Add ScreenShots

![Screenshot 2024-10-20 025129](https://github.com/user-attachments/assets/0c2869bf-0065-4320-b3c9-75aeb943fbaf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratikpawar13** [comment]
@Adityadhiman0 Dear sir can you please assign me this issue , I'll make sure to you I'll complete the task as early as possible.

**Comment by abhi03ruchi** [comment]
raise a pr for the issue, it will be reviewed and level will be assigned there based on ur work . 

here , github bot assigns issue by default .
