### ISSUE TITLE
BUG: No icon in Some pages

### ISSUE THREAD

**Issue by SrijaVuppala295** [anuragverma108/SwapReads#3789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/230979af-afaa-4cc6-a769-5a84a47793e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Raj-banerjee25** [comment]
Can you assign this issue this to me
