### ISSUE TITLE
BUG: Scroll to top UI

### ISSUE THREAD

**Issue by nisargaa20** [anuragverma108/SwapReads#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Scroll to top is in written words . Symbol of the above arrow mark will be better .

![SwapReads - Google Chrome 14-05-2024 19_13_01](https://github.com/anuragverma108/SwapReads/assets/125184228/c88913c0-0e85-4de1-9eb5-ed416783d29f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Scroll to top is in written words . Symbol of the above arrow mark will be better .
> 
> ![SwapReads - Google Chrome 14-05-2024 19_13_01](https://github.com/anuragverma108/SwapReads/assets/125184228/c88913c0-0e85-4de1-9eb5-ed416783d29f)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

yes! work on it!
