### ISSUE TITLE
BUG:Navbar is not aligned properly

### ISSUE THREAD

**Issue by pratapVansh** [anuragverma108/SwapReads#3795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

home and about us in navbar is not aligned properly.
![swapreadsbefore](https://github.com/user-attachments/assets/3214f953-bdee-4657-b946-a046f559b67c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratikpawar13** [comment]
@anuragverma108 Dear sir can you please assign me this issue to me, I'll solve this issue as early as possible .
