### ISSUE TITLE
Feat: Dark mode lacks UI .

### ISSUE THREAD

**Issue by sshivangi882** [anuragverma108/SwapReads#380]
### Describe the feature

In dark mode the logo is not visible and card are not shown  all are black, let me fix it.

### Add ScreenShots

![Screenshot (862)](https://github.com/anuragverma108/SwapReads/assets/122531720/4d18a876-0b8b-43fc-b55d-4907c97742b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> In dark mode the logo is not visible and card are not shown  all are black, let me fix it.
> 
> ### Add ScreenShots
> 
> ![Screenshot (862)](https://github.com/anuragverma108/SwapReads/assets/122531720/4d18a876-0b8b-43fc-b55d-4907c97742b9)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

sure fix it @sshivangi882 ! 
i am the mentor of this project and react to any help!
