### ISSUE TITLE
BUG: Update the Icon of the Twitter.

### ISSUE THREAD

**Issue by itskundanhere** [anuragverma108/SwapReads#3802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the Home page the icon of the twitter is old. I want to update it.
![Screenshot 2024-10-20 202020](https://github.com/user-attachments/assets/4f26d237-fc67-488f-ae35-d66dd525fc99)

please assign me @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the footer on this page , does not align with the theme of the website . add footer similar to the one on the homepage .

 u can work on this issue .  create a new issue and raise pr .
