### ISSUE TITLE
Creating Site Map Page

### ISSUE THREAD

**Issue by VidhanThakur09** [anuragverma108/SwapReads#3838]
This issue proposes the creation of a site map page for the project. A site map is a visual representation of the website's structure, making it easier for users to navigate and find the information they need. It will act as a centralized hub, providing a clear overview of all the available pages and their relationships.

### Use Case:

- **User Navigation:** The site map will serve as a valuable tool for users to quickly locate specific pages or sections within the website.
- **Search Engine Optimization (SEO):** A well-structured site map can improve the website's visibility in search engine results by providing a clear path for search engines to crawl and index content.
- **Accessibility:** The site map will enhance accessibility for users with disabilities, as it offers a visual representation of the website's structure.

### Benefits:

- **Improved User Experience:** A site map enhances user experience by making it easier for users to find their desired information.
- **Better Search Engine Rankings:** A well-optimized site map can boost the website's search engine rankings.
- **Enhanced Accessibility:** The site map improves accessibility for users with disabilities.
- **Clearer Website Structure:** The site map provides a clear visual representation of the website's structure, making it easier to understand and maintain.

@sailaja-adapa can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
@sailaja-adapa and  @anuragverma108 please review this issue.

**Comment by abhi03ruchi** [comment]
ok , u can work on this issue and raise a pr .
