### ISSUE TITLE
Feat: Hover effect to social links

### ISSUE THREAD

**Issue by SalehaTabassum** [anuragverma108/SwapReads#384]
### Describe the feature

I found that there is no hover effect to social media links . I want to add hover effects to them 

### Add ScreenShots

![Screenshot_2024-05-14-21-07-34-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/anuragverma108/SwapReads/assets/169278740/180d122e-cf73-4cc6-a5dd-07e57f98933b)

If we add hover effects it will make it look attractive 

So please assign this issue to me under GSSOC 2024 and add necessary labels 
@anu

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KashishRathore** [comment]
Please assign this task to me @anuragverma108. I have good hand on hovering effects and worked a lot. Looking forward to contribute.
