### ISSUE TITLE
Feat: can add some more audio books for premium subscription

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [anuragverma108/SwapReads#3856]
### Describe the feature

can add audio books that only accessible if user have premium subscription 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f16a889e-44b5-4068-ac40-ece800dcb3d9)

add this section just below all-user-access audiobooks

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SanikaBhalerao1345** [comment]
hii @abhi03ruchi can u pls assign me this so i can raise pr

**Comment by abhi03ruchi** [comment]
read the message given by github bot above . 

github bot assigns everyone issue with these labels by default . 
work on the issue and raise pr . depending on ur work , we will review , assign level and merge ur pr .
