### ISSUE TITLE
BUG: Navbar not aligned properly 

### ISSUE THREAD

**Issue by Arveti-likhitha** [anuragverma108/SwapReads#3857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After navigating to the benefits page when clicked on the read more in the benefits section, the navbar is not aligned to the top of the page.

![image](https://github.com/user-attachments/assets/d28bc20d-3d77-42e0-b790-d7439bb345f7)

![image](https://github.com/user-attachments/assets/d108bbd3-6980-46dd-b747-fa7f61c0b51b)

I would like to fix this issue.

Please assign this to me with the labels: gssoc-extd, hacktoberfest, hacktoberfest-accepted

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshKumar1121** [comment]
assign this to me .
