### ISSUE TITLE
BUG: navbar for mobile view

### ISSUE THREAD

**Issue by jainaryan04** [anuragverma108/SwapReads#3869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

navbar is not visible on all pages for mobile view
![image](https://github.com/user-attachments/assets/36f81979-9ce4-4ae4-b436-28b77443441c)
![image](https://github.com/user-attachments/assets/1128ca99-c1b3-41e7-9092-a1a0447cdfd8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshKumar1121** [comment]
assign this to me
