### ISSUE TITLE
Adding styling in the cards

### ISSUE THREAD

**Issue by Manishar55** [anuragverma108/SwapReads#387]
### Describe the feature

Hii @anuragverma108 
The cards in the "LITERARY REALMS " section is looking very simple.
I want to make it more attractive, I will add styling and hover effect according to the theme of the website. 
Can you please assign this task to me under GSSOC24 so that I can make it more attractive.

### Add ScreenShots

![Screenshot 2024-05-14 211740](https://github.com/anuragverma108/SwapReads/assets/154615478/6376c990-0ef5-48f4-b0c8-6e5cf80bd422)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @Manishar55 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by Shivani-Hiremath** [comment]
Can I contribute to this??

**Comment by vaishnavip27** [comment]
Hey @anuragverma108 I would love to work on this issue. I can make the UI look more attractive. Please assign me this issue. Looking forward for the apporval

**Comment by rounakdey6** [comment]
@anuragverma108 Sir , I would like to work on this issue. Please assign this work to me.
