### ISSUE TITLE
DOC: Enhancing the Book Recommendation Section.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [anuragverma108/SwapReads#3871]
### What's wrong with the existing documentation

Light Mode:
No hovering of footer sections links and Translate Button.
Improving the get recommendations button.
Elements in footer are not properly aligned.
Dark Mode:
Adding appropriate hover for the dark-mode.
The logo "X" is not visible on hovering in dark-mode.

### Add ScreenShots

Light Mode:
https://github.com/user-attachments/assets/ea60ade6-83d7-4af7-9509-14b84e8929ed

Dark-Mode:

https://github.com/user-attachments/assets/822c9c0c-90c8-4c12-b510-da2363e0bf5a

Please can you assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok , work on the issue and raise pr.
