### ISSUE TITLE
Feat: adding social icons to the left side of the website

### ISSUE THREAD

**Issue by Theboycut05** [anuragverma108/SwapReads#3886]
### Describe the feature

the side icons on the right of the website will make it interactive and catch the attention of the users and its responsive.

### Add ScreenShots

https://github.com/user-attachments/assets/3d571235-bd71-4b11-a8e1-2297a8a52ed9

https://github.com/user-attachments/assets/8e52aa14-9e48-4de6-b447-ffddd7ed5c32

![Screenshot (80)](https://github.com/user-attachments/assets/5224ce1a-722e-4587-b2f2-327cc592d8de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KanishkRaj-RAKA** [comment]
Hii, i'm Kanihk raj, can you assign me this issue

**Comment by abhi03ruchi** [comment]
the icons are already there on the left side of the website.
