### ISSUE TITLE
BUG: CLOSE SIGN ON LOGIN PAGE IN DARKMODE VISIBILITY ISSUES

### ISSUE THREAD

**Issue by sanskritilabroo** [anuragverma108/SwapReads#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In darkmode, while accessing the login page, the cross sign is too low and barely visible.
<img width="167" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/86831838/edd08888-84e5-4bde-b272-08e3fcb2f536">

I can move this cross sign higher so it is properly visible. please assign me this task as a contributor under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by RitiChandak** [comment]
completed by #399
