### ISSUE TITLE
Fixing the buttons section in footer

### ISSUE THREAD

**Issue by Jagpreet153** [anuragverma108/SwapReads#39]
The buttons in the footer takes user directly to the top of the page not to the required section . I would like to fix it . Kindly assign this task to me under GSSoC'24 .It would be a great opportunity to contribute in open source community.  

![Screenshot 2024-05-10 113932](https://github.com/anuragverma108/SwapReads/assets/119691733/3fe29a55-b1d1-4b9e-bf19-95e293476ed0)

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Jagpreet153** [comment]
@anuragverma108 Could you please clarify whether the reviews button is to be added or not as there is no such reviews section in the page and also in navbar

**Comment by anuragverma108** [comment]
Replace it with Contact.

**Comment by Jagpreet153** [comment]
@anuragverma108 I have generated PR kindly review it.....
