### ISSUE TITLE
BUG: UI and color palette in login page.

### ISSUE THREAD

**Issue by justmirr** [anuragverma108/SwapReads#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar and the login box in dark mode add UI issues to the site so I'll fix the color palette matching with the main site as well as the navbar.
![darkmode](https://github.com/anuragverma108/SwapReads/assets/75358919/cbd12463-18fd-4468-9c24-19bd7e496aa0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by justmirr** [comment]
Sure @anuragverma108, thanks for assigning me this issue!
