### ISSUE TITLE
Feat: Adding theme to the About us Page.

### ISSUE THREAD

**Issue by Deepika14145** [anuragverma108/SwapReads#3955]
### Describe the feature

Adding dark mode to the about us page so that user can toggle in between light and dark mode as per their convenience.

Benefits: Since the dark mode is only added to the main page not about us page, addinng dark mode to this page will make this website user friednly.

### Add ScreenShots

![Screenshot 2024-10-24 120339](https://github.com/user-attachments/assets/e2b24fae-fb7c-4462-8f22-6500f9fc8ffa)

Please assign me this issue and add labels like levels as per your convenience, hacktoberfest-accepted, and gssoc-extd @

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
are u working on this issue ?
