### ISSUE TITLE
Feat: Add Cursor Tail Effector 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [anuragverma108/SwapReads#3960]
### Describe the feature

Only Home page have Cursor Tail Effector, which doesn't look good.

I want to add a Cursor Tail Effector in both Community Spotlight & Audio Books page

PA please assign me this task.

https://github.com/user-attachments/assets/2218d9ef-d8aa-40ec-9f04-8c3aa6c138d0

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the cursor tail effector is not present in many pages . add the special cursor to all the pages in the website . 

u can work on this issue and raise a new pr .
