### ISSUE TITLE
BUG: Validation required in both signup and login page

### ISSUE THREAD

**Issue by BHS-Harish** [anuragverma108/SwapReads#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**I have noticed following issues in Signup/Login Page:**
- Both the Sign and Login page, The field are not validated. The form was submitted without filling data.
- The register button doesn't have enough space at bottom. It is overflow from the form.

**Screen shot**

![Screenshot 2024-05-14 221955](https://github.com/anuragverma108/SwapReads/assets/114602603/f712ca0f-27d3-4622-8cd7-cfdfb928f1cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BHS-Harish** [comment]
Hey @anuragverma108 

I would like to solve the issue.
Please assign the issue to me

Thanks in advance.

**Comment by anuragverma108** [comment]
Assigned! @BHS-Harish 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
