### ISSUE TITLE
BUG:Adding Hover Effect on Profile Avatar

### ISSUE THREAD

**Issue by QaisarMoin** [anuragverma108/SwapReads#3977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, the profile avatar lacks visual feedback when hovered over, leading to a static and less engaging user experience. Adding a hover effect will improve interactivity and provide a better user interface.
<img width="1470" alt="Screenshot 2024-10-25 at 1 48 25 AM" src="https://github.com/user-attachments/assets/dbc479c7-a811-4bef-b85d-3debb81f5855">

please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshKumar1121** [comment]
assign this to me
