### ISSUE TITLE
Feat: Change in background when dark mode is on using toggle button

### ISSUE THREAD

**Issue by Pratik-Tech-Wizard** [anuragverma108/SwapReads#3996]
### Describe the feature

Implementing a toggle button to switch to dark mode will change the background color of the application to a darker shade, enhancing visibility and reducing eye strain for users in low-light environments. This feature allows users to customize their viewing experience according to their preferences. Additionally, it improves the overall user interface by providing a modern and visually appealing aesthetic.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/61e1ea3d-a33e-4d82-84d2-633cdda65e2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
which page has this issue ? be specific.
