### ISSUE TITLE
[FEAT]; Add navbar to the login page

### ISSUE THREAD

**Issue by dakshsinghrathore** [anuragverma108/SwapReads#40]
**Describe the bug**
Currently the login/signup page is missing a navbar which makes the UX bit jarring, hence planning to create a navbar aligning with the design in the homepage

**Screenshots**
![image](https://github.com/anuragverma108/SwapReads/assets/115932772/6923d98e-2fd1-4f73-9008-57dba721bbe7)

**Comment by dakshsinghrathore** [comment]
@anuragverma108 kindly assign me this issue

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Abdal192003** [comment]
Hi @anuragverma108,
Could you please assign me this issue under gssoc'24 . I will try best to solve this issue. 
Thanks

**Comment by dakshsinghrathore** [comment]
@Abdal192003 I guess you are new to open source particularly GSSOC24, at the top right of the issue you can see that this issue is already assigned to me, would suggest you to create a new issue of your own or look for those issue which aren't assigned yet.

**Comment by Abdal192003** [comment]
@dakshsinghrathore 
Yes bro i'm new in open-source .
ok i look for other issue.
Thanks

**Comment by anuragverma108** [comment]
Any Updates @dakshsinghrathore

**Comment by lassmara** [comment]
Please assign me this issue.
