### ISSUE TITLE
Feat: Adding a ChatBot Assistant 

### ISSUE THREAD

**Issue by aryansharma220** [anuragverma108/SwapReads#400]
### Describe the feature

We should add a chatbot assistant which will suggest people which book they want on the basis of prompts they profide.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/133234867/1d70bb64-34da-458e-b024-f10292488486)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @aryansharma220 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by sanskritilabroo** [comment]
I would also like to work on this issue as a GSSOC'24 contributor. @aryansharma220 Can we work on this feature together?

**Comment by sanskritilabroo** [comment]
@anuragverma108 Please assign me this task too, as I already have prior experience in creating a basic chatbot for websites and can add my contributions here.
