### ISSUE TITLE
Alignment of map is not proper

### ISSUE THREAD

**Issue by Kajalmehta29** [anuragverma108/SwapReads#4005]
<img width="973" alt="Screenshot 2024-10-25 at 10 58 29 PM" src="https://github.com/user-attachments/assets/be1c117c-5c36-4de4-81ad-97fc4adc3a54">

Map should be aligned a bit leftwards. 
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by HarshKumar1121** [comment]
assign this to me i would like to resolve this for you
