### ISSUE TITLE
Feat: Update the image on the landing page to better convey the vision and mission of Swap Reads.

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#402]
### Describe the feature

The current image on the landing page of Swap Reads does not fully encapsulate the essence of what Swap Reads stands for. Swap Reads is the ultimate online destination for book enthusiasts to connect, exchange favorite reads, and embark on literary adventures. The landing page image should clearly communicate this vision to new and returning users.

**Objectives**:
1. **Communicate Vision**: The new image should visually represent Swap Reads as a platform where book enthusiasts can connect, exchange books, and join a vibrant community.
2. **Appeal to Target Audience**: The image should attract our target audience—book lovers and avid readers.
3. **Enhance Aesthetic Appeal**: The image should be visually appealing and align with the overall design and theme of the website.

**Suggested Image Requirements**:
- **Content**: The image should feature elements such as books, people reading, or an exchange of books in a community setting.
- **Tone and Style**: Friendly, inviting, and community-oriented.
- **Quality**: High resolution and professional quality to ensure it looks good on all devices.

**Steps to Implement**:
1. **Image Selection**: Choose or create an image that meets the above criteria. Consider using platforms like Unsplash, Pexels, or custom illustrations.
2. **Update Code**: Replace the current image file in the repository with the new image.
3. **Edit HTML/CSS**: Update the HTML and CSS files to incorporate the new image. Ensure that the new image is properly scaled and positioned on the landing page.
4. **Testing**: Test the new image on various devices and screen sizes to ensure it looks good across all platforms.
5. **Review and Merge**: Submit a pull request for the change. Once reviewed and approved, merge the change into the main branch.

**Conclusion**:
Updating the landing page image to better reflect Swap Reads' vision will enhance the user experience and attract more book enthusiasts to join our community. This change will help in creating a more inviting and engaging platform for our users.

### Add ScreenShots

![picture](https://github.com/anuragverma108/SwapReads/assets/129655645/0cf56a7f-2d5c-4436-bfeb-02c280734225)
Replace it!

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by iamanolive** [comment]
hi @anuragverma108 i'd love to work on this!

**Comment by Madhu-mac** [comment]
@anuragverma108 Assign it to me! I'll work on it...

**Comment by anuragverma108** [comment]
Assigned! @iamanolive 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by anuragverma108** [comment]
@Madhu-mac 



Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by iamanolive** [comment]
> Assigned! @iamanolive Make sure to attach before & after screenshot in your PR. Make sure to star the repo before working on it! Happy open-source contributing!

thank you so much @anuragverma108 will do!

**Comment by chakma21** [comment]
Hello @anuragverma108 
I would like to contribute to this issue on your project; would be glad if you assign it to me!.

**Comment by iamanolive** [comment]
hi @anuragverma108 i've created a rough design on canva. could you please check it out and suggest any changes if required? then i'll proceed with inserting it into the website.

**Comment by anuragverma108** [comment]
Yeah sure!
Share the link ??

**Comment by iamanolive** [comment]
@anuragverma108 any suggestions?

**Comment by anuragverma108** [comment]
Just add  book picture or reader reading book. Don't write any text. As we will just put in the right side of the landing page .

**Comment by iamanolive** [comment]
got it, can i leave the thought bubbles though? or do those also have to be removed?

**Comment by iamanolive** [comment]
got it, can i leave the thought bubbles though? or do those also have to be removed? @anuragverma108
