### ISSUE TITLE
BUG: Add Cursor Tail Effector in all pages

### ISSUE THREAD

**Issue by Subhajit-2023-44** [anuragverma108/SwapReads#4022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add a Cursor Tail Effector in all page, Events, Login, About us page
PA please assign me this task.

https://github.com/user-attachments/assets/d282517b-1f44-4141-b06b-4a084220c286

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
