### ISSUE TITLE
BUG: Not allign Navbar at Center

### ISSUE THREAD

**Issue by KrishChothani** [anuragverma108/SwapReads#4028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
Not allign navbar at center at https://swapreadsconnect.netlify.app/lol
![image](https://github.com/user-attachments/assets/6eb47d73-f19d-4613-82cb-fb866c423151)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshKumar1121** [comment]
assign this to me
