### ISSUE TITLE
BUG: Resizing the Navbar.

### ISSUE THREAD

**Issue by rishmiiee26** [anuragverma108/SwapReads#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108 For the Navbar styling, as it need some change.  Kindly assign me the task. Thank You

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @rishmiiee26 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by rishmiiee26** [comment]
Thank You, so much for the assignment !
Excited to contribute and make some changes.

Regards
