### ISSUE TITLE
BUG: Navbar Overlapping on Benefits Page Scrolling

### ISSUE THREAD

**Issue by Chitrakadyan2005** [anuragverma108/SwapReads#4041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
The navigation bar (navbar) is overlapping with the content on the Benefits page, making it difficult for users to scroll and read the information properly. This issue affects user experience, as it obscures important details and hampers navigation.

Steps to Reproduce:

Navigate to the Benefits page.
Attempt to scroll down the page.
Observe that the navbar remains fixed at the top, covering part of the content.

Expected Behavior:
The navbar should not overlap with the content. Users should be able to scroll through the Benefits page without any obstruction from the navbar.

please assign it to me under GSSOC'24EXTD, hacktoberfest'24 and level labels
@abhi03ruchi 

https://github.com/user-attachments/assets/8aa3db8f-8c31-404c-9317-f2ab1ccc799c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok . work on the issue and raise pr .
