### ISSUE TITLE
BUG: Adding Hover Effect in the Rate Us page buttons.

### ISSUE THREAD

**Issue by rishmiiee26** [anuragverma108/SwapReads#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108 For Adding the Hover Effect in the ![Screenshot 2024-05-15 at 00-16-36 Rate Us](https://github.com/anuragverma108/SwapReads/assets/154092772/ad46ad41-2c3e-4b94-bee2-d2df876bf877)( submit rating) button & Home button at the leftmost corner of the page. Kindly assign me the task. Thank You

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Message me on Discord - anuragverma_108
I want to discuss something to change UI of this Rate Us Page.

**Comment by Lakshmi060** [comment]
I would like to work on this project. I'm GSSOC 24 Contributor. Please assign it to me.

**Comment by souravgope** [comment]
i want to work on this issue
please assign me

**Comment by anuragverma108** [comment]
@Lakshmi060 @souravgope 
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by PSTabaswiniSivamorthy** [comment]
I am interested to do this task , please assign me
