### ISSUE TITLE
BUG:  Unnecessary Spacing Above Content Cards

### ISSUE THREAD

**Issue by SumaLatha2023** [anuragverma108/SwapReads#4089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Donate Books" section on the website has a noticeable gap between the heading and the content cards (Library, Schools, Organizations). 
This large gap creates an imbalanced look, making the heading appear disconnected from the content below, which may affect the visual flow and user experience.

![Screenshot 2024-10-27 154018](https://github.com/user-attachments/assets/5f1e3013-6786-43d1-98e7-3c2cf70cb6aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshKumar1121** [comment]
please assign this to  me  i will complete this within few hours
