### ISSUE TITLE
Feat: navbar gone out of the display and social media icons hiding the content behind it

### ISSUE THREAD

**Issue by DevROHIT11** [anuragverma108/SwapReads#4097]
### Describe the feature

As the navbar ratio is disturbed is going out of the display screen and the social media icons are overlapping with the content on homepage , i would like to make changes on this issue 
Some suggestion from my side that :-
1. adding that social media icons to footer will make the page more good .
2. fixing the navbar ratio and width 

please !! assign this task to me , I would like work on this because I really loved your Website.

### Add ScreenShots

![Screenshot (59)](https://github.com/user-attachments/assets/4d1ae698-1186-40ed-8690-fca59cff83be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this issue isnt there , u have zoom in too much , i guess.

**Comment by DevROHIT11** [comment]
https://github.com/user-attachments/assets/cce7976d-e1de-4b1c-ad69-0b89eb6b7150

@abhi03ruchi  please check this video i haven't zoomed the page the issue is still there ,is it bug? or any other ? i have to look so, please assign this to me

**Comment by abhi03ruchi** [comment]
this issue isnt there . 

u can work on other issues

**Comment by abhi03ruchi** [comment]
https://github.com/user-attachments/assets/662ed7d4-b94f-418e-a68b-bc79c4fd022b

enhance the UI of these pages ( LITERARY REALMS) SECTION  , no text is visible in the boxs .

**Comment by abhi03ruchi** [comment]
create a new issue , work on it . and then raise pr .

**Comment by DevROHIT11** [comment]
Okk thank you for assigning this task to me!!
