### ISSUE TITLE
BUG: Issue in Login Page

### ISSUE THREAD

**Issue by rupeshv2121** [anuragverma108/SwapReads#4115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Create new Account link not shown properly . And when we hover login button text not visible properly.

pls assign me under label gssoc-ext, hacktoberfest-accepted
@anuragverma108 @huamanraj 

https://github.com/user-attachments/assets/fbbab71d-b276-4a6d-b1ef-ec92f58c602d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this issue is already resolved . chk website.
