### ISSUE TITLE
Feat: Enhance the UI of LITERARY REALMS) SECTION

### ISSUE THREAD

**Issue by DevROHIT11** [anuragverma108/SwapReads#4117]
### Describe the feature

enhancing the UI of literary realms section as making it more attractive and making the text inside the boxes visible 

@abhi03ruchi  please assign this task to me , as I would like to contribute to your website 

### Add ScreenShots

![Screenshot (67)](https://github.com/user-attachments/assets/2c7dbfa2-2315-4b37-a114-f5a5b07b684b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevROHIT11** [comment]
can you please label this more than level 1 ??

**Comment by abhi03ruchi** [comment]
github bot assigns label by default . when u create pr , depending upon ur work , will assign u label .

**Comment by DevROHIT11** [comment]
@abhi03ruchi  I had completed my work so to which branch should i create pull request

**Comment by abhi03ruchi** [comment]
apne branch se main branch

**Comment by DevROHIT11** [comment]
And changes to commit on my branch or your branch??
