### ISSUE TITLE
Feat: In get in touch section map size is not proper.

### ISSUE THREAD

**Issue by Adityadhiman0** [anuragverma108/SwapReads#4134]
### Describe the feature

In get in touch section map size small in compare to width of the section. I want to fix it.

### Add ScreenShots

![Screenshot 2024-10-28 034634](https://github.com/user-attachments/assets/5754d5ce-6c15-4035-ae13-6188b9990169)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
it is ok .
