### ISSUE TITLE
FAQ section is not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [anuragverma108/SwapReads#414]
Hi, in the FAQ section the content is coming out of the box when screen size is reduced. I want to fix this as a contributor of GSSoC'24. Please assign me to this task.
![Screenshot 2024-05-15 020656](https://github.com/anuragverma108/SwapReads/assets/121669832/049c0e43-7cdb-429c-a22d-2a9583e9d9ea)

**Comment by anuragverma108** [comment]
Assigned! @nagalakshmi08 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by nagalakshmi08** [comment]
> Assigned! @nagalakshmi08 Make sure to attach before & after screenshot in your PR. Make sure to star the repo before working on it! Happy open-source contributing!

Okay sure ! Thanks for assigning me.
