### ISSUE TITLE
Feat:"Have a question" below contact us is not visible

### ISSUE THREAD

**Issue by JOSHITHA6** [anuragverma108/SwapReads#4141]
### Describe the feature

I have observed that the contact us section has "Have a question" which is not visible to the users. Kindly assign this issue to me under gssoc'24 extd and hacktoberfest 

### Add ScreenShots

![Screenshot (237)](https://github.com/user-attachments/assets/5a8c65b4-3427-4e81-b4dd-89a064d35e54)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
just remove ( have a question and get in touch ) text from the section.

work on the issue , and raise pr .

**Comment by JOSHITHA6** [comment]
> just remove ( have a question and get in touch ) text from the section.
> 
> work on the issue , and raise pr .

Okay

**Comment by JOSHITHA6** [comment]
![Screenshot (245)](https://github.com/user-attachments/assets/bacbf1af-b5dc-41f2-998f-760eb4838c6b)
@abhi03ruchi done. Please accept my pr under level 2 or level 3
