### ISSUE TITLE
Feat:Adding signup page

### ISSUE THREAD

**Issue by JOSHITHA6** [anuragverma108/SwapReads#4144]
### Describe the feature

I have found that the signup page is missing here. I would love to add it. So, please assign me this task under gssoc'24 extd label-2  and hacktoberfest 

### Add ScreenShots

![Screenshot (241)](https://github.com/user-attachments/assets/fc386821-be05-4386-a31f-ffea76deb8e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
chk again , create account is present .
