### ISSUE TITLE
Feat:Enhance the copyrights section

### ISSUE THREAD

**Issue by JOSHITHA6** [anuragverma108/SwapReads#4145]
### Describe the feature

The footer page's copyrights section is not properly seen. I would love to work on this. Kindly assign this issue to me under gssoc'24 extd and hacktoberfest

### Add ScreenShots

![Screenshot (242)](https://github.com/user-attachments/assets/2471ad7a-e8c9-48a8-9890-81f480ab757e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
whats the issue with the footer ? explain properly . 

#4084 is already working on enhancement of the page.

**Comment by JOSHITHA6** [comment]
The copyrights part is not visible to the users properly. I want to enhance it by improving the font color. This will increase the visibility and would be better for the users. Copyrights is an important section which cannot be neglected.

**Comment by abhi03ruchi** [comment]
it is visible .
