### ISSUE TITLE
Logo Change

### ISSUE THREAD

**Issue by Honey22205** [anuragverma108/SwapReads#415]
### Describe the feature

a fresh logo design featuring a fitting quotation for the website

### Add ScreenShots

<img width="447" alt="swap" src="https://github.com/anuragverma108/SwapReads/assets/153267539/2b6ede4a-ad6a-458b-814f-90e58826e03c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @Honey22205 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by nilesh5566** [comment]
can you please assign this issue to me #415?
