### ISSUE TITLE
Feat: Enhance Accessibility: Implement Multi-Language Support for a Global Audience

### ISSUE THREAD

**Issue by Ankul8471** [anuragverma108/SwapReads#4153]
### Describe the feature

To make our platform more inclusive and accessible to users worldwide, we propose adding multi-language support. By integrating a language translator, we can break down language barriers, enabling a smoother experience for non-native speakers and expanding our reach. This feature will allow users to select their preferred language, creating a more personalized and user-friendly interface. Let’s work together to create a truly global platform

### Add ScreenShots

![Screenshot 2024-10-28 140535](https://github.com/user-attachments/assets/0699c092-755a-4025-a0fb-84a89044257b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ankul8471** [comment]
please assign me this issue

**Comment by abhi03ruchi** [comment]
translate button is there on the homepage .
