### ISSUE TITLE
BUG:The translate button near the footer is not working

### ISSUE THREAD

**Issue by JOSHITHA6** [anuragverma108/SwapReads#4165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While clicking on the translate button, its not working. Either it must be removed or functionality for translate must be added. But its better to remove coz already main page consists the translate option which reflects to all web pages.

![Screenshot (242)](https://github.com/user-attachments/assets/74e530c2-3842-4921-b78c-4c5b6d4ed638)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
a contributor is already working on this issue . 

u may work on other issues .
