### ISSUE TITLE
BUG:I have found some unnecessary stuff being available on main page

### ISSUE THREAD

**Issue by JOSHITHA6** [anuragverma108/SwapReads#4170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have found unecessary stuff available on main page. Looks like somebody made some changes previously and might be the effect. I shall remove it. Kindly assign this issue to me under gssoc'24 extd and hacktoberfest

![Screenshot (247)](https://github.com/user-attachments/assets/a92008b6-3776-4bc9-8670-435b2c9a667b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this issue isnt there . chk again .

**Comment by JOSHITHA6** [comment]
okay
