### ISSUE TITLE
Feat: Add Animation to Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [anuragverma108/SwapReads#420]
### Describe the feature

The current dark/light mode toggle lacks animation, resulting in a sudden change in appearance that can be jarring for users.

Implement animation effects to smoothly transition between dark and light modes when toggling. This could involve a fade effect, sliding animation, or similar transition to enhance the user experience.

One alternative would be to leave the toggle as it is without animation. However, adding animation can significantly improve user experience and aesthetic appeal.

I am an open-source contributor and would like to contribute this feature enhancement to the project.

### Add ScreenShots

Once you have assigned it then I will send the SS

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> The current dark/light mode toggle lacks animation, resulting in a sudden change in appearance that can be jarring for users.
> 
> Implement animation effects to smoothly transition between dark and light modes when toggling. This could involve a fade effect, sliding animation, or similar transition to enhance the user experience.
> 
> One alternative would be to leave the toggle as it is without animation. However, adding animation can significantly improve user experience and aesthetic appeal.
> 
> I am an open-source contributor and would like to contribute this feature enhancement to the project.
> 
> 
> ### Add ScreenShots
> 
> Once you have assigned it then I will send the SS
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
