### ISSUE TITLE
Improve performance of contactUs form

### ISSUE THREAD

**Issue by kushalkumar1362** [anuragverma108/SwapReads#421]
After submit the details input fields need to be clear for better user experience.

![Screenshot_20240515-072721.png](https://github.com/anuragverma108/SwapReads/assets/140513098/1f8b4675-cb97-43ce-8887-34d9bd51434c)

![Screenshot_20240515-072724.png](https://github.com/anuragverma108/SwapReads/assets/140513098/fae9836a-5b9d-4529-ae52-3cf9dc3857b2)

**Comment by huamanraj** [comment]
> After submit the details input fields need to be clear for better user experience.
> 
> ![Screenshot_20240515-072721.png](https://github.com/anuragverma108/SwapReads/assets/140513098/1f8b4675-cb97-43ce-8887-34d9bd51434c)
> 
> 
> ![Screenshot_20240515-072724.png](https://github.com/anuragverma108/SwapReads/assets/140513098/fae9836a-5b9d-4529-ae52-3cf9dc3857b2)
> 
> 

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by kushalkumar1362** [comment]
> open-source

Ok

**Comment by kushalkumar1362** [comment]
I will submit this in 2 days , unable to submit today because of my exam

**Comment by huamanraj** [comment]
> I will submit this in 2 days , unable to submit today because of my exam 

its okay 👍
