### ISSUE TITLE
Feat: Modify the home tab navbar 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [anuragverma108/SwapReads#4213]
### Describe the feature

Modify the home tab navbar 

### Add ScreenShots

Modify the home tab navbar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the navbar is congested , so u can add a MORE dropdown in the navbar .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
I will change whole nav bar in next issue mam

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
By adding more drop down
