### ISSUE TITLE
BUG : [UI] Navbar links do not have background transition

### ISSUE THREAD

**Issue by SaranshBangar** [anuragverma108/SwapReads#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text in the Navbar links have an animation, but their background does not have any. A transition can be applied on the background colour as well to improve UI

![image](https://github.com/anuragverma108/SwapReads/assets/114401238/663de9cf-74bf-4f4c-837a-aa85465bcde9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souravgope** [comment]
i want to work on this issue

**Comment by SaranshBangar** [comment]
> i want to work on this issue 

I am already working on it

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The text in the Navbar links have an animation, but their background does not have any. A transition can be applied on the background colour as well to improve UI
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/114401238/663de9cf-74bf-4f4c-837a-aa85465bcde9)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue


Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by anuragverma108** [comment]
@souravgope 
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by SaranshBangar** [comment]
Resolved in #431
