### ISSUE TITLE
BUG: adding responsiveness to header and dark mode to map pg

### ISSUE THREAD

**Issue by Riyachauhan11** [anuragverma108/SwapReads#4239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the header of map page isnt responsive right now and theres no dark mode available on page as well. I would like to fix these issues.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
add dark mode to authors page . 

u may work on this issue and raise pr .
