### ISSUE TITLE
add close button on pop up

### ISSUE THREAD

**Issue by Kajalmehta29** [anuragverma108/SwapReads#4242]
<img width="521" alt="Screenshot 2024-10-29 at 11 39 33 PM" src="https://github.com/user-attachments/assets/37e6bd3a-9919-4194-b020-391c33cfafd5">

I want to add a close button feature. Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by abhi03ruchi** [comment]
it doesnt need close button . it dissapears auto . 

chk #4217  .
