### ISSUE TITLE
Feat: Modified the download button 

### ISSUE THREAD

**Issue by SadafKausar2025** [anuragverma108/SwapReads#426]
### Describe the feature

the download button in explore freebook section was taking full width and was not looking good 
I modified the button to shot just like a button and now it looks much good 

### Add ScreenShots

![Screenshot (1718)](https://github.com/anuragverma108/SwapReads/assets/137484958/255b1b52-9b2c-4070-9283-18f68a19e0a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Karthikkariappa08** [comment]
Hi @SadafKausar2025,
I'm excited to tackle the task of adding more style to download button webpage. With my experience in website development using HTML, CSS, and JavaScript.

Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by anuragverma108** [comment]
@SadafKausar2025 @Karthikkariappa08 
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by SadafKausar2025** [comment]
before 
![Screenshot (1722)](https://github.com/anuragverma108/SwapReads/assets/137484958/7fd206e7-5ff7-46ac-8b6c-f72f170fdb55)

after
![Screenshot (1723)](https://github.com/anuragverma108/SwapReads/assets/137484958/4223fae9-e91f-4354-87e1-22228e5f815c)

**Comment by Karthikkariappa08** [comment]
Thank you for assigning this task .
