### ISSUE TITLE
Add navbar and footer section in the cookie policy page

### ISSUE THREAD

**Issue by Antima2004** [anuragverma108/SwapReads#4260]
### Describe the feature

This PR adds a consistent navbar and footer to the Cookie Policy page to improve navigation and user experience. The navbar provides links to major sections, and the footer includes links to important policies, aligning the Cookie Policy page with the overall site structure.

### Add ScreenShots

This:
![Screenshot 2024-10-30 12 17 57 PM](https://github.com/user-attachments/assets/3d634898-5abf-406a-ba0f-ab436a206cc1)

To this:
![Screenshot 2024-10-30 12 20 22 PM](https://github.com/user-attachments/assets/3c48dea4-82fd-4eba-ae1d-7479a5e06560)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
where is this page link in the home page ? in footer i am unable to see

**Comment by Antima2004** [comment]
cooki policy hover in that page
