### ISSUE TITLE
BUG:about page not found

### ISSUE THREAD

**Issue by dipak2005** [anuragverma108/SwapReads#4261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in the about us page only footer widget not any other section in about page
![Screenshot 2024-10-30 122707](https://github.com/user-attachments/assets/8409f2ff-fa8e-4b8e-844b-050c3566d968)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by avinashkrsingh01** [comment]
can you assign me this task?
