### ISSUE TITLE
BUG: Register Button and Submit Button Improper CSS

### ISSUE THREAD

**Issue by jain-anshika** [anuragverma108/SwapReads#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Register Button Issue 
- ## It is not looking good.
![image](https://github.com/anuragverma108/SwapReads/assets/115166105/5195d5dd-21ea-448e-9399-ff47ba9076c3)

# Submit button 
- ## It should be either white or have white gradient effect otherwise is it mixed with the background and overall the combination can be improved.
![image](https://github.com/anuragverma108/SwapReads/assets/115166105/354fd5bb-d2ae-4e2c-88dd-b8a353d9ecde)

Please assign this issue to me under GSSoC'24, I would like to contribute to this project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Karthikkariappa08** [comment]
Hi @jain-anshika,
I'm excited to tackle the task in login page. With my experience in website development using HTML, CSS, and JavaScript.



Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by anuragverma108** [comment]
Assigned! @jain-anshika 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by krati234** [comment]
assign this please
