### ISSUE TITLE
BUG: Change the cursor 

### ISSUE THREAD

**Issue by Mansi-Tanwar** [anuragverma108/SwapReads#4270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cursor is kind of annoying plus when you hover it over something it completely covers the content below. I would love to rectify this if you assign the task to me. 
![image](https://github.com/user-attachments/assets/40883871-237f-4d22-9c69-e21efb1219c4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
how will u rectify  ?

**Comment by Mansi-Tanwar** [comment]
we can make the cursor transparent as in any other website.

**Comment by abhi03ruchi** [comment]
the cursor is ok .

**Comment by abhi03ruchi** [comment]
u may work on other issues . 
like --> enhance footer of edit profile page . the current footer doesnt match the website theme . 

copy footer design from any other page and add there .

**Comment by Mansi-Tanwar** [comment]
@abhi03ruchi ok assign the task to me. I will do that. And thank you for the help.

**Comment by abhi03ruchi** [comment]
create a new issue regarding this . work on it and raise pr

**Comment by Mansi-Tanwar** [comment]
@abhi03ruchi is there any other issue i can work on?? I have completed this one.

**Comment by abhi03ruchi** [comment]
chk the my profile and edit details page . enhance the UI of these pages .

my profile page --> add footer  similar to that in other pages . and UI acc to the theme of the website . like change the button  UI like that in home page . etc ...

**Comment by abhi03ruchi** [comment]
add dark mode to these pages .

u can work on these issues and raise pr . create separate pr for specific issues.
