### ISSUE TITLE
Recommend page not found in the copyright policy

### ISSUE THREAD

**Issue by Antima2004** [anuragverma108/SwapReads#4271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the copyright policy page, recommend page its working showing that page not found error in the footer section of the page.
![Screenshot 2024-10-30 160827](https://github.com/user-attachments/assets/f6e564ae-c937-4a57-ae75-f115277e8175)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Antima2004** [comment]
047f59eed9894219811a89d42d339cb280347bfc
I have completed this issue also but the commit goes in the previous pr , please marked as completed and give the level label to this pr
before:

https://github.com/user-attachments/assets/2cb723db-4f5a-42e0-a715-446409a4462d

After:

https://github.com/user-attachments/assets/24ba161c-bf00-4f4d-b288-2ced3d4b55f6

**Comment by Antima2004** [comment]
@abhi03ruchi  assign this also level label and mark as completed as I completed in the previous pr

**Comment by Antima2004** [comment]
@abhi03ruchi can I get points for this???

**Comment by abhi03ruchi** [comment]
no , u didnt raise separate pr for it .
