### ISSUE TITLE
Feat: To adding the animation effect to social media icons 

### ISSUE THREAD

**Issue by Sujal1201** [anuragverma108/SwapReads#4278]
### Add ScreenShots

<img width="556" alt="image" src="https://github.com/user-attachments/assets/51ac8dd2-717c-4665-b6db-34c114db4e69">

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sujal1201** [comment]
Please assign me to this issue

**Comment by abhi03ruchi** [comment]
which pages have this issue ?
