### ISSUE TITLE
BUG: Random container before donate books section on main page

### ISSUE THREAD

**Issue by Mrunali01** [anuragverma108/SwapReads#4283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a blank white container before the donate books section on the main page

<img width="600" alt="image" src="https://github.com/user-attachments/assets/b556895c-4e9d-462f-bd90-6453f6d10db1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this is the book exchange form . there is some bug here .  when we load all the genre from above section , then only the form is visible . 

u may work on resolving the issue .
