### ISSUE TITLE
BUG: Enhance fotter of edit profile page

### ISSUE THREAD

**Issue by Mansi-Tanwar** [anuragverma108/SwapReads#4287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current footer doesn't match the website theme. I would like to change it to like other pages of website. Please assign the task to me. Thank you. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by Mansi-Tanwar** [comment]
@atmajaa is there any other issue on which i can work.??

**Comment by atmajaa** [comment]
@Mansi-Tanwar  try raising an issue for the "How do you prefer to read" pop up. It currently doesn't have a close btn option

**Comment by atmajaa** [comment]
@Shalinis19137 Create an issue first. You'll be assigned if it is valid

**Comment by Shalinis19137** [comment]
ok
