### ISSUE TITLE
BUG: Chatbot does not answer questions

### ISSUE THREAD

**Issue by aditi-pai04** [anuragverma108/SwapReads#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The chatbot does not provide an answer to the questions. Rather 'insufficient AI credits' is displayed and the bot asks for the next question. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @aditi-pai04 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by RitiChandak** [comment]
@aditi-pai04 We are closing these issue as it has been solved now
