### ISSUE TITLE
BUG: Visitor count getting hidden

### ISSUE THREAD

**Issue by Gauravtb2253** [anuragverma108/SwapReads#4297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The visitor count is not shown properly

![image](https://github.com/user-attachments/assets/090d2d70-b407-4be3-a6c9-37efa59e23ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
its visible . maybe u have zoom in website too much .

**Comment by Gauravtb2253** [comment]
its not visible in my laptop at 100% zoom so I thought it could be bug
