### ISSUE TITLE
Addition of social media links

### ISSUE THREAD

**Issue by Jagpreet153** [anuragverma108/SwapReads#43]
When the user clicks on social media icons it shows top of the page 
Kindly assign it to me under GSSoC'24

![Screenshot 2024-05-10 141448](https://github.com/anuragverma108/SwapReads/assets/119691733/028d4c6c-3311-4fb4-a795-3722e5059fc6)

**Comment by Suvam3456** [comment]
@anuragverma108 Please assign me this issue, i can add icons with attractive animation and css

**Comment by Shreya-060304** [comment]
Hello there . Please assign me with this project . I can modify your website with various social media links that could enhance the engagement of the website. @anuragverma108 please assign this to me

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by anuragverma108** [comment]
Assigned !

**Comment by khushikunte** [comment]
I am khushi kunte.I would like to work on this issues.Please assign this task to me.

**Comment by SalehaTabassum** [comment]
Hi @anuragverma108 please assign this issue.i would like to work on this

**Comment by SalehaTabassum** [comment]
Hi @anuragverma108 please assign this issue.i would like to work on this

**Comment by Mastermind730** [comment]
Hi @anuragverma108 please assign this issue.i would like to work on this
