### ISSUE TITLE
Social Icon is not showing in the audiobook 

### ISSUE THREAD

**Issue by Antima2004** [anuragverma108/SwapReads#4317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Social Icon is not showing in the audiobook page of your footer section
![Screenshot 2024-10-31 122611](https://github.com/user-attachments/assets/664dbd35-d72e-4d7b-8679-b3c02cce857a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the footer in this page  has to be changed , it doesnt match the general footer design . 

u can copy the footer design from community forum page , and add here . 

u may work on this issue and raise pr .

**Comment by abhi03ruchi** [comment]
create a new issue for it .
