### ISSUE TITLE
BUG: Unwwanted '//' needs to be removed.

### ISSUE THREAD

**Issue by rasmirajesh** [anuragverma108/SwapReads#4326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an unwanted '//' symbol under the Load more button. I will remove it as causes a mismatch with the overall layout of the  homepage.

the issue is:
![image](https://github.com/user-attachments/assets/7fdcd819-b505-485f-b41d-2bc8ff3049ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
someone else is working on this issue .
