### ISSUE TITLE
BUG:Updating twitter logo

### ISSUE THREAD

**Issue by YadlaMani** [anuragverma108/SwapReads#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updating the twitter logo to X
![image](https://github.com/anuragverma108/SwapReads/assets/133841094/4170703c-c944-4cdb-9767-ee8461d70e55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by YadlaMani** [comment]
@anuragverma108 pls assign me this issue

**Comment by anuragverma108** [comment]
Assigned! @YadlaMani 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by YadlaMani** [comment]
@anuragverma108  made the pull request  pls check it once
