### ISSUE TITLE
Feat: Added new Animated icons in contact page

### ISSUE THREAD

**Issue by SadafKausar2025** [anuragverma108/SwapReads#435]
### Describe the feature

I took the animated icons from Lordicon and apply it to the contact page 
and now it looks much better
It works in both dark and light page

### Add ScreenShots

before
![Screenshot (1724)](https://github.com/anuragverma108/SwapReads/assets/137484958/2aeb97e9-d0be-4499-becc-55ea0eef29ca)

after in sun mode
![Screenshot (1725)](https://github.com/anuragverma108/SwapReads/assets/137484958/23ab69e9-d315-4a64-a6b5-08d408494c7e)

after in dark mode
![Screenshot (1726)](https://github.com/anuragverma108/SwapReads/assets/137484958/1ce6f305-0032-4ae4-8027-c0d093063e56)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me #435?

**Comment by huamanraj** [comment]
> can you please assign this issue to me #

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by SadafKausar2025** [comment]
yes, I have created a pull request and PR no is #436.
Can you please merge my PR ?

**Comment by krati234** [comment]
assign this please
