### ISSUE TITLE
Feat:FOOTER REQUIRED IN EVENTS PAGE

### ISSUE THREAD

**Issue by likitha-kapu** [anuragverma108/SwapReads#4363]
### Describe the feature

The addition of a footer section on the events page is necessary to enhance user experience and accessibility. This footer should include key elements such as home,benefits,contact etc to encourage engagement. The addition of Swap Reads info is also required int the footer section.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/769bdc2e-7047-468f-bd06-2fc6c2d48a05)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by likitha-kapu** [comment]
@anuragverma108 please assign this task to me

**Comment by abhi03ruchi** [comment]
<img width="1440" alt="Screenshot 2024-11-01 at 9 20 35 AM" src="https://github.com/user-attachments/assets/70d3b90b-3c44-4625-a5c8-cb2139013af6">

add this kind of footer here .

**Comment by abhi03ruchi** [comment]
u can copy footer design from community spotlight and add here

**Comment by likitha-kapu** [comment]
@abhi03ruchi 
![image](https://github.com/user-attachments/assets/1a841761-72d6-4536-8c74-13fb7ae45da6)
Is this okay?

**Comment by likitha-kapu** [comment]
@abhi03ruchi or check this..I have added icons
![image](https://github.com/user-attachments/assets/0854f0ef-05ee-44c7-b38c-c8533d06c926)

**Comment by abhi03ruchi** [comment]
its ok . 

just correct alignment a little bit and also font colors also. 

chk community forum footer , u can copy footer design from there .

**Comment by likitha-kapu** [comment]
@abhi03ruchi can you once pls look at my pull request

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi i have no much idea of it ...as I am a new contributor

i was just saying that open the community forum page html code , copy the footer code and paste it to ur event.html , and css . copy and paste .

**Comment by likitha-kapu** [comment]
@abhi03ruchi 
![image](https://github.com/user-attachments/assets/c5becdc9-370a-4c37-8fc1-981ab8a81de8)
Is this okay?

**Comment by abhi03ruchi** [comment]
> <img alt="Screenshot 2024-11-01 at 9 20 35 AM" width="1440" src="https://private-user-images.githubusercontent.com/105661636/382224905-70d3b90b-3c44-4625-a5c8-cb2139013af6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjEyMjksIm5iZiI6MTczMDUyMDkyOSwicGF0aCI6Ii8xMDU2NjE2MzYvMzgyMjI0OTA1LTcwZDNiOTBiLTNjNDQtNDYyNS1hNWM4LWNiMjEzOTAxM2FmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNDE1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDRhYWFiNTYwYjVmZjAyNTk1ZjMyNWZmM2E3MzMxMmE4YjA3NjRmY2YwYTQ3ZDc5YmEwNDlhZmNiYTk3MzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.C_9Dm2AGcoBfVt6YenheH0W-GYJlJo5d1msBqGrx64Q">
> add this kind of footer here .



fix the font color  and also add spacing like in the quick links . correct the icons hover effect also

**Comment by likitha-kapu** [comment]
@abhi03ruchi I have made the changes...check out if this is okay

https://github.com/user-attachments/assets/cdcdde36-1d98-4ba3-9951-bee56cbdcf9c

**Comment by abhi03ruchi** [comment]
ok . change blue color . have u added the 2 lines below the horizontal line? 

raise pr after it .
