### ISSUE TITLE
Fixing Footer Links for Improved Website Navigation

### ISSUE THREAD

**Issue by Adi-gitX** [anuragverma108/SwapReads#44]
Problem Statement:
Users are having trouble accessing the correct pages from the footer links on the website. The links such as "Benefits" and "Literary Realms" are redirecting users to the home page instead of their intended pages.

Task:
The task is to update the footer links so that they direct users to the correct pages instead of just the home page.

Steps to Solve:
To resolve the issue, follow the below steps:
1. Identify Issue: Find the code responsible for the footer links to determine the cause of incorrect redirection.
2. Update Links: Correct the paths for each footer link so that they point to the correct pages.
3. Test: Verify that clicking on each link now takes users to the expected pages.
4. Commit Changes: Once fixed, commit the changes to the code repository.
5. Communicate: If working with others, inform them of the changes made, and ensure they agree with the changes.

i would like to work for this issue under gssoc 2024
<img width="1680" alt="Screenshot 2024-05-10 at 2 52 43 PM" src="https://github.com/anuragverma108/SwapReads/assets/159440749/3b4a1453-2e5c-4c39-ae5a-f58f1d907290">

**Comment by Agrima11** [comment]
would u pls assign me this project
