### ISSUE TITLE
BUG:Merged branch with conflicts

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#441]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I added the rate us modal in PR #430 which was merged
Now all the code is missing meaning either someone deleted it or a PR with conflicts was merged.

rate us page right now: 
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/3901df90-63f4-41cf-945c-03b51cbc43d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Stiffpixels 
I don't know myself how it got conflicted.  Solve the conflicting issues & raise PR again. I will merge it.
