### ISSUE TITLE
BUG: fixing issues in audio book pg and adding popup modal

### ISSUE THREAD

**Issue by Riyachauhan11** [anuragverma108/SwapReads#4432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The header and bg looks messed up and the play button under premium audio books leads users directly to login page without telling them why so. To address this i would like to add a popup and fix the header and other appearance issues.

![image](https://github.com/user-attachments/assets/cafcb43d-ddbd-4e38-82b3-64aaa8a424b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
the navbar of the audio page is ok . 

for acccessing premium books the user first needs to login in the website. if the user is logged they can access the premium books too .

**Comment by abhi03ruchi** [comment]
u can work on other issues , like enhancing header and footer of events page .
