### ISSUE TITLE
Feat: ✨ UI Enhancements , 🐞 Bug fixes and Code Improvements

### ISSUE THREAD

**Issue by Sanchita76** [anuragverma108/SwapReads#4435]
### Describe the feature

**Proposed Solutions to UI Enhancement**

- **UI and Styling**:

Updated the background color to a softer tone (#f4f4f9) and set a white background for the container.
Added shadows to the container and button for a more modern feel.
Used the Google Font "Roboto" for a cleaner appearance.
Added a more prominent hover effect on the button.

- **Accessibility:**

Added aria-label for the translate button and aria-live="polite" to announce the translated text to screen readers.
Loading Indicator:

- Show a "Translating..." indicator while translation is in progress.

- Error Handling:
Displays an error message if translation fails.

### Add ScreenShots

Relevant Proof

![image](https://github.com/user-attachments/assets/8c677a41-0092-4300-a557-9f358f972992)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
which page do u want to update ? be specific .

explain clearly what issue u want to resolve . add relevant screenshots or demo video of the website .
