### ISSUE TITLE
BUG: SIGN UP Page not working properly 

### ISSUE THREAD

**Issue by Mansi-Tanwar** [anuragverma108/SwapReads#4445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, there is this issue on the website 

![image](https://github.com/user-attachments/assets/766c2f6d-f9f8-47ea-ac49-72797ca2a8e3)

whenever I try to register this msg pops up but I am not getting why it is showing this pop-up. Can you please help me with the issue, maybe I can rectify it. @abhi03ruchi @atmajaa please help me with this issue. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
ok , work on the issue . for backend ur project uses firebase .

**Comment by Mansi-Tanwar** [comment]
@abhi03ruchi i am saying i found the issue, but don't know where to start with. Please guide me a little in this that how to start this where to find this problem in codebase.

**Comment by Mansi-Tanwar** [comment]
no but i can try

**Comment by abhi03ruchi** [comment]
> @abhi03ruchi i am saying i found the issue, but don't know where to start with. Please guide me a little in this that how to start this where to find this problem in codebase.

i will have to see to it . i had messaged u in  #4270 . U CAN Work on these issues for now .

**Comment by abhi03ruchi** [comment]
also chk Help center page , in profile avatar . u can enhance this page too . take inspiration from refund policy page .
