### ISSUE TITLE
QUERY: Embed Video in README.md File

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [anuragverma108/SwapReads#4468]
# Not related to your repository, Just a personal doubt

@sailaja-adapa @abhi03ruchi 
Sorry for the mention but I wanted your help on something.

I have been working on my repository and intended to embed a demo video for reference purposes for users who may visit it. However, despite numerous attempts, I encountered difficulties embedding the video into my repository's README.md file. Consequently, I began searching through all the repositories I contributed to, hoping to identify examples of successful video embedding. During my search, I came across your repository that effectively incorporates a demo video (screenshots attached below).

I would greatly appreciate your guidance on how I can embed a demo video into my repository's README.md file. 

This is the link that you have attached in your README.md file that is generating the video.

I noticed that you have added this line in your code to embed the demo video of your repository:

```
https://github.com/user-attachments/assets/f430e59e-d744-4b60-9884-b7eb4643ba72
```

Here's how it is looking:
![image](https://github.com/user-attachments/assets/446a6b47-70d2-4fc4-97a8-8e8d0d253cd6)

**Comment by rajdeepchakraborty-rc** [comment]
Oh, I forgot there was automation of labels. Please remove the labels. Sorry for the inconvenience.

**Comment by abhi03ruchi** [comment]
what difficulty are u facing ? size issue ?

**Comment by rajdeepchakraborty-rc** [comment]
> what difficulty are u facing ? size issue ?

The video is not showing on my repository:
![image](https://github.com/user-attachments/assets/b342a6a3-6a99-4ae5-95e5-ccda5fc6cf27)

![image](https://github.com/user-attachments/assets/c52c1f15-ef5c-42db-a97c-bd3c19d53573)

**Comment by sailaja-adapa** [comment]
Try to embed the video again properly @rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
> Try to embed the video again properly @rajdeepchakraborty-rc

@sailaja-adapa I have tried already. Can you tell me how you got this link for your repository:
```
https://github.com/user-attachments/assets/f430e59e-d744-4b60-9884-b7eb4643ba72
```

**Comment by abhi03ruchi** [comment]
a contributor had added this feature .  just click on attach files and add the video . and wait for sometime , this link will come .

**Comment by rajdeepchakraborty-rc** [comment]
> a contributor had added this feature . just click on attach files and add the video . and wait for sometime , this link will come .

Thanks for the help @abhi03ruchi. I just figured it out myself a while before doing the same thing. 
Please remove the labels on the issue and close it.
