### ISSUE TITLE
Feat:Main logo not looking Good

### ISSUE THREAD

**Issue by jayesh2474** [anuragverma108/SwapReads#448]
### Describe the feature

When we switch to dark theme we can see watermark clearly in logo background. Now after someone fix this logo not looking good i can make logo without watermark,
in logo we need png format which was good looking.
kindly assign me under Gssoc'24

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/115784462/7b7d926c-50ff-4486-9948-874c79de9373)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> When we switch to dark theme we can see watermark clearly in logo background. Now after someone fix this logo not looking good i can make logo without watermark,
> in logo we need png format which was good looking.
> kindly assign me under Gssoc'24
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/115784462/7b7d926c-50ff-4486-9948-874c79de9373)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
