### ISSUE TITLE
Feat: Pointer movement is not professional

### ISSUE THREAD

**Issue by skanarul8002** [anuragverma108/SwapReads#4495]
### Describe the feature

Really website is good but pointer movement is not good so i want to make a pointer movement as professional.
please assign me @anur

### Add ScreenShots

see the image:
![image](https://github.com/user-attachments/assets/32826343-0f31-4d3e-991b-d144c4ad9e33)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
how will u make the pointer look professional ?

**Comment by skanarul8002** [comment]
@abhi03ruchi, like A web application's pointer . There are no back threads etc .that exist in your project.

**Comment by skanarul8002** [comment]
Can I start the work tell me.. please

**Comment by abhi03ruchi** [comment]
no , the custom cursor is ok . 

u can work on other issues .
