### ISSUE TITLE
Feat: Revamp Genre Pages

### ISSUE THREAD

**Issue by haseebzaki-07** [anuragverma108/SwapReads#4509]
### Describe the feature

Revamp the genre pages and add details to the books.

### Add ScreenShots

![Screenshot 2024-11-03 165724](https://github.com/user-attachments/assets/ba1febc3-b7ae-44c6-9e37-823f184185e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
there are more pages too . click on load more button . are u working on them ?

**Comment by haseebzaki-07** [comment]
hey @abhi03ruchi I am working on them, will raise a PR soon
