### ISSUE TITLE
Feat: Literary Realms WebPages

### ISSUE THREAD

**Issue by sanskritilabroo** [anuragverma108/SwapReads#451]
### Describe the feature

1. Currently, under literary realms we've covered, we can see the names of the genres, but not the books they contain. I can create the basic structure and UI for a few webpages(like eg. romantic escapes) where we showcase the books we currently have available for swapping(I can add a few books for now). It will follow our website's theme and basic shop-type cards to showcase the books.

2. Will also have to add hover + link the genres cards to these webpages.

Let me know if this is okay and I can proceed as a contributor under GSSOC'24. @anuragverma108 @huamanraj 

### Add ScreenShots

Structure for each webpage:
<img width="815" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/86831838/d421167d-2cd0-4e76-9c2a-58c584f624a8">

Linking required for each genre card:
<img width="871" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/86831838/f2a20f7d-f06b-476a-a21e-dee2ed4482f9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> 1. Currently, under literary realms we've covered, we can see the names of the genres, but not the books they contain. I can create the basic structure and UI for a few webpages(like eg. romantic escapes) where we showcase the books we currently have available for swapping(I can add a few books for now). It will follow our website's theme and basic shop-type cards to showcase the books.
> 
> 
> 2. Will also have to add hover + link the genres cards to these webpages.
> 
> Let me know if this is okay and I can proceed as a contributor under GSSOC'24. @anuragverma108 @huamanraj 
> 
> ### Add ScreenShots
> 
> Structure for each webpage:
> <img width="815" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/86831838/d421167d-2cd0-4e76-9c2a-58c584f624a8">
> 
> Linking required for each genre card:
> <img width="871" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/86831838/f2a20f7d-f06b-476a-a21e-dee2ed4482f9">
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by RitiChandak** [comment]
completed #1077
