### ISSUE TITLE
Improvement in UI of Navbar in Dark Mode 

### ISSUE THREAD

**Issue by Deekshashakyawal** [anuragverma108/SwapReads#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Navbar needs improvement specially in Dark Mode 
I want to work on this issue , please assign me under GSSoC'24 . I want to contribute. 

![Screenshot 2024-05-31 122114](https://github.com/anuragverma108/SwapReads/assets/119758705/62e4813c-8e6e-4b4a-bdc1-f9f9975493b7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nilesh5566** [comment]
can you please assign this issue to me #455?

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The Navbar needs improvement specially in Dark Mode 
> I want to work on this issue , please assign me under GSSoC'24 . I want to contribute. 
> 
> ![Screenshot 2024-05-15 151557](https://github.com/anuragverma108/SwapReads/assets/119758705/5e03c244-51f2-4e1e-8696-8be296e6e463)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Deekshashakyawal** [comment]
I made changes in the UI of Navbar in Dark Mode , Please let me know if you have any suggestions or changes that I should make so that it looks more User friendly. 

![Screenshot 2024-05-16 195239](https://github.com/anuragverma108/SwapReads/assets/119758705/244e2a36-0034-4f4f-86b1-ef566e935b83)

**Comment by krati234** [comment]
assign this please
