### ISSUE TITLE
🐛BUG: Missing mouse pointer effect on Book Wishlist page

### ISSUE THREAD

**Issue by akash70629** [anuragverma108/SwapReads#4564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the book wishlist page, the mouse pointer effect is missing.

## Screenshot
![image](https://github.com/user-attachments/assets/ac69edf4-5d91-47df-9fa2-6719349f4f6a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
add it in all account detail pages , u created .

**Comment by akash70629** [comment]
> add it in all account detail pages , u created .

Aye aye captain ![image](https://github.com/user-attachments/assets/da3e3cfd-96b0-4d47-a5a7-8a444a2c9aea)
