### ISSUE TITLE
BUG: Main Heading Not Visible in Dark Theme

### ISSUE THREAD

**Issue by neeru24** [anuragverma108/SwapReads#4566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 In dark mode, the main heading blends into the background, making it hard to read. Update the color or add contrast for better visibility.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
which heading ?

**Comment by neeru24** [comment]
> which heading ?

![Screenshot 2024-11-04 152328](https://github.com/user-attachments/assets/0fff25f0-b4db-4222-983a-b63820324883)

**Comment by abhi03ruchi** [comment]
ok , rename the issue , mention the page also . --> https://swapreadsconnect.netlify.app/assets/html/freebooks .

**Comment by abhi03ruchi** [comment]
u can also work on enhancing the page .
