### ISSUE TITLE
Backend for contact us form 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [anuragverma108/SwapReads#4597]
### Describe the feature

i can design api for submitting backend 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/938c7f75-9dc0-4620-bbf4-976aeb33212d)

for this contact form 

i will take care of folder structure 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this form is working fine . 

our website uses firebase in backend .  chk login page  form  that doesnt work properly . 

u can work on this issue and raise pr .
