### ISSUE TITLE
Feat: Add dedicated page for the contributors

### ISSUE THREAD

**Issue by yashksaini-coder** [anuragverma108/SwapReads#4608]
### Describe the feature

My feat is to add a dedicated page to the contributors os that their overall stats are visible to be showcased

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e0b3432e-797f-4f8e-b4a3-29dbacaebabe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
this page already exists in our project

**Comment by yashksaini-coder** [comment]
> this page already exists in our project

where exactly ??

**Comment by abhi03ruchi** [comment]
chk homepage footer
