### ISSUE TITLE
DOC: Add Code Of Conduct

### ISSUE THREAD

**Issue by Priyanshu2631** [anuragverma108/SwapReads#461]
### What's wrong with the existing documentation

A Code of Conduct.md file is necessary in a repository for a smooth contribution and collaboration without causing any conflicts. Please assign this issue to me under GSSOC'24, I hv the documentation ready already, can create a PR the moment you assign me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
