### ISSUE TITLE
Feat:Footer Enhancement required in Community page

### ISSUE THREAD

**Issue by likitha-kapu** [anuragverma108/SwapReads#4623]
### Describe the feature

The footer on the community page is misaligned, causing a poor user experience. Elements within the footer, such as text and icons, are not properly positioned, leading to an unbalanced appearance that disrupts the overall layout of the page.

### Add ScreenShots

This is the present view of the community page
![Screenshot 2024-11-05 131548](https://github.com/user-attachments/assets/9d35ad7b-5fbb-495e-a004-2acba72a260a)
I would like to change the structure similar to the events page:
![image](https://github.com/user-attachments/assets/56fffd69-514b-4987-b42e-33c2ffba2f62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by likitha-kapu** [comment]
@anuragverma108 please assign me this issue and assign me a level2 label

**Comment by abhi03ruchi** [comment]
https://swapreadsconnect.netlify.app/comsp , its ok . that was a redundant page , which is now been deleted .
