### ISSUE TITLE
BUG: Remove Blank Container

### ISSUE THREAD

**Issue by AnushkaChouhan25** [anuragverma108/SwapReads#4672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an unnecessary blank container on the home page, which does not looking good.
![image](https://github.com/user-attachments/assets/913078c3-3551-4918-b151-f3dfcb061c16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
there is book exchange hub .
