### ISSUE TITLE
Feat: Improve the FAQ's section

### ISSUE THREAD

**Issue by SnowyWinter13** [anuragverma108/SwapReads#468]
### Describe the feature

I would like to add an animation element that makes it look smoother when the Faq's are opened. Right now they open instantly and it doesn’t look very smooth. 

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-05-15 at 7 00 47 PM" src="https://github.com/anuragverma108/SwapReads/assets/122365389/9b43934e-cd85-410d-b5b5-73ac4178d764">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by rounakdey6** [comment]
Please assign this issue to me sir
