### ISSUE TITLE
Feat:Adding a contributors page

### ISSUE THREAD

**Issue by Son7c** [anuragverma108/SwapReads#4689]
### Describe the feature

I would add anew page dedicated to all the contributors in this project which will display the stats of this project ex- no. of forks, stars etc. and also show stats of the contributors , no. of contributions done and also i would add cool animation on hovering contributors card.

### Add ScreenShots

![Screenshot 2024-11-06 183031](https://github.com/user-attachments/assets/bab24539-0eae-42e9-b5be-01f0e249a0b5)

There is no seperate contributors page apart from the contributors in about us page, 

I would create a page that contains only contribution and stats

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
we already have the page . chk homepage footer.

**Comment by Son7c** [comment]
@abhi03ruchi The contributors are present in the about us page, please give me the opportunity to make a new page just mentioning the contributors, Trust me I won't disappoint you.

**Comment by abhi03ruchi** [comment]
https://swapreadsconnect.netlify.app/contributor/contributorss
