### ISSUE TITLE
BUG: The Edit profile page not working on website

### ISSUE THREAD

**Issue by pinakviramgama** [anuragverma108/SwapReads#4706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When user clicks on my-profile from home page then edit profile is not working at all

![image](https://github.com/user-attachments/assets/f2de886c-60a9-44fe-b3bd-f992ef1bffa8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhi03ruchi** [comment]
it is working . 

https://swapreadsconnect.netlify.app/profiletest . chk .

**Comment by abhi03ruchi** [comment]
the above project which u pasted pic of isnt our .
