### ISSUE TITLE
modify buttons style

### ISSUE THREAD

**Issue by root-0101** [anuragverma108/SwapReads#471]
- Making all the button to default as "Send Now" button
- It is crucial to make the buttons more visually appealing which attract the users 
![Screenshot 2024-05-15 195412](https://github.com/anuragverma108/SwapReads/assets/142779809/fcf42ad1-6af4-4c83-bb04-10ea423bf336)
![Screenshot 2024-05-15 195444](https://github.com/anuragverma108/SwapReads/assets/142779809/532c6c1e-7cf1-45fe-954c-e01ca67efebd)
![Screenshot 2024-05-15 195510](https://github.com/anuragverma108/SwapReads/assets/142779809/6192f411-06e8-49af-8e97-0c6eb8109ff2)

**Comment by pratikgurjar** [comment]
@anuragverma108 please assign this issue to me. Under GSSoC'24

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by KashishRathore** [comment]
Please Assign this task @anuragverma108.
