### ISSUE TITLE
BUG:Footer responsiveness is not working even after the update .

### ISSUE THREAD

**Issue by psychic-coder** [anuragverma108/SwapReads#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I searched the issue list and there was an issue already raised related to  footer update and that last was marked done but yet the footer is not completely  responsive . I would like to work on the complete responsiveness of the footer . And will add more animations and will make the ui better . 

<img width="575" alt="Screenshot 2024-05-15 at 10 19 21 PM" src="https://github.com/anuragverma108/SwapReads/assets/134062997/bde79a00-fd1b-4c7e-b869-abddb3e040fe">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> I searched the issue list and there was an issue already raised related to  footer update and that last was marked done but yet the footer is not completely  responsive . I would like to work on the complete responsiveness of the footer . And will add more animations and will make the ui better . 
> 
> <img width="575" alt="Screenshot 2024-05-15 at 10 19 21 PM" src="https://github.com/anuragverma108/SwapReads/assets/134062997/bde79a00-fd1b-4c7e-b869-abddb3e040fe">
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by psychic-coder** [comment]
Thankyou @huamanraj for assigning it to me.
