### ISSUE TITLE
in main page play buttion linking issue

### ISSUE THREAD

**Issue by kartikmehta18** [anuragverma108/SwapReads#481]
![image](https://github.com/anuragverma108/SwapReads/assets/125860170/484c9b02-36ae-458f-b07e-b479af84c1e6)
 button only redirect youtube not redirect your proper channel

**Comment by huamanraj** [comment]
> @pratikgurjar  plz assign me this

there is no video to add here! what you are going to do here?

**Comment by kartikmehta18** [comment]
when we click on this it redirect to https://www.youtube.com/ but there is no need to redirect i gues

**Comment by huamanraj** [comment]
> when we click on this it redirect to https://www.youtube.com/ but there is no need to redirect i gues

then fix this

**Comment by kartikmehta18** [comment]
> > when we click on this it redirect to https://www.youtube.com/ but there is no need to redirect i gues
> 
> then fix this
please check pr 
https://github.com/anuragverma108/SwapReads/pull/504
