### ISSUE TITLE
BUG: Imrove UI

### ISSUE THREAD

**Issue by Sambit-Mondal** [anuragverma108/SwapReads#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Pointer disappears and text arrow comes as cursor while hovering over the Rate Us button in the Navbar.

Kindly assign me to solve this issue under GSSoC '24.
Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!
