### ISSUE TITLE
Feat: Addition of Google Map in the Contact Us form

### ISSUE THREAD

**Issue by Sambit-Mondal** [anuragverma108/SwapReads#489]
### Describe the feature

I want to add a Google Map feature to the Contact Form in the website, along with the address, as it'll make the contact form more complete with the pinned Map location on it.

Kindly assign me this issue under GSSoC '24.

Thank you!

### Add ScreenShots

Before:

![Screenshot 2024-05-16 021800](https://github.com/anuragverma108/SwapReads/assets/138088550/bc0c2b13-b4c6-49b7-bc2d-d2105232611c)

After:

![Screenshot 2024-05-16 021556](https://github.com/anuragverma108/SwapReads/assets/138088550/350d7cd8-3350-4090-8612-b02bcdfc669e)

(P.S.: The After part is for illlustration purposes, the actual feature will be similar like that, but of course it'll be just an integration into the already existing UI design)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by carolinelall** [comment]
@anuragverma108 Sir, Please assign me this issue, I would love to work on it as I can assist in adding a Google form
