### ISSUE TITLE
HOVER EFECT IN NAVBAR

### ISSUE THREAD

**Issue by sakshiglaze** [anuragverma108/SwapReads#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @anuragverma108,
I have encountered little delay in zoom and hover effect on the navbar icons. Also the bubbles around doesn't seems pretty accurate.

https://github.com/anuragverma108/SwapReads/assets/129287425/1ce179e9-b174-4341-95e3-55445aa126f7

https://github.com/anuragverma108/SwapReads/assets/129287425/40fe9c85-1ec7-4229-bb6c-94808bd11943

I would like to improve the responsiveness. Please assign this issue under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by vaishnavip27** [comment]
Hey @anuragverma108 I would love to work on this issue as i have good experience in building websites. Please assign me this issue. Looking forward for the approval

**Comment by anuragverma108** [comment]
@vaishnavip27 Issues are assigned at first come first serve basis.
If a contributor doesn't contribute within a week then it would be assigned to next person who asked for it. 
I would recommend to find some other issue and work on it.

**Comment by sakshiglaze** [comment]
Thank You for assigning the issue!
I'm working on it and will raise PR as soon as possible.
