### ISSUE TITLE
BUG: Dark Mode Icon Disappeared from Navbar

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/129655645/80d5970c-641c-4810-9802-cb7fa5f22356)

The dark mode icon, which allows users to switch between light and dark modes, is no longer visible on the navigation bar. This issue affects the overall user experience as users are unable to easily toggle dark mode.

If anyone is interested in fixing this issue, please leave a comment expressing your interest, and I will assign it to you under the GirlScript Summer of Code (GSSOC) - Level 2 program. Your contributions will help improve the user experience for everyone using SwapReads. Thank you for your support and enthusiasm!

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ANAMASGARD** [comment]
Sir I am GSSOC 24 Contributor would really appreciate that if you assign me this issue I will try my best to solve this problem .

**Comment by huamanraj** [comment]
> Sir I am GSSOC 24 Contributor would really appreciate that you assign me this issue , I will try my best to solve this problem .

work on it!

**Comment by sshivangi882** [comment]
hey ! I am working on it.
