### ISSUE TITLE
BUG: Text not appearing on testimonial over flip.

### ISSUE THREAD

**Issue by nagalakshmi08** [anuragverma108/SwapReads#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,
When the testimonial is flipped on hover, the text doesn't appear, and a blank card shows up.

![Screenshot 2024-05-16 112138](https://github.com/anuragverma108/SwapReads/assets/121669832/b80a4ec6-338f-4868-b73f-0693f7d47289)
Please assign me this issue , I will solve this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Hello,
> When the testimonial is flipped on hover, the text doesn't appear, and a blank card shows up.
> 
> ![Screenshot 2024-05-16 112138](https://github.com/anuragverma108/SwapReads/assets/121669832/b80a4ec6-338f-4868-b73f-0693f7d47289)
> Please assign me this issue , I will solve this task.
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

fix this!
