### ISSUE TITLE
Testimonials text responsive and bordering on dark mode.

### ISSUE THREAD

**Issue by sharmi4590** [anuragverma108/SwapReads#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The testimonial cards are not visible on the dark mode , only the image and name is visible . I will add some shadow boxing to it so that it will look as cards in dark mode as well. And need to make the text in the testimonials responsive as well .
![Screenshot_20240516-123035](https://github.com/anuragverma108/SwapReads/assets/102676949/1e0009e8-5332-4ee1-ba61-be96183c3351)
![Screenshot_20240516-123012](https://github.com/anuragverma108/SwapReads/assets/102676949/ef4c560a-b93a-47da-8283-4c2372ee622f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
