### ISSUE TITLE
Improve User Experience: Change 'Registering' to 'Creating Account' and Enhance Button Visibility

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#508]
### Describe the feature

Hey @anuragverma108 . Enhance the user experience on our login page by making two key changes:

- Change the text from "Registering" to "Creating Account" to make it clearer and more inviting for new users.
- Adjust the button colors for better visibility, ensuring that the button text is easily readable.

These changes are intended to improve clarity and usability for our users, ultimately leading to a more seamless registration and login process.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Before making the changes:
![Screenshot 2024-05-16 125411](https://github.com/anuragverma108/SwapReads/assets/159511364/8340df2f-ea45-4d6f-87e0-361f09bad2c1)

After making the changes:
![Screenshot 2024-05-16 125540](https://github.com/anuragverma108/SwapReads/assets/159511364/f2289a0a-4a1a-4f33-b6e6-7d83cad79167)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
