### ISSUE TITLE
No dark mode on login page

### ISSUE THREAD

**Issue by Vanicoding27** [anuragverma108/SwapReads#512]
There is no dark mode for login/signup page which affect user experience.

![Screenshot 2024-05-16 132105](https://github.com/anuragverma108/SwapReads/assets/165997406/43a50bca-0616-4b1a-a3a1-409d10b51f58)

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by nishant0708** [comment]
hey i can fix this issule.please assign it to me under gssoc24

**Comment by KashishRathore** [comment]
Please assign this task to me. Looking forward to contribute

**Comment by huamanraj** [comment]
> Please assign this task to me. Looking forward to contribute

assigned!
