### ISSUE TITLE
BUG:social media icons in the footer are not working

### ISSUE THREAD

**Issue by nagamukesh** [anuragverma108/SwapReads#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

social media handles in the footer are simply directing to the home page itself
I can make them working 
please assign this issue to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sunnyajit** [comment]
can you please assign me this issue?
