### ISSUE TITLE
Align  contact card to right

### ISSUE THREAD

**Issue by Vanicoding27** [anuragverma108/SwapReads#527]
It would be better if we align contact card to right 

![Screenshot 2024-05-16 150626](https://github.com/anuragverma108/SwapReads/assets/165997406/f8a115a9-efd9-476c-af2d-6999fdd74e39)

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.

**Comment by huamanraj** [comment]
> It would be better if we align contact card to right 
> 
> ![Screenshot 2024-05-16 150626](https://github.com/anuragverma108/SwapReads/assets/165997406/f8a115a9-efd9-476c-af2d-6999fdd74e39)
> 

assigned! tag me when you create a PR!
