### ISSUE TITLE
Clicking on Read more button in the cards is directing us to Home

### ISSUE THREAD

**Issue by Suvam3456** [anuragverma108/SwapReads#53]
In the ,"Unleash the Magic of Book Swapping" section of website, by clicking on the Read more in each card ,user is directed to the top at Home. It should be removed since the card length is sufficient to accommodate the description provided  in each card.

Please assign me this issue under GSSOC'24 @anuragverma108.

Screenshot:
![b](https://github.com/anuragverma108/SwapReads/assets/99579881/cc4ccb55-9d51-4c4e-a48b-2f1792b558a3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Brave/chrome

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Aryan-joh** [comment]
hii @anuragverma108 i want to work on this please assign this to me

**Comment by Suvam3456** [comment]
Hey,I have raised a PR @anuragverma108
