### ISSUE TITLE
Feat: Update the Scroll to Top button

### ISSUE THREAD

**Issue by rashmikauthaa** [anuragverma108/SwapReads#533]
### Describe the feature

- Let's make the Scroll to Top button more interactive using a icon.
- It is crucial to make the buttons more visually appealing which satisfices the users.

### Add ScreenShots

![before](https://github.com/anuragverma108/SwapReads/assets/164472969/822dffb3-23da-4b1d-8bf0-04a31a91e0ac)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krati234** [comment]
assign this please

**Comment by huamanraj** [comment]
> 
> assign this please
> 
> 

yes! do it

**Comment by RitiChandak** [comment]
@krati234 any updates?
