### ISSUE TITLE
Change Shadow on "Unleash the Magic of Book Swapping!" cards

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#535]
### Describe the feature

I would like to add a good shadow on the cards so that they will look more realistic

### Add ScreenShots

![Screenshot 2024-05-16 173204](https://github.com/anuragverma108/SwapReads/assets/85826117/a92cfa5c-57de-4770-8a8f-0a33a05b8466)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ridhima10** [comment]
@anuragverma108 kindly assign me this issue. It will make it look more realistic

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> I would like to add a good shadow on the cards so that they will look more realistic
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-16 173204](https://github.com/anuragverma108/SwapReads/assets/85826117/a92cfa5c-57de-4770-8a8f-0a33a05b8466)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue
assigned! tag me when you create a PR! and i am the mentor of thos project so reach out for any help!
