### ISSUE TITLE
Missing Borders on Form Fields on the "Contact Us" Page

### ISSUE THREAD

**Issue by Pratikchaudhari5** [anuragverma108/SwapReads#536]
Description:
There are missing borders on the form fields on the "Contact " page of the website. Specifically, the fields for name, email, and other details do not have visible borders, which affects the user experience.

Expected Behavior:
The form fields should have visible borders to clearly delineate where users should input their information.
![image](https://github.com/anuragverma108/SwapReads/assets/104305163/3c68d173-a6c8-4052-9608-0a8bc472734d)

Please assign me this issue.

**Comment by kg-06** [comment]
I want to work on this issue.
