### ISSUE TITLE
BUG: Title and Logo not showing

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The logo and title are missing both in dark and light mode
![Screenshot 2024-05-16 194019](https://github.com/anuragverma108/SwapReads/assets/130165687/35964312-1b8a-41a8-a760-9c207fd8fda0)
![image](https://github.com/anuragverma108/SwapReads/assets/130165687/b1d13cfe-e44c-403c-bf5f-0975379b7c26)
I will again add the title and logo.
Please assign this issue to me @anu

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.
