### ISSUE TITLE
BUG: Hovering effect on the social media icons missing

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It would look nice there is a hovering effect present on the social media icons which is missing. I would like to add the hovering effect to the icons.
Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Noopur-Thombare** [comment]
Please assign me this issue.I would like to work on it as a contributor under GSSOC'24.
