### ISSUE TITLE
Overlapping content of footer  

### ISSUE THREAD

**Issue by Deekshashakyawal** [anuragverma108/SwapReads#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Please Assign me this issue . I want to contribute under GSSoC'24 . 
![Screenshot 2024-05-16 200902](https://github.com/anuragverma108/SwapReads/assets/119758705/681bdbde-0d2c-4b3f-b28e-8ed4fa01a59d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Noopur-Thombare** [comment]
I would like to work on this issue. Please assign me this as a contributor under GSSOC'24.
