### ISSUE TITLE
[ENHANCEMENT] : Making a Contact page more attractive .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#543]
### Describe the feature

As the contact page is looking simple i can enhance it by adding some animation and give even spacing between the submit button and subject field .

### Add ScreenShots

![Screenshot 2024-05-16 202250](https://github.com/anuragverma108/SwapReads/assets/118350936/64edd082-e96c-453b-9122-28064a9bec06)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by geetanjali-22** [comment]
I would like to work on  this issue. Please assign it to me under GSSOC'24.
