### ISSUE TITLE
[Fixes]: Remove second message and subject inbox 

### ISSUE THREAD

**Issue by theashikagupta** [anuragverma108/SwapReads#548]
### Describe the feature

In footer there are double inbox for same input - subject and message 
First : before submit button
Second: after submit button

### Add ScreenShots

![Screenshot 2024-05-16 205756](https://github.com/anuragverma108/SwapReads/assets/136061047/b256b0f1-7b44-484b-af7b-2209714089fb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by theashikagupta** [comment]
@anuragverma108 Kindly assign me this issue for GSSoC'24

**Comment by anuragverma108** [comment]
@theashikagupta 

This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
