### ISSUE TITLE
BUG: Dark mode theme is not working on the login page 

### ISSUE THREAD

**Issue by harshmishra19** [anuragverma108/SwapReads#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login page is not switching to dark mode when the dark mode theme is enabled. And I can Fix this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by uraj1** [comment]
@anuragverma108 Please assign me this issue, I can fix this asap

**Comment by harshmishra19** [comment]
@anuragverma108 any update?

**Comment by harshmishra19** [comment]
@anuragverma108 ??

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The login page is not switching to dark mode when the dark mode theme is enabled. And I can Fix this issue.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!
