### ISSUE TITLE
BUG: Navbar Hamburger not responsive

### ISSUE THREAD

**Issue by aryansharma220** [anuragverma108/SwapReads#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/133234867/3f584825-e6f8-4987-8982-d8e17d17b962)

The components should appear vertically

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/133234867/3f584825-e6f8-4987-8982-d8e17d17b962)
> 
> The components should appear vertically
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

fix this!
