### ISSUE TITLE
BUG: Fixing Website Navigation and Adding 'Books' Section

### ISSUE THREAD

**Issue by Deekshit7483** [anuragverma108/SwapReads#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's a problem where the navigation menu and the footer on the website are all jumbled up, making it hard for users to see everything clearly. Also, the "Rate Us" option in the navigation is hidden because of this mess. Plus, in the footer, the text is all mixed up.

Solution:

To fix this, we're going to add a new section to the navigation called "Books." This will make it easy for users to find and look at the books available on the site. We'll also tidy up the navigation and footer so they don't overlap anymore. This means adjusting how things are arranged and styled so everything looks neat and tidy, and users can easily find what they need.

![Screenshot from 2024-05-16 21-22-13](https://github.com/anuragverma108/SwapReads/assets/58986536/4ee4ef52-5e97-42fe-93a9-1f00a1e7e0b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Noopur-Thombare** [comment]
please assign this issue to me. I would like to work on it
