### ISSUE TITLE
Book Recommendation SystemFeat:

### ISSUE THREAD

**Issue by simran1658** [anuragverma108/SwapReads#558]
### Describe the feature

The book recommendation feature provides users with a curated list of book suggestions tailored to their genre preferences. Users can explore these recommendations, each accompanied by essential details like title, author, publication year, average rating, and a brief description. This feature aims to facilitate users in discovering new books aligned with their interests, enhancing their reading experience by offering personalized suggestions within their preferred genre. We will provide a user preference form or bar where users can enter their preferences or select genres. Based on this input, we will recommend books matching their chosen genres. Now I am providing you a raw sample of it.

### Add ScreenShots

![WhatsApp Image 2024-05-16 at 21 37 47_ebb1e329](https://github.com/anuragverma108/SwapReads/assets/143636749/1407e685-3658-4079-bd35-b56467aaca37)
![WhatsApp Image 2024-05-16 at 22 42 48_49106b86](https://github.com/anuragverma108/SwapReads/assets/143636749/df28bef8-67fd-40b7-8133-dfab0140cfb8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanskritilabroo** [comment]
I would like to work on creating this book recommender system. Please assign me this as a contributor under GSSOC'24. @anuragverma108 @huamanraj

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Nandhinirameshmala** [comment]
I would like to work on this project. Please assign me to this project as a contributor under GSSOC'24. @anuragverma108 @huamanraj
