### ISSUE TITLE
Feat: Reset password page

### ISSUE THREAD

**Issue by APOORVAVERMAA** [anuragverma108/SwapReads#559]
### Describe the feature

Hello there, @anuragverma108!
I'd like to contribute to this awesome project by adding a forgot password/ reset password page as it is still missing. Please assign me this task.

### Add ScreenShots

Here are my ideas:
![Screenshot 2024-05-16 at 11 07 07 PM](https://github.com/anuragverma108/SwapReads/assets/145578756/8ccb4d6c-7014-4d43-87ce-803dfa9a1ef5)

![Screenshot 2024-05-16 at 11 03 15 PM](https://github.com/anuragverma108/SwapReads/assets/145578756/8f56883c-7843-42ee-b6f4-32e41d0ed5ba)

![Screenshot 2024-05-16 at 11 07 52 PM](https://github.com/anuragverma108/SwapReads/assets/145578756/4c18d3fd-0e6c-40f1-bfa1-02ed3480c3bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please
