### ISSUE TITLE
Adding Dark mode functionality

### ISSUE THREAD

**Issue by tat-tvam-asii** [anuragverma108/SwapReads#56]
I would like to add dark mode feature to the website. Please asssign this issue to me under GSSOC'24

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by anuragverma108** [comment]
Assigned!

**Comment by khushikunte** [comment]
I am khushi kunte.I would like to work on this issues.Please assign me this!!

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 Please assign me this issue
