### ISSUE TITLE
Enhancement: Footer design

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#560]
### Describe the feature

Modify the footer design and make it more attractive. Make the newsletter section more visually attractive, add hover effects on the social icons
Add transitions and fix spacing

### Add ScreenShots

![Screenshot 2024-05-16 231442](https://github.com/anuragverma108/SwapReads/assets/146661411/3151d651-f1c6-47bf-b289-13ccadd9cf4a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by sau-mili** [comment]
Please check the pull request: [#609](url)
I have added screenrecording in the req itself
