### ISSUE TITLE
BUG: Fix the navigation buttons on hover, adding better effects and alignment to transform.

### ISSUE THREAD

**Issue by justmirr** [anuragverma108/SwapReads#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On hovering over the navigation items, the elements transform with bad effects while also not maintaining the gap and size of the other items.

I'll fix it by writing a better effect on the elements' hover and their adjacent items.

![navbutton](https://github.com/anuragverma108/SwapReads/assets/75358919/685e352d-4fff-45cb-893f-5e40749da87d)
![navbutton2](https://github.com/anuragverma108/SwapReads/assets/75358919/7a9191ff-e599-4028-a1d5-09f5b786154e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please
