### ISSUE TITLE
BUG: Dark mode content invisible in Testimonial section.

### ISSUE THREAD

**Issue by shalinii31** [anuragverma108/SwapReads#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In dark mode, the testimonial section's content is not visible. Text is  getting disappear, affecting readability and user experience. This issue needs urgent attention for proper display in dark mode."

![WhatsApp Image 2024-05-17 at 10 49 52_225fc40b](https://github.com/anuragverma108/SwapReads/assets/143832323/1a63abfe-ecdc-40fc-862b-7d2aa1d0eb9a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by ChhaviRohilla** [comment]
@krati234 have you solved it, yesterday I raised the same issue.
It is not accepted yet!
but I have changed the code
