### ISSUE TITLE
Adding a scroll back to top button 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [anuragverma108/SwapReads#565]
### Describe the feature

Adding a scroll back to top button that would take the user back to the current home page 

### Add ScreenShots

![Uploading Screenshot_20240517_112038.jpg…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@anuragverma108  kindly assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please
