### ISSUE TITLE
Adding other social media icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [anuragverma108/SwapReads#566]
### Describe the feature

Adding other valid social media icons such  as GitHub and LinkedIn in the footer section 

### Add ScreenShots

![Screenshot_20240517_112423](https://github.com/anuragverma108/SwapReads/assets/117037441/c002186d-b75d-4fe7-86bd-7f4f57a4c968)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@anuragverma108 kindly assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by krati234** [comment]
assign this please

**Comment by carolinelall** [comment]
@anuragverma108 Sir, Please assign me this issue, I would love to work on it.
I have experience in the relevant technologies, which I believe will be valuable in addressing the issue effectively.

**Comment by anuragverma108** [comment]
@carolinelall 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.
