### ISSUE TITLE
BUG:Login and register functionality is completely broken

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Right now registration and sign in is not possible on the website. As can be seen from the below video or you can try yourself:

https://github.com/anuragverma108/SwapReads/assets/32983571/34db2186-298a-44b7-a907-792600ae7981

I have worked on a fix that fixes this issue as seen below:

https://github.com/anuragverma108/SwapReads/assets/32983571/92df2016-5848-4613-a3ef-fd64ba222a2e

please assign me this issue as I have already solved it just need permission to PR.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankita685** [comment]
please assign it to me

**Comment by Stiffpixels** [comment]
@anuragverma108 this is still broken can you assign me?

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Right now registration and sign in is not possible on the website. As can be seen from the below video or you can try yourself:
> 
> 
> https://github.com/anuragverma108/SwapReads/assets/32983571/34db2186-298a-44b7-a907-792600ae7981
> 
> 
> I have worked on a fix that fixes this issue as seen below:
> 
> https://github.com/anuragverma108/SwapReads/assets/32983571/92df2016-5848-4613-a3ef-fd64ba222a2e
> 
> 
> please assign me this issue as I have already solved it just need permission to PR.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned!
