### ISSUE TITLE
[Enhancement]: Improve Visual Presentation of Login/Signup Text in Header

### ISSUE THREAD

**Issue by bandhan-majumder** [anuragverma108/SwapReads#57]
**Issue: Improve Visual Appeal of Login/Signup Text**

**Description:**
The current appearance of the "Login/Signup" text in the header lacks visual appeal, impacting the overall aesthetics of the project. 

**Proposed Solution:**
Introduce a visually appealing element, such as a button or div, behind the "Login/Signup" text to enhance its appearance and draw user attention.

**Additional Details:**
- **Element Type:** Consider using a button or div as the background for the "Login/Signup" text.
- **Styling:** Apply appropriate color and styling to the element to make it visually appealing and consistent with the project's design language.
- **Placement:** Ensure the new element integrates smoothly with the existing header layout without causing any disruption.

**Alternatives Considered:**
While a button is suggested as the primary solution, alternative elements like divs could also be explored for achieving the desired visual enhancement.

**Additional Context:**
![Screenshot 2024-05-10 190346](https://github.com/anuragverma108/SwapReads/assets/133476557/56cc4a06-a2b7-44c8-b97a-3c6e8af15577)

**Comment by bandhan-majumder** [comment]
kindly assign this issue to me

**Comment by jaygupta17** [comment]
I would like to implement this. Please assign me this issue.

**Comment by sakshiiiii26** [comment]
I would like to improve its visual apeal.please assign me this issue.

**Comment by anuragverma108** [comment]
Issue already exists!
