### ISSUE TITLE
BUG: Underline doesn't appear under the Contact heading

### ISSUE THREAD

**Issue by Sambit-Mondal** [anuragverma108/SwapReads#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The underline doesn't appear under the Contact heading, like it appears under Testimonials, Benefits or other sections' headings.
Below attached is a screenshot of the same issue.

![Screenshot 2024-05-17 120539](https://github.com/anuragverma108/SwapReads/assets/138088550/450caadb-3482-4cf5-bde3-5f15d7d7e6f7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sambit-Mondal** [comment]
@anuragverma108 Kindly assign me this issue under GSSoC '24.

**Comment by AditiJ04** [comment]
Can you assign this issue to me?

**Comment by huamanraj** [comment]
> @anuragverma108 Kindly assign me this issue under GSSoC '24.

assigned
