### ISSUE TITLE
BUG:Repeatition of Subject and Message in Contact 

### ISSUE THREAD

**Issue by Brinda-07** [anuragverma108/SwapReads#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Contacts section there is a repeatition of two textareas namely:
Subject
Your Message
![Screenshot 2024-05-17 125850](https://github.com/anuragverma108/SwapReads/assets/154052901/9ad77d58-ffe3-431c-bf37-598eff61b572)

Please assign the issue to me so that i can remove this bug

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChhaviRohilla** [comment]
Hi! I see this issue hasn't been solved. Kindly assign this issue to me @anuragverma108 

Before:
![Screenshot 2024-05-17 134458](https://github.com/anuragverma108/SwapReads/assets/136676662/3ab4bcda-a9e6-4c33-b492-5c14a8da32c9)

After:
![Screenshot 2024-05-17 135117](https://github.com/anuragverma108/SwapReads/assets/136676662/a68d271d-155b-4843-a952-8047dc17742f)

In addition to this I saw in LIGHT MODE contact div is not as visible as in DARK MODE
![Screenshot 2024-05-17 134559](https://github.com/anuragverma108/SwapReads/assets/136676662/4c43357f-a77a-4baa-b9c3-7cb4b064c6af)

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!

**Comment by Sambit-Mondal** [comment]
@anuragverma108 You had told to solve this issue in my previous PR (#525 )

As a part of that, I had raised this issue, and also linked a PR to this!
Kindly check
