### ISSUE TITLE
Feat: Adding animations to the UI

### ISSUE THREAD

**Issue by Sambit-Mondal** [anuragverma108/SwapReads#576]
### Describe the feature

I want to add some animations while moving the cursor over the website, and clicking a button. This feature will surely enhance the website, and ensure an improved User experience.

Kindly assign me this issue under GSSoC '24.

Thank you!

### Add ScreenShots

I don't have screenshots right now, because I've not implemented it yet, but if assigned, I can assure not to disappoint you by any chance.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
