### ISSUE TITLE
Feat: Adding a Pull Request Template

### ISSUE THREAD

**Issue by Asymtode712** [anuragverma108/SwapReads#577]
### Describe the feature

Often, pull requests lack necessary details, making it difficult for reviewers to understand the changes, the reasons behind them, and how to test them. This can lead to delays in the review process, increased back-and-forth communication, and potential oversight of critical issues.
The solution is to implement a standardized pull request template. This template should include sections that prompt the author to provide essential information, such as:

- A brief description of the changes.
- The issue or feature being addressed (linked to relevant issue tracker entries).
- Screenshots or GIFs (if the changes include UI modifications).
- Checklist for confirming code adheres to coding standards, tests are added/updated, and documentation is updated.

### Add ScreenShots

![Pull Req](https://github.com/anuragverma108/SwapReads/assets/115717746/3c9e8e14-b69b-463b-8bc7-f1e3386733e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@anuragverma108 please assign me this issue under gssoc'24

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
