### ISSUE TITLE
After Send Now box again there is subject and message box

### ISSUE THREAD

**Issue by Shreesanyog** [anuragverma108/SwapReads#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the send now button again there are boxes for subject and message. 

![image](https://github.com/anuragverma108/SwapReads/assets/166977453/cb2d6c69-574f-4b4c-aaec-7fc233c67ccb)

-----

**I want to fix this as-**
![image](https://github.com/anuragverma108/SwapReads/assets/166977453/db8a5b7f-0545-465c-bcc0-2b1700d27db5)

-----
Please assign this to me under GSSoC and please give labels to it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
