### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by AtharvKasar04** [anuragverma108/SwapReads#58]
Adding a relevant favicon for the website.

@anuragverma108 Please assign this issue to me. I'll add a relevant favicon (related to the projec.)

**Comment by ayush-kumarrai** [comment]
I can apply the best favicon made by me on your website. Just, assign this task to me

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by anuragverma108** [comment]
Assigned!
