### ISSUE TITLE
Feat: Add an eye icon to show or hide the password when user wants .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#580]
### Describe the feature

If their is a eye button in the password field in login and signup then it helps the user to show or hide the password when they want 

### Add ScreenShots

![Screenshot 2024-05-17 140602](https://github.com/anuragverma108/SwapReads/assets/118350936/70f7ba3f-8013-4367-9296-ab4c28736f55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by NAhmad231** [comment]
hey can you assign this issue to me under GSSoc , I'm excited to work on it . Once assign and completed i'll attach the screenshot

**Comment by Ayushmaanagarwal1211** [comment]
Hii @NAhmad231 i already  raised PR for the same please check
