### ISSUE TITLE
BUG: Elements of navbar overlapping with each other in mobile .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the mobile view the elements of the navbar are overlapping with each other .
![Screenshot 2024-05-17 140912](https://github.com/anuragverma108/SwapReads/assets/118350936/3802c745-aee6-4e90-8f77-50e9cac101ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by brewcoder6113** [comment]
Please assign this issue to me under Gssoc'24 @anuragverma108

**Comment by Ayushmaanagarwal1211** [comment]
Hii @anuragverma108 i raised a pr for this issue and password toggling feature please review it .
