### ISSUE TITLE
BUG: Contact section elements are not aliened in the center of the page

### ISSUE THREAD

**Issue by chaanakyaaM** [anuragverma108/SwapReads#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The elements in the contact section are not aliened in the center of the webpage and makes the webpage unprofessional.

![Screenshot (216)](https://github.com/anuragverma108/SwapReads/assets/131477601/00363acc-6882-4da4-bc17-2e45575d5563)
![Screenshot (217)](https://github.com/anuragverma108/SwapReads/assets/131477601/bffbb364-9a28-4239-8147-951f65d0a6ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Noopur-Thombare** [comment]
please assign this issue to me. I would like to work on it

**Comment by chaanakyaaM** [comment]
ok

**Comment by chaanakyaaM** [comment]
I'm so glad that you have assigned an issue to me, but it seems to be like the issue is already solved.
