### ISSUE TITLE
Feat: Add a page where a book reader can log in and add or remove books from their available list for book swapping

### ISSUE THREAD

**Issue by shreyaslal** [anuragverma108/SwapReads#585]
### Describe the feature

- User authentication with text and password inputs
- Add, view, and manage your book collection
- Arrange book swaps by adding and removing books from your available list
- Responsive design with a centered layout
- Elegant UI with a soft color palette and box shadows

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/143954783/4bb8a417-92e1-4008-99b2-d798fc2c4baf)
![image](https://github.com/anuragverma108/SwapReads/assets/143954783/6ae581b7-8c9b-40ca-b54a-4243f484c8db)
![image](https://github.com/anuragverma108/SwapReads/assets/143954783/2b2c9dae-aa58-4224-8263-d611ab846464)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by shreyaslal** [comment]
@anuragverma108 I have created a PR #588 with respect to this issue, Please kindly review it and merge it. Regards

**Comment by shreyaslal** [comment]
@huamanraj Please merge PR with respect to this issue.
