### ISSUE TITLE
BUG: At login page the text and the login container is overlapping with each other .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At the time of login the text after the " Welcome to SwapReads  " is overlapping with login container .
![Screenshot 2024-05-17 162750](https://github.com/anuragverma108/SwapReads/assets/118350936/e2fdeb85-2bc7-4c18-8d45-e06180cca206)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> At the time of login the text after the " Welcome to SwapReads  " is overlapping with login container .
> ![Screenshot 2024-05-17 162750](https://github.com/anuragverma108/SwapReads/assets/118350936/e2fdeb85-2bc7-4c18-8d45-e06180cca206)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it 💪
