### ISSUE TITLE
UI : Imrprove navbar hover animation

### ISSUE THREAD

**Issue by ritu713** [anuragverma108/SwapReads#594]
### Describe the feature

On hovering over the navbar, the size of the navbar changes significantly.
This can be improved by using different techniques of showing a hover.

### Add ScreenShots

Current: 
![image](https://github.com/anuragverma108/SwapReads/assets/124053206/ebffd3dc-a686-4bce-9e04-ce672383dc13)
Proposed:
![image](https://github.com/anuragverma108/SwapReads/assets/124053206/4229d817-1b0d-4e27-823e-1ab0b39fbba7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> On hovering over the navbar, the size of the navbar changes significantly.
> This can be improved by using different techniques of showing a hover.
> 
> ### Add ScreenShots
> 
> Current: 
> ![image](https://github.com/anuragverma108/SwapReads/assets/124053206/ebffd3dc-a686-4bce-9e04-ce672383dc13)
> Proposed:
> ![image](https://github.com/anuragverma108/SwapReads/assets/124053206/4229d817-1b0d-4e27-823e-1ab0b39fbba7)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

do it buddy 💪
