### ISSUE TITLE
BUG: No reaction after submitting rating.

### ISSUE THREAD

**Issue by saketh-05** [anuragverma108/SwapReads#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If we rate the website with a 5 star on Rate us pop up, The card is blank without any reaction. I will make it look more attractive and eye-catchy. Please assign this issue to me under GSSoC'24.
![Screenshot 2024-05-17 193240](https://github.com/anuragverma108/SwapReads/assets/134281589/8d3f082c-8fb3-4973-a73d-d13f496787f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adya07pandey** [comment]
![Screenshot 2024-05-18 005824](https://github.com/anuragverma108/SwapReads/assets/170106669/908c9b75-9cb6-41c5-b02a-09ca9d349340)
I think the Rate Us popup can box can be designed more effectively.
![Screenshot 2024-05-18 005551](https://github.com/anuragverma108/SwapReads/assets/170106669/dea62342-5ad7-4187-a1ad-0a1d4629d61a)
I would like to design the pop-up box. Please assign this issue to me under GSSOC 24
