### ISSUE TITLE
in dark mode navbar hover color is no match to ui

### ISSUE THREAD

**Issue by kartikmehta18** [anuragverma108/SwapReads#598]
![image](https://github.com/anuragverma108/SwapReads/assets/125860170/ac902a9a-7ae9-434a-99ce-88a5effd53dc)
when we switch in dark mode navbar hover color does not match to UI (red color is looking bad ) we want to add color same as the button color
so it is a ui base issue if its genuan plz assign me @anuragverma108

**Comment by anshig135** [comment]
I would like to resolve this issue. Kindly assign me this under GSSOC'24.

**Comment by kartikmehta18** [comment]
https://github.com/anuragverma108/SwapReads/pull/771#issuecomment-2127103863
plz review this pr
