### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [anuragverma108/SwapReads#6]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by Abdal192003** [comment]
Hi Princegupta101,

Could please assign this issue to me under gssoc24. 
Interested to work on this issue.
Thanks

**Comment by RiyaaBhatt** [comment]
Hello team,

I would like to contribute to our project by adding a learn.md file to provide learning resources and guidelines. This file will serve as a central place for newcomers and existing contributors to understand the project structure, best practices, and how to get started.

Tasks to be Completed:

Create a learn.md file in the project repository.
Include sections such as:
Project Overview
Contribution Guidelines
Coding Standards
Setup Instructions
Useful Resources
Contact Information
Ensuing the learn.md file is well-formatted and easy to navigate.
I believe this addition will greatly benefit our contributors and streamline the onboarding process. Please assign me this task, and I'll start working on it right away as part of GSSOC'24.

Thank you for considering my contribution!

Best regards.

**Comment by RiyaaBhatt** [comment]
hello @Abdal192003  and @huamanraj  can you provide discord id for further communication

**Comment by huamanraj** [comment]
> hello @Abdal192003  and @huamanraj  can you provide discord id for further communication

till now there is no discord server but you can ping me on my personal id: `amanraj #1894`

**Comment by anuragverma108** [comment]
Any Updates @RiyaaBhatt
