### ISSUE TITLE
after login the username must show in the home page but not showing 

### ISSUE THREAD

**Issue by Subhams-GIT** [anuragverma108/SwapReads#60]
the username must show and there should be a profile page for user as well 
can i use my own db for testing if assigned under gssoc 24

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Subhams-GIT** [comment]
have you used firebase as your backend or js

**Comment by khushikunte** [comment]
I am khushi kunte.I would like to work on this issues.Please assign this task to me.

**Comment by Subhams-GIT** [comment]
please allow me to push changes its showing access denied
