### ISSUE TITLE
BUG: Dark Mode has various differences in style [ Improvised navbar and section color for better appearance]

### ISSUE THREAD

**Issue by ChhaviRohilla** [anuragverma108/SwapReads#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The style of site is not good in visual when mode is changed from **light** to **dark**
Major differences are in: shadow alignment, background color, text color
@anuragverma108 kindly assign this issue to me

Added Screenshots for reference :
![Screenshot 2024-05-17 134559](https://github.com/anuragverma108/SwapReads/assets/136676662/1beb4f8e-9846-4434-aa8c-6cedaaad0f25)
![Screenshot 2024-05-17 135117](https://github.com/anuragverma108/SwapReads/assets/136676662/34667cce-c94f-4dcc-94af-a69ba3b4d808)
![Screenshot 2024-05-17 214922](https://github.com/anuragverma108/SwapReads/assets/136676662/3f7a7090-5415-4ff0-8346-d1e685ae5803)
![Screenshot 2024-05-17 214929](https://github.com/anuragverma108/SwapReads/assets/136676662/0e23dcf8-806a-4c8a-b250-f15223ffa7e3)
![Screenshot 2024-05-17 214949](https://github.com/anuragverma108/SwapReads/assets/136676662/db01e2aa-adc3-49c8-8465-10dc48855236)
![Screenshot 2024-05-17 214957](https://github.com/anuragverma108/SwapReads/assets/136676662/23c8088e-ec01-4957-ada9-f09e86d1c611)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChhaviRohilla** [comment]
@anuragverma108 assign this issue to me

**Comment by huamanraj** [comment]
> @anuragverma108 assign this issue to me
> 
> After correction:
> ![Screenshot 2024-05-18 143000](https://github.com/anuragverma108/SwapReads/assets/136676662/eb21d99f-8b21-49d3-8b6b-64364f2f9368)
> ![Screenshot 2024-05-18 143009](https://github.com/anuragverma108/SwapReads/assets/136676662/dacf4300-b9a4-46be-9056-e554b1122d1d)
> ![Screenshot 2024-05-18 143039](https://github.com/anuragverma108/SwapReads/assets/136676662/6355b1c6-b19e-42fa-a586-e7925812f2b2)
> ![Screenshot 2024-05-18 143110](https://github.com/anuragverma108/SwapReads/assets/136676662/2c7d1faf-fc2f-4b57-b13f-819cd21b58be)
> 

assigned!

**Comment by ChhaviRohilla** [comment]
@huamanraj sir the time I raised this issue there was one less section, addition of a new section changed the color property of other section therefore I made changes accordingly.

Adding screenshot for reference:
**Before:**
![Screenshot 2024-05-22 000433](https://github.com/anuragverma108/SwapReads/assets/136676662/5a3a917e-6863-431c-b2f7-c621003a603d)
![Screenshot 2024-05-22 000454](https://github.com/anuragverma108/SwapReads/assets/136676662/040c6430-6709-4455-baf0-95fdf15b5f5b)
![Screenshot 2024-05-22 000519](https://github.com/anuragverma108/SwapReads/assets/136676662/cc7b6c66-e0cf-4597-9758-592b647ffb7e)

 
**After:**
![Screenshot 2024-05-22 000620](https://github.com/anuragverma108/SwapReads/assets/136676662/31302ca9-779e-47da-8b0a-0c91b5471d1f)
![Screenshot 2024-05-22 000641](https://github.com/anuragverma108/SwapReads/assets/136676662/79303a15-02c2-445a-a629-cd2ffd2cc47c)
![Screenshot 2024-05-22 000751](https://github.com/anuragverma108/SwapReads/assets/136676662/dccf4db0-add7-46ce-bccd-cb21c302dfaa)


if all okay?
can i raise the pull request


In addition to this I tried to improvised the navbar 
**before:**
![Screenshot 2024-05-22 000420](https://github.com/anuragverma108/SwapReads/assets/136676662/514634b1-bb1d-4cf3-836f-73b6662ab1aa)
**After:**
![Screenshot 2024-05-22 000608](https://github.com/anuragverma108/SwapReads/assets/136676662/3f35f391-8a43-4b2e-acfc-fb8c900b6850)

**Comment by huamanraj** [comment]
> @huamanraj sir the time I raised this issue there was one less section, addition of a new section changed the color property of other section therefore I made changes accordingly.
> 
> Adding screenshot for reference:
> **Before:**
> ![Screenshot 2024-05-22 000433](https://github.com/anuragverma108/SwapReads/assets/136676662/5a3a917e-6863-431c-b2f7-c621003a603d)
> ![Screenshot 2024-05-22 000454](https://github.com/anuragverma108/SwapReads/assets/136676662/040c6430-6709-4455-baf0-95fdf15b5f5b)
> ![Screenshot 2024-05-22 000519](https://github.com/anuragverma108/SwapReads/assets/136676662/cc7b6c66-e0cf-4597-9758-592b647ffb7e)
> 
>  
> **After:**
> ![Screenshot 2024-05-22 000620](https://github.com/anuragverma108/SwapReads/assets/136676662/31302ca9-779e-47da-8b0a-0c91b5471d1f)
> ![Screenshot 2024-05-22 000641](https://github.com/anuragverma108/SwapReads/assets/136676662/79303a15-02c2-445a-a629-cd2ffd2cc47c)
> ![Screenshot 2024-05-22 000751](https://github.com/anuragverma108/SwapReads/assets/136676662/dccf4db0-add7-46ce-bccd-cb21c302dfaa)
> 
> 
> if all okay?
> can i raise the pull request
> 
> 
> In addition to this I tried to improvised the navbar 
> **before:**
> ![Screenshot 2024-05-22 000420](https://github.com/anuragverma108/SwapReads/assets/136676662/514634b1-bb1d-4cf3-836f-73b6662ab1aa)
> **After:**
> ![Screenshot 2024-05-22 000608](https://github.com/anuragverma108/SwapReads/assets/136676662/3f35f391-8a43-4b2e-acfc-fb8c900b6850)
> 

awesome work @ChhaviRohilla 👏! 
raise a PR and dont forget to do changes in the latest codebase other it can lead to conflicts! 
also tag me in PR!
