### ISSUE TITLE
Feat: Add 3 more Genres poetry, philosophy and adventure fiction

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#602]
### Describe the feature

I want to add 3 more book genres so that we can explore a variety of books.
There are 9 genres and I want to add 3 more.
I want to work on this issue.
Please assign this task to me @anuragverma108 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/130165687/aa69d71e-0abe-4c5a-996d-19d913cf7f79)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> I want to add 3 more book genres so that we can explore a variety of books.
> There are 9 genres and I want to add 3 more.
> I want to work on this issue.
> Please assign this task to me @anuragverma108 
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/130165687/aa69d71e-0abe-4c5a-996d-19d913cf7f79)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

do it 💪

**Comment by ParthNakum21** [comment]
Hello, I'm interested in contributing to the project by adding more number of genres. It will be helpful for the diverse readers. Could you please assign this task to me under GSSoC with appropriate level?
