### ISSUE TITLE
Feat :Logo in the navbar

### ISSUE THREAD

**Issue by ananya-sh30** [anuragverma108/SwapReads#603]
### Describe the feature

Hi I would like to design the logo according to the colors of the website and then add it to the leftmost part of the navbar.
Please consider assigning this issue to me along with gssoc labels. 

### Add ScreenShots

Here is the reference 
![Screenshot 2024-05-17 224449](https://github.com/anuragverma108/SwapReads/assets/142817946/207f2d97-bddd-42a0-90db-4cc713ba7cc3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ananya-sh30** [comment]
@huamanraj please review this logo and let me know if there are any changes to be made.
![logo_whitebg](https://github.com/anuragverma108/SwapReads/assets/142817946/148c935b-547d-4fe6-9a92-6229c4671b31)

![Screenshot 2024-05-18 023615](https://github.com/anuragverma108/SwapReads/assets/142817946/7b612400-7bb1-45e7-8d38-16087fc9f9b5)

**Comment by ananya-sh30** [comment]
This is another idea I came up with-
![logo2](https://github.com/anuragverma108/SwapReads/assets/142817946/608b166a-c64d-42df-9356-8d79fefbfef5)
Let me know which one is better so that I can proceed further

**Comment by NAhmad231** [comment]
hey can you assign this issue to me , i'll try my best

**Comment by huamanraj** [comment]
> @huamanraj please review asap so that I can proceed with the pull request 

this is good 💯

**Comment by huamanraj** [comment]
> This is another idea I came up with-
> ![logo2](https://github.com/anuragverma108/SwapReads/assets/142817946/608b166a-c64d-42df-9356-8d79fefbfef5)
> Let me know which one is better so that I can proceed further
> 

this one is good just remove the upper text slogan @ananya-sh30

**Comment by ananya-sh30** [comment]
Okay I'll do that
