### ISSUE TITLE
BUG: Log in/Sign up form not responsive

### ISSUE THREAD

**Issue by karishmaaa101** [anuragverma108/SwapReads#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On clicking the **log in/sign up page** :
![image](https://github.com/anuragverma108/SwapReads/assets/104766763/16f2ddf9-7a0e-403a-b5cf-9efc0fa063df)
 It redirects to this page ( as shown below):
 On clicking **sign up with google**,its says to **fill necessary fields:**

![image](https://github.com/anuragverma108/SwapReads/assets/104766763/864c0139-1c50-4400-893a-3a3f64610155)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Albert-2** [comment]
hey @anuragverma108 
I am very good at responsive designs so can you please assign me this issue
Thank You...!

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.

**Comment by anuragverma108** [comment]
@karishmaaa101 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
@Albert-2 @KashishRathore 
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by karishmaaa101** [comment]
Yes I am working on it.
