### ISSUE TITLE
Feat:Navbar needs to be fixed in small Device

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#606]
### Describe the feature

Navbar needs to be fixed for small device

### Add ScreenShots

![Screenshot_20240517_225217](https://github.com/anuragverma108/SwapReads/assets/59639410/858ba012-2e1e-4587-a41d-2ed3c2a8925b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @anuragverma108 please assign this issue to me under gssoc 24

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Navbar needs to be fixed for small device
> 
> ### Add ScreenShots
> 
> ![Screenshot_20240517_225217](https://github.com/anuragverma108/SwapReads/assets/59639410/858ba012-2e1e-4587-a41d-2ed3c2a8925b)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned
