### ISSUE TITLE
Feat: swap reads and quicks link overlap each other in mobile view

### ISSUE THREAD

**Issue by kapilG0** [anuragverma108/SwapReads#607]
### Describe the feature

Swap reads and quick links overlap each other in mobile view

### Add ScreenShots

![Screenshot_20240517_225646](https://github.com/anuragverma108/SwapReads/assets/59639410/820f9631-b1ea-42df-b161-7542858f4795)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @anuragverma108 please assign this issue to me under gssoc 24

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Swap reads and quick links overlap each other in mobile view
> 
> ### Add ScreenShots
> 
> ![Screenshot_20240517_225646](https://github.com/anuragverma108/SwapReads/assets/59639410/820f9631-b1ea-42df-b161-7542858f4795)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

issue is already opened!
