### ISSUE TITLE
[BUG] : Footer Links are not functional

### ISSUE THREAD

**Issue by Sudhanshu2306** [anuragverma108/SwapReads#61]
**Describe the bug**
Home Benefits Literary Realms Pricing Review Contact in the footer section do not redirects to particular section

**To Reproduce**
1. Go to 'Footer'
2. Click on 'Home' etc
3. It do not redirects

**Expected behavior**
It should redirect to different sections.

**Screenshots**
![image](https://github.com/anuragverma108/SwapReads/assets/126086429/f45aa793-8ea6-4021-860a-9cf91bf81537)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [e.g. chrome]

**Comment by Sudhanshu2306** [comment]
small bug, please merge the fixed code, I'll create a pull request in 5 minutes.

**Comment by anuragverma108** [comment]
Assigned

**Comment by Sudhanshu2306** [comment]
@anuragverma108  Thank you! Please check for the pull request made.
