### ISSUE TITLE
BUG:  login page reset button is not working 

### ISSUE THREAD

**Issue by mk016** [anuragverma108/SwapReads#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-18 at 1 43 14 AM](https://github.com/anuragverma108/SwapReads/assets/117855423/b2b976a6-6d90-4662-b1f9-53de9c025402)

please assign for solve this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamhvsharma** [comment]
Assign me!
