### ISSUE TITLE
BUG:  In the Navbar Genre Button Underline is not Showing  ( LIght & dark )

### ISSUE THREAD

**Issue by mk016** [anuragverma108/SwapReads#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="724" alt="Screenshot 2024-05-18 at 3 50 03 AM" src="https://github.com/anuragverma108/SwapReads/assets/117855423/72a7505c-4616-4f75-bbb4-4493f8671eda">
<img width="1419" alt="Screenshot 2024-05-18 at 3 51 18 AM" src="https://github.com/anuragverma108/SwapReads/assets/117855423/ef162ac4-eb2c-432a-92bb-4752578e878b">
please assign i can fix this 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> <img width="724" alt="Screenshot 2024-05-18 at 3 50 03 AM" src="https://github.com/anuragverma108/SwapReads/assets/117855423/72a7505c-4616-4f75-bbb4-4493f8671eda">
> <img width="1419" alt="Screenshot 2024-05-18 at 3 51 18 AM" src="https://github.com/anuragverma108/SwapReads/assets/117855423/ef162ac4-eb2c-432a-92bb-4752578e878b">
> please assign i can fix this 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned
