### ISSUE TITLE
BUG: Improve Newsletter Title Visibility in Dark Mode

### ISSUE THREAD

**Issue by ojasvi004** [anuragverma108/SwapReads#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Under the dark background, the dark grey "Newsletter" text is not very legible. The low contrast makes it difficult to read. I suggest changing the text to lighter shades to improve readability.

![image](https://github.com/anuragverma108/SwapReads/assets/123376306/10b61559-4b33-450f-9057-26a346682e8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Under the dark background, the dark grey "Newsletter" text is not very legible. The low contrast makes it difficult to read. I suggest changing the text to lighter shades to improve readability.
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/123376306/10b61559-4b33-450f-9057-26a346682e8c)
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned!
