### ISSUE TITLE
Feat: Rate Us popup

### ISSUE THREAD

**Issue by adya07pandey** [anuragverma108/SwapReads#626]
### Describe the feature

The Rate Us pop can be improved to make it more attractive. The current popup looks like this in light and dark mode both.

### Add ScreenShots

![Screenshot 2024-05-18 135502](https://github.com/anuragverma108/SwapReads/assets/170106669/44dfd828-bf96-49b5-9071-c7962e83daec)
![Screenshot 2024-05-18 135439](https://github.com/anuragverma108/SwapReads/assets/170106669/0c3bb49a-5c83-4d9f-b311-aa0aae56e297)
My plan is to redesign it to make it look more elegant.
![Screenshot 2024-05-18 005551](https://github.com/anuragverma108/SwapReads/assets/170106669/d81e95a8-692e-4bdb-909a-365154abecef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> The Rate Us pop can be improved to make it more attractive. The current popup looks like this in light and dark mode both.
> 
> 
> ### Add ScreenShots
> 
> ![Screenshot 2024-05-18 135502](https://github.com/anuragverma108/SwapReads/assets/170106669/44dfd828-bf96-49b5-9071-c7962e83daec)
> ![Screenshot 2024-05-18 135439](https://github.com/anuragverma108/SwapReads/assets/170106669/0c3bb49a-5c83-4d9f-b311-aa0aae56e297)
> My plan is to redesign it to make it look more elegant.
> ![Screenshot 2024-05-18 005551](https://github.com/anuragverma108/SwapReads/assets/170106669/d81e95a8-692e-4bdb-909a-365154abecef)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned

**Comment by anuragverma108** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/129655645/ea4c93e3-fb6b-4fa5-a9a9-edf92d36af6e)
Two boxes are overlapping over each other. 
pull all the changes & do this again. I am reverting our PR
