### ISSUE TITLE
BUG: NavBar not visible in dark mode and Pricing divs have no shadow effect therefore not visually appealing

### ISSUE THREAD

**Issue by ChhaviRohilla** [anuragverma108/SwapReads#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Before:**
Light mode navbar is visible
![Screenshot 2024-05-18 143823](https://github.com/anuragverma108/SwapReads/assets/136676662/c3c0bf3b-25c9-4280-8625-f281e832b003)

dark mode nav bar is **not** visible
![Screenshot 2024-05-18 143828](https://github.com/anuragverma108/SwapReads/assets/136676662/356e67a4-06d4-4304-9749-564b3ff72960)

pricing div **no shadow** 
![Screenshot 2024-05-18 144034](https://github.com/anuragverma108/SwapReads/assets/136676662/decb88ce-55d8-4351-8650-1ad1e81a43df)

visually not appealing
![Screenshot 2024-05-18 144050](https://github.com/anuragverma108/SwapReads/assets/136676662/e45daeae-7da8-4d5e-99ba-ceb918013e37)

**After:**
(nav one is for illustration purpose )
![Screenshot 2024-05-18 144824](https://github.com/anuragverma108/SwapReads/assets/136676662/a07ad21b-1260-473a-99bb-c5e20fdb802e)
![Screenshot 2024-05-18 144847](https://github.com/anuragverma108/SwapReads/assets/136676662/a9624922-f428-4c9c-bccd-3469035abeb0)
![Screenshot 2024-05-18 144855](https://github.com/anuragverma108/SwapReads/assets/136676662/440db8a0-a7c7-455d-99a8-677e0611096c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChhaviRohilla** [comment]
@anuragverma108  or @huamanraj assign this to me

**Comment by huamanraj** [comment]
> @anuragverma108  or @huamanraj assign this to me

assigned!

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
I am looking forward to do this in min. time with max. efficient.
@huamanraj
