### ISSUE TITLE
Realignment of Navbar | Enhancement of Navbar

### ISSUE THREAD

**Issue by iamhvsharma** [anuragverma108/SwapReads#630]
I would like to work on the navbar as it is not looking good. we need to change some words and realign all the list element in the navbar so that it should come in a single row horizontally. 

![image](https://github.com/anuragverma108/SwapReads/assets/123243221/1d07c910-c490-4716-b787-f5421dae584f)

Please assign me

**Comment by Albert-2** [comment]
hey @anuragverma108 
I really want to contribute to this issue can you please assign me the same.
Thank You...!
Happy Coding...:)

**Comment by iamhvsharma** [comment]
Hey @anuragverma108 

My code is ready which is solving this issue. 
Kindly assign me this issue :)

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.
