### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by iamhvsharma** [anuragverma108/SwapReads#631]
In the Book Exchange section.

There is no margin between the Paragraph and Book Title.

There should be the same margin that is given between Book Title and Autor.

![image](https://github.com/anuragverma108/SwapReads/assets/123243221/29a3ff87-efbd-435d-97dd-dd3a16d955c2)

Please assign me.

**Comment by Paavni-Goyal** [comment]
Hey, can you please assign me this issue. I can contribute to the same.

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.

**Comment by huamanraj** [comment]
> In the Book Exchange section.
> 
> There is no margin between the Paragraph and Book Title.
> 
> There should be the same margin that is given between Book Title and Autor.
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/123243221/29a3ff87-efbd-435d-97dd-dd3a16d955c2)
> 
> Please assign me.
> 
assigned! tag me when you create a PR!
