### ISSUE TITLE
BUG: Contact form Email input is accepting any input.

### ISSUE THREAD

**Issue by iamhvsharma** [anuragverma108/SwapReads#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the contact form, there is an Email Input.

Which is accepting any input but the condition is that there should be '@' and some text after that. We can restrict that there should be a @gmail in the email. 

![image](https://github.com/anuragverma108/SwapReads/assets/123243221/1e05cd01-6b16-4cd8-922e-396b7410402a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> On the contact form, there is an Email Input.
> 
> Which is accepting any input but the condition is that there should be '@' and some text after that. We can restrict that there should be a @gmail in the email. 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/123243221/1e05cd01-6b16-4cd8-922e-396b7410402a)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

fix it!

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
I am looking forward to do this in min. time with max. efficient.
