### ISSUE TITLE
Code Structuring : the contributors made the repo dirty and hard to understand for new contributors! Structure the code in a good manner!

### ISSUE THREAD

**Issue by huamanraj** [anuragverma108/SwapReads#635]
You can work collaboratively with multiple contributors everyone will get PR merged with L3 GSSOC!

**Comment by komalverma04** [comment]
I want to work on this issue. Please assign it to me.

**Comment by huamanraj** [comment]
> I want to work on this issue. Please assign it to me.

work on it! you can always reach out to me for any help!

**Comment by CoderGirl2844** [comment]
I want to work on this issue ,please assign it to me @huamanraj

**Comment by huamanraj** [comment]
> I want to work on this issue ,please assign it to me @huamanraj 

you can work collaboratively with @komalverma04

**Comment by CoderGirl2844** [comment]
Please assign it to me @huamanraj

**Comment by Ajita369** [comment]
I will like to work on this issue, can you please assign this issue to me?
