### ISSUE TITLE
BUG: Genre is not updating in navbar when we scroll to it 

### ISSUE THREAD

**Issue by YukiP7** [anuragverma108/SwapReads#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever we scroll down a website and hover over the navbar, different elements are addressed on the website. The issue is that the "genre" section is not updating when we scroll to it. Instead, it shows "benefits" in the place of "genre."

![Screenshot 2024-05-18 202738](https://github.com/anuragverma108/SwapReads/assets/109288720/5401910f-b211-4764-8eb5-333f67d9d367)

I would like you to assign this issue to me and label it as gssoc .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
I am looking forward to do this in min. time with max. efficient.
