### ISSUE TITLE
Feat: Decrease the Navbar Content

### ISSUE THREAD

**Issue by theeayushkumar** [anuragverma108/SwapReads#644]
### Describe the feature

It looks very bad because the navbar has many options i would like to decrease the navbar contents 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/128235540/01c5b2d0-f866-4c08-b065-7c3be733cf00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> It looks very bad because the navbar has many options i would like to decrease the navbar contents 
> 
> ### Add ScreenShots
> 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/128235540/01c5b2d0-f866-4c08-b065-7c3be733cf00)
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

yes do it! use some expanding list type of elements!

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
I am looking forward to do this in min. time with max. efficient.
