### ISSUE TITLE
Typo error in romance genre

### ISSUE THREAD

**Issue by Ajita369** [anuragverma108/SwapReads#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The first sentence of romance genre has some grammatical errors . The sentence should be more like this "A romance is understood to be a love story that is primarily focused on the relationship between the main characters of the story."  instead of what is written.
![image](https://github.com/anuragverma108/SwapReads/assets/162597493/636c1861-e795-4e8d-8530-914bf82e2264)
I will like to work on this issue so please assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Iamkg11** [comment]
Please assign this issue to me under GssoC'24

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The first sentence of romance genre has some grammatical errors . The sentence should be more like this "A romance is understood to be a love story that is primarily focused on the relationship between the main characters of the story."  instead of what is written.
> ![image](https://github.com/anuragverma108/SwapReads/assets/162597493/636c1861-e795-4e8d-8530-914bf82e2264)
> I will like to work on this issue so please assign this issue to me under GSSOC'24.
> 
> 
> 
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it!

**Comment by shruti-mishraa** [comment]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?
The issue I addressed was a typo in the description of the Romance genre. Specifically,  adding quotation marks around the phrases "love stories" and "happily ever after" for consistency and clarity.

![Screenshot 2024-05-19 162257](https://github.com/anuragverma108/SwapReads/assets/92870611/eb738cba-a2ec-4ccf-99b6-d774c539bbcf)

I would like to work on this issue so please assign this issue to me under GSSOC'24.

### Record
- [ ] I agree to follow this project's Code of Conduct

- [ ]  I'm a GSSOC'24 contributor

- [ ]  I want to work on this issue
