### ISSUE TITLE
AI chatbot

### ISSUE THREAD

**Issue by aditi9402** [anuragverma108/SwapReads#646]
### Describe the feature

An AI chatbot specific to the site's data. 
I created this for one of my projects earlier. It would look something like this:

### Add ScreenShots

![Screenshot (562)](https://github.com/anuragverma108/SwapReads/assets/114405540/d71edcb3-f6ce-4a26-82ed-8cf77ea57061)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
great! assigned
