### ISSUE TITLE
Feat: Add back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#649]
### Describe the feature

The back to top scroll button is button which helps in easy navigation of the website. The smooth scrolling to top of the website is the functionality of the button.
Please assign this issue to me @anuragverma108 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/130165687/8ec8b301-f281-4b4d-b43f-b7830f622846)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
assigned!! use a svg icon with the theme similar to website

**Comment by RitiChandak** [comment]
@Saimanjari777 Done 

Great contribution to GSSOC'24!
