### ISSUE TITLE
BUG: Dark mode not present for Login/SignUp

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login/sign up doesn't has the dark mode which I would like to add to make it more appealing.
![image](https://github.com/anuragverma108/SwapReads/assets/130165687/d37674df-695d-4c23-9ad5-ff3a21e9afec)
Please assign this task to me @anuragverma108 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The login/sign up doesn't has the dark mode which I would like to add to make it more appealing.
> ![image](https://github.com/anuragverma108/SwapReads/assets/130165687/d37674df-695d-4c23-9ad5-ff3a21e9afec)
> Please assign this task to me @anuragverma108 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned!
