### ISSUE TITLE
BUG: Changing the colour of navbar while in dark mode.

### ISSUE THREAD

**Issue by rishmiiee26** [anuragverma108/SwapReads#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-18 225201](https://github.com/anuragverma108/SwapReads/assets/154092772/02b66b51-2690-4b40-834c-af621ae2aaf9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![Screenshot 2024-05-18 225201](https://github.com/anuragverma108/SwapReads/assets/154092772/02b66b51-2690-4b40-834c-af621ae2aaf9)
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it!
