### ISSUE TITLE
Feat: Subscribe to newsletter must be just above the footer and in the center of web page, taking 100% of width

### ISSUE THREAD

**Issue by divyalaldinani** [anuragverma108/SwapReads#654]
### Describe the feature

now:
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/06212313-b6ba-4055-b597-27d803994c8b)

should be like this:
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/444a97eb-6fe7-41af-a375-73675ed6c20b)

### Add ScreenShots

added above

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> now:
> ![image](https://github.com/anuragverma108/SwapReads/assets/82147067/06212313-b6ba-4055-b597-27d803994c8b)
> 
> 
> should be like this:
> ![image](https://github.com/anuragverma108/SwapReads/assets/82147067/444a97eb-6fe7-41af-a375-73675ed6c20b)
> 
> 
> ### Add ScreenShots
> 
> added above
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

but then we have to redesign the footer cause there is a lot of empty space

**Comment by divyalaldinani** [comment]
> > ### Describe the feature
> > now:
> > ![image](https://private-user-images.githubusercontent.com/82147067/331820073-06212313-b6ba-4055-b597-27d803994c8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTY4NjYsIm5iZiI6MTcxNjA1NjU2NiwicGF0aCI6Ii84MjE0NzA2Ny8zMzE4MjAwNzMtMDYyMTIzMTMtYjZiYS00MDU1LWI1OTctMjdkODAzOTk0YzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE4MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMmFlZTdhOWQ3N2I4NmJkMzVmNmQ2MDBlZjFkZDkwMzY2MWFkMDY0M2Q1Yzk2MWEwOGQ0MTIzMjk1NmZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NhHQESk3gAbdtjfgvx0XMYExfiFLOnH8S_18WQ5FgyQ)
> > should be like this:
> > ![image](https://private-user-images.githubusercontent.com/82147067/331820168-444a97eb-6fe7-41af-a375-73675ed6c20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTY4NjYsIm5iZiI6MTcxNjA1NjU2NiwicGF0aCI6Ii84MjE0NzA2Ny8zMzE4MjAxNjgtNDQ0YTk3ZWItNmZlNy00MWFmLWEzNzUtNzM2NzVlZDZjMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE4MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTUwMTljOTNmYmUwZmQxYzNkNDI2ZGI5ZjQwYzk2ODAwOTBmYjM0OTFmMGE3ODg4MDAyZGJhNDc2YzMzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oi1urlXtA7to9FNwQnEwq5zLfkZ0yMeVDNBjgmbq6AU)
> > ### Add ScreenShots
> > added above
> > ### Record
> > 
> > * [x]  I agree to follow this project's Code of Conduct
> > * [x]  I'm a GSSOC'24 contributor
> > * [x]  I want to work on this issue
> 
> but then we have to redesign the footer cause there is a lot of empty space

yeah, you are right, check out the footer of this
https://www.deeplearning.ai/

if you want, i can change it to something like this

**Comment by divyalaldinani** [comment]
hey @huamanraj let me know, if i should start working on it..

**Comment by huamanraj** [comment]
> hey @huamanraj let me know, if i should start working on it..

great 👍 
yup work on it! and take care of website theme! 

and ping me for any help you need. 
 i am the mentor of this project!

**Comment by anuragverma108** [comment]
@divyalaldinani 

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by divyalaldinani** [comment]
@huamanraj @anuragverma108 
it looks like this now
![image](https://github.com/anuragverma108/SwapReads/assets/82147067/6fe42612-eb03-4722-8d17-d9d64a4ba80f)

should i make changes to footer also? like adjusting the sm icons ?

**Comment by divyalaldinani** [comment]
@anuragverma108 hey can you check it once?

> @huamanraj @anuragverma108 it looks like this now ![image](https://private-user-images.githubusercontent.com/82147067/333877047-6fe42612-eb03-4722-8d17-d9d64a4ba80f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjk4NzgsIm5iZiI6MTcxNzA2OTU3OCwicGF0aCI6Ii84MjE0NzA2Ny8zMzM4NzcwNDctNmZlNDI2MTItZWIwMy00NzIyLThkMTctZDlkNjRhNGJhODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExNDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMTBlNmMwM2Q5N2Q3NDFhYzY5MTdlODZiMWQ4M2Q3ZWYwZjg3ZTlkYWNhZmM0OWNkOTBkOWFmZWI2OGQyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8P7AJwqR2eCzwl5B0JkvQKSWohArchlC6Wp_1R7pFE)
> 
> should i make changes to footer also? like adjusting the sm icons ?

**Comment by divyalaldinani** [comment]
@huamanraj @anuragverma108 can you check it once?

**Comment by huamanraj** [comment]
> @huamanraj @anuragverma108 can you check it once?

sorry for the late response because there are a lot of issues and PRs in repo 
and thanks for showing the patience and understanding 
you can go with this and create a PR on the latest codebase! 
i am the project mentor so reach out to me for any help needed! @divyalaldinani
