### ISSUE TITLE
Fix login page's new content's UI issue.

### ISSUE THREAD

**Issue by justmirr** [anuragverma108/SwapReads#657]
As the contributors have added new content to the login box, I'd like to fix the UI issues that come with it like the alignment, color, font, and effects that do not match with the login page, more of which can be seen in dark mode. The size of the login box is getting bigger too with all the additions.

![loginpage](https://github.com/anuragverma108/SwapReads/assets/75358919/38169ed6-af61-472d-9f80-068ac5b4283c)
![loginpage (2)](https://github.com/anuragverma108/SwapReads/assets/75358919/8bb2e0b9-75ea-4806-9189-02bd9418c4ec)

**Comment by justmirr** [comment]
Also, this first horizontal line is visually annoying too.

**Comment by medhakashyap** [comment]
@justmirr please assign this issue to me for GSSoC'24

**Comment by anuragverma108** [comment]
@justmirr 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
