### ISSUE TITLE
Adding transitions to Navigation bar components.

### ISSUE THREAD

**Issue by PSP2706** [anuragverma108/SwapReads#66]
This issue aims to improve user experience by implementing smooth transitions for the components in the navigation bar. By adding transitions, we can create a more polished and seamless navigation experience, enhancing aesthetic appeal.

**Comment by PSP2706** [comment]
Please assign me this task.

**Comment by anuragverma108** [comment]
Assigned!

**Comment by sakshiiiii26** [comment]
I want to work on this please assign me this task.

**Comment by krati234** [comment]
assign please

**Comment by PSP2706** [comment]
I created a pull request on May 11 which was merged

**Comment by RitiChandak** [comment]
@PSP2706 okay
