### ISSUE TITLE
add hover effect on chapter card

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#662]
### Describe the feature

add a hover effect on chapter card
> curser on the card its does hover(zoom out) effect

### Add ScreenShots

<img width="1207" alt="Screenshot 2024-05-19 at 2 47 01 AM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/e1c8e80f-ac9a-472f-b99e-fbdffc769a7d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
i can add the hover effect on the chapter card with box shadows and div animations, make it look minimalistic yet interesting.

**Comment by huamanraj** [comment]
> i can add the hover effect on the chapter card with box shadows and div animations, make it look minimalistic yet interesting. 

assigned! tag me when you create a PR!

**Comment by harshcodesit** [comment]
done sir. created a PR

**Comment by harshcodesit** [comment]
> > i can add the hover effect on the chapter card with box shadows and div animations, make it look minimalistic yet interesting.
> 
> assigned! tag me when you create a PR!

done sir, created a PR  #724
