### ISSUE TITLE
Feat: UI enhancement

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [anuragverma108/SwapReads#663]
### Describe the feature

In the above picture, the login and sign-up are not that accurate. It can be changed or should merge with the login and signup already created. 

Can you assign it to me? @anuragverma108 

Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/122172211/9cbaf7b3-881b-4608-ad15-3d95c2ada621)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Akshitha-reddy-13** [comment]
Thank you so much!! 

I will start working on it and complete it ASAP.
