### ISSUE TITLE
Feat: Add Cookies Feature

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#664]
### Describe the feature

It helps websites remember information about your visit, which can make it easier to visit the site again and make the site more useful to you.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> It helps websites remember information about your visit, which can make it easier to visit the site again and make the site more useful to you.
> 
> ### Add ScreenShots
> 
> .
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!
