### ISSUE TITLE
BUG: Improve footer UI in dark mode

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Many elements in footer are not seen in dark mode. 
Also the colour of social media icons does not match with the website's UI.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/89eb748c-45d3-4e13-a9bd-121ee299105a)

I want to work on this. @huamanraj @anuragverma108 Please assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
i can totally help with that, make the UI more appealing and add animations, and some interactive codepen elements can also be added

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Many elements in footer are not seen in dark mode. 
> Also the colour of social media icons does not match with the website's UI.
> ![image](https://github.com/anuragverma108/SwapReads/assets/146222028/89eb748c-45d3-4e13-a9bd-121ee299105a)
> 
> I want to work on this. @huamanraj @anuragverma108 Please assign this to me under GSSoC'24.
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!
