### ISSUE TITLE
#multiple send now button in contact section

### ISSUE THREAD

**Issue by roushanverma23** [anuragverma108/SwapReads#669]
### Describe the feature

multiple send now button in contact section

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/137530796/71855904-692d-426b-8be9-5a5a2ace05f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by roushanverma23** [comment]
@anuragverma108 please assign this to me i want to work on this 

---------------------------------------------------------------------------------------------
![gssoc](https://github.com/anuragverma108/SwapReads/assets/137530796/65ad44be-1203-4f1e-8d75-bdc9834fb357)

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
