### ISSUE TITLE
BUG: Two send button in Contact Us section

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/30e23e69-c8d2-445b-9605-5af4a0eb1611)

there are two subject, your message sections and 2 send buttons

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@anuragverma108 please assign this issue to me. I am participating as a contributor in GSSoC'24

**Comment by geetanjali-22** [comment]
I would like to work on this project. Please assign it to me under GSSOC'24.
