### ISSUE TITLE
BUG: In the forget page home button is not working

### ISSUE THREAD

**Issue by AbhiDiva96** [anuragverma108/SwapReads#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## On the forget page, the home button is not working.
it required improvement in path.

pls assigned me under the gssoc'24
@anuragverma108 

## Issue
https://github.com/anuragverma108/SwapReads/assets/112077897/5d4611a3-7c31-478d-b558-9a653ecd3956

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhiDiva96** [comment]
hey @anuragverma108 
pls visit this issue and assigned me.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by AbhiDiva96** [comment]
hey @anuragverma108 
fix the issue and created PR pls review .
