### ISSUE TITLE
Changing Hover effects in Dark Mode

### ISSUE THREAD

**Issue by anagha-chaudhari** [anuragverma108/SwapReads#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've noticed that hover effects are a bit depressing in the dark mode. I would like to modify the hover effects in the dark mode to make them more appealing. Can you assign me this issue?

![swapReads](https://github.com/anuragverma108/SwapReads/assets/143149376/34e24799-0bbe-425d-8e52-e7581f9d689f)

![swapReads2](https://github.com/anuragverma108/SwapReads/assets/143149376/f347e2b1-55f8-4417-8e69-b040970a7b0d)

![swapReads3](https://github.com/anuragverma108/SwapReads/assets/143149376/bce3f05c-22ed-4af0-96fc-d88e60710f17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> I've noticed that hover effects are a bit depressing in the dark mode. I would like to modify the hover effects in the dark mode to make them more appealing. Can you assign me this issue?
> 
> ![swapReads](https://github.com/anuragverma108/SwapReads/assets/143149376/34e24799-0bbe-425d-8e52-e7581f9d689f)
> 
> ![swapReads2](https://github.com/anuragverma108/SwapReads/assets/143149376/f347e2b1-55f8-4417-8e69-b040970a7b0d)
> 
> ![swapReads3](https://github.com/anuragverma108/SwapReads/assets/143149376/bce3f05c-22ed-4af0-96fc-d88e60710f17)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

preopend issue
