### ISSUE TITLE
BUG: Enhance RegisterSchema with Additional Validations 

### ISSUE THREAD

**Issue by sum1t-here** [anuragverma108/SwapReads#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In backend there is no validation for password asking the password should be :
 - Lowercase & Uppercase
  - Number (0-9)
  - Special Character (!@#$%^&*)
  - Atleast 8 Character
<img width="1440" alt="Screenshot 2024-05-19 at 7 17 10 PM" src="https://github.com/anuragverma108/SwapReads/assets/126807055/85343b43-f36d-43dd-afa9-23bfa3c43d50">
user gets created successfully without password validation

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> In backend there is no validation for password asking the password should be :
>  - Lowercase & Uppercase
>   - Number (0-9)
>   - Special Character (!@#$%^&*)
>   - Atleast 8 Character
> <img width="1440" alt="Screenshot 2024-05-19 at 7 17 10 PM" src="https://github.com/anuragverma108/SwapReads/assets/126807055/85343b43-f36d-43dd-afa9-23bfa3c43d50">
> user gets created successfully without password validation
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue
assigned! tag me when you create a PR!
