### ISSUE TITLE
Feat: Title of the navbar and enhancement of the footer

### ISSUE THREAD

**Issue by jayanththalla** [anuragverma108/SwapReads#679]
### Describe the feature

Add title of the swapread in the navbar and add hover effects to the icons of the social media icons and alignment of the footer details 
please assign @pa

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/121346142/95ff4d17-56bd-4e34-83db-69117803554e)
![image](https://github.com/anuragverma108/SwapReads/assets/121346142/1ab13e0d-1b16-4462-8f43-0b9d2f5b08e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> /assign me @Pa

work on it 💪

**Comment by g-sandeep-reddy** [comment]
can you please assign me the issue  ?
