### ISSUE TITLE
Login Page issue

### ISSUE THREAD

**Issue by pankaj-bind** [anuragverma108/SwapReads#68]
**Describe the bug**
Login page is not properly center aligned.
Login ang sign up page must be on different pages.
Login button is poorly developed.
It is not interactive, looks like poorly developed.

**To Reproduce**
1. Go to 'Login/Signup'
2. See error

**Expected behavior**
It must be on the centralized properly.

**Screenshots**

Screenshots

Desktop (please complete the following information):

OS: Windows 11
Browser Microsoft Edge
Version 124.0.2478.80
Smartphone (please complete the following information):

Additional context
I'm a GSSoC'24 contributor please assign me this work. Since before this I made a pull request which was properly merged so I know everything about this project. I will developed an interactive login page with some security features.
![1](https://github.com/anuragverma108/SwapReads/assets/73558583/4895a870-d177-43c0-8247-a901ef559aa4)

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Jatingupta9120** [comment]
Assign this issue to me
