### ISSUE TITLE
Feat: Optimising conversation with bot

### ISSUE THREAD

**Issue by Dilpreet0501** [anuragverma108/SwapReads#685]
### Describe the feature

A menu can be provided which contains all the the questions that the bot can reply. Also, a closing line can be added on ending conversation with bot.

@huamanraj , kindly assign me this issue under GSSoC'24, I'll do my best.

### Add ScreenShots

On asking any questions , bot replies like this, thus a menu is must.
![Screenshot 2024-05-20 082521](https://github.com/anuragverma108/SwapReads/assets/100590445/fa5da438-427d-4774-916e-5da97d9803a0)

Closing line like Thankyou for contacting us, can be added.
![Screenshot 2024-05-20 082131](https://github.com/anuragverma108/SwapReads/assets/100590445/8bff6698-9102-4bf7-aa45-257085c69921)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> A menu can be provided which contains all the the questions that the bot can reply. Also, a closing line can be added on ending conversation with bot.
> 
> @huamanraj , kindly assign me this issue under GSSoC'24, I'll do my best.
> 
> ### Add ScreenShots
> 
> On asking any questions , bot replies like this, thus a menu is must.
> ![Screenshot 2024-05-20 082521](https://github.com/anuragverma108/SwapReads/assets/100590445/fa5da438-427d-4774-916e-5da97d9803a0)
> 
> Closing line like Thankyou for contacting us, can be added.
> ![Screenshot 2024-05-20 082131](https://github.com/anuragverma108/SwapReads/assets/100590445/8bff6698-9102-4bf7-aa45-257085c69921)
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

go on 💪

**Comment by Dilpreet0501** [comment]
Sure, thank you!
