### ISSUE TITLE
BUG: Testimonials Section: Hover Glitch and Lag 

### ISSUE THREAD

**Issue by aadii2504** [anuragverma108/SwapReads#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/119524954/fe70d593-e472-4be1-87f5-0301f4f28f89

While interacting with the Testimonials section on the website, I noticed a significant glitch and lag during hover events. The animation is not smooth and **appears jittery**, which detracts from the overall user experience.

**Steps to Reproduce:**

1. Navigate to the Testimonials section of the website.
2. Hover over the testimonials.
3. Observe the glitchy and lagging behavior of the hover effect.

**Expected Behavior:**
The hover effect should be smooth and responsive, providing a seamless user experience.

**Proposed Solution:**
I want to work on this issue to enhance the responsiveness and smoothness of the hover effects in the Testimonials section. This will involve optimizing the CSS and possibly the JavaScript handling these events to ensure a fluid and glitch-free experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> 
> https://github.com/anuragverma108/SwapReads/assets/119524954/fe70d593-e472-4be1-87f5-0301f4f28f89
> 
> While interacting with the Testimonials section on the website, I noticed a significant glitch and lag during hover events. The animation is not smooth and **appears jittery**, which detracts from the overall user experience.
> 
> **Steps to Reproduce:**
> 
> 1. Navigate to the Testimonials section of the website.
> 2. Hover over the testimonials.
> 3. Observe the glitchy and lagging behavior of the hover effect.
> 
> **Expected Behavior:**
> The hover effect should be smooth and responsive, providing a seamless user experience.
> 
> **Proposed Solution:**
> I want to work on this issue to enhance the responsiveness and smoothness of the hover effects in the Testimonials section. This will involve optimizing the CSS and possibly the JavaScript handling these events to ensure a fluid and glitch-free experience.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it 💪

**Comment by Deepanshi0019** [comment]
I want to work on this issue

**Comment by Praneeth-2602** [comment]
Hello @anuragverma108 sir, I would like to work on this issue.

**Comment by Praneeth-2602** [comment]
@huamanraj sir can I work on this issue? Please reassign this to me.
