### ISSUE TITLE
BUG:Logo Visibility Issue on Black Theme:

### ISSUE THREAD

**Issue by driyash9881** [anuragverma108/SwapReads#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Issue Description:**  
The problem arises from using a white logo image on a black theme. This  an unappealing white space, detracting from the overall aesthetic quality of the design.
![image](https://github.com/anuragverma108/SwapReads/assets/118407844/f2e1e857-5165-423e-89a9-2fa0b32d7baa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by driyash9881** [comment]
please assign this issue to me

**Comment by huamanraj** [comment]
> please assign this issue to me

assigned

**Comment by ParthNakum21** [comment]
Hello, I'm interested in contributing to the project improving the LOGO visibility issue. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by driyash9881** [comment]
> > please assign this issue to me
> 
> assigned
