### ISSUE TITLE
#signup with google not working 

### ISSUE THREAD

**Issue by roushanverma23** [anuragverma108/SwapReads#688]
### What's wrong with the existing documentation

signup with google not working

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/137530796/2ea1b6cb-8516-4c6e-8e16-3de7893fb95a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### What's wrong with the existing documentation
> 
> signup with google not working
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/137530796/2ea1b6cb-8516-4c6e-8e16-3de7893fb95a)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!

**Comment by roushanverma23** [comment]
@huamanraj please review the code once and verify if it is working properly. if not please let me know
