### ISSUE TITLE
Adding a back button to redirect to homescreen instead of full Text and improve the login page UI

### ISSUE THREAD

**Issue by VivekMohanta03** [anuragverma108/SwapReads#69]

**Comment by ayush-kumarrai** [comment]
I can do that by changing the text to a symbol of going back. Assign me the task

**Comment by aashkaaaaaa** [comment]
"I am excited to take on this project and am confident in my ability to succeed. Please consider assigning me to this project and I will work tirelessly to ensure it is completed to the best of my abilities."

**Comment by anythingkartik** [comment]
Can you give a chance and assign this issue

**Comment by anuragverma108** [comment]
Already implement in some other issue. Find some other issues and work on it.
