### ISSUE TITLE
BUG: Navbar Page Titles: Not aligned

### ISSUE THREAD

**Issue by aarushroyy** [anuragverma108/SwapReads#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The page titles in the Navbar are not aligned properly, with longer ones taking 2 lines of space. Makes it look odd and unappealing. Can be fixed for better User Experience. 

![image](https://github.com/anuragverma108/SwapReads/assets/69352438/71a37700-5ba0-4cc2-98d5-87040ed6688d)

Thanks a lot,
Aarush

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AyushSinghRajput1366** [comment]
Can you please assign me for this issue...

**Comment by aarushroyy** [comment]
Hey @anuragverma108 

I opened this issue and am an active Contributor at GSSoC. Request you to please assign this to me.

Thank you,
Aarush

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The page titles in the Navbar are not aligned properly, with longer ones taking 2 lines of space. Makes it look odd and unappealing. Can be fixed for better User Experience. 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/69352438/71a37700-5ba0-4cc2-98d5-87040ed6688d)
> 
> Thanks a lot,
> Aarush
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!
