### ISSUE TITLE
Feat:navigation bar has some double line items which are not looking good

### ISSUE THREAD

**Issue by Abhinavagarwa** [anuragverma108/SwapReads#699]
### Describe the feature

gssoc24
read code of conduct
i will be extending a bit and making letter little smaller making it more applealing and good looking

### Add ScreenShots

<img width="1470" alt="Screenshot 2024-05-20 at 10 50 57 PM" src="https://github.com/anuragverma108/SwapReads/assets/119868907/1f14160f-2791-4c96-86f9-4e6ea7867f3f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> gssoc24
> read code of conduct
> i will be extending a bit and making letter little smaller making it more applealing and good looking
> 
> ### Add ScreenShots
> 
> <img width="1470" alt="Screenshot 2024-05-20 at 10 50 57 PM" src="https://github.com/anuragverma108/SwapReads/assets/119868907/1f14160f-2791-4c96-86f9-4e6ea7867f3f">
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

issue already opened
