### ISSUE TITLE
Feat: Improve the Booklist for Swapping page UI and add a Book Review Section

### ISSUE THREAD

**Issue by SampurnaDan09** [anuragverma108/SwapReads#701]
### Describe the feature

**GSSOC'24**
The UI is not quite appealing and I aim to make it a bit attractive for that page.
Also, I suggest adding a book review section for the 1st time readers who are confused about which book to read. People can post their thoughts about a book there.

### Add ScreenShots

![Screenshot (331)](https://github.com/anuragverma108/SwapReads/assets/146513605/04e2a3aa-f9b8-4a61-9d0c-eeaa6200abe0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> **GSSOC'24**
> The UI is not quite appealing and I aim to make it a bit attractive for that page.
> Also, I suggest adding a book review section for the 1st time readers who are confused about which book to read. People can post their thoughts about a book there.
> 
> ### Add ScreenShots
> 
> ![Screenshot (331)](https://github.com/anuragverma108/SwapReads/assets/146513605/04e2a3aa-f9b8-4a61-9d0c-eeaa6200abe0)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!

**Comment by SampurnaDan09** [comment]
Hi @huamanraj 
I hope you're doing well.
I have a small query. Would you like me to make the book review section fully functional? Or just the UI will do as of now? 
I have made a dummy section but it's not functional yet.

**Comment by huamanraj** [comment]
> Hi @huamanraj 
> I hope you're doing well.
> I have a small query. Would you like me to make the book review section fully functional? Or just the UI will do as of now? 
> I have made a dummy section but it's not functional yet.

hello @SampurnaDan09
UI will do for now! in future PR you can add complete functionality!

**Comment by SampurnaDan09** [comment]
Ok thank you @huamanraj

**Comment by SampurnaDan09** [comment]
Hi @huamanraj 
I have created a PR.
You may have a look into it.

**Comment by SampurnaDan09** [comment]
Hey @huamanraj 
Did I do the PR correctly??
I guess maybe I have not done it the right way.
Could you please let me know if I have done it right or not?

**Comment by SampurnaDan09** [comment]
Hi @huamanraj 
Sorry to bother you again.
But could you please confirm whether I did the PR correctly or not?
