### ISSUE TITLE
 Improve FAQ Section with Smooth Scroll for Better User Experience

### ISSUE THREAD

**Issue by govindumeesala** [anuragverma108/SwapReads#704]
### Describe the feature

The current FAQ section lacks a smooth scroll effect when a question is opened. This abrupt opening of the answer does not provide a good user experience, as it can be jarring and make it difficult for users to follow the content.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/129055361/766c9b26-be86-4178-8de0-6f64fbc6265e)

To enhance the user experience, implement a smooth scroll effect when a question is opened. This will ensure that the answer smoothly transitions into view, making it easier and more pleasant for users to read the answers.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> The current FAQ section lacks a smooth scroll effect when a question is opened. This abrupt opening of the answer does not provide a good user experience, as it can be jarring and make it difficult for users to follow the content.
> 
> ### Add ScreenShots
> 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/129055361/766c9b26-be86-4178-8de0-6f64fbc6265e)
> 
> To enhance the user experience, implement a smooth scroll effect when a question is opened. This will ensure that the answer smoothly transitions into view, making it easier and more pleasant for users to read the answers.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [ ] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!
