### ISSUE TITLE
Feat: Simplify the navbar 

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#705]
### Describe the feature

Nav bar is having many elements which is not looking good. I want to work on this by making only the main elements seen on the navbar and adding a dropdown menu with the name "more" for other elements. Please assign this to me under GSSoC'24. 
@anuragverma108 @huamanraj 

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/146222028/9ea9a142-9df4-4190-ae3f-424e241ff13b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> Nav bar is having many elements which is not looking good. I want to work on this by making only the main elements seen on the navbar and adding a dropdown menu with the name "more" for other elements. Please assign this to me under GSSoC'24. 
> @anuragverma108 @huamanraj 
> 
> ### Add ScreenShots
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/146222028/9ea9a142-9df4-4190-ae3f-424e241ff13b)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! tag me when you create a PR!

**Comment by DhanaAswini** [comment]
I personallu think that the navbar is a bit clumsy and unable for the users to use the platform properly. I would like to rearrange the elemnts and make it more designable. Please assign the task to me.
