### ISSUE TITLE
BUG 🐞: Back-to-top and chatbot buttons overlapping

### ISSUE THREAD

**Issue by MastanSayyad** [anuragverma108/SwapReads#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As you can see below chatbot button is overlapping with the back to top button.

![image](https://github.com/anuragverma108/SwapReads/assets/101971980/669c99e2-8d7e-444e-996a-e7be5440df56)

![image](https://github.com/anuragverma108/SwapReads/assets/101971980/ec88642f-af4b-4dd9-a60c-81625d3e7185)
### **Feature solution:**
The back to top button should be in left bottom instead of right bottom. Additionally increasing the size of back to top to balance matching on the both sides

### Expected solution may look like this;

![image](https://github.com/anuragverma108/SwapReads/assets/101971980/980c1e24-e031-4527-be0e-8133f2bb2814)

![image](https://github.com/anuragverma108/SwapReads/assets/101971980/fe475fc2-74b9-4721-8a1a-021fa2d339e5)

Could you please Assign this issue to me under GSSOC'24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MastanSayyad** [comment]
@anuragverma108 @huamanraj Please take a look at this issue and assign me to work on it under gssoc24

**Comment by huamanraj** [comment]
> @anuragverma108 @huamanraj Please take a look at this issue and assign me to work on it under gssoc24

if you can move the backt.to top button upon the bot when the bot opens then i can assign you this issue!

**Comment by MastanSayyad** [comment]
> if you can move the backt.to top button upon the bot when the bot opens then i can assign you this issue!


@huamanraj Well I would have done that but I think someone solved this overlapping issue, you can check on the website...However, there is still one issue which is Go-to-top button alignment/position and size of the button which is completely inconsistent so maybe you can assign this minor change to me. it's just work of a couple of minutes and done.

**Comment by MastanSayyad** [comment]
@huamanraj To be honest the idea of yours doesn't look good to me as you can see, the button on the chatbot.

![image](https://github.com/anuragverma108/SwapReads/assets/101971980/c95f2633-9d14-48a2-a28a-a386f48f4cc4)

**Comment by huamanraj** [comment]
> @huamanraj To be honest the idea of yours doesn't look good to me as you can see, the button on the chatbot.
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/101971980/c95f2633-9d14-48a2-a28a-a386f48f4cc4)
> 

the button must be easily accessible so whats your plan?

**Comment by MastanSayyad** [comment]
Yeah absolutely, the button must be easily accessible. let's move the bot button and its container little left and align both buttons, by doing so it will be easily accessible as well as it will not overlap on each other plus it look great too

**Here is the feature solution:**


https://github.com/anuragverma108/SwapReads/assets/101971980/01849506-7496-4275-bf1e-4e1c41bd4a83

Looks fine isn't it? additionally I will change the inconsistent color of the goto top button to match the color of bot button and website's design theme,

**Comment by MastanSayyad** [comment]
@huamanraj @anuragverma108 pls assign this issue to me if possible.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
