### ISSUE TITLE
Creating a relevant logo and favicon to the website

### ISSUE THREAD

**Issue by rahul-p19** [anuragverma108/SwapReads#71]
**Is your feature request related to a problem? Please describe.**
The website needs a logo and a favicon to take the already impressive UI to the next level.

**Describe the solution you'd like**
I could create a logo, with feedback from you, which could be added in the left side of the navbar which currently contains the website name. It could also be added as a favicon.

**Describe alternatives you've considered**
If you don't like the attached image, you can give me any suggestions and I'll try to make a logo according to your needs.

**Additional context**
![Screenshot 2024-05-10 202501](https://github.com/anuragverma108/SwapReads/assets/140929748/40045924-c5ee-4096-94c1-023c5d60e7b0)

**Comment by ayushrskiaa** [comment]
Hello @anuragverma108  I can do it. Can you please assign it to me.

**Comment by anuragverma108** [comment]
Assigned!
I didn't liked the logo.
Make some other good looking logo using canva

**Comment by rahul-p19** [comment]
@anuragverma108 Could you tell me what type of logo would you like? 
Does something like this look good?
![image](https://github.com/anuragverma108/SwapReads/assets/140929748/b5ba0cf6-eacd-49c5-b258-239bd0eebb2c)
Or maybe a simple logo with the initials SR from SwapReads? And also what colours would you like? Feedback would be appreciated, to help me make a better design for you.

**Comment by carolinelall** [comment]
Sir, Please assign me this issue, I would love to work on it.
I have experience in the relevant technologies, which I believe will be valuable in addressing the issue effectively.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by yeolesanskruti** [comment]
@anuragverma108 
Since this issue is not resolved. I want to work on this under GSSoC'24.

I have made a logo.
![Screenshot 2024-05-29 234047](https://github.com/anuragverma108/SwapReads/assets/129084275/330fbd0f-1106-4bcf-a280-e3620f434fce)

@anuragverma108  Please review and suggest any changes.

**Comment by yeolesanskruti** [comment]
@anuragverma108  I would like to know your feedback. Please look into this issue.
GSSoC'24

**Comment by huamanraj** [comment]
not planned as i discussed with team!!
