### ISSUE TITLE
Feat: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [anuragverma108/SwapReads#718]
### Describe the feature

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add ScreenShots

![issue closed](https://github.com/anuragverma108/SwapReads/assets/115717746/eef52443-ac23-42d2-aca0-acb47a84dc77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@huamanraj please assign me this issue under gssoc'24

**Comment by Asymtode712** [comment]
@huamanraj please assign me this issue under gssoc'24

**Comment by huamanraj** [comment]
> ### Describe the feature
> 
> This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.
> 
> ### Add ScreenShots
> 
> ![issue closed](https://github.com/anuragverma108/SwapReads/assets/115717746/eef52443-ac23-42d2-aca0-acb47a84dc77)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned

**Comment by Yashraghuvans** [comment]
I can fix this issue ,
@Yashraghuvans Please assign me this task under gssoc24 and mention lable according to the issue.

**Comment by Asymtode712** [comment]
@Yashraghuvans I am already assigned to it please work on some other issue
Thank you!
