### ISSUE TITLE
Adding a parallax effect to the home page image

### ISSUE THREAD

**Issue by Ridhima10** [anuragverma108/SwapReads#72]
Your website is simple yet beautiful.
I would like to add a parallax effect to image in the home page to make it look more appealing
![Screenshot 2024-05-10 201826](https://github.com/anuragverma108/SwapReads/assets/85826117/756fcec8-fabc-42e9-b318-f67b992608e2)

https://github.com/anuragverma108/SwapReads/assets/85826117/ceb1501d-6a8f-42f9-889e-c75d6261bb60

Please assign me this issue
Best regards.

**Comment by anuragverma108** [comment]
Assigned!
