### ISSUE TITLE
Feat: Add eye symbol for password in booklists for swapping

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#721]
### Describe the feature

There is no eye symbol in the password section in the booklists for swapping.
![image](https://github.com/anuragverma108/SwapReads/assets/130165687/547d8d55-0e4b-455e-a65c-ce171f619e21)
Please assign this task to me!

### Add ScreenShots

I want to add the eye symbol which helps to show the password and hide as well.
![Screenshot 2024-05-21 204733](https://github.com/anuragverma108/SwapReads/assets/130165687/cf80fad2-3d53-4415-8d4d-c7e6088444fb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
