### ISSUE TITLE
BUG: Visibility and UI of the login form is so bad, it should be fixed asap

### ISSUE THREAD

**Issue by shnwz-solves** [anuragverma108/SwapReads#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# The issue
The login form is not clearly visible and also it is not following the principles of UI/UX. There is no modern touch, not even basic color and alignment concept is used here.

### Screenshot
![image](https://github.com/anuragverma108/SwapReads/assets/126380641/c1317a56-f382-451d-a21f-af55cace6613)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
