### ISSUE TITLE
BUG: The hover effect on navbar element is disturbing the alignments of the navbar with the rest of the website.

### ISSUE THREAD

**Issue by shnwz-solves** [anuragverma108/SwapReads#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# The issue
Hover effect on the navabar element is making the alignment worse by expanding the element's size and the expansion is done under the navbar that's why the size of navbar is disturbed while hovering.

### video

https://github.com/anuragverma108/SwapReads/assets/126380641/fce0a4a7-ec83-42d7-8d33-4396702e72e9

It needs to be fixed asap as it is directly related to UI/UX which is a crucial part of a website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Jemipaul123** [comment]
Hey @shnwz-solves  can you assign me this issue under GSSOC'24? I am a fullstack web developer.

**Comment by anuragverma108** [comment]
Assigned!

@shnwz-solves Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
@Jemipaul123 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by Jemipaul123** [comment]
Oh sorry. Got it!!. 
@anuragverma108 
I have issued another bug, can you check it and assign me under the GSSOC'24 label?
