### ISSUE TITLE
BUG: Subscribe buttton is not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [anuragverma108/SwapReads#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/125277258/32369a3f-5741-49f9-8ee8-7662b7b5f00d)
BUG: Subscribe buttton is not working

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!

**Comment by RamakrushnaBiswal** [comment]
hi @anuragverma108 i get 2 index.html files in your website which one is used ?
one is Assests/html/index.html
2nd is index.html

**Comment by RamakrushnaBiswal** [comment]
@anuragverma108 any update ?

**Comment by RitiChandak** [comment]
@RamakrushnaBiswal what the pr number?
