### ISSUE TITLE
BUG: login/signup button was removed

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login/signup button was removed to provide more space for the navbar.

I would like to increase the width of the page based on screen sizes so as to provide more space for navbar items and add the login/signup button again 

right now:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/98f0d44b-4a4f-4bca-a186-6971d2cf2387)

after my fix:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/64bc376e-b183-4a20-824a-bb2c346f69d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by ParthNakum21** [comment]
Hello @anuragverma108, I'm interested in contributing to the project by fixing login/sign-up button after login. I will add logout button instead of login/sign-up after the user has logged-in. Could you please assign this task to me under GSSoC with appropriate level?
