### ISSUE TITLE
BUG: Social media icon not redirecting

### ISSUE THREAD

**Issue by priyaladesara** [anuragverma108/SwapReads#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This  **social media icons are not redirecting** to the sites instead it is taking to the top of site . need to attack social media accounts to those. 

<img width="188" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/120974820/2c273b86-ed06-405b-ab64-6696f5f94b8c">
  

I can fix this issue ,
 @huamanraj  Please assign me this task under **gssoc24** and mention lable according to the issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by annoy004** [comment]
can i work on this

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
