### ISSUE TITLE
BUG:Links not Working

### ISSUE THREAD

**Issue by kashisharora9462** [anuragverma108/SwapReads#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, the social media links are not functioning as expected, which hampers our ability to effectively engage with our audience and promote our initiatives. I have the skills and experience necessary to not only fix these issues but also to optimize our social media presence for better visibility and engagement.Please assign me the task to enable them .
![Screenshot 2024-05-22 145603](https://github.com/anuragverma108/SwapReads/assets/153215875/931de2d2-dd42-41c6-bee7-3ae28e6f1538)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arpit4521** [comment]
@anuragverma108 please assign me this issue under gssoc label

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
