### ISSUE TITLE
BUG:Social media redirect

### ISSUE THREAD

**Issue by Yashraghuvans** [anuragverma108/SwapReads#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This social media icons are not redirecting to the sites instead it is taking to the top of site this lead to less connectivity with social media accounts to those.

I can fix this issue ,
@Yashraghuvans
 Please assign me this task under gssoc24 and mention lable according to the issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
Take social media handles from me. Message me on Discord - @anuragverma_108

**Comment by Yashraghuvans** [comment]
Sure i have started the work and surely connect with our on discord

**Comment by harshcodesit** [comment]
I also want to work on the issue please assign me, You can check my previous contributions

**Comment by Yashraghuvans** [comment]
I am working on this issue kindly find some other issues for you
