### ISSUE TITLE
BUG:Text not visible in Darkmode

### ISSUE THREAD

**Issue by Brinda-07** [anuragverma108/SwapReads#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Literary Realms section ,while we are switching dark mode on,the text is not visible
We can change the color to a darker one so that visibility is fine

From this:
![Screenshot 2024-05-22 153337](https://github.com/anuragverma108/SwapReads/assets/154052901/b2187493-5b97-466c-86eb-47ecbd753b57)

To this:
![Screenshot 2024-05-22 153818](https://github.com/anuragverma108/SwapReads/assets/154052901/2eb02334-eb51-4f34-a2ac-bc8e48608add)
 
Plz @anuragverma108 Assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by akku-07** [comment]
I'd like to contribute to this issue too, can you assign this to me as well sir?

![333](https://github.com/anuragverma108/SwapReads/assets/155133233/9575826e-1938-41d8-8ff9-6f1e3462f574)
