### ISSUE TITLE
BUG: SwapReads Navbar Logo: doesn't switch in Dark Theme

### ISSUE THREAD

**Issue by aarushroyy** [anuragverma108/SwapReads#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The SwapReads logo in the Navbar doesn't change while switching the themes, whereas all other components do, making it look odd. A little design edit and change can bring about a better look. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
