### ISSUE TITLE
Boxes of Benefits are not proper

### ISSUE THREAD

**Issue by Ajita369** [anuragverma108/SwapReads#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The height of the boxes of the benefits section is not proper , there is some difference in few of them which is not visually appealing.
Here are screenshots :
![image](https://github.com/anuragverma108/SwapReads/assets/162597493/0e16137c-ee4c-4293-af9c-6c61b6686ce7)
![image](https://github.com/anuragverma108/SwapReads/assets/162597493/8d38e416-02f8-471d-9a57-5b515b070b36)
I will like to work on this issue so please assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
I can make it look even and more immersive, You can check my work at chapter card,  kindly assign me the issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by harshcodesit** [comment]
Hey, @anuragverma108 

i have created a PR :- Alignment of the Benifits Card #784
