### ISSUE TITLE
Adding Stripe Checkout for automating transactions

### ISSUE THREAD

**Issue by Chelseasingla1** [anuragverma108/SwapReads#74]
**Is your feature request related to a problem? Please describe.**
When trying to click on buynow it is not redirecting to any page for transactions and not visible how many transactions are done.

**Describe the solution you'd like**
I would like to add Stripe checkout feature in it , which will help to redirect to payment methods in Stripe.

**Describe alternatives you've considered**
Alternatively for storage purpose i will try to add firebase connection with it displaying the user name and transaction details in it.

**Additional context**
I have tried Stripe feature before so please me this issue under GSSoC'24

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Jatingupta9120** [comment]
Assign this issue to me

**Comment by Chelseasingla1** [comment]
> Assigned!

Okay Thankyou!!

**Comment by Chelseasingla1** [comment]
> Assigned!

Hi, i am almost done with this isssue should i create a PR or first you want discussions?
