### ISSUE TITLE
Update Project Footer

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 . This issue is to track the proposed changes to the project footer.

Before making the changes, the footer looks like:
![Screenshot 2024-05-22 191735](https://github.com/anuragverma108/SwapReads/assets/159511364/23fc0e69-4a08-485b-9b25-f0a051f2a6bd)

After making the changes, the footer looks like:
![Screenshot 2024-05-22 191007](https://github.com/anuragverma108/SwapReads/assets/159511364/586cc710-67e3-49fb-b471-44f98ec9f5d9)

**please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevanshPaliwal** [comment]
@anuragverma108 please assign this issue to me

**Comment by harshcodesit** [comment]
I can improve the footer with embedded animated newsletter form and more div CSS

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
