### ISSUE TITLE
Login Page CSS Not Loading - Incorrect Path

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [anuragverma108/SwapReads#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @anuragverma108 . This issue reports that the CSS file for the login page (login.css) is not loading correctly. 
The current path specified in login.html is:    href="login.css"
However, the correct path should be:    href="./assets/css/login.css"
This discrepancy is causing the CSS to not be applied to the login page.

In addremovebook.html also the css file is not connected properly.

**please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by rounakdey6** [comment]
Please assign this work to me sir
