### ISSUE TITLE
Feat:Would u like to add preloader?

### ISSUE THREAD

**Issue by Anjaliavv51** [anuragverma108/SwapReads#745]
### Describe the feature

Preloader gives idea to the user.

### Add ScreenShots

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/7ef2cd29-dc32-44db-9225-81f4d28bdc45

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
