### ISSUE TITLE
BUG: Alignment of Cards Images and text is not reponsive in mobile view.

### ISSUE THREAD

**Issue by alok2424** [anuragverma108/SwapReads#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In mobile view, the hero page is not fully responsive ,alignments of card's images and the text above it not lie at the center. It must be lie at the center of the page for an interactive user experience.

https://github.com/anuragverma108/SwapReads/assets/130597958/f6470ef8-7380-486c-9ce4-5da3f91e7cad

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by RitiChandak** [comment]
@alok2424 any updates ?
