### ISSUE TITLE
Wrong numbering in "Literary Realms We've Covered"

### ISSUE THREAD

**Issue by VanshikaAg12** [anuragverma108/SwapReads#748]
The series starts with "09." instead of "01." as shown in the screenshot. Kindly assign me this issue under GSSoC'24
![Screenshot (10)](https://github.com/anuragverma108/SwapReads/assets/156996206/07160210-334d-4299-8621-311aa666a7d8)

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by arpit4521** [comment]
@anuragverma108 please assign me this issue under gssoc label i can fix asap

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
