### ISSUE TITLE
BUG: Fix the Theme

### ISSUE THREAD

**Issue by sau-mili** [anuragverma108/SwapReads#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The high contrast mustard yellow background spoils the theme of the website. I would like to fix it and add better background styles.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ParthNakum21** [comment]
Hello @anuragverma108, I'm interested in contributing to the project by improving the theme. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by anuragverma108** [comment]
@sau-mili 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by ParthNakum21** [comment]
> @ParthNakum21
> 
> Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

Thanks for the reply!
