### ISSUE TITLE
Text of some sections are not clearly visible in dark mode.

### ISSUE THREAD

**Issue by ayushrskiaa** [anuragverma108/SwapReads#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Texts are not visible clearly.

![Screenshot from 2024-05-23 08-46-24](https://github.com/anuragverma108/SwapReads/assets/130389607/b4382d42-2707-4ce8-8242-9722864a2e57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by annoy004** [comment]
can i fix this issue

**Comment by ayushrskiaa** [comment]
@annoy004 I want to solve this thats why I raised this issue. please raise another one.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
