### ISSUE TITLE
Updating UI/UX design of Landing page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [anuragverma108/SwapReads#76]
Hey, I'm a UIUX designer And I have worked on many projects before where I have improved the designs of the website. So I think I can update the design of swapreads, as the current design does not match what the website caters So we can change the typography, colour schemes, Visual hierarchy to make the website more engaging and user friendly.

Please assign this issue to me under GSSoc'24 (Level-3)

**Comment by anuragverma108** [comment]
@PiyushKalyanpy Show me the screenshot after updating the UI in your local system. If I liked it then I will surely merge it.
