### ISSUE TITLE
BUG: Validation for Book Exchange Hub input fields & Enhanchment in Password Requirments

### ISSUE THREAD

**Issue by PankajR007** [anuragverma108/SwapReads#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Issues:** 
![Screenshot (35)](https://github.com/anuragverma108/SwapReads/assets/130495518/f51f9717-de5c-4c5a-9483-c6ccde496fa2)

"More" navigation in navbar UI is bit squeezed.

![Screenshot (36)](https://github.com/anuragverma108/SwapReads/assets/130495518/df81ecaf-7a7e-4178-8627-8c72c61b6e58)

Validation for input fields inBook Exchange HUB.

![benfits ui issue](https://github.com/anuragverma108/SwapReads/assets/130495518/264e03de-c7da-45c3-b8da-79219889b26c)

UI is not attractive would like to change the color in Unleash the Magic of BookSwapping div cards

![rate us issue](https://github.com/anuragverma108/SwapReads/assets/130495518/06d0fe19-3f8b-492b-9bc3-8647efec7ef2)

Rate US UI is not looking looking Good would like to enhace it.

![register ui enhanchment](https://github.com/anuragverma108/SwapReads/assets/130495518/2cfc027c-a4e0-4479-8a59-eb3fabe6ea91)

The UI of Password Requirment is not looking good in create account page.

**Solutions:**
1)Improve the UI of More in [navbar]
2)Book Exchange Hub validation for all input fields 
3) Unleash the Magic of Book Swapping of [change UI for cards] 
4)Rate US ui issue
5) Create Account [improve UI for password requirement]

Hi, I have raised the following issues i'm intersted to work on those, please assign these issues to me under gssoc 24 label and under appropriate level badge.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@PankajR007 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by PankajR007** [comment]
@anuragverma108  Sure, Thank you for assigning this issue to me, will start working on it.

**Comment by Maheshwari-Love** [comment]
@anuragverma108 is @PankajR007 is still working on it? 
If not then can you please assign this issue to me...

**Comment by PankajR007** [comment]
I have completed it will raise the PR Today.
