### ISSUE TITLE
Adding different types of currency in Book Exchange Hub price

### ISSUE THREAD

**Issue by Chelseasingla1** [anuragverma108/SwapReads#77]
**Is your feature request related to a problem? Please describe.**
It is not clear what type of currency one is using while mentioning amount about particular book in book exchange hub. 

**Describe the solution you'd like**
I would like to add new feature where one can chose which currency they can use.

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under GSSoC'24

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Chelseasingla1** [comment]
> Assigned!

Okay thankyou!!
