### ISSUE TITLE
ui bg yellow colour looking bad /Text not visible

### ISSUE THREAD

**Issue by kartikmehta18** [anuragverma108/SwapReads#772]
ui bg yellow colour looking  is bad is dont match color theam and Text also not visible
![image](https://github.com/anuragverma108/SwapReads/assets/125860170/6912ebd5-a91b-41a2-9e20-27525974cfac)

**Comment by huamanraj** [comment]
> ui bg yellow colour looking is bad is dont match color theam and Text also not visible ![image](https://private-user-images.githubusercontent.com/125860170/333200445-6912ebd5-a91b-41a2-9e20-27525974cfac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzI1MDQsIm5iZiI6MTcxNjQ3MjIwNCwicGF0aCI6Ii8xMjU4NjAxNzAvMzMzMjAwNDQ1LTY5MTJlYmQ1LWE5MWItNDFhMi05ZTIwLTI3NTI1OTc0Y2ZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMzUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTc2ZGI2YmNiNThjMTA5YTRmNWNmMTJjOGY0NTdhODBjOTk1ZDc2MDMyZTliNzkxMTBiMTVmYmMwMmVlZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnbspYYlRS9x-AfL_VU9Sw7oc31FEHJw7wPKOMwq5MM)

yes previously it was different if you can apply that it would be nice !!
