### ISSUE TITLE
BUG: there is no logout button on index page. it is in login page so move that from login page to index page after login ! 

### ISSUE THREAD

**Issue by huamanraj** [anuragverma108/SwapReads#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BUG: there is no logout button on index page. it is in login page so move that from login page to index page after login ! 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by roushanverma23** [comment]
@huamanraj please assign

**Comment by huamanraj** [comment]
> @huamanraj please assign, I want to work on this 

assigned 👏

**Comment by huamanraj** [comment]
> > @huamanraj please assign, I want to work on this 
> 
> assigned!

**Comment by arpit4521** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> BUG: there is no logout button on index page. it is in login page so move that from login page to index page after login !
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue
