### ISSUE TITLE
Responsive UI of login page 

### ISSUE THREAD

**Issue by Deekshashakyawal** [anuragverma108/SwapReads#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to contribute under GSSOC'24 . I want to update the UI of login page and also make it responsive as the text is overflowing from the button , and the instructions for setting a password is not aligned according to the page.

![Screenshot 2024-05-23 194506](https://github.com/anuragverma108/SwapReads/assets/119758705/a5f87332-b767-4387-9061-5241941e26ba)
  

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by lassmara** [comment]
Please assign me this issue.
