### ISSUE TITLE
BUG: Book management page is not responsive 

### ISSUE THREAD

**Issue by Deekshashakyawal** [anuragverma108/SwapReads#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to contribute under GSSOC'24 . Please assign this issue to me .
The content is not visible properly for a smaller screen like a smartphone, I need to make it responsive.

![Screenshot 2024-05-23 195545](https://github.com/anuragverma108/SwapReads/assets/119758705/402930db-a938-4cc6-8796-8d3b7e7a4145)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
