### ISSUE TITLE
Update Readme.md DOC:

### ISSUE THREAD

**Issue by Meetjain1** [anuragverma108/SwapReads#778]
### What's wrong with the existing documentation

Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project and many more small updates 

@anuragverma108  @huamanraj assign this issue to me I will update it 
I am working under gssoc24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Meetjain1** [comment]
> > ### What's wrong with the existing documentation
> > Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project and many more small updates
> > @anuragverma108  @huamanraj assign this issue to me I will update it
> > I am working under gssoc24
> > ### Record
> > 
> > * [x]  I agree to follow this project's Code of Conduct
> > * [x]  I'm a GSSOC'24 contributor
> > * [x]  I want to work on this issue
> 
> work on it also decreases the content of readme by adding some links to it and also make a section where the admin and mentor contact details are displayed so anyone can reach out easily!

@huamanraj okk sure .

**Comment by Meetjain1** [comment]
@huamanraj I think some sections from the readme need to move to contributing.md file

like these, let me know I will create a issue for this and move these to contributing.md file

![swa1](https://github.com/anuragverma108/SwapReads/assets/133582566/0a594866-436e-4c2d-ada8-cbffa07a54eb)

![swap2](https://github.com/anuragverma108/SwapReads/assets/133582566/4c34cab1-854b-4fcb-889a-245336d2fdea)

**Comment by huamanraj** [comment]
> @huamanraj I think some sections from the readme need to move to contributing.md file
> 
> like these, let me know I will create a issue for this and move these to contributing.md file
> 
> ![swa1](https://github.com/anuragverma108/SwapReads/assets/133582566/0a594866-436e-4c2d-ada8-cbffa07a54eb)
> 
> ![swap2](https://github.com/anuragverma108/SwapReads/assets/133582566/4c34cab1-854b-4fcb-889a-245336d2fdea)
> 
> 
> 

yes! just give a bold link on readme

**Comment by Meetjain1** [comment]
> > @huamanraj I think some sections from the readme need to move to contributing.md file
> > like these, let me know I will create a issue for this and move these to contributing.md file
> > ![swa1](https://private-user-images.githubusercontent.com/133582566/333799692-0a594866-436e-4c2d-ada8-cbffa07a54eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NjkyLTBhNTk0ODY2LTQzNmUtNGMyZC1hZGE4LWNiZmZhMDdhNTRlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVjN2EwOGQ4NDFmZjQ0MjJjYjA5N2E3MWY2MGIyY2Q4NTY5ODM0NTg3ZjNhY2IxOWM5MDBiOGZhYWUyMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xu-f3VfBQeBYzC-ymzGItWUn-de9_ckyI06XKK9rB_4)
> > ![swap2](https://private-user-images.githubusercontent.com/133582566/333799707-4c34cab1-854b-4fcb-889a-245336d2fdea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NzA3LTRjMzRjYWIxLTg1NGItNGZjYi04ODlhLTI0NTMzNmQyZmRlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU0MDlhYzZjN2RiZGEwZmUzOTA5MWM2MWYzYTNlZmYwNjY5Y2JhOGIwODYwNzU4ZGIzYWViM2JiNDg1YjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbnM5SdlTAhbfVxLdo5CGd2m39gjrpuIAShpG_ujtso)
> 
> yes! just give a bold link on readme

yes sure @huamanraj , also can you please share the admin and mentor contact details links that I have to add in readme

**Comment by huamanraj** [comment]
> > > @huamanraj I think some sections from the readme need to move to contributing.md file
> > > like these, let me know I will create a issue for this and move these to contributing.md file
> > > ![swa1](https://private-user-images.githubusercontent.com/133582566/333799692-0a594866-436e-4c2d-ada8-cbffa07a54eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NjkyLTBhNTk0ODY2LTQzNmUtNGMyZC1hZGE4LWNiZmZhMDdhNTRlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVjN2EwOGQ4NDFmZjQ0MjJjYjA5N2E3MWY2MGIyY2Q4NTY5ODM0NTg3ZjNhY2IxOWM5MDBiOGZhYWUyMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xu-f3VfBQeBYzC-ymzGItWUn-de9_ckyI06XKK9rB_4)
> > > ![swap2](https://private-user-images.githubusercontent.com/133582566/333799707-4c34cab1-854b-4fcb-889a-245336d2fdea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NzA3LTRjMzRjYWIxLTg1NGItNGZjYi04ODlhLTI0NTMzNmQyZmRlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU0MDlhYzZjN2RiZGEwZmUzOTA5MWM2MWYzYTNlZmYwNjY5Y2JhOGIwODYwNzU4ZGIzYWViM2JiNDg1YjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbnM5SdlTAhbfVxLdo5CGd2m39gjrpuIAShpG_ujtso)
> > 
> > yes! just give a bold link on readme
> 
> yes sure @huamanraj , also can you please share the admin and mentor contact details links that I have to add in readme

i will share it till tonight i am right now busy, you can remind me if i don't share till 10pm!

**Comment by Meetjain1** [comment]
> > @huamanraj I think some sections from the readme need to move to contributing.md file
> > like these, let me know I will create a issue for this and move these to contributing.md file
> > ![swa1](https://private-user-images.githubusercontent.com/133582566/333799692-0a594866-436e-4c2d-ada8-cbffa07a54eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NjkyLTBhNTk0ODY2LTQzNmUtNGMyZC1hZGE4LWNiZmZhMDdhNTRlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVjN2EwOGQ4NDFmZjQ0MjJjYjA5N2E3MWY2MGIyY2Q4NTY5ODM0NTg3ZjNhY2IxOWM5MDBiOGZhYWUyMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xu-f3VfBQeBYzC-ymzGItWUn-de9_ckyI06XKK9rB_4)
> > ![swap2](https://private-user-images.githubusercontent.com/133582566/333799707-4c34cab1-854b-4fcb-889a-245336d2fdea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NzA3LTRjMzRjYWIxLTg1NGItNGZjYi04ODlhLTI0NTMzNmQyZmRlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU0MDlhYzZjN2RiZGEwZmUzOTA5MWM2MWYzYTNlZmYwNjY5Y2JhOGIwODYwNzU4ZGIzYWViM2JiNDg1YjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbnM5SdlTAhbfVxLdo5CGd2m39gjrpuIAShpG_ujtso)
> 
> yes! just give a bold link on readme

I have created issue #852 to shift the content to contribuiting and make it more summarized and attracting. have a look and assign me @huamanraj

**Comment by Meetjain1** [comment]
> > > > @huamanraj I think some sections from the readme need to move to contributing.md file
> > > > like these, let me know I will create a issue for this and move these to contributing.md file
> > > > ![swa1](https://private-user-images.githubusercontent.com/133582566/333799692-0a594866-436e-4c2d-ada8-cbffa07a54eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NjkyLTBhNTk0ODY2LTQzNmUtNGMyZC1hZGE4LWNiZmZhMDdhNTRlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVjN2EwOGQ4NDFmZjQ0MjJjYjA5N2E3MWY2MGIyY2Q4NTY5ODM0NTg3ZjNhY2IxOWM5MDBiOGZhYWUyMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xu-f3VfBQeBYzC-ymzGItWUn-de9_ckyI06XKK9rB_4)
> > > > ![swap2](https://private-user-images.githubusercontent.com/133582566/333799707-4c34cab1-854b-4fcb-889a-245336d2fdea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NzA3LTRjMzRjYWIxLTg1NGItNGZjYi04ODlhLTI0NTMzNmQyZmRlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU0MDlhYzZjN2RiZGEwZmUzOTA5MWM2MWYzYTNlZmYwNjY5Y2JhOGIwODYwNzU4ZGIzYWViM2JiNDg1YjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbnM5SdlTAhbfVxLdo5CGd2m39gjrpuIAShpG_ujtso)
> > > 
> > > 
> > > yes! just give a bold link on readme
> > 
> > 
> > yes sure @huamanraj , also can you please share the admin and mentor contact details links that I have to add in readme
> 
> i will share it till tonight i am right now busy, you can remind me if i don't share till 10pm!

okk sure @huamanraj

**Comment by huamanraj** [comment]
> > > @huamanraj I think some sections from the readme need to move to contributing.md file
> > > like these, let me know I will create a issue for this and move these to contributing.md file
> > > ![swa1](https://private-user-images.githubusercontent.com/133582566/333799692-0a594866-436e-4c2d-ada8-cbffa07a54eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NjkyLTBhNTk0ODY2LTQzNmUtNGMyZC1hZGE4LWNiZmZhMDdhNTRlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVjN2EwOGQ4NDFmZjQ0MjJjYjA5N2E3MWY2MGIyY2Q4NTY5ODM0NTg3ZjNhY2IxOWM5MDBiOGZhYWUyMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xu-f3VfBQeBYzC-ymzGItWUn-de9_ckyI06XKK9rB_4)
> > > ![swap2](https://private-user-images.githubusercontent.com/133582566/333799707-4c34cab1-854b-4fcb-889a-245336d2fdea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MjYsIm5iZiI6MTcxNjY0MDYyNiwicGF0aCI6Ii8xMzM1ODI1NjYvMzMzNzk5NzA3LTRjMzRjYWIxLTg1NGItNGZjYi04ODlhLTI0NTMzNmQyZmRlYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU0MDlhYzZjN2RiZGEwZmUzOTA5MWM2MWYzYTNlZmYwNjY5Y2JhOGIwODYwNzU4ZGIzYWViM2JiNDg1YjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VbnM5SdlTAhbfVxLdo5CGd2m39gjrpuIAShpG_ujtso)
> > 
> > 
> > yes! just give a bold link on readme
> 
> yes sure @huamanraj , also can you please share the admin and mentor contact details links that I have to add in readme


Hello @Meetjain1,
here are the contact details!! 

Project Admin:

Anurag Verma 

Discord: anuragverma_108
Linkedin: https://www.linkedin.com/in/anurag-verma-b91417253/
Email: anuragvermacontact@gmail.com

Mentor: 

Aman Raj
Discord: amanraj
Linkedin: https://www.linkedin.com/in/huamanraj/
Email: amanraj12.ar@gmail.com
