### ISSUE TITLE
Navbar Styling

### ISSUE THREAD

**Issue by rajkrsingh9** [anuragverma108/SwapReads#78]
In the site, to go to the top of the page for accessing the navbar It is needed to scroll to the top. It would be very good as a feature to have a fixed navbar and a jump to the top button.

**Describe the solution you'd like**
I will fix the navbar at the  top. 
I would also add a feature of hover opacity to make the page more beautiful. 

**Describe alternatives you've considered**
Yes we instead of this we can have a jump to the top button.

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24.

**Comment by VedaVarxha** [comment]
@anuragverma108 I would like to work on this issue under GSSOC'24. Please assign it to me

**Comment by anuragverma108** [comment]
Issue already exists
