### ISSUE TITLE
Cursor animation in mobile

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#780]
### Describe the feature

Cursor animation should be disabled on mobile as it does not work with touchscreen swipes.
It is not a good user experience as the custom animation just stays in one point blocking content.

### Add ScreenShots

![Screenshot_2024-05-23-20-32-31-830_com kiwibrowser browser](https://github.com/anuragverma108/SwapReads/assets/32983571/0d362d88-e63c-406d-aab4-4a6b52881f5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
