### ISSUE TITLE
improve hover effect on chepater card

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#787]
### What's wrong with the existing documentation

i want to improve hover effect on cheapter card ......

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-05-24 at 12 56 18 AM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/ffd9b712-2fcd-468e-9ad3-ff3f3b1092d1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shuhaki** [comment]
please assign me i want to do

**Comment by harshcodesit** [comment]
@huamanraj 
I can improve the hover effect on the chapter card and make it immersive, I have implemented the hover effect on the genre cards.

kindly assign me the issue
