### ISSUE TITLE
BUG: padding , cards size and arrangement

### ISSUE THREAD

**Issue by annoy004** [anuragverma108/SwapReads#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

padding is not there
![Screenshot 2024-05-24 090533](https://github.com/anuragverma108/SwapReads/assets/125680283/6aad0671-445a-4450-b750-fd5d5a58ea08)

cards are not of same size so we can apply the scroll function cards
![Screenshot 2024-05-24 090600](https://github.com/anuragverma108/SwapReads/assets/125680283/7d71feb7-5581-41ad-b370-598fba154768)

can arrange all the quic klinks  in one  line in full screen so the remaining two section will get more space 
![Screenshot 2024-05-24 090628](https://github.com/anuragverma108/SwapReads/assets/125680283/ef71143a-eff1-4866-8793-eba289d2bc3b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Praneeth-2602** [comment]
@anuragverma108 sir, Please assign this issue to me under GSSOC'24.
