### ISSUE TITLE
BUG: Remove the cursor effect 

### ISSUE THREAD

**Issue by AnikethDeb2004** [anuragverma108/SwapReads#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It feels very weird , and overall experience of the cursor effect is too lame 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> It feels very weird , and overall experience of the cursor effect is too lame 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [ ] I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by aasthabagrawal** [comment]
Plz assign it to me

**Comment by Ananyajain2004** [comment]
Is there an existing issue for this?
 I have searched the existing issues
What happened?
It feels very weird , and overall experience of the cursor effect is too lame

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by gudia18** [comment]
working on it

**Comment by anuragverma108** [comment]
@AnikethDeb2004 Since you did not responded from a very long time. So I have assigned it to @gudia18
