### ISSUE TITLE
More button getting hide on clicking

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i am clicking on more its dropdown menu hides the more button, also there is two more buttons
![Screenshot 2024-05-24 100516](https://github.com/anuragverma108/SwapReads/assets/146806880/5dad6a22-38c3-40f9-8975-89ad3168e225)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> when i am clicking on more its dropdown menu hides the more button, also there is two more buttons
> ![Screenshot 2024-05-24 100516](https://github.com/anuragverma108/SwapReads/assets/146806880/5dad6a22-38c3-40f9-8975-89ad3168e225)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

@Ketanop321 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
