### ISSUE TITLE
BUG:  Increase the font size of headings which are not visible clearly

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The headings are not clearly visible and the font size is less. I will increase the font size and make it visible.
![Screenshot 2024-05-24 124823](https://github.com/anuragverma108/SwapReads/assets/130165687/68a839a2-3e64-4ef5-82fe-0ff43a9362c7)
![Screenshot 2024-05-24 124837](https://github.com/anuragverma108/SwapReads/assets/130165687/2f2696b1-461f-4d8b-8030-8afbf445d219)
Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sweta-66** [comment]
I'm a GSSOC'24 contributor
please assign this issue to me

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The headings are not clearly visible and the font size is less. I will increase the font size and make it visible.
> ![Screenshot 2024-05-24 124823](https://github.com/anuragverma108/SwapReads/assets/130165687/68a839a2-3e64-4ef5-82fe-0ff43a9362c7)
> ![Screenshot 2024-05-24 124837](https://github.com/anuragverma108/SwapReads/assets/130165687/2f2696b1-461f-4d8b-8030-8afbf445d219)
> Please assign this issue to me.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

assigned! 
happy open-source contributing 🎉
