### ISSUE TITLE
BUG: Enhance Dark Mode UI with Additional Color Highlights

### ISSUE THREAD

**Issue by flute-v** [anuragverma108/SwapReads#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current dark mode UI is good, but adding more colors can make it look better and easier to use. This issue aims to introduce a wider range of colors (or a specific color palette), making the UI more attractive and user-friendly.

Here are few options for the Dark Mode UI color palette:
1. https://colorhunt.co/palette/331d2c3f2e3ea78295efe1d1
2. https://colorhunt.co/palette/070f2b1b1a55535c919290c3
3. https://colorhunt.co/palette/2d32504247697077a1f6b17a
4. https://colorhunt.co/palette/49243e704264bb8493dbafa0

![Options of color palette](https://github.com/anuragverma108/SwapReads/assets/129399359/c21cb112-2e3e-4c41-bf2c-0c5f1ba92dd4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The current dark mode UI is good, but adding more colors can make it look better and easier to use. This issue aims to introduce a wider range of colors (or a specific color palette), making the UI more attractive and user-friendly.
> 
> Here are few options for the Dark Mode UI color palette:
> 1. https://colorhunt.co/palette/331d2c3f2e3ea78295efe1d1
> 2. https://colorhunt.co/palette/070f2b1b1a55535c919290c3
> 3. https://colorhunt.co/palette/2d32504247697077a1f6b17a
> 4. https://colorhunt.co/palette/49243e704264bb8493dbafa0
> 
> ![Options of color palette](https://github.com/anuragverma108/SwapReads/assets/129399359/c21cb112-2e3e-4c41-bf2c-0c5f1ba92dd4)
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it @flute-v ! 
also if you want, work on mobile responsiveness together you will get L3 PR merged!

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The current dark mode UI is good, but adding more colors can make it look better and easier to use. This issue aims to introduce a wider range of colors (or a specific color palette), making the UI more attractive and user-friendly.
> 
> Here are few options for the Dark Mode UI color palette:
> 1. https://colorhunt.co/palette/331d2c3f2e3ea78295efe1d1
> 2. https://colorhunt.co/palette/070f2b1b1a55535c919290c3
> 3. https://colorhunt.co/palette/2d32504247697077a1f6b17a
> 4. https://colorhunt.co/palette/49243e704264bb8493dbafa0
> 
> ![Options of color palette](https://github.com/anuragverma108/SwapReads/assets/129399359/c21cb112-2e3e-4c41-bf2c-0c5f1ba92dd4)
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it @flute-v ! 
also if you want, work on mobile responsiveness together you will get L3 PR merged!

**Comment by flute-v** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]  I have searched the existing issues
> > 
> > ### What happened?
> > The current dark mode UI is good, but adding more colors can make it look better and easier to use. This issue aims to introduce a wider range of colors (or a specific color palette), making the UI more attractive and user-friendly.
> > Here are few options for the Dark Mode UI color palette:
> > 
> > 1. https://colorhunt.co/palette/331d2c3f2e3ea78295efe1d1
> > 2. https://colorhunt.co/palette/070f2b1b1a55535c919290c3
> > 3. https://colorhunt.co/palette/2d32504247697077a1f6b17a
> > 4. https://colorhunt.co/palette/49243e704264bb8493dbafa0
> > 
> > ![Options of color palette](https://private-user-images.githubusercontent.com/129399359/333537025-c21cb112-2e3e-4c41-bf2c-0c5f1ba92dd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjkyMTMsIm5iZiI6MTcxNjU2ODkxMywicGF0aCI6Ii8xMjkzOTkzNTkvMzMzNTM3MDI1LWMyMWNiMTEyLTJlM2UtNGM0MS1iZjJjLTBjNWYxYmE5MmRkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTAzZjliNGYzNDI5YzExYTFkNzc0MjRjYzRkNDYzNjFlYWRhZjVkOWJmZjg2ZTliNWFmZGJlY2IzNjA4MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eQ-oQ3-xN6c_CCySlwlsic1XNQDhyRi04ctOSiWs71Q)
> > ### Record
> > 
> > * [x]  I agree to follow this project's Code of Conduct
> > * [x]  I'm a GSSOC'24 contributor
> > * [x]  I want to work on this issue
> 
> work on it @flute-v ! also if you want, work on mobile responsiveness together you will get L3 PR merged!

Thanks for the assignment! I'll start working on it right away.
