### ISSUE TITLE
BUG: Two "more" buttons in navbar 

### ISSUE THREAD

**Issue by ayush-848** [anuragverma108/SwapReads#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/126975547/aa3a0230-6580-4be5-b8b9-2283b82ca71e)

As you can see there are 2 more buttons 

The first one is inactive while the 2nd one is a dropdown
I am able to deduce that the 1st one is the bug .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@anuragverma108 Please check if this is a bug. If yes then assign this issue to me

**Comment by huamanraj** [comment]
> @anuragverma108 Please check if this is a bug because in the index.html it is showing 
> ![image](https://github.com/anuragverma108/SwapReads/assets/126975547/e00aa36e-7c3f-47bd-a287-7e57e5211e15)
> 

ya it is a bug! solve this it should be a logout button after login and and not visible before login

**Comment by huamanraj** [comment]
> @anuragverma108 Please check if this is a bug because in the index.html it is showing 
> ![image](https://github.com/anuragverma108/SwapReads/assets/126975547/e00aa36e-7c3f-47bd-a287-7e57e5211e15)
> 

ya it is a bug! solve this it should be a logout button after login and and not visible before login! @ayush-848
