### ISSUE TITLE
Implement BOOK search feature

### ISSUE THREAD

**Issue by Karthik-vangapandu8** [anuragverma108/SwapReads#81]
implement a search functionality on the website to allow users to easily find books they are interested in swapping. This feature will enhance user experience by providing a convenient way to discover available books for exchange

Describe the solution you'd like:
Integration of APIs like Google Books API or Goodreads API to fetch book information.
User-friendly search interface with options to search by book title, author, genre, or ISBN.
Display search results with relevant book details such as title, author, cover image, and brief description.

**Comment by Karthik-vangapandu8** [comment]
We can implement BOOK search feauture so that the users can find books easily
can i use my own db for testing if assigned under gssoc 24

**Comment by anuragverma108** [comment]
Great feature @Karthik-vangapandu8 !
I liked it. I have label in Level 3 of GSSOC'24.
Work on it!
Best of Luck!

**Comment by Karthik-vangapandu8** [comment]
thanks Anurag I will work on this for surely @anuragverma108

**Comment by Aryan-joh** [comment]
@anuragverma108 i want to contribute on this please assign this project to me...

**Comment by suraj-9849** [comment]
@anuragverma108 I would like to work on this issue please assign this to me under @gssoc

**Comment by RitiChandak** [comment]
@Karthik-vangapandu8 Any updates?

**Comment by Aryan-joh** [comment]
@anuragverma108 please assigned this project to me i want to  work on this ..
