### ISSUE TITLE
Need improvement in Reset page 

### ISSUE THREAD

**Issue by YukiP7** [anuragverma108/SwapReads#817]
### Describe the feature

"Reset Page" UI needs improvement similar to the website. The "Reset Page" UI requires improvement to align with the website's design and functionality. At present, it lacks an impressive appearance and user experience. I want to ensure that the Contact and Help options in the navbar are clickable.

### ScreenShots

![Screenshot 2024-05-24 230719](https://github.com/anuragverma108/SwapReads/assets/109288720/103f58fd-6510-45d7-bbad-78f7fedf62c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @YukiP7 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
