### ISSUE TITLE
Need Improvement in ui for dark mode 

### ISSUE THREAD

**Issue by YukiP7** [anuragverma108/SwapReads#820]
Proper padding is needed for different sections of the website, and the colors in dark mode are not impressive. Changes are needed in the background color as well for dark mode . 

![Screenshot 2024-05-24 233022](https://github.com/anuragverma108/SwapReads/assets/109288720/6c86be9c-f90f-4d88-8452-80b8e54375d4)

Solution:
- I can work on dark mode UI. 
- By Providing proper padding space and background color.

**Comment by YukiP7** [comment]
@anuragverma108  Please do assign me this issue under gssoc and level2 labels.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
