### ISSUE TITLE
Dark mode button is not aligned correctly

### ISSUE THREAD

**Issue by Gamerking177** [anuragverma108/SwapReads#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/130808542/22f9c02f-bffd-4f12-8fc0-ac00e4d3beab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@Gamerking177 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
