### ISSUE TITLE
improve background in day mode

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#824]
### What's wrong with the existing documentation

upgrade background color for better looking for user

### Add ScreenShots

<img width="1438" alt="Screenshot 2024-05-25 at 12 16 34 AM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/0466def5-d721-454f-ae6b-116955f7b688">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
