### ISSUE TITLE
BUG: no proper spacing and padding in between

### ISSUE THREAD

**Issue by annoy004** [anuragverma108/SwapReads#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

margin and padding issue
![Screenshot 2024-05-25 010800](https://github.com/anuragverma108/SwapReads/assets/125680283/86e06c77-b919-48e3-b66c-d094b66b1dc0)

![Screenshot 2024-05-25 010808](https://github.com/anuragverma108/SwapReads/assets/125680283/72f397f0-74ea-45a6-a81a-185ecaf0a5d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
