### ISSUE TITLE
very small size of social media icons

### ISSUE THREAD

**Issue by suhanigupta23** [anuragverma108/SwapReads#826]
### What's wrong with the existing documentation

The size of the social media icons on the footer are very small. 
Please assign me this issue under Gssoc'24.

### Add ScreenShots

<img width="1431" alt="Screenshot 2024-05-25 at 8 22 36 AM" src="https://github.com/anuragverma108/SwapReads/assets/144280247/75bc0b4e-58af-4935-8fe3-3503c198d624">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
