### ISSUE TITLE
[BUG] : Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [anuragverma108/SwapReads#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this project `400 to 730`  doesn't responsible.
- `molbile` site cannot be proper work, The `box container` can be arrange in the `left` side.

### Expected behaviour
[Screencast from 2024-05-25 08-43-27.webm](https://github.com/anuragverma108/SwapReads/assets/121082414/62d5ebd6-e28b-49d3-af54-5e3f6ab68371)

### Actual behaviour

[Screencast from 2024-05-25 08-44-07.webm](https://github.com/anuragverma108/SwapReads/assets/121082414/d6b8c8d2-68d1-48dd-9d88-465cf34690e1)

- please assign me..
- i will ready for work in..

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @sivaprasath2004 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
