### ISSUE TITLE
BUG: navbar not visible on login page

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [anuragverma108/SwapReads#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is not visible on the login page. I would like to make changes so that navbar is there on the login page as well.
![image](https://github.com/anuragverma108/SwapReads/assets/99084211/5122c8bd-470c-4609-800c-468a0b64fded)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepthi-Ramineni** [comment]
Can you please assign this issue to me...??? I would like to work on it.

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The navbar is not visible on the login page. I would like to make changes so that navbar is there on the login page as well. ![image](https://private-user-images.githubusercontent.com/99084211/333772216-5122c8bd-470c-4609-800c-468a0b64fded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mzk4ODcsIm5iZiI6MTcxNjYzOTU4NywicGF0aCI6Ii85OTA4NDIxMS8zMzM3NzIyMTYtNTEyMmM4YmQtNDcwYy00NjA5LTgwMGMtNDY4YTBiNjRmZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMWE2ZmM2NjBiYTY0ZDMwMzU0YzcyOGUzNWQ1NDllYTUwZTdmOTQ3NmIwMGZiZmRiYzM3NTlhMzA0YzJiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tSaHqAxk6FP7p3hLCArUObinpSu6lJP7gTV1owmzK6E)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Astha-Raghuwanshi** [comment]
On it!!!
