### ISSUE TITLE
BUG: No way to close the more dropdown list 

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [anuragverma108/SwapReads#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The more dropdown list does not close when any other page is opened. Also there is not other way to close it except reloading the page.
I would like to resolve this issue to close the dropdown list as required 
![image](https://github.com/anuragverma108/SwapReads/assets/99084211/e75a62b9-2324-44c7-aa28-00f69edcacc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The more dropdown list does not close when any other page is opened. Also there is not other way to close it except reloading the page. I would like to resolve this issue to close the dropdown list as required ![image](https://private-user-images.githubusercontent.com/99084211/333772324-e75a62b9-2324-44c7-aa28-00f69edcacc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mzk5NDMsIm5iZiI6MTcxNjYzOTY0MywicGF0aCI6Ii85OTA4NDIxMS8zMzM3NzIzMjQtZTc1YTYyYjktMjMyNC00NGM3LWFhMjgtMDBmNjllZGNhY2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMjA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MDRjYTk4MDM4NDkyY2Y2MWE0NmM4NjAzMTlhMjFkNDcyYzFhM2RhOWMxMDM2YTBmZjY3ZWYyNGM5NDE4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAAI0y6hioSskkpTOTvYXW-5y0g19zMmjLkbAWId5AY)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
make it better in dark mode and take care of responsive and other elements shouldn't be affected!! 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Astha-Raghuwanshi** [comment]
Thanks...working on it!!
