### ISSUE TITLE
Feat: The icon leads to home page

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [anuragverma108/SwapReads#832]
### Describe the feature

As of now the swap reads icon on the navbar does not lead anywhere. We can change it to redirect to the homepage every time it is clicked.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/99084211/2e517d4f-263a-4e9e-b904-3112b268f57c)
clicking on this will redirect us to the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> As of now the swap reads icon on the navbar does not lead anywhere. We can change it to redirect to the homepage every time it is clicked.
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/99084211/333772693-2e517d4f-263a-4e9e-b904-3112b268f57c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDAwOTUsIm5iZiI6MTcxNjYzOTc5NSwicGF0aCI6Ii85OTA4NDIxMS8zMzM3NzI2OTMtMmU1MTdkNGYtMjYzYS00ZTllLWI5MDQtMzExMmIyNjhmNTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NmY1YjBmOTAwNGUyZGI3MTY5MGVjY2M2YjA0MDQyMzA2ZTY2MTFlNTlhNzg1NzJmMzNlMGU5ZDRiOGE3MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4-iWG0_apzZ335W7FcIFk6BH5dv2ULJWbUrWUkweKo) clicking on this will redirect us to the home page
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Astha-Raghuwanshi** [comment]
on it!!
