### ISSUE TITLE
BUG: The price cards are of uneven size

### ISSUE THREAD

**Issue by shreya-paul-17** [anuragverma108/SwapReads#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the price section, the 3 cards provided sidewise is of uneven size. It will look better if the price cards are made of the same size and will become visually appealing.

Here is an attached screenshot of the same:
![swapreads](https://github.com/anuragverma108/SwapReads/assets/135226069/d67eeac3-f447-4913-8d1b-66e265141b3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepthi-Ramineni** [comment]
I would like to work on this. can you please assign this to me....???

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> In the price section, the 3 cards provided sidewise is of uneven size. It will look better if the price cards are made of the same size and will become visually appealing.
> 
> Here is an attached screenshot of the same: ![swapreads](https://private-user-images.githubusercontent.com/135226069/333773891-d67eeac3-f447-4913-8d1b-66e265141b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDAxNDEsIm5iZiI6MTcxNjYzOTg0MSwicGF0aCI6Ii8xMzUyMjYwNjkvMzMzNzczODkxLWQ2N2VlYWMzLWY0NDctNDkxMy04ZDFiLTY2ZTI2NTE0MWIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjhlZDlhNDk3NTdjNTU3OGNkYzU2ZjNjOGE2OGY1ZDZjNDc5MDMwMjU1Mjc4YTFlOGNhYmYwN2ZiMDU1OTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.05eqLI6zyFpfYPnfm4Y1_rZkQlDNQoIfQjVvNLfktWc)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
take care of responsive and other elements shouldn't be affected!!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

i am the mentor of this project and gssoc you can react out to me for any kind of help regarding anything!!

Happy open-source contributing!

**Comment by harshcodesit** [comment]
I can get the cards aligned properly, I have worked on the same issue with the benifits card

please assign the issue to me
