### ISSUE TITLE
Feat: More Visually Appealing and Insightful Logo

### ISSUE THREAD

**Issue by Praneeth-2602** [anuragverma108/SwapReads#836]
### > Why do we have to change the Logo?
> **The current logo's concept seems slightly misaligned with our main project. Additionally, the cursive font makes it difficult to read the text at a glance. While the current colors are light, they appear somewhat dull and lack visual impact.**

### > The New Design
> **The icon in the new logo effectively depicts the essence of our project. It features a bold, easy-to-read font, and the use of Red (Pigment) color draws more attention and conveys energy, in alignment with principles from color psychology.**

I am interested in contributing to the above mentioned changes under **GSSOC'24**.

### The Current Logo -

![current_logo](https://github.com/anuragverma108/SwapReads/assets/137754636/43044304-d2d0-4a6e-b9bb-dff09c319901)

#### Logo -
![new_logo](https://github.com/anuragverma108/SwapReads/assets/137754636/8226d6fd-522d-462d-9a7a-d917a4a2045e)

#### Banner -
![new_logo_banner](https://github.com/anuragverma108/SwapReads/assets/137754636/679f4a54-9e10-4ead-80ee-ba73950b0d23)

#### Icon -
![new_logo_Icon_light](https://github.com/anuragverma108/SwapReads/assets/137754636/ef44a4ce-fd70-460b-878e-934a700cb86e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Praneeth-2602** [comment]
Please assign this issue to me under **GSSOC'24**.

**Comment by huamanraj** [comment]
great work @Praneeth-2602 but i think the font should be more bold? what is your take?

**Comment by Praneeth-2602** [comment]
#### This is the logo with updated font (At highest resolution) -


![image](https://github.com/anuragverma108/SwapReads/assets/137754636/1310807b-4f20-4bea-b2f1-d7d8a6105832)


#### Here are a few snippets with this logo on our website -

![image](https://github.com/anuragverma108/SwapReads/assets/137754636/6e5ee2de-e4d1-404a-92bf-1fabec4945c2)

Sir, please approve the above changes so that I can proceed with a PR.
