### ISSUE TITLE
BUG: Flickering Issue in the Testimonals part.

### ISSUE THREAD

**Issue by saiumasankar** [anuragverma108/SwapReads#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When hovering on the a card of a person in testimonals, they are filckering and not rotating properly. I would like to change them to rotate when we click on the card or hover on it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> When hovering on the a card of a person in testimonals, they are filckering and not rotating properly. I would like to change them to rotate when we click on the card or hover on it
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!
make it better in dark mode and take care of responsive and other elements shouldn't be affected!!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.


Happy open-source contributing!
