### ISSUE TITLE
BUG: Add drop down symbol for MORE in the navbar

### ISSUE THREAD

**Issue by Saimanjari777** [anuragverma108/SwapReads#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The more button when hovered it shows the list and disappears. I want to add the drop down symbol so that the users can understand its a dropdown list which increases the user readability.
![image](https://github.com/anuragverma108/SwapReads/assets/130165687/120630b9-4f0c-44f9-a43d-d64514b73267)
Please assign this issue to me. I would like to work on this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The more button when hovered it shows the list and disappears. I want to add the drop down symbol so that the users can understand its a dropdown list which increases the user readability. ![image](https://private-user-images.githubusercontent.com/130165687/333778101-120630b9-4f0c-44f9-a43d-d64514b73267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDAyOTQsIm5iZiI6MTcxNjYzOTk5NCwicGF0aCI6Ii8xMzAxNjU2ODcvMzMzNzc4MTAxLTEyMDYzMGI5LTRmMGMtNDRmOS1hNDNkLWQ2NDUxNGI3MzI2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjJkNDljNmVmNGY0ODBmZTM5M2MxMjVhMWNmNTYzNTRkZTg4ZTFlMGI0MjhiNGMwMDk0ODYxNjg4OGY0MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UV4Y-th6qy-BMmdGErX6ThfZ5aS4qyTWC5-Lxjx41jU) Please assign this issue to me. I would like to work on this
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.



Happy open-source contributing!
