### ISSUE TITLE
BUG: The title "Some Frequently asked questions" is situated in testimonals part.

### ISSUE THREAD

**Issue by saiumasankar** [anuragverma108/SwapReads#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To my observation, I observed that the title " Some Frequently asked questions" is situated at testimonal part. I would like to place it in the down part.
![issue1](https://github.com/anuragverma108/SwapReads/assets/119750857/0b2a07b4-0c83-4f84-b477-c3fb37e3b218)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjaykasaudhan** [comment]
Can you please assign me this issue?

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> To my observation, I observed that the title " Some Frequently asked questions" is situated at testimonal part. I would like to place it in the down part. ![issue1](https://private-user-images.githubusercontent.com/119750857/333778570-0b2a07b4-0c83-4f84-b477-c3fb37e3b218.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mzk4NTEsIm5iZiI6MTcxNjYzOTU1MSwicGF0aCI6Ii8xMTk3NTA4NTcvMzMzNzc4NTcwLTBiMmEwN2I0LTBjODMtNGY4NC1iNDc3LWMzZmIzN2UzYjIxOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjE5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWMyMjM4NmRiNzYwN2ZkNWNlMGE1MGE2OTViNjQyZWVmNWZiYjcyZjk5NDY2NTAwZDFiM2Y5MmE1YzU2OGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GDvtYKhv9qAITiQLAKjKrvmGMLq86UE-FOWtC_mE7TM)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by harshcodesit** [comment]
@huamanraj 
Can you assign the issue to me , You can see my results in previous works
