### ISSUE TITLE
Add License.md file at Repository

### ISSUE THREAD

**Issue by Chandana-756** [anuragverma108/SwapReads#844]
I have come across the LICENSE.md file is missing in the repository. Including a license promotes collaboration by clearly outlining permissions and limitations. It enhances the repository's credibility and compliance with open-source community standards. Lastly, it helps users understand their obligations and rights regarding the code.

I would like to work on this issue under GSSOC'24

**Comment by huamanraj** [comment]
> I have come across the LICENSE.md file is missing in the repository. Including a license promotes collaboration by clearly outlining permissions and limitations. It enhances the repository's credibility and compliance with open-source community standards. Lastly, it helps users understand their obligations and rights regarding the code.
> 
> I would like to work on this issue under GSSOC'24

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Chandana-756** [comment]
Can you add the GSSOC'24 labels

**Comment by Chandana-756** [comment]
I have create a pull request #856 . Kindly check this pr.
