### ISSUE TITLE
Feat: Implementing Multilingual Support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [anuragverma108/SwapReads#848]
### Describe the feature

On exploring the SwapReads, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.

### Add ScreenShots

The below image of the website represents that it is present only in english language
![WhatsApp Image 2024-05-25 at 15 56 04_621cbfce](https://github.com/anuragverma108/SwapReads/assets/139578011/f9077513-c7d6-4226-b7b0-8388b1e33f3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Describe the feature
> On exploring the SwapReads, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.
> 
> ### Add ScreenShots
> The below image of the website represents that it is present only in english language ![WhatsApp Image 2024-05-25 at 15 56 04_621cbfce](https://private-user-images.githubusercontent.com/139578011/333791288-f9077513-c7d6-4226-b7b0-8388b1e33f3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mzk3MTUsIm5iZiI6MTcxNjYzOTQxNSwicGF0aCI6Ii8xMzk1NzgwMTEvMzMzNzkxMjg4LWY5MDc3NTEzLWM3ZDYtNDIyNi1iN2IwLTgzODhiMWUzM2YzYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMjE2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODllYzQ2NjE4Y2NjOTJhZWJlZjE3ZGE4OTE1ODM5ODNmMGMwMDVlMmRhMTk0NzRiNWNjM2M3YWU1ODI1MTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pffbe-PmGvfO9MMt0JEGwi6CLLkQhjxRya2dA3Tsn3E)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
