### ISSUE TITLE
Alignment of the section are not same and for mobile the books and genre section can be better

### ISSUE THREAD

**Issue by Vijayaa21** [anuragverma108/SwapReads#849]
I want to align all the sections of the literature realm and pricing section on mobile. These sections appear too small, but there is extra space available. I want to optimize the UI to improve the mobile experience in dark mode.

**Comment by huamanraj** [comment]
> I want to align all the sections of the literature realm and pricing section on mobile. These sections appear too small, but there is extra space available. I want to optimize the UI to improve the mobile experience in dark mode.

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
