### ISSUE TITLE
Bug Report: Replace Landing Page Image

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The image on the landing page currently depicts a novel. This does not effectively convey the core idea of SwapReads.com, which is to swap old books and build a reading culture. The image should be replaced with one that better represents the website's purpose.

**Steps to Reproduce:**
1. Open the homepage (index.html).
2. Observe the image displayed on the landing page.

**Expected Behavior:**
The landing page should feature an image that effectively represents the idea of SwapReads.com as a platform for swapping old books and fostering a reading culture.

**Actual Behavior:**
The landing page currently features an image of a novel, which does not convey the website's primary purpose.

**Suggested Solution:**
Replace the current image with one of the same dimensions that depicts the concept of book swapping and building a reading community.

**Screenshots:**
![landing page](https://github.com/anuragverma108/SwapReads/assets/129655645/57e66bda-40f9-4bc1-8983-d0387eaf48b1)

**Environment:**
- Browser: Chrome, Firefox
- Device: Desktop, Laptop
- Operating System: Windows 10, macOS

**Additional Information:**
The new image should maintain the visual appeal and dimensions of the current image but should clearly depict the themes of book swapping and community building.

If anyone wants to work on this issue then do comment, I will assign it to you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by YadlaMani** [comment]
@anuragverma108 i can work on this issue assign me this

**Comment by anuragverma108** [comment]
@YadlaMani 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
