### ISSUE TITLE
Feat: Reader Connections

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#858]
### Describe the feature

The Reader Connections feature will allow users to connect and chat with each other, fostering a community where book enthusiasts can share reading interests, recommendations, and experiences.

**Key Components:**

1. **User Directory:** Searchable directory with filters to find users by location, genres, and reading interests.
2. **Enhanced User Profiles:** Detailed profiles with favorite books, genres, and interests.
3. **Connection Requests:** Send and receive friend requests to connect with other readers.
4. **Private Messaging:** Direct messaging system for connected users to chat and share recommendations.
5. **Interest Groups:** Join or create groups based on genres or themes with group chats.
6. **Reading Interest Tags:** Tag profiles with specific interests to improve searchability.
7. **Discussion Forums:** Centralized forums for various book-related discussions.
8. **Notification System:** Real-time and email notifications for messages and connection activities.
9. **Privacy Controls:** Settings to manage who can see profiles and send connection requests.

**Note:** I am the Project Admin. If you want to work on this issue, please comment, and I will assign it to you under GSSoC Level 3.

### Add ScreenShots

![landing page](https://github.com/anuragverma108/SwapReads/assets/129655645/46cf372d-9223-4c74-8790-ec046ed4fa0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Sakshi007c** [comment]
I would like  to work on this issue @anuragverma108 , please assign this to me.

**Comment by huamanraj** [comment]
> I would like  to work on this issue @anuragverma108 , please assign this to me.
> 
> 

Great 👍 Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Sakshi007c** [comment]
@huamanraj will keep that in mind

**Comment by Sakshi007c** [comment]
Hi @huamanraj, could you please create a separate issue for each feature under level 3?

**Comment by Maheshwari-Love** [comment]
@huamanraj @anuragverma108 can you assign this to me...
 I can make the same as per above issue requirements , something like following design: 
![Screenshot 2024-06-03 135952](https://github.com/anuragverma108/SwapReads/assets/142833275/3ba2ec90-839f-40c1-9df8-489bd3ab914e)
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/4f974fc8-2ec2-4eb7-bac4-c1f5a1b61fbc)

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/fffb49a4-671f-4f18-aacc-4fbe75464643)

**Comment by Sakshi007c** [comment]
@Maheshwari-Love  I am currently working on it .

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love I am currently working on it .

@Sakshi007c okay then NO problem...Keep it up

**Comment by RitiChandak** [comment]
@Sakshi007c Any updates??

**Comment by RitiChandak** [comment]
@Maheshwari-Love Do you want to work?

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love Do you want to work?

@RitiChandak yes sure!

**Comment by RitiChandak** [comment]
@Maheshwari-Love Assigned !
