### ISSUE TITLE
Fix the Responsiveness of the Login Page & improve the UI.

### ISSUE THREAD

**Issue by Karthikeyan1508** [anuragverma108/SwapReads#86]
Hello @anuragverma108 !

I would like work upon this issue.
Could you please assign me under GSSoC'24?

**Comment by adinathraut** [comment]
Hello @anuragverma108  !

I have resolved this issue kindly assign me this

**Comment by anuragverma108** [comment]
Assigned!
Create PR & show before vs after screenshot of the page.

**Comment by Bhumika1312** [comment]
Hi there! 
Can you please assign the issue related to the login/signup form to me for the GSSOC'24. I have some ideas to improve the form's responsiveness, and I believe I can make a significant contribution to the project.

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by Aryan-joh** [comment]
Hii @anuragverma108 i have done this type of project please assign to me
