### ISSUE TITLE
BUG: overlapping of buttons

### ISSUE THREAD

**Issue by HK853** [anuragverma108/SwapReads#861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![nwv0dTXiPV](https://github.com/anuragverma108/SwapReads/assets/113816862/31d1c71f-4dee-4698-98b2-9f346e9c61c6)

I want to fix that issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HimanshuGolyan01** [comment]
Hi @anuragverma108 i would like to work on this issue ? Please assign me this issue ?

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
