### ISSUE TITLE
BUG: Text on 'Subscribe' button becomes invisible on hover

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When hovering over the 'Subscribe' button in the footer, the text becomes invisible due to the hover effect applied to the button. This makes it difficult for users to read the text.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
