### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Aditi-P22** [anuragverma108/SwapReads#87]
**Is your feature request related to a problem? Please describe.**
As web environments continue to feature lengthy pages, users often face challenges navigating back to the top after scrolling through content. Integrating a "Back to Top" button alleviates this issue by providing a convenient and efficient means for users to return to the beginning of the page with minimal effort. Therefore, the proposed feature directly addresses the problem of cumbersome navigation on lengthy webpages, enhancing overall usability and user satisfaction.

**Describe the solution you'd like**
The proposed solution involves implementing a visually discreet yet easily accessible button, positioned at the bottom right corner of the viewport. Upon clicking or tapping, the button smoothly scrolls the page back to the top, providing a seamless navigation experience. The button's design will align with the project's aesthetic principles while maintaining clarity and functionality.

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24.

**Comment by Saqib7khan** [comment]
I have already fixed this issue . I have added a new button "back to top" and this button  is on bottom right corner (pinned) i.e when a user scrolls , the button does not disappear . This button takes the user to the top of the page .
Please assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
Assigned @Aditi-P22

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
