### ISSUE TITLE
BUG:  : label for the "Book title" given in Book Exchange Hub is in wrong style and written twice

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we go through the Book Exchange Hub the form is given for connecting to the readers, in that form the first field of book title label is writen twice and in wrong Style.

![image](https://github.com/anuragverma108/SwapReads/assets/142833275/799fc7d4-f413-4240-a471-c933b254601e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@anuragverma108 @huamanraj can you please this task to me, it will be very helpful for me.

**Comment by HimanshuGolyan01** [comment]
can you please assign me this issue ? @anuragverma108

**Comment by anuragverma108** [comment]
@Maheshwari-Love 

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by Maheshwari-Love** [comment]
@anuragverma108  I have fixed the issue and made a pull request, kindly review it and if any changes required please let me know.
