### ISSUE TITLE
Feature: Can we add Free E-Books features?

### ISSUE THREAD

**Issue by shruti-mishraa** [anuragverma108/SwapReads#871]
### Describe the feature

The "Free E-Books" feature provides users with access to a diverse collection of literary works, curated and made accessible through our platform. Users can explore a wide range of books spanning various genres, from classics to contemporary literature. Each book listing includes details such as cover image, and a convenient download link, allowing users to easily access and enjoy their favorite reads. With our "Free E-Books" feature, users can embark on literary adventures, discover new authors, and indulge in the joy of reading.

### Add ScreenShots
![Screenshot 2024-05-26 101243](https://github.com/anuragverma108/SwapReads/assets/92870611/8857b9ae-d1d5-481e-addc-a9045ed294c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shruti-mishraa** [comment]
@anuragverma108 let me work on the feature...

**Comment by anuragverma108** [comment]
Assigned! @shruti-mishraa 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
