### ISSUE TITLE
BUG: header alignment

### ISSUE THREAD

**Issue by aashkaaaaaa** [anuragverma108/SwapReads#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/138461600/41a2bb81-8267-4b86-bd93-04465a3cfaa5)
the header alignment is not proper, plz assign me this issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned! @aashkaaaaaa 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
