### ISSUE TITLE
BUG: Navbar is not proper i

### ISSUE THREAD

**Issue by Shivam250702** [anuragverma108/SwapReads#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is not proper and we can see the text and navbar distance is also not proper , The size of navbar is less than that of components in it

![image](https://github.com/anuragverma108/SwapReads/assets/103785990/500ba3da-f4b5-465d-837d-bd3d81b19b37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @huamanraj
