### ISSUE TITLE
Feat: Add About Page

### ISSUE THREAD

**Issue by Hemashree21** [anuragverma108/SwapReads#877]
### Describe the feature

I want to work on adding the About page for highlighting the features of the website so that when a new user visits the website, they will get a brief idea about it. I have attached one of the template below and I will also make sure that the page is responsive.
@anuragverma108 can you please assign this issue to me?

### Add ScreenShots

![Screenshot 2024-05-20 163822](https://github.com/anuragverma108/SwapReads/assets/138188163/b6aa5a3b-db83-4f77-834d-944e42f2138b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
hello great issue here are some instructions:
Create a about us page and dont add it in index but just make a page and add the access button in navbar 'more' button! 
and theme should match the website 
@Hemashree21

happy open source contributing 🦋
