### ISSUE TITLE
BUG: The UI for the Book Recommendation page can be improved to enhance user experience 

### ISSUE THREAD

**Issue by Maheshwari-Love** [anuragverma108/SwapReads#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently a new page for the book recommendation was added to Project , but the UI of this page need improvement.
Also there are less option given for selecting the genre. 
![image](https://github.com/anuragverma108/SwapReads/assets/142833275/fe6db5a9-5159-47c6-8b58-094f34ced998)

I can fix this efficiently, and make UI interactive

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@anuragverma108 kindly assign me this issue, and add the required labels please

**Comment by huamanraj** [comment]
> Also the Genres given in option are less as compared to we have mention in our Home page to explore
> so I think there should be more option for selection at least that of what we have mention in home page
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/142833275/247e92d0-5812-4d4a-91aa-47831b703b91)
> 
> given options 
> 
> ![image](https://github.com/anuragverma108/SwapReads/assets/142833275/4b9579b5-e682-4616-86ce-dab7e7607119)
> 
> @anuragverma108 kindly assign me this issue, and add the required labels please

work on it 💪
