### ISSUE TITLE
Adding description in the sign up feature of "Your Booklist For Shopping"

### ISSUE THREAD

**Issue by VanshikaAg12** [anuragverma108/SwapReads#884]
For a better understanding to the user, "Don't have an account yet?" can be added near the Sign Up feature of "Your Booklist For Shopping", as it isn't already mentioned. 
![Screenshot 2024-05-26 151333](https://github.com/anuragverma108/SwapReads/assets/156996206/5f640171-03e0-41f1-901a-813ecd571036)

**Comment by VanshikaAg12** [comment]
Kindly assign me this issue under GSSoC'24.

**Comment by huamanraj** [comment]
> Kindly assign me this issue under GSSoC'24.

assigned! 
work on it 💪!
