### ISSUE TITLE
Feat: Enhancement of User preference Bar

### ISSUE THREAD

**Issue by taneeshaa15** [anuragverma108/SwapReads#885]
### Describe the feature

This page is looking very dull, I will make it more beautiful by adding some features in UI. 

### Add ScreenShots

![gssoc1](https://github.com/anuragverma108/SwapReads/assets/157527085/8a978192-26b9-4008-8e63-4dbd08f47ce3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@anuragverma108 Please assign me this issue under the label GSSoC'24. Thankyou

**Comment by huamanraj** [comment]
> @anuragverma108 Please assign me this issue under the label GSSoC'24. Thankyou

issue already assigned to someone else!
