### ISSUE TITLE
Feat: Improving the login page.

### ISSUE THREAD

**Issue by taneeshaa15** [anuragverma108/SwapReads#886]
### Describe the feature

I will make the login page more attractive by improving the UI through figma.

### Add ScreenShots

![gssoc2](https://github.com/anuragverma108/SwapReads/assets/157527085/0334e441-0116-471d-918e-8efc9a80e805)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@anuragverma108 Please assign me this issue and add appropriate labels.

**Comment by huamanraj** [comment]
> @anuragverma108 Please assign me this issue and add appropriate labels.

Assigned
before coding it must get the designs approved by me or project admin! 
i am the mentor so ask for any help you need !

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.


Happy open-source contributing!

**Comment by taneeshaa15** [comment]
@huamanraj Started working on it, will share my progress soon.

**Comment by taneeshaa15** [comment]
@huamanraj Can you please add gssoc label also?

**Comment by huamanraj** [comment]
> @huamanraj Can you please add gssoc label also?
> 

sorry i missed that in hurry!

**Comment by huamanraj** [comment]
> @huamanraj Started working on it, will share my progress soon.

great 👍
