### ISSUE TITLE
Feat: Enhancing  UI of the footer.

### ISSUE THREAD

**Issue by Changingthegame** [anuragverma108/SwapReads#887]
![SwapReads](https://github.com/anuragverma108/SwapReads/assets/169473705/243fe434-574f-4d24-b97e-1a44b057dda5)
### Describe the feature

Hello  @anuragverma108 , I visited your website and I myself found it very nice and attractive . One thing I noticed was that in the footer of the website, it appears that the content seems to be misaligned and appears distorted. So, there should be a nice footer in your website.

### Add ScreenShots

If you would like, I can take a closer look at the issue and provide a solution to fix it promptly. Also I can use some nice fonts wherever required and also I am thinking of aligning the content vertically so that the footer appears nice and it becomes easier for the user to find out the content in footer easy.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Changingthegame** [comment]
I am eager to work on this issue ,so can you please assign me this issue as soon as possible. Also , I have starred your github repository.

**Comment by huamanraj** [comment]
> I am eager to work on this issue ,so can you please assign me this issue as soon as possible. Also , I have starred your github repository.

Assigned!
must get the design approved!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
