### ISSUE TITLE
BUG:Rating Us Page is not Responsive and No favicon in Rating Us page

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add favicon in Rating Us Page and make Rating Us Page Responsive with use of html and css.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> I want to add favicon in Rating Us Page and make Rating Us Page Responsive with use of html and css.
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

work on it!
