### ISSUE TITLE
[BUG] : empty fields are also excepted in Book Exchange section

### ISSUE THREAD

**Issue by Sudhanshu2306** [anuragverma108/SwapReads#89]
**Describe the bug**
In Book Exchange Hub even if Book Title or Author's name or price is missing it is getting an accepted alert.

**To Reproduce**
1. Go to 'Book Exchange Hub'
2. Click on 'Connect with a Reader' without filling any fields
3. Acceptance Alert pops up

**Expected behavior**
It should give an alert of add data to all fields + specific datatype accordingly.

**Screenshots**
![image](https://github.com/anuragverma108/SwapReads/assets/126086429/4e553f97-6fb2-4acf-9bf1-2c5f89d9afc0)

**Desktop (please complete the following information):**
 - OS: Windows]
 - Browser [Chrome]

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Sudhanshu2306** [comment]
Thank You! I have created a pull request, please see if any changes are required. #103 fixes #89
