### ISSUE TITLE
BUG: Some pages are not responsive

### ISSUE THREAD

**Issue by Madhuri36** [anuragverma108/SwapReads#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Book Recommendation page is not responsive on smaller devices.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/ace66619-a8ac-4857-8a04-c937ea05703e)

Apart from this, benefits page is also not looking good on smaller devices as there is an overflow.
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/4ede699d-0044-479f-9457-d8f7cbf8c094)

Even this portion is not having responsiveness across all devices:
![image](https://github.com/anuragverma108/SwapReads/assets/146222028/4cc92cc4-0368-4170-a65d-0d75dfc31a21)

I would like to work on this. Please assign it to me under GSSoC'24. @anuragverma108 @huamanraj 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Book Recommendation page is not responsive on smaller devices.
> ![image](https://github.com/anuragverma108/SwapReads/assets/146222028/ace66619-a8ac-4857-8a04-c937ea05703e)
> 
> Apart from this, benefits page is also not looking good on smaller devices as there is an overflow.
> ![image](https://github.com/anuragverma108/SwapReads/assets/146222028/4ede699d-0044-479f-9457-d8f7cbf8c094)
> 
> Even this portion is not having responsiveness across all devices:
> ![image](https://github.com/anuragverma108/SwapReads/assets/146222028/4cc92cc4-0368-4170-a65d-0d75dfc31a21)
> 
> I would like to work on this. Please assign it to me under GSSoC'24. @anuragverma108 @huamanraj 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
