### ISSUE TITLE
Fix the Chatbot feature.

### ISSUE THREAD

**Issue by AditiPrabhakar** [anuragverma108/SwapReads#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here I've noticed that the chatbot is giving blank response after every message, I've worked on Botpress before i can fix this issue.

![Screenshot (104)](https://github.com/anuragverma108/SwapReads/assets/139689410/86eb70b8-6467-47b5-88ae-986c77f8fc69)

Also i can add more round edges to the text boxes as they look very rectangular, not going quite with the theme.

Also I can change the text message 'This Chatbot was built surprisingly fast.....' to more user friendly and interactive like 'Welcome to SwapReads!' or 'How can we assist you?'.

The placeholder should be with the name of the chatbot as 'Chat with Mia'.

I can change the icon (black S) to more styled color, as it isn't going with the color palate used.

Please assign me this issue, i will not disappoint!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Here I've noticed that the chatbot is giving blank response after every message, I've worked on Botpress before i can fix this issue.
> 
> ![Screenshot (104)](https://github.com/anuragverma108/SwapReads/assets/139689410/86eb70b8-6467-47b5-88ae-986c77f8fc69)
> 
> 
> Also i can add more round edges to the text boxes as they look very rectangular, not going quite with the theme.
> 
> Also I can change the text message 'This Chatbot was built surprisingly fast.....' to more user friendly and interactive like 'Welcome to SwapReads!' or 'How can we assist you?'.
> 
> The placeholder should be with the name of the chatbot as 'Chat with Mia'.
> 
> I can change the icon (black S) to more styled color, as it isn't going with the color palate used.
> 
> Please assign me this issue, i will not disappoint!
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
i am the GSSOC project mentor so reach out for any help!
Happy open-source contributing!

**Comment by AditiPrabhakar** [comment]
Please send me an invite link, so that I can have the access to update the chatbot.


1) Go to your workspace and select on members, then click on 'Invite member'.

![Screenshot (105)](https://github.com/anuragverma108/SwapReads/assets/139689410/908be479-ab39-4680-a652-eefd3cf9e949)


2) Then enter my email id: aditiprabhakar04@gmail.com 
and change the viewer mode to manager / administrator mode, so that I can change the files.

![Screenshot (106)](https://github.com/anuragverma108/SwapReads/assets/139689410/d57943a6-466f-4821-8a99-bd797d10e430)
