### ISSUE TITLE
BUG:Contact Page: Inconsistent Spacing Between Map and Contact Information

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1388" alt="Screenshot 2024-05-26 at 9 55 01 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/91fe86e4-a4c0-4957-9959-b2c7dc4c4b71">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shiuli-19** [comment]
Could you please assign it to me.I have made the changes.
<img width="1358" alt="Screenshot 2024-05-26 at 10 49 45 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/7c93be85-0382-4b3b-b607-498fd3ae65e1">

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> 
> <img width="1388" alt="Screenshot 2024-05-26 at 9 55 01 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/91fe86e4-a4c0-4957-9959-b2c7dc4c4b71">
> 
> 
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
