### ISSUE TITLE
BUG:Overlapping Scroll to Top and Chat Buttons on Contact Page

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="142" alt="Screenshot 2024-05-26 at 9 59 52 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/c8d71475-b7f9-48c3-b6b6-cb620ddc1c3a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> <img width="142" alt="Screenshot 2024-05-26 at 9 59 52 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/c8d71475-b7f9-48c3-b6b6-cb620ddc1c3a">
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
