### ISSUE TITLE
BUG: Text on 'Subscribe' button becomes invisible on hover

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When hovering over the 'Subscribe' button, the text becomes invisible due to the hover effect applied to the button. This makes it difficult for users to read the text.
![before](https://github.com/anuragverma108/SwapReads/assets/129402285/1549de2e-40b2-49f7-9a13-e45c17f213d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Hi @anuragverma108,
Please assign this issue to me under GSSOC'24

**Comment by huamanraj** [comment]
> Hi @anuragverma108,
> Please assign this issue to me under GSSOC'24

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
