### ISSUE TITLE
SignUp / Login Page

### ISSUE THREAD

**Issue by kdanjana** [anuragverma108/SwapReads#9]
GirlScriptCode of Summer
The sign in for new and registered users is not aligned properly. I want to align the main header , signup and sign in parts properly on the page. Please assign this issue to me.
<img width="893" alt="sthg" src="https://github.com/anuragverma108/SwapReads/assets/103878831/4f0197fb-4f8a-4fe4-8912-73a0d31bcd73">

**Comment by kamalesh-og** [comment]
Hi,
I'm one of the contributors for the GSOCC'24, I would love to take up this issue and work on this UI.
I have experience in Web Design and I can assure you that I make this UI more attractive and good-looking with proper formatting fonts and design of the page.
Can you please assign this issue to me
Thank you!

**Comment by anushkapal28** [comment]
As a GSSoC'24 contributor, I'm excited to tackle this UI issue. With my background in web design, I'm confident I can enhance the aesthetics and usability of the page with proper formatting, fonts, and design elements. Could you please assign this task to me?

**Comment by RiyaaBhatt** [comment]
Hello there,

As a contributor for GSSOC'24, I'm eager to tackle this issue and enhance the UI. With my background in Web Design, I can assure you that I'll create an attractive and visually appealing UI with proper formatting, fonts, and overall page design.

I kindly request you to assign this issue to me so that I can get started and contribute my skills to make the UI more appealing and user-friendly.

Thank you for considering my request!

Best regards.

**Comment by VarshaPednekar** [comment]
I kindly request you to assign this issue to me under gssoc'24

**Comment by anuragverma108** [comment]
Assigned @RiyaaBhatt
Since among all contributors who are the one who is firmly saying that you can improve the UI the page and make it look awesome. So I am assigning it to you.

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by Yuvika-14** [comment]
Pls assign this issue to me. Lete show off my skills

**Comment by Sahil21dev** [comment]
@anuragverma108 Hello sir , I have some improvisations to the code , can you please assign it to me  under GSSOC 24 . 
I'll not disappoint you .

**Comment by Sahil21dev** [comment]
https://github.com/anuragverma108/SwapReads/pull/26 

Please have a look .

**Comment by RiyaaBhatt** [comment]
Hello sir! I've completed the task you assigned me earlier. Could you take a look at it when you get a chance? I put in quite a bit of effort, so I hope it meets your expectations. Thanks!
