### ISSUE TITLE
Changing the text to a close button

### ISSUE THREAD

**Issue by aryansharma220** [anuragverma108/SwapReads#90]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/anuragverma108/SwapReads/assets/133234867/58f5aa5c-4bb1-4066-a942-a38496a44428)
This text does not looks very appealing

**Describe the solution you'd like**
We can use a cross button to close the login/signup page and redirect to home page

@anuragverma108 please allow me to work on it, if you like my idea

**Comment by Saqib7khan** [comment]
I want to work on this issue please assign it to me .

**Comment by JainArchit16** [comment]
@anuragverma108 please allow me to work on it

**Comment by anythingkartik** [comment]
Hello @anuragverma108 I want to work on this one, since this is my first time working in open source , Can you provide me this task, I want to learn .
Here is my Linkedin  linkedin.com/in/itskartikgupta/
Thank You
