### ISSUE TITLE
Title: Documentation Update: Correct Typo Errors in Pull Request Checklist

### ISSUE THREAD

**Issue by shruti-mishraa** [anuragverma108/SwapReads#902]
### What's wrong with the existing documentation

###Description:
The current pull request checklist in the documentation contains typo errors and formatting issues. This issue is to update the checklist to ensure clarity and correctness for all contributors. Below is the corrected version and details of the errors.

###Screenshots
![Screenshot 2024-05-26 183858](https://github.com/anuragverma108/SwapReads/assets/92870611/5c4894c7-7014-427e-9bc1-2ba5cff50e1c)

### Checklist Errors:
1.Typo Error: resourses should be resources.
2.The text after Please delete options that are not relevant. should be in lowercase.

![Screenshot 2024-05-26 183858](https://github.com/anuragverma108/SwapReads/assets/92870611/3fc54c4d-50d0-4fb3-9277-ed1ebf0b3492)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shruti-mishraa** [comment]
@anuragverma108

**Comment by huamanraj** [comment]
> @anuragverma108 

Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
i am the project mentor reach out to me for any help! 

Happy open-source contributing!
