### ISSUE TITLE
BUG:The length of the pricing cards in pricing are unequal

### ISSUE THREAD

**Issue by shiuli-19** [anuragverma108/SwapReads#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Could you please assign it to me.I have made the following changes.
Before:
<img width="1266" alt="Screenshot 2024-05-26 at 11 04 23 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/ac1fd703-7e7e-4544-8fb0-8b7ec4ec56f8">
After:
<img width="1390" alt="Screenshot 2024-05-26 at 11 26 53 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/31298c1a-a845-4495-9974-573aa28edff8">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Could you please assign it to me.I have made the following changes.
> Before:
> <img width="1266" alt="Screenshot 2024-05-26 at 11 04 23 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/ac1fd703-7e7e-4544-8fb0-8b7ec4ec56f8">
> After:
> <img width="1390" alt="Screenshot 2024-05-26 at 11 26 53 PM" src="https://github.com/anuragverma108/SwapReads/assets/119745655/31298c1a-a845-4495-9974-573aa28edff8">
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

preopend issue it is!
