### ISSUE TITLE
back to top button and  chatbot button is colliding to each other

### ISSUE THREAD

**Issue by Ketanop321** [anuragverma108/SwapReads#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

back to top button and chat bot button are colliding with each other
![Screenshot 2024-05-26 235350](https://github.com/anuragverma108/SwapReads/assets/146806880/554b3b18-d672-4e29-8732-9b92f9e9da49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> back to top button and chat bot button are colliding with each other
> ![Screenshot 2024-05-26 235350](https://github.com/anuragverma108/SwapReads/assets/146806880/554b3b18-d672-4e29-8732-9b92f9e9da49)
> 
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

preopend issue it is !
