### ISSUE TITLE
links are not working in footer 

### ISSUE THREAD

**Issue by PrabhjotBajwa** [anuragverma108/SwapReads#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@anuragverma108 plz assign this issue to me under gssoc24 label i can resolve this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KASHISHROY** [comment]
Can you please assign this issue to me?
I can resolve this issue.
