### ISSUE TITLE
Logo not changed in the login/signup page

### ISSUE THREAD

**Issue by suhanigupta23** [anuragverma108/SwapReads#910]
### What's wrong with the existing documentation

The logo of swap reads is not changed in the login/signup page.

### Add ScreenShots

<img width="1062" alt="Screenshot 2024-05-27 at 9 10 58 AM" src="https://github.com/anuragverma108/SwapReads/assets/144280247/a59df617-9765-49ee-84e8-61d59dceacd1">

I want to work on this issue under gssoc'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
