### ISSUE TITLE
BUG: Testimony Card Swiper not working correctly

### ISSUE THREAD

**Issue by aryansharma220** [anuragverma108/SwapReads#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/anuragverma108/SwapReads/assets/133234867/6014780f-1de1-4c4d-863d-28897d6c9c3d

The swiper is glitching out.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by aryansharma220** [comment]
@anuragverma108 The UI of the website has been broken. Please look into the matter.
