### ISSUE TITLE
Add footer and header to all pages

### ISSUE THREAD

**Issue by Sneha123-zudo** [anuragverma108/SwapReads#919]
### Describe the feature

I want to header and footer to all pages of website as it make the UI of the website better.

### Add ScreenShots

<img width="867" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/145490348/863ef942-df34-4194-8ceb-f99ffb15d62b">
<img width="853" alt="image" src="https://github.com/anuragverma108/SwapReads/assets/145490348/efd18663-c8bf-48cb-9f73-8217f6db8b72">

PLease assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Hi @anuragverma108, @Sneha123-zudo ,
I want to work on this issue please assign this to me.

**Comment by anuragverma108** [comment]
Assigned! @Sneha123-zudo 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
