### ISSUE TITLE
BUG: Genre Cards Not Working Properly on Hover Effect

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hover effect on the genre cards is not functioning as expected. When hovering over a genre card, the cards are getting excessively zoomed, which is not the intended visual effect and results in a poor user experience.
[recording-2024-05-27-12-43-09.webm](https://github.com/anuragverma108/SwapReads/assets/129402285/dc4d0567-ffd4-400f-80b3-f28f3fce3504)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Please assign this issue to me!

**Comment by tanyaachaturvedi** [comment]
Please assign this issue to me

**Comment by anuragverma108** [comment]
Assigned! @Saksham2k3s 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
@tanyaachaturvedi 

Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
