### ISSUE TITLE
Feat: Dark light mode feature should be added.

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [anuragverma108/SwapReads#921]
### Describe the feature

Dark and light mode feature should be added.

### Add ScreenShots

https://github.com/anuragverma108/SwapReads/assets/138589633/ff355484-17b2-4ed9-b499-8d81f5db072f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ishitamukherjee2004** [comment]
Hello, @anuragverma108 Please assign this issue to me.

**Comment by anuragverma108** [comment]
Assigned! @Ishitamukherjee2004 

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by DiyaMittal02** [comment]
please assign this issue to me
