### ISSUE TITLE
BUG: In the navbar the toggle button, google logo etc arr not organized properly.

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [anuragverma108/SwapReads#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![WhatsApp Image 2024-05-27 at 12 45 23_92ab4b4b](https://github.com/anuragverma108/SwapReads/assets/138589633/0ad34623-d596-46f5-b698-f15583719baa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ishitamukherjee2004** [comment]
Hello @anuragverma108 Please assign this issue to me.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
