### ISSUE TITLE
Feat: hover in footer icons

### ISSUE THREAD

**Issue by aashkaaaaaa** [anuragverma108/SwapReads#923]
### Describe the feature

we can change size and add hover in icons

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/138461600/61982273-3ca6-4f1f-a289-910cdde9a296)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@huamanraj Please assign me this issue under gssoc label.

**Comment by Dishaaa-T** [comment]
@anuragverma108 @huamanraj please assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment]
@aashkaaaaaa 
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by anuragverma108** [comment]
@taneeshaa15 @Dishaaa-T 


Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
