### ISSUE TITLE
Feat: FAQ

### ISSUE THREAD

**Issue by aashkaaaaaa** [anuragverma108/SwapReads#924]
### Describe the feature

instead of Faq we can improve to FAQ, which looks professional.

### Add ScreenShots

![image](https://github.com/anuragverma108/SwapReads/assets/138461600/7cc8827c-9ee1-4410-b3c2-02147bffd70e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by nilesh07g** [comment]
@anuragverma108  
Assign this issue to me I want to work on this **issue** under GSSOC'24
