### ISSUE TITLE
BUG: Add Email Validator to Ensure Correct Format for Gmail Addresses

### ISSUE THREAD

**Issue by skshrinaya** [anuragverma108/SwapReads#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current code lacks an email validator to ensure that email addresses are in the correct format, specifically for Gmail addresses ending with @gmail.com. The current implementation does not validate the email format correctly for Gmail addresses.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DiyaMittal02** [comment]
I would like to work on this project. Please assign it to me.

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!

**Comment by skshrinaya** [comment]
Thank You for assigning me this issue.
