### ISSUE TITLE
Genre button

### ISSUE THREAD

**Issue by JanitKumar** [anuragverma108/SwapReads#932]
### Describe the feature

button of genre is too big in size and its size should be reduced

### Add ScreenShots

![Screenshot 2024-05-27 185500](https://github.com/anuragverma108/SwapReads/assets/126192349/2eeaab0d-28f8-42c0-8135-b3bb937c7c0c)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@JanitKumar already solved
