### ISSUE TITLE
Modifying The Footer Section

### ISSUE THREAD

**Issue by surendar-05** [anuragverma108/SwapReads#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no proper alignment, some elements overlap each other as well as some icons are in correct size 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by surendar-05** [comment]
Heyy I want to work on this issue Assign me under GSSOC'24

**Comment by nilesh07g** [comment]
I want to work on this issue and solve
assign me under GSSOC`24

**Comment by surendar-05** [comment]
I have already completed half of it. Can you choose a different issue?
