### ISSUE TITLE
BUG: The alignment of the page is not done properly; the title and the book image are overlapping each other.

### ISSUE THREAD

**Issue by akashacharya09** [anuragverma108/SwapReads#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![glitch1](https://github.com/anuragverma108/SwapReads/assets/100611979/f20c2b47-84ca-49b9-a125-773f1ce031be)

Currently, there is a problem with the page alignment. Specifically, the title of the book and the image of the book are overlapping. This overlap creates a cluttered and confusing visual presentation, making it difficult for users to read the title clearly and see the book cover properly.

To resolve this issue, the layout of the page needs to be adjusted so that the title and the book image are properly spaced and positioned. This might involve changing the CSS properties such as margins, padding, and positioning to ensure that each element on the page is clearly separated and visually appealing. By correcting this alignment issue, we can improve the overall user experience and readability of the page.

**Please assign me this task.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
