### ISSUE TITLE
BUG: Book Listing Visibility Issue

### ISSUE THREAD

**Issue by 18Venus** [anuragverma108/SwapReads#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The genre boxes and books listed are getting overlapped leading to books visibility being damaged. Also it would be better if each row had 4/5 books rather than 3.
![overlap](https://github.com/anuragverma108/SwapReads/assets/149051659/e64daec6-745d-4df2-9b91-78eee45e2c9e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
