### ISSUE TITLE
Broken Social Media Links

### ISSUE THREAD

**Issue by AnantPatel1** [anuragverma108/SwapReads#94]
Issue:
The social media links (Facebook, LinkedIn, etc.) on the home page under contact section  are not functioning as expected. Instead of redirecting to the respective social media profiles, clicking on them causes the page to scroll up, indicating a broken link.

Expected Behavior:
Clicking on the social media links should redirect users to the corresponding social media profiles.

Actual Behavior:
Clicking on the social media links causes the page to scroll up, indicating a broken link.

I would like to work on resolving this issue as part of the GSSOC'24 program.

**Comment by anuragverma108** [comment]
Issue already exits & solved.
