### ISSUE TITLE
Feat: EXPERIENCE BLOGS

### ISSUE THREAD

**Issue by 18Venus** [anuragverma108/SwapReads#940]
### Describe the feature

Users can have a chance to share their experiences through blogs. It can be of how the site helped them or maybe any literary experience or book suggestions or anything!

### Add ScreenShots

I have not yet worked on the feature. Pls assign it to me so that I can develop this section and add SS!
It shall look like any blog site.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 18Venus** [comment]
@huamanraj hello! To make this blog page dynamic i.e accepting blogs from users and storing and retrieving from a db i'll have to set up a json file and also npm...are ok with that? Aur do you want me to have 2-3 static blogs only... ? Thank you!

**Comment by huamanraj** [comment]
> @huamanraj hello! To make this blog page dynamic i.e accepting blogs from users and storing and retrieving from a db i'll have to set up a json file and also npm...are ok with that? Aur do you want me to have 2-3 static blogs only... ? Thank you! 

keep it Static for now

**Comment by 18Venus** [comment]
Sure. Thank you.
