### ISSUE TITLE
upgrade the hover speed of play button

### ISSUE THREAD

**Issue by shuhaki** [anuragverma108/SwapReads#944]
### What's wrong with the existing documentation

upgrade and improve the hover speed of play button

### Add ScreenShots

<img width="214" alt="Screenshot 2024-05-28 at 2 09 02 AM" src="https://github.com/anuragverma108/SwapReads/assets/145912232/47e03f24-8107-4cd8-9d40-f23de92a8fe1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
