### ISSUE TITLE
Feat: More Relevant Loader Animation

### ISSUE THREAD

**Issue by Praneeth-2602** [anuragverma108/SwapReads#945]
## What's wrong with the current loader animation?

The current loader animation is rather simplistic and lacks elements that convey or depict the thematic or conceptual info of the website. Enhancing this animation to reflect the site's theme and purpose would provide a more engaging and informative user experience (UX).

## The New Animation

The new animation, as depicted in the second part of the video attached, features a visual element resembling an open book, suggesting themes of knowledge, learning, or documentation. This new design effectively aligns with the website's theme and enhances the user experience (UX) by providing a more engaging and contextually relevant visual cue during loading times.

> I would like to **contribute** to the above mentioned change under **GSSOC'24**

### Add ScreenShots

# 
https://github.com/anuragverma108/SwapReads/assets/137754636/f0eff2b7-e983-4d31-9094-643fa238b757
# 

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
