### ISSUE TITLE
BUG: Two Sections genre and Free- E-Books are Overlapping

### ISSUE THREAD

**Issue by shruti-mishraa** [anuragverma108/SwapReads#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Genre Section and the Free E-books Sections are overlapping.
Let me resolve the issues.
![Screenshot 2024-05-28 083756](https://github.com/anuragverma108/SwapReads/assets/92870611/43292b7a-a493-45ab-86b0-8bc10b747473)

![Screenshot 2024-05-28 083803](https://github.com/anuragverma108/SwapReads/assets/92870611/d9bba30a-6332-41f8-8644-2519bc43a776)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shruti-mishraa** [comment]
@anuragverma108 let me work on the issue.

**Comment by shruti-mishraa** [comment]
@anuragverma108

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
