### ISSUE TITLE
BUG: The gap between the navbar and the header is very less and shown like overlapping .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/SwapReads#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The gap between the navbar and the text and image is very less It looks like overlapping .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by susrith-maddi** [comment]
Please assign me this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Ayushmaanagarwal1211** [comment]
@anuragverma108 thanks for assigning this issue to me but unfortunately i was able to see this bug before now it may be solved by someone i am not seeing this bug so i am unassigning me and please close this issue .
