### ISSUE TITLE
BUG:The hero image is not covering properly and cursor

### ISSUE THREAD

**Issue by Stiffpixels** [anuragverma108/SwapReads#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Hero image is not covering properly see:
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/b6f5460c-f294-4697-8ac9-7698c68aba73)

fixed: 
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/ecd54e5f-f441-47bb-9967-89a1d983258b)

The cursor is static in the top left corner
![image](https://github.com/anuragverma108/SwapReads/assets/32983571/f60cac86-52e5-4089-ad92-e49854d34d0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
