### ISSUE TITLE
BUG:reDesign home page with perfect layout 

### ISSUE THREAD

**Issue by Varsani2520** [anuragverma108/SwapReads#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in home all the cards and content are not a look like a good ,
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/95745d48-56be-4b4e-8f62-15dc1dce72d7)
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/a863396b-e7aa-4ebe-8478-205835313b4f)
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/7535bec2-98d0-409d-9c9e-785da8e837af)
i can do like this:
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/fbaa2116-335f-4012-940e-697c0293dfff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
