### ISSUE TITLE
BUG:swiper button is not working

### ISSUE THREAD

**Issue by Varsani2520** [anuragverma108/SwapReads#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

prev and next button not working in testinomial card:
![image](https://github.com/anuragverma108/SwapReads/assets/137641079/a6f7762f-3aaf-4fe8-ab48-6124bf874463)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
