### ISSUE TITLE
BUG:Site not Responsive

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The entire site is not responsive, resulting in layout issues and misalignment when viewed on different devices and screen sizes. This affects the overall user experience, especially on mobile devices and smaller screens.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
@kashnx Assigned!

Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.

Happy open-source contributing!
