### ISSUE TITLE
BUG:Overflowing Home Page

### ISSUE THREAD

**Issue by nishant0708** [anuragverma108/SwapReads#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I will fix this overflowing issue of home page

https://github.com/anuragverma108/SwapReads/assets/101548649/85a555fe-589c-47cd-90c6-979d5bd7be8d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
