### ISSUE TITLE
BUG: The Back to Top Arrow button is not working

### ISSUE THREAD

**Issue by kashvi9** [anuragverma108/SwapReads#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicked on the **Back to Top Arrow button**, it must direct you to the home page at the top, but it does nothing. Instead user has to scroll themselves.

Here is a screenshot,

![image](https://github.com/anuragverma108/SwapReads/assets/169376061/01c315e8-b076-4ac4-b907-84674c64ae4e)

Hello PA @anuragverma108, 
Kindly assign me this issue under GSSOC'24.
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
It is working ! Do check again

**Comment by kashvi9** [comment]
Sorry but it wasn't working then
