### ISSUE TITLE
BUG: Fix the Genre page 

### ISSUE THREAD

**Issue by Utsavladia** [anuragverma108/SwapReads#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The components zooms too much and everything else dissappear.
I would fix this hover effects and cards alignment to fix the user experience and unnecessary zooming all over the screen.

![image](https://github.com/anuragverma108/SwapReads/assets/124615886/70329d75-f3bf-483e-ba4e-d57442b55c80)

![image](https://github.com/anuragverma108/SwapReads/assets/124615886/fed7358e-1fc1-4c4b-badf-806ef1fa420f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
please assign this issue to me ,sir @anuragverma108

**Comment by anuragverma108** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
