### ISSUE TITLE
BUG: Login/SignUp page overflow in small size by navbar options also it does not have favicon.

### ISSUE THREAD

**Issue by zalabhavy** [anuragverma108/SwapReads#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In small size device login/signup page is overlapping by navbar options also this page not have favicon.
![image](https://github.com/anuragverma108/SwapReads/assets/126322584/0d243583-dfdd-49b5-b975-6160e8973e4a)
I will hide options of navbar for solve that overlapping during login/singup.
![image](https://github.com/anuragverma108/SwapReads/assets/126322584/422ae86b-4b86-4bd5-885b-318b74bcaf6d)
Favicon is not present.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
