### ISSUE TITLE
BUG: Align "Connect with Reader" Button to Center

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Connect with a Reader" button on the [specific page or section] is currently not aligned to the center. This issue affects the visual consistency of the page and the user experience.
![connect-with-render](https://github.com/anuragverma108/SwapReads/assets/129402285/e74162a3-a346-4d08-a1bb-5a8a2cb31daa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Please assign this issue to me

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by vishal02527** [comment]
@anuragverma108 please assign this issue to me. I will resolve this issue in less time.
