### ISSUE TITLE
BUG: Typo/Formatting Issue in Romance Paragraph in Genre Section

### ISSUE THREAD

**Issue by Saksham2k3s** [anuragverma108/SwapReads#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a typo or formatting issue in the romance paragraph in the genre section. The paragraph contains unnecessary quotation marks ("") which affect the readability and professionalism of the content.
![quato issue](https://github.com/anuragverma108/SwapReads/assets/129402285/20c0c71b-825b-4530-b200-38db4fa29ae2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Please assign this issue to me

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
