### ISSUE TITLE
Adding and E-book section to the homepage before user logs in

### ISSUE THREAD

**Issue by samarsajad** [anuragverma108/SwapReads#974]
### Describe the feature

Adding an E-Books section to the homepage before logging in would enhance the user experience by providing easy access to digital reading materials. Each book cover could serve as a clickable link, leading users to more detailed information about the E-Book, such as its synopsis, author information, and reader reviews.

### Add ScreenShots

![Screenshot 2024-05-29 021425](https://github.com/anuragverma108/SwapReads/assets/142666229/c29babba-151b-4331-8c0d-c914e02cd305)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by samarsajad** [comment]
Please review my pull request @anuragverma108
