### ISSUE TITLE
BUG: Different Navbar on Forgot Password Page

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar displayed on the Forgot Password page is different from the navbar used on the rest of the application. This inconsistency affects the user experience and visual continuity of the site.

Request:
Please assign this issue to me. I will work on updating the Forgot Password page to use the same navbar as the rest of the application, ensuring a consistent user experience.

Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by abhibhande** [comment]
Can i work on this problem
