### ISSUE TITLE
BUG:Refactor Code to Remove Repetition and Delete Commented Sections

### ISSUE THREAD

**Issue by kashnx** [anuragverma108/SwapReads#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current codebase contains repetitive code and commented sections that are no longer necessary. This clutter affects code readability, maintainability, and overall efficiency. Refactoring the code to eliminate redundancy and remove unnecessary comments will improve the code quality.

Request:
Please assign this issue to me. I will refactor the code to remove repetition and delete unnecessary commented sections, improving the overall quality and maintainability of the codebase.

Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragverma108** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
