### ISSUE TITLE
BUG: Fix Navbar height

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/SwapReads#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/anuragverma108/SwapReads/assets/129655645/1f5586bf-179e-4ffe-8b8b-cf5e4222a5bb)
The existing navbar is has taken too much height. Fix it. 

If anyone wants to work on this issue do comment, I will assign it to you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by kashnx** [comment]
I want to work on this issue.

**Comment by anuragverma108** [comment]
Assigned!

**Comment by anuragverma108** [comment]
Assigned! @kashnx 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by aasthabagrawal** [comment]
Plz assign it to me.
