### ISSUE TITLE
Feat: Contact us section is not visually appealing

### ISSUE THREAD

**Issue by shifa-s11** [anuragverma108/SwapReads#979]
### Describe the feature

it is overlapping the map and not going with the whole theme . Please assign this issue to me i will correct it 

### Add ScreenShots

![Screenshot (40)](https://github.com/anuragverma108/SwapReads/assets/144918231/4eab38c8-61f1-4b3f-ada3-479b7ef4515d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shifa-s11** [comment]
Please assign this issue to me , i really want to work on this amazing project

**Comment by RitiChandak** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/96969496/401ef1e7-6533-4372-af2a-d48e65546c25)
I think it looks fine.
