### ISSUE TITLE
BUG: Swapping of cards is not smooth 

### ISSUE THREAD

**Issue by shifa-s11** [anuragverma108/SwapReads#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Swapping of cards is not smooth , please assign this issue to me i am eager to work on this project

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by huamanraj** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> Swapping of cards is not smooth , please assign this issue to me i am eager to work on this project
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!
