### ISSUE TITLE
Feat: adding sliding feature 

### ISSUE THREAD

**Issue by shifa-s11** [anuragverma108/SwapReads#981]
### Describe the feature

adding the sliding feature in the testimonials. 

### Add ScreenShots

![Screenshot (42)](https://github.com/anuragverma108/SwapReads/assets/144918231/1097722c-b621-4ca7-abc3-ed751840316c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shifa-s11** [comment]
I really want to contribute to this amazing project

**Comment by Bhumi-letscode** [comment]
hey @RitiChandak. I would love to work on this part of the website. The sliding effect will make it really cool. Kindly assign me this task to be able to contribute on this wonderful project.
