### ISSUE TITLE
Feat: Icons not aligned

### ISSUE THREAD

**Issue by shifa-s11** [anuragverma108/SwapReads#982]
### Describe the feature

chat icon is not aligned properly with the other 

### Add ScreenShots

![Uploading Screenshot (43).png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shifa-s11** [comment]
I really want to contribute to this amazing project

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
