### ISSUE TITLE
Feat:Changing the colors in dark mode

### ISSUE THREAD

**Issue by Brinda-07** [anuragverma108/SwapReads#983]
### Describe the feature

In the dark mode , the color of the heading red is not quite appealing.
We can change the color to some lighter shade so that it is visible clearly

Plz assign this issue to me
@anuragverma108 

### Add ScreenShots

![Screenshot 2024-05-29 093616](https://github.com/anuragverma108/SwapReads/assets/154052901/70fb3b42-b9e1-4269-b845-5f9af8da31d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
