### ISSUE TITLE
BUG: Align Send Now button to center

### ISSUE THREAD

**Issue by kashvi9** [anuragverma108/SwapReads#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The **Send Now** Button in Contact Form is towards right, I think it should be aligned to center.

Here's a screenshot

![image](https://github.com/anuragverma108/SwapReads/assets/169376061/464f00b6-880f-4faa-ba42-a8005f2737a7)

Hello PA @anuragverma108 ,
I can solve this issue once assigned under GSSOC'24.
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vishal02527** [comment]
@RitiChandak @anuragverma108 Please assign this issue to me, I will resolve the issue in very less time.

**Comment by RitiChandak** [comment]
@vishal02527 this issue is already assigned to kashvi9
