### ISSUE TITLE
Feat: Icon-Based Navbar Enhancement

### ISSUE THREAD

**Issue by Dhevamuthu** [anuragverma108/SwapReads#995]
### Describe the feature

We propose to enhance the website's navigation bar (navbar) by replacing text-based menu items with visually appealing icons. This change aims to improve user experience, making the navbar more effective, engaging, and modern.

Objective:

Increase user engagement and satisfaction by creating a visually stimulating navbar.
Enhance the aesthetic appeal of the website, aligning it with contemporary design trends.
Improve the usability of the navbar, making it quicker and easier for users to navigate the site.

Benefits:

Visual Appeal: Icons are more visually appealing than text, providing a sleek and modern look to the website.
Recognition and Speed: Icons can be recognized and processed faster than text, allowing users to find and select the desired navigation options more quickly.
Space Efficiency: Icons take up less space, allowing for a cleaner and more organized navbar.
Universal Understanding: Well-designed icons can be universally understood, reducing language barriers for international users.

Conclusion:
Transitioning from a text-based to an icon-based navbar is a strategic enhancement aimed at improving the overall user experience. By making navigation more intuitive and aesthetically pleasing, we expect to see higher user satisfaction and engagement rates.

### Add ScreenShots

![Screenshot 2024-05-29 122419](https://github.com/anuragverma108/SwapReads/assets/123234572/e0791018-8756-4a16-a68a-461429b3d1e1)

we can make the navbar as like below one..
![Screenshot 2024-05-29 122807](https://github.com/anuragverma108/SwapReads/assets/123234572/f755cadd-87dc-4d9c-81da-2f66cc690067)
![Screenshot 2024-05-29 122821](https://github.com/anuragverma108/SwapReads/assets/123234572/c6d62061-c015-4f3d-883f-231213ef53c5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Can u assign me this issue under GSSOC 2024

**Comment by huamanraj** [comment]
> Can u assign me this issue under GSSOC 2024

this doesn't go well with the theme! could you share how it is going to look on the website?

**Comment by Dhevamuthu** [comment]
Here instead of displaying the names as buttons in the navbar, we can place icons corresponding to the names..
For home, we can place home button ad similarly for other, we can display the images as icon for its navigation 
![IMG_20240530_104540](https://github.com/anuragverma108/SwapReads/assets/123234572/1821f044-b412-4526-8b99-b49c08de1c38)

**Comment by huamanraj** [comment]
> Here instead of displaying the names as buttons in the navbar, we can place icons corresponding to the names..
> For home, we can place home button ad similarly for other, we can display the images as icon for its navigation 
> ![IMG_20240530_104540](https://github.com/anuragverma108/SwapReads/assets/123234572/1821f044-b412-4526-8b99-b49c08de1c38)
> 

ok! 
Assigned!
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by Dhevamuthu** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/123234572/c5934f53-acb1-4297-aa82-261e7816535c)


Is this okay?

**Comment by Dhevamuthu** [comment]
![image](https://github.com/anuragverma108/SwapReads/assets/123234572/38b91dbf-99fd-4c37-9e5c-dd84d2af1054)

Is this okay?

**Comment by Dhevamuthu** [comment]
Actually I don't know what happened. It is working well but when I commit it, some issues are happening.
