### ISSUE TITLE
BUG:Duplicate Mouse Pointers on Title Bar Interaction

### ISSUE THREAD

**Issue by Dhevamuthu** [anuragverma108/SwapReads#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In our current application, an issue has been identified where moving the mouse pointer to the title bar results in the appearance of two separate pointers on the web app page. When the mouse is moved to the title bar, the pointer behaves as expected in the title bar area, but simultaneously, another pointer remains active and visible within the app interface. This anomaly leads to the presence of two pointers: one that moves to the title bar and another that stays within the app.

This issue significantly disrupts user experience by causing confusion and reducing the overall usability of the app. Users may find it difficult to interact with elements within the application accurately, as the duplicate pointer may lead to incorrect clicks or selections. This behavior is not only visually distracting but also undermines the professionalism and reliability of the application.

Addressing this issue is critical to ensure a seamless and intuitive user experience. The solution will involve identifying and rectifying the cause of the persistent in-app pointer when the mouse interacts with the title bar. By resolving this, we aim to restore the expected single-pointer functionality and enhance the overall usability and user satisfaction of our application.

https://github.com/anuragverma108/SwapReads/assets/123234572/6f4bd2d6-645f-47c8-b5f6-e77f3ff3db8d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Thankyou for assigning it to me

**Comment by RitiChandak** [comment]
@Dhevamuthu any updates?

**Comment by Dhevamuthu** [comment]
Working on it .Will update you soon.
